### PR TITLE
serve peer linearizable member list

### PR DESCRIPTION
**Pull request by chaochn47**
Related to https://github.com/etcd-io/etcd/issues/14174

To add a meaningful test, a new failpoint and fail case may be introduced to the functional test cases. I think it's a overkill.. 

Appreciate any comment or suggestion how to test this change!! Thanks

---
I will add another commit to update the CHANGELOG to make current one backportable.

### CODE REVIEW

**Comment by chaochn47** [comment]
Both Integration tests and grpcproxy integration tests failed at the following 2 cases.

```
=== FAIL: integration TestDoubleClusterSizeOf1 (5.58s)
     logger.go:130: 2022-06-29T01:20:49.363Z	WARN	m0	timed out waiting for read index response (local node might have slow network)	{"member": "m0", "timeout": "5.2s"}
    logger.go:130: 2022-06-29T01:20:49.363Z	WARN	m0	failed to serve linearizable member list	{"member": "m0", "error": "etcdserver: request timed out"}
    logger.go:130: 2022-06-29T01:20:49.363Z	WARN	m0	unexpected v2 response error	{"member": "m0", "remote-addr": "@", "internal-server-error": "etcdserver: request timed out"}
    logger.go:130: 2022-06-29T01:20:49.363Z	WARN	m1	failed to unmarshal cluster response	{"member": "m1", "address": "unix://127.0.0.1:2103205737/members", "error": "json: cannot unmarshal object into Go value of type []*membership.Member"}
    cluster.go:317: failed to initialize the etcd server: cannot fetch cluster info from peer urls: could not retrieve cluster information from the given URLs

=== FAIL: integration TestIssue3699 (30.70s)
...
```

I am suspecting it's the test itself breaks. Will spend some time investigating the problem.

**Comment by chaochn47** [comment]
Looks like in case of growing etcd member size from 1 to 2, Linearizable read notify will hang up which is expected. 

We may want to fail open in this case and expect up to 7s bootstrap delay in such scenario.. @ahrtr

**Comment by ahrtr** [comment]
You might need to use [waitAppliedIndex](https://github.com/etcd-io/etcd/blob/7a1cecd5fafcea03adfb11b6bed49e901cd1dcf2/server/etcdserver/v3_server.go#L259).

See example at [v3_server.go#L281](https://github.com/etcd-io/etcd/blob/7a1cecd5fafcea03adfb11b6bed49e901cd1dcf2/server/etcdserver/v3_server.go#L281)

**Comment by chaochn47** [comment]
> or keep it as it's for now, because when K8s or users retry and then it will work. Users may also add some sleep between adding the new node and starting the new node if they have a automated operator. 

Yeah, it sounds like a feasible solution and I also expect retry should succeed eventually. 

If this solution is picked, we should document this behavior and call this out in https://etcd.io/docs/v3.5/op-guide/runtime-configuration/#error-cases-when-adding-members.

**Pull request closed without merging**
