### PR TITLE
added ibm doc

### PR DESCRIPTION
**Pull request by marifse**
* Added IBM doc setup for etcd

### CODE REVIEW

**Comment by gyuho** [comment]
@nate-double-u @spzala Could you comment on this?

**Comment by nate-double-u** [comment]
I mentioned this PR in the [docs removal PR](https://github.com/etcd-io/etcd/pull/12660) as it may be affected by it. 

The Documentation folder is largely being removed, so this PR may have to make some changes. Likely a PR into the [website repo](https://github.com/etcd-io/website) will have to be made in order to capture the docs change.

**Comment by spzala** [comment]
@gyuho it seems like aws doc was added before the etcd project become a CNCF project. IMHO, the maintainers should discuss and decide the project's approach for adding new provider specific doc and its scope. If that sounds good, I will initiate that discussion? That will help us review this PR and any similar future ones. (Any new doc will go to website repo as @nate-double-u mentioned once https://github.com/etcd-io/etcd/pull/12660 is merged so we should discuss doc scope for the website.) Thanks!

**Comment by gyuho** [comment]
> The Documentation folder is largely being removed

Could you lead us in that direction :)

@marifse Please work with @nate-double-u 

@spzala Regarding aws.md, I wouldn't mind removing all platform specific docs, maybe make it generic that are applicable to all platforms.

**Comment by spzala** [comment]
> > The Documentation folder is largely being removed
> 
> Could you lead us in that direction :)
> 
> @marifse Please work with @nate-double-u
> 
> @spzala Regarding aws.md, I wouldn't mind removing all platform specific docs, maybe make it generic that are applicable to all platforms.
@gyuho I am fine with the aws.md, and going forward with your suggestion.

**Comment by nate-double-u** [comment]
Hi @marifse, we have finished migrating the Documentation to https://github.com/etcd-io/website/, so this PR should be closed and can be recreated in the website repo now.

**Comment by ptabor** [comment]
Is there a CNCF requirement to not have solution/platform specific docs/howtos/integration code ?

**Comment by nate-double-u** [comment]
> Is there a CNCF requirement to not have solution/platform specific docs/howtos/integration code ?

No, I don't think there is. DexIdP, for instance, has a whole section on their site showing different platform specific howtos for their  connectors: https://dexidp.io/docs/connectors/

**Comment by ptabor** [comment]
We discussed this on the last community [meeting](https://docs.google.com/document/d/16XEGyPBisZvmmoIHSZzv__LoyOeluC5a4x353CX0SIM/edit#heading=h.tu6uwzxqfg8x): 

I understood (@spzala, @nate-double-u please check if I get this right) goes in following directions: 
  - etcd wants to host such "How to style" documents to help our users
  - we recognize that it might be challenging to make sure such documents are kept up-to-data
 
Thus we are proposing: 
  - hosting them in form of "dated" blog-posts in: https://github.com/etcd-io/website/tree/master/content/blog to be presented in https://etcd.io/blog/
  - Linking to them from the e.g. platforms/howtos page in the etcd doc. 

I'm closing this PR, as it does not belong to this repo any longer. 
But please work with @nate-double-u on putting it in https://github.com/etcd-io/website

**Pull request closed without merging**
