### PR TITLE
[3.4] mvcc: push down RangeOptions.limit argv into index tree to reduce memory overhead

### PR DESCRIPTION
**Pull request by fuweid**
Backports:
* #11990 
* #13060
* And update the UT from #14124

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

----

Related to #15072

### CODE REVIEW

**Comment by ahrtr** [comment]
This PR changed the protocol between etcdserver and client side, it may have some impact on all clients, e.g., K8s. So I tend not to backport this one.

**Comment by fuweid** [comment]
Hi @ahrtr , would you please to point out the protocol change in the pr? I didn't follow you. Thanks!

**Comment by ahrtr** [comment]
> Hi @ahrtr , would you please to point out the protocol change in the pr? I didn't follow you. Thanks!

Previously I was thinking the `RangeResult.Count` value might change with this PR,  but it seems that it doesn't. So I think this PR is acceptable.

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you!

**Comment by fuweid** [comment]
Thanks!

**Comment by ahrtr** [comment]
Please also add a changelog item.

**Comment by fuweid** [comment]
> Please also add a changelog item.

Sure!

It might be late because of holiday.
I will send the pr next Tuesday~

**Pull request merged**
