### PR TITLE
clientv3: support serializable `MemberList` operation

### PR DESCRIPTION
**Pull request by ahrtr**
Fix https://github.com/etcd-io/etcd/issues/15243

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by serathius** [comment]
Let's discuss other options to solve https://github.com/etcd-io/etcd/issues/15243 before we start implementation.

**Comment by ahrtr** [comment]
Please see my comment in https://github.com/etcd-io/etcd/issues/15243#issuecomment-1423257824.

**Comment by ahrtr** [comment]
This PR should be a simple & straightforward change, and @serathius seems be also OK with this change per his comment https://github.com/etcd-io/etcd/issues/15243#issuecomment-1423788295. 

Do you have any other comments or objections? @mitake @ptabor @spzala

**Comment by ahrtr** [comment]
Just added changelog items and updated etcdctl's README.

**Comment by mitake** [comment]
@ahrtr I think it's fine to add the flag to etcdctl. This PR exposes the flag of the API as from the CLI, it should be safe. I have no objections.
Membership change especially for one node cluster is tricky, let me follow https://github.com/etcd-io/etcd/issues/15243 for understanding essential problems.

**Comment by ahrtr** [comment]
> @ahrtr I think it's fine to add the flag to etcdctl. This PR exposes the flag of the API as from the CLI, it should be safe. I have no objections. Membership change especially for one node cluster is tricky, let me follow #15243 for understanding essential problems.

Thanks @mitake for the feedback. Please read https://github.com/etcd-io/etcd/issues/15243#issuecomment-1418305327 for quick reference.

**Comment by spzala** [comment]
@ahrtr I also think this approach is fine. In the past, I think, before we changed to linearizable to always true user could get stale data mistakenly but now with providing options for l or s, users should be aware of the output somthing similar to get operation behavior. One thought here is to add a brief doc on when the user may want to use serializable for cases like the one described in the issue related to this PR. Thanks!

**Comment by ahrtr** [comment]
> One thought here is to add a brief doc on when the user may want to use serializable for cases like the one described in the issue related to this PR

Makes sense to me. thx @spzala 

Just updated the comment of `clientv3.WithSerializable` to clarify the warning (of reading stale data) and use cases. Please see the second commit: https://github.com/etcd-io/etcd/pull/15261/commits/9aced4c996a5422ff9b70b7dd7b073639c241dd8

**Review by spzala — COMMENTED** [review]
Thanks so much for the quick doc update @ahrtr !! While we wait on other reviewer feedback, I think also a good idea to update some of this specially the second paragraph content in the etcdctl doc updates for the memberlist?

**Comment by ahrtr** [comment]
> I think also a good idea to update some of this specially the second paragraph content in the etcdctl doc updates for the memberlist?

Thanks @spzala for the feedback. Do you mean to update the [memberlist doc in etcdctl/README.md](https://github.com/ahrtr/etcd/blob/memberlist_20230208/etcdctl/README.md#member-list)? I intentionally keep it consistent with [the doc for Get](https://github.com/ahrtr/etcd/blob/memberlist_20230208/etcdctl/README.md#get-options-key-range_end).

The new added flag `--consistency` for [MemberList](https://github.com/etcd-io/etcd/blob/822eeaf9f2d9e327df5f4cab8ff075c9b5727320/client/v3/cluster.go#L37) has exactly the same behavior as the existing [Get](https://github.com/etcd-io/etcd/blob/822eeaf9f2d9e327df5f4cab8ff075c9b5727320/client/v3/kv.go#L49) operation. I think it makes more sense to update (already done) the [clientv3.WithSerializable()](https://github.com/ahrtr/etcd/blob/9aced4c996a5422ff9b70b7dd7b073639c241dd8/client/v3/op.go#L421-L431) which is shared by both `MemberList` and `Get`. 

If we update the doc for memberlist, then we need to update it for the Get as well. So we either keep it as it's or update both. WDYT?

**Comment by spzala** [comment]
> > I think also a good idea to update some of this specially the second paragraph content in the etcdctl doc updates for the memberlist?
> 
> Thanks @spzala for the feedback. Do you mean to update the [memberlist doc in etcdctl/README.md](https://github.com/ahrtr/etcd/blob/memberlist_20230208/etcdctl/README.md#member-list)? I intentionally keep it consistent with [the doc for Get](https://github.com/ahrtr/etcd/blob/memberlist_20230208/etcdctl/README.md#get-options-key-range_end).
> 
> The new added flag `--consistency` for [MemberList](https://github.com/etcd-io/etcd/blob/822eeaf9f2d9e327df5f4cab8ff075c9b5727320/client/v3/cluster.go#L37) has exactly the same behavior as the existing [Get](https://github.com/etcd-io/etcd/blob/822eeaf9f2d9e327df5f4cab8ff075c9b5727320/client/v3/kv.go#L49) operation. I think it makes more sense to update (already done) the [clientv3.WithSerializable()](https://github.com/ahrtr/etcd/blob/9aced4c996a5422ff9b70b7dd7b073639c241dd8/client/v3/op.go#L421-L431) which is shared by both `MemberList` and `Get`.
> 
> If we update the doc for memberlist, then we need to update it for the Get as well. So we either keep it as it's or update both. WDYT?

@ahrtr thank you and yes, what you did to keep consistent with Get in the README is good. But, yes, I was referring to the README. The reason I was thinking to update README (and as you pointed out for MemberList and we should add similar doc for Get as well) is because end users may not refer to the Go code ([clientv3.WithSerializable()](https://github.com/ahrtr/etcd/blob/9aced4c996a5422ff9b70b7dd7b073639c241dd8/client/v3/op.go#L421-L431)) always and providing them heads up in README can be handy. WDYT :) Thanks!

**Comment by ahrtr** [comment]
Done & thx @spzala

**Review by spzala — APPROVED** [review]
@ahrtr lgtm, I think it's a good quick fix. Thanks for working on it.

**Review by serathius — APPROVED** [review]

**Pull request merged**
