### PR TITLE
[3.4] fix(defrag): handle errors during defrag

### PR DESCRIPTION
**Pull request by ghouscht**
Backport of https://github.com/etcd-io/etcd/pull/18822 to 3.4.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]

**Review by serathius — APPROVED** [review]

**Comment by ahrtr** [comment]
cc @ivanvc @jmhbnz

**Comment by ivanvc** [comment]
Link to #18810

**Pull request merged**
