### PR TITLE
server/etcdserver/api/etcdhttp: exclude the same alarm type activated by multiple peers

### PR DESCRIPTION
**Pull request by chaochn47**
#12880 failed to exclude all alarms activated by multiple members for a given alarm type. 

### Reproduce
etcd version `3.4.17`
```
$ rm -rf infra1.etcd infra2.etcd infra3.etcd ~/log/etcd/infra*
$ ./bin/etcd --name infra1 \
--listen-client-urls http://127.0.0.1:2379 \
--advertise-client-urls http://127.0.0.1:2379 \
--listen-peer-urls http://127.0.0.1:12380 \
--initial-advertise-peer-urls http://127.0.0.1:12380 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' --initial-cluster-state new \
--quota-backend-bytes 200000 > ~/log/etcd/infra1.log 2>&1 &

$ ./bin/etcd --name infra2 \
--listen-client-urls http://127.0.0.1:22379 \
--advertise-client-urls http://127.0.0.1:22379 \
--listen-peer-urls http://127.0.0.1:22380 \
--initial-advertise-peer-urls http://127.0.0.1:22380 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' --initial-cluster-state new \
--quota-backend-bytes 200000 > ~/log/etcd/infra2.log 2>&1 &

$ ./bin/etcd --name infra3 \
--listen-client-urls http://127.0.0.1:32379 \
--advertise-client-urls http://127.0.0.1:32379 \
--listen-peer-urls http://127.0.0.1:32380 \
--initial-advertise-peer-urls http://127.0.0.1:32380 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' --initial-cluster-state new \
--quota-backend-bytes 200000 > ~/log/etcd/infra3.log 2>&1 &

$ for n in {1..3868}; do sleep 0.1; dd if=/dev/urandom bs=1024 count=17 | ETCDCTL_API=3 etcdctl --endpoints http://localhost:2379,http://127.0.0.1:22379,http://127.0.0.1:32379  put /registry/pods/${n} ; done
$ ctrl+c

$ etcdctl alarm list
memberID:9372538179322589801 alarm:NOSPACE
memberID:10501334649042878790 alarm:NOSPACE
memberID:18249187646912138824 alarm:NOSPACE

$ curl "http://localhost:2379/health?exclude=NOSPACE"
{"health":"false"}

# etcd log
2021-11-09 06:01:51.367165 W | etcdserver/api/etcdhttp: /health error due to memberID:10501334649042878790 alarm:NOSPACE
```

### After this PR
```
curl "http://localhost:2379/health?exclude=NOSPACE"
{"health":"true","reason":""}
```

PTAL @hexfusion @gyuho

### CODE REVIEW

**Review by hexfusion — APPROVED** [review]
lgtm

**Comment by hexfusion** [comment]
please update changelogs for backports thanks!

**Review by spzala — APPROVED** [review]
lgtm 
Thanks!

**Comment by chaochn47** [comment]
Updated the change log with the backport PRs. PTAL thanks!!

**Pull request merged**
