### PR TITLE
docs: remove warning that etcd 3.5.0 was not yet released

### PR DESCRIPTION
**Pull request by ghouscht**
See description in https://github.com/etcd-io/etcd/issues/18410

### CODE REVIEW

**Review by serathius — APPROVED** [review]

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, Thomas.

**Review by ahrtr — APPROVED** [review]
Thanks for the cleanup!

**Comment by ivanvc** [comment]
/retitle [3.5] docs: remove warning that etcd 3.5.0 was not yet released

**Pull request merged**
