### PR TITLE
dependency: bump github.com/golang-jwt/jwt/v4 to v4.5.0

### PR DESCRIPTION
**Pull request by ahrtr**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
cc @spzala

**Comment by ahrtr** [comment]
@mitake @spzala PTAL, thx

**Review by spzala — APPROVED** [review]
lgtm Thank you @ahrtr

**Comment by spzala** [comment]
Sorry for taking longer to review @ahrtr

**Comment by ahrtr** [comment]
Thanks @spzala

**Pull request merged**
