### PR TITLE
*: avoid closing a watch with ID 0 incorrectly

### PR DESCRIPTION
**Pull request by kafuu-chino**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This PR backports https://github.com/etcd-io/etcd/pull/14296 to release-3.4. cc @ahrtr  @mitake

### CODE REVIEW

**Comment by ahrtr** [comment]
Thanks @kafuu-chino for backporting the PR. 

Unfortunately, release-3.4 doesn't have integration test at all, so you have to remove the integration test case for now.

**Comment by ahrtr** [comment]
Please try to manually verify this PR indeed fixes the issue, thx

**Comment by kafuu-chino** [comment]
> Please try to manually verify this PR indeed fixes the issue, thx

In my local test, the token expires and watch can trigger normally.

**Review by ahrtr — APPROVED** [review]
LGTM 

Thank you @kafuu-chino

**Comment by ahrtr** [comment]
cc @mitake @spzala to double confirm

**Comment by mitake** [comment]
@ahrtr @kafuu-chino I think just the path of integration test is different in release-3.4, and we can backport the test case like this? https://github.com/etcd-io/etcd/pull/14548/files#diff-93bc434c49bed544fa4df1bd0750fb22f98c12da81c75f8026520b4eed986108

**Comment by ahrtr** [comment]
> @ahrtr @kafuu-chino I think just the path of integration test is different in release-3.4, and we can backport the test case like this? https://github.com/etcd-io/etcd/pull/14548/files#diff-93bc434c49bed544fa4df1bd0750fb22f98c12da81c75f8026520b4eed986108

Thanks @mitake for the reminder. release-3.4 indeed has integration test, and paths are as below,

https://github.com/etcd-io/etcd/blob/de11726a8acd32d86ee9bb959a45b2e22c9d84bd/test#L185-L188

**Comment by kafuu-chino** [comment]
> > @ahrtr @kafuu-chino I think just the path of integration test is different in release-3.4, and we can backport the test case like this? https://github.com/etcd-io/etcd/pull/14548/files#diff-93bc434c49bed544fa4df1bd0750fb22f98c12da81c75f8026520b4eed986108
> 
> Thanks @mitake for the reminder. release-3.4 indeed has integration test, and paths are as below,
> 
> https://github.com/etcd-io/etcd/blob/de11726a8acd32d86ee9bb959a45b2e22c9d84bd/test#L185-L188

ok, I'll take a look today.

**Comment by kafuu-chino** [comment]
Integration test has been added. @ahrtr @mitake

**Comment by mitake** [comment]
Thanks @kafuu-chino @ahrtr !

**Pull request merged**
