### PR TITLE
Migrate PR testing from travis to GitHub actions

### PR DESCRIPTION
**Pull request by serathius**
Travis totally broke :(, context: https://github.com/etcd-io/etcd/pull/13125
This PR backports https://github.com/etcd-io/etcd/pull/12922 to release-3.4 branch to continue it's maintenance.

### CODE REVIEW

**Comment by serathius** [comment]
Ha, shellcheck failed :(

**Comment by lilic** [comment]
I suspect there might be more failures, as CI didn't run on a couple of PRs we merged it seems. Let me know if you need any help with this!

**Comment by serathius** [comment]
Hmm very strange errors with fmt
```
etcd $ gvm install go1.15.11
Updating Go source...
Installing go1.15.11...
 * Compiling...
go1.15.11 successfully installed!
etcd $ gvm use go1.15.11
Now using version go1.15.11
etcd $ GOARCH=amd64 PASSES='fmt bom dep' ./test
Running with TEST_CPUS: 1,2,4
Starting 'fmt' pass at Wed 23 Jun 2021 04:49:12 PM CEST
'shellcheck' started at Wed 23 Jun 2021 04:49:12 PM CEST
'shellcheck' completed at Wed 23 Jun 2021 04:49:13 PM CEST
'markdown_you' started at Wed 23 Jun 2021 04:49:13 PM CEST
'markdown_you' completed at Wed 23 Jun 2021 04:49:13 PM CEST
'markdown_marker' started at Wed 23 Jun 2021 04:49:13 PM CEST
Skipping marker...
'markdown_marker' completed at Wed 23 Jun 2021 04:49:13 PM CEST
'goword' started at Wed 23 Jun 2021 04:49:13 PM CEST
Skipping goword...
'goword' completed at Wed 23 Jun 2021 04:49:13 PM CEST
'gofmt' started at Wed 23 Jun 2021 04:49:13 PM CEST
'gofmt' completed at Wed 23 Jun 2021 04:49:13 PM CEST
'govet' started at Wed 23 Jun 2021 04:49:13 PM CEST
go: downloading github.com/dustin/go-humanize v0.0.0-20171111073723-bb3d318650d4
go: downloading github.com/coreos/go-semver v0.2.0
go: downloading github.com/spf13/pflag v1.0.1
go: downloading github.com/coreos/go-systemd v0.0.0-20180511133405-39ca1b05acc7
go: downloading github.com/google/uuid v1.0.0
go: downloading github.com/jonboulle/clockwork v0.1.0
go: downloading golang.org/x/net v0.0.0-20210405180319-a5a99cb37ef4
go: downloading google.golang.org/grpc v1.26.0
go: downloading github.com/prometheus/client_golang v1.0.0
go: downloading github.com/json-iterator/go v1.1.7
go: downloading github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2
go: downloading go.etcd.io/bbolt v1.3.3
go: downloading golang.org/x/sys v0.0.0-20210510120138-977fb7262007
go: downloading github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/beorn7/perks v1.0.0
go: downloading github.com/prometheus/procfs v0.0.2
go: downloading go.uber.org/zap v1.10.0
go: downloading github.com/spf13/cobra v0.0.3
go: downloading golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2
go: downloading github.com/urfave/cli v1.20.0
go: downloading sigs.k8s.io/yaml v1.1.0
go: downloading github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
go: downloading github.com/soheilhy/cmux v0.1.4
go: downloading github.com/cockroachdb/datadriven v0.0.0-20190809214429-80d97fb3cbaa
go: downloading gopkg.in/cheggaaa/pb.v1 v1.0.25
go: downloading github.com/prometheus/common v0.4.1
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.0.1-0.20190118093823-f849b5445de4
go: downloading github.com/bgentry/speakeasy v0.1.0
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/olekukonko/tablewriter v0.0.0-20170122224234-a0225b3f23b5
go: downloading github.com/creack/pty v1.1.11
go: downloading go.uber.org/atomic v1.3.2
go: downloading golang.org/x/text v0.3.3
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/mattn/go-runewidth v0.0.2
go: downloading github.com/coreos/pkg v0.0.0-20160727233714-3ac0863d7acf
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.9.5
go: downloading github.com/tmc/grpc-websocket-proxy v0.0.0-20200427203606-3cfed13b9966
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading go.uber.org/multierr v1.1.0
go: downloading github.com/golang/groupcache v0.0.0-20160516000752-02826c3e7903
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/google/btree v1.0.0
'govet' completed at Wed 23 Jun 2021 04:49:15 PM CEST
'govet_shadow' started at Wed 23 Jun 2021 04:49:15 PM CEST
go: downloading golang.org/x/tools v0.1.3
go: found golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow in golang.org/x/tools v0.1.3
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading golang.org/x/mod v0.4.2
go: found golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow in golang.org/x/tools v0.1.3
'govet_shadow' completed at Wed 23 Jun 2021 04:49:20 PM CEST
'revive' started at Wed 23 Jun 2021 04:49:20 PM CEST
Skipping revive...
'revive' completed at Wed 23 Jun 2021 04:49:20 PM CEST
'license_header' started at Wed 23 Jun 2021 04:49:20 PM CEST
'license_header' completed at Wed 23 Jun 2021 04:49:21 PM CEST
'receiver_name' started at Wed 23 Jun 2021 04:49:21 PM CEST
'receiver_name' completed at Wed 23 Jun 2021 04:49:21 PM CEST
'commit_title' started at Wed 23 Jun 2021 04:49:21 PM CEST
fatal: HEAD does not point to a branch
fatal: Not a valid object name 
'commit_title' completed at Wed 23 Jun 2021 04:49:21 PM CEST
Finished 'fmt' pass at Wed 23 Jun 2021 04:49:21 PM CEST
Starting 'bom' pass at Wed 23 Jun 2021 04:49:21 PM CEST
Finished 'bom' pass at Wed 23 Jun 2021 04:49:21 PM CEST
Starting 'dep' pass at Wed 23 Jun 2021 04:49:21 PM CEST
Checking package dependencies...
Finished 'dep' pass at Wed 23 Jun 2021 04:49:21 PM CEST
Success
etcd $ echo $?
0
```
It doesn't look like this is go1.15.11 related

**Comment by serathius** [comment]
I fixed some minor issues, but will require help with remaining ones. We have consistant failures on:
* linux-amd64-fmt on both 1.12.17 and 1.15.11
* linux-amd64-grpcproxy on 1.12.17 (1.15.11 is marked with allow_failures).

Could someone take a look into them? I don't have enough context in those. @lilic ?
I would be inclined try to get any test on release-3.4 branch and fix them later one by one if needed.

We could do that by excluding those tests or marking with allow_failures. WDYT?

**Comment by lilic** [comment]
So we had a few flakes in release-3.4 branch, so we could be hitting those. A lot of them were fixed in 3.5. I added 1.15 testing so can have a look, they were for sure passing before when my PR got merged.

> linux-amd64-fmt on both 1.12.17 and 1.15.11

let me have a look at that one, as I ran it before locally.

**Comment by lilic** [comment]
Ah its green now? 🎉 👏

**Comment by serathius** [comment]
When it flakes, try try and try again.

**Comment by serathius** [comment]
I disabled some tests that just failed for me, please verify if those make sense

**Review by ptabor — APPROVED** [review]

**Review by hexfusion — APPROVED** [review]

**Comment by hexfusion** [comment]
lets start here thanks!

**Pull request merged**
