### PR TITLE
tools/benchmark: support --count-only for range

### PR DESCRIPTION
**Pull request by fuweid**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]

**Comment by fuweid** [comment]
I think the failed case can be fixed by #16173

```
2023-07-07T07:34:49.8130130Z /home/runner/work/etcd/etcd/bin/etcdctl (/home/runner/work/etcd/etcd/bin/etcdctl_--insecure-transport=false_--insecure-skip-tls-verify=true_--endpoints=https://localhost:20000_user_add_:foobar_--interactive=false_-w_json) (37413): Error: empty user name is not allowed
2023-07-07T07:34:49.8130786Z     user_test.go:78: 
2023-07-07T07:34:49.8131419Z         	Error Trace:	/home/runner/work/etcd/etcd/tests/common/user_test.go:78
2023-07-07T07:34:49.8132759Z         	            				/home/runner/work/etcd/etcd/tests/framework/testutils/execute.go:38
2023-07-07T07:34:49.8133642Z         	            				/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_386.s:1326
2023-07-07T07:34:49.8135645Z         	Error:      	"match not found.  Set EXPECT_DEBUG for more info Errs: [unexpected exit code [128] after running [/home/runner/work/etcd/etcd/bin/etcdctl --insecure-transport=false --insecure-skip-tls-verify=true --endpoints=https://localhost:20000 user add :foobar --interactive=false -w json]], last lines:\n" does not contain "user name"
2023-07-07T07:34:49.8136609Z         	Test:       	TestUserAdd_Simple/ClientAutoTLS/empty_username_not_allowed
2023-07-07T07:34:49.8137197Z     logger.go:130: 2023-07-07T07:34:49.789Z	INFO	closing test cluster...
2023-07-07T07:34:49.8137987Z     logger.go:130: 2023-07-07T07:34:49.789Z	INFO	stopping server...	{"name": "TestUserAdd_SimpleClientAutoTLSempty_username_not_allowed-test-0"}
```

**Review by chaochn47 — APPROVED** [review]

**Review by jmhbnz — APPROVED** [review]
LGTM

**Comment by fuweid** [comment]
ping @ahrtr @serathius

**Comment by fuweid** [comment]
Thanks!

**Pull request merged**
