### PR TITLE
Fixed periodic compaction tests

### PR DESCRIPTION
**Pull request by srivastav-abhishek**
Fixes: #17054 and #17487

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]
LGTM

@jmhbnz @ivanvc

**Review by jmhbnz — APPROVED** [review]
LGTM - Many thanks for addressing these longstanding flakes @srivastav-abhishek

**Review by ivanvc — APPROVED** [review]
LGTM. This is not my area of expertise, but the implementation looks good. Thanks, Abhishek.

**Pull request merged**
