### PR TITLE
Automated cherry pick of #10468 on release-3.4

### PR DESCRIPTION
**Pull request by jingyih**
Cherry pick of #10468 on release-3.4.

#10468: etcdserver: remove auth validation loop

### CODE REVIEW

**Comment by jingyih** [comment]
@mitake @gyuho
#10218 was included in 3.4 release. Let's also cherry pick this. So that on server side there is no auth loop on error `ErrAuthOldRevision`.

**Comment by gyuho** [comment]
lgtm,

can we highlight this change? (e.g. "please handle err auth old revision error in client side")

**Comment by jingyih** [comment]
> can we highlight this change? (e.g. "please handle err auth old revision error in client side")

From client's perspective, they need to handle `ErrAuthOldRevision` w/ or w/o this change. The only difference is that w/o the change, server hangs with all CPU cycles used by the loop.

**Comment by jingyih** [comment]
fmt test failed:

Earlier we merged commit bb5ba14aac5396bf26affdf29a4f57219a52a901 which has a bad commit title. This will make all future PRs in this branch fail the fmt test.

**Comment by xqzhang2015** [comment]
@jingyih is this PR blocked by CI?

**Comment by jingyih** [comment]
> > can we highlight this change? (e.g. "please handle err auth old revision error in client side")
> 
> From client's perspective, they need to handle `ErrAuthOldRevision` w/ or w/o this change. The only difference is that w/o the change, server hangs with all CPU cycles used by the loop.

Given that it is always the case that "client needs to handle ErrAuthOldRevision", do you think this PR needs a changelog highlight?

**Pull request merged**
