### PR TITLE
Increase timeout for deactivating failpoint

### PR DESCRIPTION
**Pull request by serathius**
Caused https://github.com/etcd-io/etcd/actions/runs/8449504923/job/23143725180 flake

cc @ahrtr @jmhbnz @MadhavJivrajani

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
@serathius if you can retrigger the jobs they should be fine, GH had a minor outage which only now got fixed.

**Comment by MadhavJivrajani** [comment]
Hmm

etcd has retriggering of workflows enabled, I'm not sure why this isn't working...

**Comment by serathius** [comment]
Retriggered it manually.

**Pull request merged**
