### PR TITLE
upgrade debian12 & bookworm (pull request 16487)

### PR DESCRIPTION
**Pull request by SagarRawat24**
signed-off-by: Sagar Rawat sagarrawat24291@gmail.com

### CODE REVIEW

**Review by jmhbnz — APPROVED** [review]
LGTM Once tests green.  Thanks @SagarRawat24.

@ahrtr can you please kick these off?

Edit: Note fixes https://github.com/etcd-io/etcd/issues/16462

**Comment by ahrtr** [comment]
This PR is breaking `FAIL: TestConnectionMultiplexing/ServerTLS/ClientTLS/curl/http1.0`. 

It looks like http 1.0 isn't supported any more in go:1.20-bookworm. Since HTTP 1.0 has already been obsoleted, it's OK to update the test case.

**Comment by SagarRawat24** [comment]
@jmhbnz  should we update the test case from HTTP 1.0 to 1.1 or other version either we don't need to update

**Comment by jmhbnz** [comment]
> @jmhbnz should we update the test case from HTTP 1.0 to 1.1 or other version either we don't need to update

Please remove the "1.0" entry in this line:

https://github.com/etcd-io/etcd/blob/e4e05c5713300d131e0c55af3fdb60d315c3b17f/tests/e2e/cmux_test.go#L124

**Pull request closed without merging**
