### PR TITLE
pkg/debugutil: add both on-cpu & off-cpu profiling support

### PR DESCRIPTION
**Pull request by wilsonwang371**
fgprof is a useful profiler for both on-cpu & off-cpu profiling. I am using it to profile some of the tricky problems in etcd. I think this will be very helpful for us when debugging using both on-cpu & off-cpu approach.

Signed-off-by: Wilson Wang <wilsonny371@gmail.com>

### CODE REVIEW

**Comment by wilsonwang371** [comment]
@ptabor 
Hi Piotr, can you give me some suggestions on this? Do you think we can use fgprof in etcd?

Btw, can you give me some context on the failures? I am not quite sure about the failures here.

**Comment by ptabor** [comment]
Please try: 
```
go mod tidy
./scripts/fix.sh
```
in the root repo dir. Usually helps with such failure.

**Comment by ptabor** [comment]
A.d. your question... 

I don't see any problems with such dependency for etcd-server. 
I feel kind of unconfortable about adding more (transitive) dependencies to etcd-client, that are becoming
dependencies of etcd users as well. 

I wonder whether we should split the pkg into pkg/light, such that client-only dependencies are isolated.

**Comment by wilsonwang371** [comment]
> A.d. your question...
> 
> I don't see any problems with such dependency for etcd-server.
> I feel kind of unconfortable about adding more (transitive) dependencies to etcd-client, that are becoming
> dependencies of etcd users as well.
> 
> I wonder whether we should split the pkg into pkg/light, such that client-only dependencies are isolated.

Got your point. I think we may need more discussion on this. If I need offcpu analysis, I think the best way would be apply a small patch.

Thanks

**Pull request closed without merging**
