### PR TITLE
embed: Close the Err channel when done.

### PR DESCRIPTION
**Pull request by purpleidea**
This closes the error channel when done to signify that we've exited.

I'm curious if this will pass all the tests. I think this is different than server.StopNotify() which can trigger *before* Stop() is called, where as I'm expecting this to trigger when embed is completely done.

Note: a simpler version might have been to just add a method for e.stopc, but I felt that wouldn't have been as elegant.

Comments welcome.

### CODE REVIEW

**Comment by purpleidea** [comment]
Okay, seems this panics with `	panic: close of nil channel` because the error channel is only initialized half way through the Start method. :/ Feels like maybe this needs a rethink or a refactor of this code, so I'm going to pause this patch for now.

But looking at the code, if the initial Validate fails, the Close will happen and panic the `stopc` anyways. So maybe that's another bug. (Not related to this patch.)

**Comment by gyuho** [comment]
@purpleidea There are some other issues with `embed` package now. We will try to address them and review this before 3.4 release. Thanks!

**Comment by wenjiaswe** [comment]
@wenjiaswe @jingyih

**Comment by ptabor** [comment]
Please rebase if the PR still needed.

**Comment by ptabor** [comment]
Created new variant: https://github.com/etcd-io/etcd/pull/12828.

**Pull request closed without merging**
