### PR TITLE
[3.5] Backport healthcheck code cleanup

### PR DESCRIPTION
**Pull request by siyuanfoundation**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

Cherry-picked necessary changes from https://github.com/etcd-io/etcd/pull/13655 to prepare for the livez/healthz backport.

### CODE REVIEW

**Comment by siyuanfoundation** [comment]
cc @chaochn47 @serathius

**Review by serathius — APPROVED** [review]

**Comment by siyuanfoundation** [comment]
cc @ahrtr

**Comment by ahrtr** [comment]
Please signoff the commit.

**Comment by siyuanfoundation** [comment]
> Please signoff the commit.
done

**Review by ahrtr — APPROVED** [review]

**Pull request merged**
