### PR TITLE
etcd: upgrade go version from 1.21.3 to 1.21.4

### PR DESCRIPTION
**Pull request by arjunmalhotra1**
To keep etcd projects up to date with the latest patch releases & incorporate the latest security updates.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by jmhbnz — COMMENTED** [review]
Hey @arjunmalhotra1 - Thanks for raising this update.

Please ensure your commit is signed so the developer certificate of origin (DCO) check passes, i.e:

```bash
git rebase HEAD~1 --signoff
git push --force
```

**Comment by arjunmalhotra1** [comment]
> Hey @arjunmalhotra1 - Thanks for raising this update.
> 
> Please ensure your commit is signed so the developer certificate of origin (DCO) check passes, i.e:
> 
> ```shell
> git rebase HEAD~1 --signoff
> git push --force
> ```

Much thanks for the commands I was struggling a bit with it, regular rebase was not working.

**Comment by arjunmalhotra1** [comment]
Thank you @jmhbnz :)

**Comment by jmhbnz** [comment]
Hey @arjunmalhotra1 - As described in https://github.com/etcd-io/etcd/issues/16891 can you also please raise pull requests to update the golang version for `release-3.5` and `release-3.4` branches 🙏🏻

**Pull request merged**
