### PR TITLE
etcdserver: cherry-pick skip client san verification option for 3.2 version. 

### PR DESCRIPTION
**Pull request by andyliuliming**

### CODE REVIEW

**Comment by andyliuliming** [comment]
will also pick the test case soon.

**Comment by wenjiaswe** [comment]
Add original PR link: #10524 . Similar to #11196, 3.2 cherry pick involves a little more code change, lgtm for me, please make sure all all related tests are tested and passed (not sure if travis test include all necessary one, e2e, functional, unit and integration).

Defer to @hexfusion to decide if this is feasible to backport to previous version. Note: this does not change the default behavior.

It would be great if you could also update the documentation: #11045, Documentation/op-guide/configuration.md and CHANGELOG.

**Comment by andyliuliming** [comment]
@wenjiaswe thanks for the review.
updated the document &
send another PR to add the changelog:
https://github.com/etcd-io/etcd/pull/11219
because did not found the changelog file in this release branch.

**Comment by wenjiaswe** [comment]
lgtm, thanks!

**Comment by andyliuliming** [comment]
Hi @wenjiaswe @gyuho, when would the 3.2.28 version been released?
thanks.

**Comment by andyliuliming** [comment]
Hi @jpbetz may I know when would 3.2.28 been release?
we need to upgrade the 3.1.x version to 3.2.x version and then to higher versions. thanks very much.

**Comment by andyliuliming** [comment]
@gyuho could you please help cut one new release of 3.2? thanks.

**Comment by wenjiaswe** [comment]
@andyliuliming @gyuho we have a couple outstanding etcd 3.2 fixes we'd like to merge (soon) and then we'll release. Thank you!

**Comment by andyliuliming** [comment]
@wenjiaswe thanks for the response.

**Pull request merged**
