### PR TITLE
Rename mixin for kube-prometheus backward compatibility

### PR DESCRIPTION
**Pull request by spzala**
The change of dir name is causing warnings for projects
that allow legacy imports (like kube-prometheus) because
there already a dir named mixin. 

For example,
WARN: cannot link 'github.com/etcd-io/etcd/contrib/mixin' to '/home/ubuntu/src/github.com/some/repo/jsonnet/tests/vendor/mixin', because package 'github.com/thanos-io/thanos/mixin' already uses that name. The absolute import still works
WARN: cannot link 'github.com/prometheus-operator/prometheus-operator/jsonnet/mixin' to '/home/ubuntu/src/github.com/some/repo/jsonnet/tests/vendor/mixin', because package 'github.com/thanos-io/thanos/mixin' already uses that name. The absolute import still works

### CODE REVIEW

**Comment by spzala** [comment]
related,
https://github.com/prometheus-operator/kube-prometheus/pull/932
https://github.com/etcd-io/etcd/pull/12686

**Comment by spzala** [comment]
@underrun we will wait on before merging until you or someone from your team tell us to prevent any breaking../cc @ptabor

**Comment by underrun** [comment]
this can be closed without merge - kube-prometheus can fix this issue by adding a non-colliding name to their jsonnetfile, and at this point the name change won't affect older versions either.

thank you so much for working through naming and location issues!

**Comment by spzala** [comment]
@underrun you are welcome, and perfect! Glad that proper fix is in place :)

**Pull request closed without merging**
