### PR TITLE
Makefile: add .PHONY: clean

### PR DESCRIPTION
**Pull request by imalasong**

### CODE REVIEW

**Comment by ivanvc** [comment]
Hi, @imalasong. Thanks for the pull request. Please ensure your commit is signed so the developer certificate of origin (DCO) check passes, i.e:

```
git rebase HEAD~1 --signoff
git push --force
```

**Comment by imalasong** [comment]
> Hi, @imalasong. Thanks for the pull request. Please ensure your commit is signed so the developer certificate of origin (DCO) check passes, i.e:
> 
> ```
> git rebase HEAD~1 --signoff
> git push --force
> ```

ok

**Comment by ivanvc** [comment]
@imalasong, I noticed that `all`, `verify`, and `fix` are not phony targets either. Do you have the capacity to address them? It's fine if you add them to a follow-up PR.

**Comment by imalasong** [comment]
> @imalasong, I noticed that `all`, `verify`, and `fix` are not phony targets either. Do you have the capacity to address them? It's fine if you add them to a follow-up PR.

this ok

**Pull request closed without merging**
