### PR TITLE
auth: Customize the settings of simpleTokenTTL.

### LINKED ISSUE #11978: auth: Customize simpleTokenTTL settings
# version
etcd Version: 3.3.17
Git SHA: 6d80523
Go Version: go1.14.2
Go OS/Arch: linux/amd64

# feature

simple Token TTL default value is `auth.simpleTokenTTL = 5 * time.Minute`

Sometimes, this value is not sufficient for use, I hope it can be given to the user to customize the setting.

https://github.com/etcd-io/etcd/blob/49f91d629a78c3d6ae285aec7f4bb3b00fb49c03/auth/simple_token.go#L40-L41

and 

https://github.com/etcd-io/etcd/blob/49f91d629a78c3d6ae285aec7f4bb3b00fb49c03/auth/simple_token.go#L60-L69

I'll send a PR to fix it.

/cc @gyuho @xiang90 @jpbetz @spzala @jingyih 

#11980

### PR DESCRIPTION
**Pull request by cfc4n**
auth: Customize simpleTokenTTL settings.

simple Token TTL default value is auth.simpleTokenTTL = 5 * time.Minute.

Sometimes, this value is not sufficient for use, I hope it can be given to the user to customize the setting.

Fixes #11978

### CODE REVIEW

**Comment by xiang90** [comment]
What is your use case to shorten this?

**Comment by cfc4n** [comment]
> What is your use case to shorten this?

Please read https://github.com/etcd-io/etcd/issues/11978#issuecomment-641901937 for the reason.

**Comment by cfc4n** [comment]
> @cfc4n meanwhile you wait for reviews, can you please fix this small build error https://travis-ci.com/github/etcd-io/etcd/jobs/344653990#L356 thanks!

OK,I'll finish it today ,but there is not notic by `goword`, and give me that `Skipping goword...`, Can you tell me why?

**Comment by cfc4n** [comment]
> can you also add this change to changelog and reflect in the documentation of the flags?

Do I need to send a new PR for CHANGELOG or in this pr?

**Comment by cfc4n** [comment]
@gyuho PTAL, Thanks.

**Pull request merged**
