### PR TITLE
all: Change Printf and friends to Print if there is no formatting

### PR DESCRIPTION
**Pull request by sashamelentyev**
Signed-off-by: Sasha Melentyev <sasha@melentyev.io>

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @sashamelentyev 

Could anyone also consider to improve the pipeline to discover such issue automatically? cc @tjungblu @cenkalti @vivekpatani

**Review by spzala — APPROVED** [review]
lgtm Thanks @sashamelentyev

**Comment by vivekpatani** [comment]
@ahrtr do you have some tools in mind? I was thinking some sort of overlay, that runs on every PR, and catches these inconsistencies/rules, fails the PR, and tells you what syntax/problems to fix, so that it doesn't enter.

One thing that comes to mind is [SonarCloud](https://docs.sonarcloud.io/improving/pull-request-analysis/), where it catches the stinks/smells of a code, and reports back instantly on the PR.

About already existing code smells, I can work on those, and submit PRs and clean up the code base that way. Feel free to feedback.

**Comment by ahrtr** [comment]
An option is to investigate whether there is an existing linter integrated into https://github.com/golangci/golangci-lint.

**Comment by vivekpatani** [comment]
@ahrtr I won't be able to get to this for at least until the week of 5th December, so if no one takes this up until then, I'll take it up.

**Comment by ahrtr** [comment]
> @ahrtr I won't be able to get to this for at least until the week of 5th December, so if no one takes this up until then, I'll take it up.

Thank you. No problem, it isn't an urgent task.

**Pull request merged**
