### PR TITLE
Rename master to main in README and other *.md files

### PR DESCRIPTION
**Pull request by chalin**
- Renamed `master` to `main` in relevant `*.md` files
  - Contributes to #12949
  - Followup to #12956
- Some copyedits in README

---

- **Note**: I did **not** update `codecov.io` badge because `main` doesn't work.
  - Maybe someone on the team needs to update the [codecov.io/etcd-io/etcd/settings](https://app.codecov.io/gh/etcd-io/etcd/settings)?
  - Badge tests:
    - Using `master` works: [Coverage](https://codecov.io/gh/etcd-io/etcd)
    - Use `main` doesn't: [Coverage](https://codecov.io/gh/etcd-io/etcd)

cc @gyuho @ptabor @hexfusion @nate-double-u

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
@chalin Thanks!

**Comment by chalin** [comment]
All: here's the followup issue for the codecov.io settings update and the badge path change, #13002.

**Comment by hexfusion** [comment]
Really appreciate this @chalin :+1:

**Pull request merged**
