### PR TITLE
tests/robustness: Implement loading client reports

### PR DESCRIPTION
**Pull request by serathius**
This PR makes local investigation of failing robustness workflows easier.
Just download the report and dump them into `./tests/robustness/testdata/` directory and run tests.

Not documenting for now as I want to collect more feedback on the tool.

cc @ahrtr @ptabor @jmhbnz @chaochn47 @fuweid

### CODE REVIEW

**Comment by serathius** [comment]
ping @jmhbnz @chaochn47 @fuweid

**Comment by chaochn47** [comment]
Thanks @serathius! This is great to reproduce the failure by reloading all the operations and validate. I don't have any critical comments. 

I guess the generated client reports is planned to be dropped after getting LGTM labels, right?

**Comment by serathius** [comment]
> I guess the generated client reports is planned to be dropped after getting LGTM labels, right?

No, I want to keep the test data to have an example of how the file structure should look like.

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @serathius great addition.

**Review by fuweid — COMMENTED** [review]
LGTM!

**Pull request merged**
