### PR TITLE
CHANGELOG: Add v3.4.3

### LINKED ISSUE #11353: CHANGELOG-3.4 missing entries
The [CHANGELOG-3.4.md](https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md) file is missing an entry for the [3.4.3](https://github.com/etcd-io/etcd/releases/tag/v3.4.3) release and shows [3.4.2](https://github.com/etcd-io/etcd/releases/tag/v3.4.2) as unreleased.

### PR DESCRIPTION
**Pull request by spzala**
Add v3.4.3 and fix v3.4.2 release date.

Fixes #11353

### CODE REVIEW

**Comment by spzala** [comment]
Thanks @jingyih 
Merging it /cc @gyuho

**Comment by jingyih** [comment]
Just noticed we are missing changelog updates from #11184 and #11211. They are backported to v3.4.2 and v3.3.16.

Context:
#11184 fixes https://github.com/kubernetes/kubernetes/issues/83028
#11211 fixes https://github.com/kubernetes/kubernetes/issues/83550

**Comment by spzala** [comment]
@jingyih ahh :-) I searched for only 3.4.3 changes. I will add them unless you are adding. Thanks!

**Comment by jingyih** [comment]
> @jingyih ahh :-) I searched for only 3.4.3 changes. I will add them unless you are adding. Thanks!

Please go ahead:)

**Comment by spzala** [comment]
:) sounds good, thanks @jingyih

**Comment by spzala** [comment]
> Just noticed we are missing changelog updates from #11184 and #11211. They are backported to v3.4.2 and v3.3.16.
> 
> Context:
> #11184 fixes [kubernetes/kubernetes#83028](https://github.com/kubernetes/kubernetes/issues/83028)
> #11211 fixes [kubernetes/kubernetes#83550](https://github.com/kubernetes/kubernetes/issues/83550)

@jingyih hi, so these both needs to be added in changlog for 3.4.2, 3.3.16 and also 3.5 right? I don't see it's been added anywhere.

**Comment by jingyih** [comment]
> > Just noticed we are missing changelog updates from #11184 and #11211. They are backported to v3.4.2 and v3.3.16.
> > Context:
> > #11184 fixes [kubernetes/kubernetes#83028](https://github.com/kubernetes/kubernetes/issues/83028)
> > #11211 fixes [kubernetes/kubernetes#83550](https://github.com/kubernetes/kubernetes/issues/83550)
> 
> @jingyih hi, so these both needs to be added in changlog for 3.4.2, 3.3.16 and also 3.5 right? I don't see it's been added anywhere.

Yes. I believe they are missing in all change logs.

**Comment by spzala** [comment]
OK, thanks @jingyih !!

**Pull request merged**
