### PR TITLE
Add an option to keep_going with run for modules on failure

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
The existing logic in the function `run_for_modules` exits the loop through modules when there is a failure.

This change adds an environment variable ` KEEP_GOING_MODULE` to have the option to continue running tests in other modules even on failure with one of them.

### CODE REVIEW

**Comment by serathius** [comment]
FYI In https://github.com/etcd-io/etcd/issues/13896#issuecomment-1502846512 we proposed to split/remove `./scripts/test.sh` which is somewhat separate direction from this PR that tries to fix the script.

**Review by jmhbnz — APPROVED** [review]
As mentioned above we have a plan to restructure how the test scripts work in future. Please feel welcome to continue with that after this merges if you are interested.

Putting the future changes aside, in the interim this change itself looks OK to me, thanks @Rajalakshmi-Girish.

**Comment by ahrtr** [comment]
Previously you added `PASSES_CONTINUE` in https://github.com/etcd-io/etcd/pull/15813; now you add `KEEP_GOING_MODULE` in this PR. Can we have consistent naming?
- `KEEP_GOING_TESTSUITE` or `KEEP_GOING_SUITE`
- `KEEP_GOING_MODULE`

**Comment by Rajalakshmi-Girish** [comment]
Messed up while rebasing and resolving conflicts :(

**Pull request closed without merging**
