### PR TITLE
lease: cleanup typo words in lessor.go

### PR DESCRIPTION
**Pull request by ethan-daocloud**
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>

Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by jingyih** [comment]
Thanks!  Could you change commit title to use format "<package>:<description>", something like "lease: fix typo".

**Comment by ethan-daocloud** [comment]
> Thanks! Could you change commit title to use format ":", something like "lease: fix typo".

@jingyih 
sure. is that ok now?

**Comment by jingyih** [comment]
> > Thanks! Could you change commit title to use format ":", something like "lease: fix typo".
> 
> @jingyih
> sure. is that ok now?

I meant the commit title. Otherwise the test will fail:
https://travis-ci.com/etcd-io/etcd/jobs/225892091#L582

**Comment by ethan-daocloud** [comment]
@jingyih 
Done, thank you.

**Pull request merged**
