### PR TITLE
Try to deflake testing raftAfterSaveSleep failpoint

### PR DESCRIPTION
**Pull request by serathius**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by serathius** [comment]
I think I found the root cause

```
[0;94m% 'gofail' 'enable' 'server/etcdserver/' 'server/lease/leasehttp' 'server/mvcc/' 'server/wal/' 'server/mvcc/backend/'
[0mgo: downloading go.etcd.io/gofail v0.1.0
go: downloading github.com/stretchr/testify v1.8.4
go: removed go.etcd.io/etcd/etcdctl/v3 v3.5.15
go: removed go.etcd.io/etcd/etcdutl/v3 v3.5.15
go: removed go.etcd.io/etcd/server/v3 v3.5.15
go: removed go.etcd.io/etcd/tests/v3 v3.5.15
go: downgraded go.etcd.io/gofail v0.2.0 => v0.1.0
go: downgraded go.etcd.io/gofail v0.2.0 => v0.1.0
go: downgraded go.etcd.io/gofail v0.2.0 => v0.1.0
go: downgraded go.etcd.io/gofail v0.2.0 => v0.1.0
```

**Comment by serathius** [comment]
cc @henrybear327

**Comment by henrybear327** [comment]
> I think I found the root cause, the we build older releases the gofail is downgraded :(
> 
> ```
> �[0;94m% 'gofail' 'enable' 'server/etcdserver/' 'server/lease/leasehttp' 'server/mvcc/' 'server/wal/' 'server/mvcc/backend/'
> �[0mgo: downloading go.etcd.io/gofail v0.1.0
> go: downloading github.com/stretchr/testify v1.8.4
> go: removed go.etcd.io/etcd/etcdctl/v3 v3.5.15
> go: removed go.etcd.io/etcd/etcdutl/v3 v3.5.15
> go: removed go.etcd.io/etcd/server/v3 v3.5.15
> go: removed go.etcd.io/etcd/tests/v3 v3.5.15
> go: downgraded go.etcd.io/gofail v0.2.0 => v0.1.0
> go: downgraded go.etcd.io/gofail v0.2.0 => v0.1.0
> go: downgraded go.etcd.io/gofail v0.2.0 => v0.1.0
> go: downgraded go.etcd.io/gofail v0.2.0 => v0.1.0
> ```

Ah ha, good catch!

**Pull request closed without merging**
