### PR TITLE
*: Bump to go 1.17.6

### PR DESCRIPTION
**Pull request by mrueg**
* Bump to golang 1.17.3 (https://groups.google.com/g/golang-announce/c/0fM21h43arc/m/a2Hu_dWRAAAJ)
* Update functional test Dockerfile to go 1.17.3
* Update functional test Dockerfile to fedora 35

### CODE REVIEW

**Comment by justaugustus** [comment]
go1.17.5, which includes some security fixes, is out: https://groups.google.com/g/golang-announce/c/hcmEScgc00k

**Comment by mrueg** [comment]
Thanks @justaugustus bumped it to 1.17.5

@serathius  @hexfusion I've added a small change to the makefile which will build it locally. This should make it easier to bump the versions in the future, as semaphore will pass then.

**Review by hexfusion — APPROVED** [review]

**Comment by justaugustus** [comment]
> Thanks @justaugustus bumped it to 1.17.5

No worries! One more thing!
Ensure any references to golang/x/net are updated to a remediated version (ref: https://github.com/kubernetes/kubernetes/pull/106949).

**Review by serathius — APPROVED** [review]

**Comment by mrueg** [comment]
Not sure why the functional DELAY_PEER_PORT_TX_RX_LEADER_UNTIL_TRIGGER_SNAPSHOT test failed, I rebased onto latest master.

**Comment by justaugustus** [comment]
FYI go1.17.6 is out: https://groups.google.com/g/golang-announce/c/95ZD3rKn4DI

**Comment by mrueg** [comment]
@serathius @hexfusion could you approve the workflows to run again?

**Review by serathius — APPROVED** [review]
I can, but I don't think I have permissions to enable CI.

**Review by spzala — COMMENTED** [review]
Sounds great. Thanks @mrueg Running cI.

**Comment by mrueg** [comment]
@hexfusion @ptabor looks like all tests except for codeql passed :) Can we merge and maybe backport to 3.5?

**Review by ptabor — APPROVED** [review]
Thank you.

**Pull request merged**
