### PR TITLE
[2024-07-03] Manual Dependency Bump

### PR DESCRIPTION
**Pull request by ArkaSaha30**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

Dependabot raised raised the following PRs:
- https://github.com/etcd-io/etcd/pull/18258
- https://github.com/etcd-io/etcd/pull/18261

### CODE REVIEW

**Comment by henrybear327** [comment]
@ArkaSaha30 the commit message format according to the guide is of the format `"dependency: bump github.com/spf13/cobra from 1.6.1 to 1.7.0"` :)

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @ArkaSaha30.

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Comment by ivanvc** [comment]
@ArkaSaha30, oh I just noticed that I think you missed github.com/prometheus/common from /tools/mod (#18261).

I'm checking why `make verify-dep` didn't fail, and it's because it doesn't check the dependencies inside `/tools/mod` :scream:

**Comment by ahrtr** [comment]
> @ArkaSaha30, oh I just noticed that I think you missed `github.com/prometheus/common` from `/tools/mod` (#18261).
> 
> I'm checking why `make verify-dep` didn't fail, and it's because it doesn't check the dependencies inside `/tools/mod` 😱

Thanks @ivanvc. Let's just deliver a separate PR to fix it.

**Comment by henrybear327** [comment]
@ArkaSaha30 please update https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit?gid=1394774387#gid=1394774387 with the link to this PR (and the follow-up PR)! Thanks

**Pull request merged**
