### PR TITLE
tests: Run linearizability tests on arm64

### PR DESCRIPTION
**Pull request by serathius**
As functional tests were removed, I'm adding back the matching linearizability tests.
cc @ahrtr @ptabor 
For now running on PR, will be changed to periodic.

### CODE REVIEW

**Comment by ahrtr** [comment]
Please consider to add label `self-hosted`,
FYI. https://github.com/etcd-io/etcd/pull/15233#issuecomment-1426876260

**Comment by serathius** [comment]
I'm having problems with passing labels through template input. It requires static typing, but `runs-on` field is dynamically typed :(. It can be a string `ubuntu-latest`, a list ["Linux", "Arm64] and even a map to select labels.

**Comment by serathius** [comment]
Making as draft until I figure it out.

**Comment by serathius** [comment]
Looking for workaround based on https://github.com/community/community/discussions/11692?sort=old

**Comment by serathius** [comment]
Ok, managed to get the linearizability test to start, but I'm getting an error:
```
linearizability_test.go:175: cannot start: match not found.  Set EXPECT_DEBUG for more info Errs: [unexpected exit code [2] after running [/home/runner/actions-runner/_work/etcd/etcd/bin/etcd --name TestLinearizabilityClusterOfSize1LowTraffic-test-0 --listen-client-urls http://localhost:20000 --advertise-client-urls http://localhost:20000 --listen-peer-urls http://localhost:20001 --initial-advertise-peer-urls http://localhost:20001 --initial-cluster-token new --data-dir /tmp/TestLinearizabilityClusterOfSize1LowTraffic4200436402/001 --snapshot-count 100 --experimental-compaction-batch-limit 100 --experimental-watch-progress-notify-interval 100ms --initial-cluster TestLinearizabilityClusterOfSize1LowTraffic-test-0=http://localhost:20001 --initial-cluster-state new]], last lines:
        panic: failed to open database [recovered]
        	panic: failed to open database
        
        goroutine 1 [running]:
        go.etcd.io/etcd/server/v3/verify.Verify.func1()
        	go.etcd.io/etcd/server/v3/verify/verify.go:66 +0x334
        panic({0x9fd7e0, 0x40002cc5b0})
        	runtime/panic.go:884 +0x20c
        go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x2?, {0x4000168128?, 0x0?, 0x0?})
        	go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x7c
        go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x40003e2dd0, {0x4000406300, 0x2, 0x2})
        	go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x2bc
        go.uber.org/zap.(*Logger).Panic(0x40000123c0?, {0xbb918e?, 0x4000168388?}, {0x4000406300, 0x2, 0x2})
        	go.uber.org/zap@v1.24.0/logger.go:258 +0x54
        go.etcd.io/etcd/server/v3/storage/backend.newBackend({{0x40000123c0, 0x4d}, 0x5f5e100, 0x2710, {0x0, 0x0}, 0x2[80](https://github.com/etcd-io/etcd/actions/runs/4275560286/jobs/7443004280#step:5:81)000000, 0x400041a070, 0x0, 0x0, ...})
        	go.etcd.io/etcd/server/v3/storage/backend/backend.go:186 +0x280
        go.etcd.io/etcd/server/v3/storage/backend.NewDefaultBackend(0xffffd847ad4b?, {0x40000123c0?, 0xbb6630?})
        	go.etcd.io/etcd/server/v3/storage/backend/backend.go:170 +0xb0
        go.etcd.io/etcd/server/v3/verify.Verify({{0xffffd847ad4b?, 0xb?}, 0x8a?, 0x400041a070?})
        	go.etcd.io/etcd/server/v3/verify/verify.go:72 +0x290
        go.etcd.io/etcd/server/v3/verify.VerifyIfEnabled({{0xffffd847ad4b?, 0x0?}, 0x0?, 0x400041a070?})
        	go.etcd.io/etcd/server/v3/verify/verify.go:90 +0x58
        go.etcd.io/etcd/server/v3/verify.MustVerifyIfEnabled({{0xffffd847ad4b?, 0xbb2c80?}, 0x48?, 0x400041a070?})
        	go.etcd.io/etcd/server/v3/verify/verify.go:99 +0x38
        go.etcd.io/etcd/server/v3/embed.(*Etcd).Close.func1()
        	go.etcd.io/etcd/server/v3/embed/etcd.go:395 +0x5c
        go.etcd.io/etcd/server/v3/embed.(*Etcd).Close(0x400057ce00)
        	go.etcd.io/etcd/server/v3/embed/etcd.go:455 +0x60c
        go.etcd.io/etcd/server/v3/embed.StartEtcd.func1()
        	go.etcd.io/etcd/server/v3/embed/etcd.go:110 +0x88
        go.etcd.io/etcd/server/v3/embed.StartEtcd(0x4000329500)
        	go.etcd.io/etcd/server/v3/embed/etcd.go:126 +0x58c
        go.etcd.io/etcd/server/v3/etcdmain.startEtcd(0x4000329500)
        	go.etcd.io/etcd/server/v3/etcdmain/etcd.go:206 +0x24
        go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2({0x40001[82](https://github.com/etcd-io/etcd/actions/runs/4275560286/jobs/7443004280#step:5:83)680, 0x19, 0x1a})
        	go.etcd.io/etcd/server/v3/etcdmain/etcd.go:129 +0xd58
        go.etcd.io/etcd/server/v3/etcdmain.Main({0x4000182680?, 0x19, 0x1a})
        	go.etcd.io/etcd/server/v3/etcdmain/main.go:40 +0x120
        main.main()
        	go.etcd.io/etcd/server/v3/main.go:31 +0x40
```

**Comment by jmhbnz** [comment]
Closing this as the work has been completed in https://github.com/etcd-io/etcd/pull/15886 ✔️

**Pull request closed without merging**
