### PR TITLE
tests: remaining errors.Is conversions

### PR DESCRIPTION
**Pull request by redwrasse**
Remaining errors.Is conversions for the `tests` directory, as part of https://github.com/etcd-io/etcd/issues/18576.

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]

**Comment by ivanvc** [comment]
Hi @redwrasse, thanks for your pull request. I think for this PR we may be missing (but correct me if I'm wrong):

* `tests/integration/v3_grpc_test.go:1565`
* `tests/integration/v3_lease_test.go:1089`
* `tests/integration/clientv3/watch_test.go:812`
* `tests/integration/clientv3/maintenance_test.go:307`

**Comment by redwrasse** [comment]
Let me add those in, thanks @ivanvc.

**Comment by redwrasse** [comment]
I must have messed this one up too with a force-push. Will try to fix tomorrow.

**Comment by redwrasse** [comment]
Opening a new draft PR here https://github.com/etcd-io/etcd/pull/18634- this time won't force push and will squash commits once it's all done.

**Pull request closed without merging**
