### PR TITLE
gosum: fix can not go build before go mod verify

### PR DESCRIPTION
**Pull request by haroldHT**
fix this problem
#10469

### CODE REVIEW

**Comment by gyuho** [comment]
Which Go version are you using?

**Comment by hexfusion** [comment]
ref: https://github.com/etcd-io/etcd/issues/10437#issuecomment-458509021

**Comment by haroldHT** [comment]
@gyuho @hexfusion 
## Environment:
* etcd.exe --version
  etcd Version: 3.3.0+git
  Git SHA: [2cf9e51](https://github.com/etcd-io/etcd/commit/24fc2a983ae39b4fe09cef3db434c812fdc97cff)
  Go Version: go1.11.4
  Go OS/Arch: CentOS Linux release 7.5.1804 (Core)

**Comment by gyuho** [comment]
Closing in favor of https://github.com/etcd-io/etcd/pull/10486.

**Pull request closed without merging**
