### PR TITLE
[3.5] etcdserver: bump OpenTelemetry to 1.0.1 and gRPC to 1.41.0

### PR DESCRIPTION
**Pull request by ahrtr**
Fix https://github.com/etcd-io/etcd/issues/14311 by cherry picking https://github.com/etcd-io/etcd/pull/13361 to 3.5.

Signed-off-by: Benjamin Wang <wachao@vmware.com>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
cc @spzala @ptabor @serathius Please take a look, thx.

cc @nikhita @dims

**Comment by ahrtr** [comment]
cc @dashpole 

Just rebased the PR to merge @damemi 's PR https://github.com/etcd-io/etcd/pull/14318

**Review by spzala — APPROVED** [review]
lgtm
Thanks, @ahrtr !! Please squash commits before merging.

**Review by dashpole — APPROVED** [review]

**Comment by ahrtr** [comment]
> lgtm Thanks, @ahrtr !! Please squash commits before merging.

Thanks @spzala . I intentionally created a separate commit for each different kind of change for better review and future archaeology (debug).

**Comment by ahrtr** [comment]
Thanks @dashpole for the review as well.

**Comment by spzala** [comment]
> > lgtm Thanks, @ahrtr !! Please squash commits before merging.
> 
> Thanks @spzala . I intentionally created a separate commit for each different kind of change for better review and future archaeology (debug).

Ok, cool. Thanks @ahrtr !!

**Pull request merged**
