### PR TITLE
[3.4] etcd: upgrade go version from 1.20.10 to 1.20.11

### PR DESCRIPTION
**Pull request by arjunmalhotra1**
To keep etcd projects up to date with the latest patch releases & incorporate the latest security updates.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by serathius** [comment]
Please sign DCO

**Comment by ahrtr** [comment]
Also refer to https://github.com/etcd-io/etcd/pull/16901

**Review by jmhbnz — CHANGES_REQUESTED** [review]
Hey @arjunmalhotra1 - I was expecting this backport to only be a patch version increase from `1.20.10` to `1.20.11` as described in the associated issue https://github.com/etcd-io/etcd/issues/16891.

I don't think the community has broadly agreed to bump minor version for stable version policy yet?

**Comment by arjunmalhotra1** [comment]
Thanks @jmhbnz I have fixed it.

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @arjunmalhotra1

**Review by fuweid — APPROVED** [review]
LGTM

**Review by ahrtr — APPROVED** [review]
lgtm

Thanks.

**Pull request merged**
