### PR TITLE
Update changelog for 3.4.28

### PR DESCRIPTION
**Pull request by ahrtr**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
Waiting for @chaochn47 to finish bumping grpc-go version for 3.4.

**Comment by ahrtr** [comment]
All items planned for 3.4.28 are done!

**Comment by ahrtr** [comment]
cc @serathius

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @ahrtr

**Pull request merged**
