### PR TITLE
pkg: replace the deprecated Expect with ExpectWithContext in pkg/expect/expect_test.go

### PR DESCRIPTION
**Pull request by demoManito**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

remove assert library

reference: https://github.com/golang/go/wiki/TestComments#assert-libraries

### CODE REVIEW

**Comment by ahrtr** [comment]
It's an interesting discussion. Points from my side,
1. Obviously, the benefit of `github.com/stretchr/testify` is it can simplify the implementation, and accordingly have cleaner code. Personally I don't agree with the point from [TestComments#assert-libraries](https://github.com/golang/go/wiki/TestComments#assert-libraries). `testify` doesn't create a mini-language, instead it just exposes some useful and easy-to-understand functions.
2. The `github.com/stretchr/testify` is heavily used in etcd, not only the `pkg` module. It needs some effort to totally get rid of it.

**Comment by demoManito** [comment]
> It's an interesting discussion. Points from my side,
> 
> 1. Obviously, the benefit of `github.com/stretchr/testify` is it can simplify the implementation, and accordingly have cleaner code. Personally I don't agree with the point from [TestComments#assert-libraries](https://github.com/golang/go/wiki/TestComments#assert-libraries). `testify` doesn't create a mini-language, instead it just exposes some useful and easy-to-understand functions.
> 2. The `github.com/stretchr/testify` is heavily used in etcd, not only the `pkg` module. It needs some effort to totally get rid of it.

Good morning, thank you for your reply

it takes a lot of effort to get rid of him completely. Deleting the assert library in the pkg is just an attempt, because there are relatively few places to use assert in this package. There are many cases where t.Error and assert are mixed in etcd. I want to try to unify the etcd testing style.

**Comment by ahrtr** [comment]
My suggestion is to keep using `github.com/stretchr/testify` because it can simplify the test code, accordingly cleaner.

**Comment by demoManito** [comment]
> My suggestion is to keep using `github.com/stretchr/testify` because it can simplify the test code, accordingly cleaner.

ok, the modification of the deletion assertion library has been withdrawn, and the change to replace the deprecated method is reserved

**Comment by ahrtr** [comment]
Please signoff the commit: `git rebase HEAD~1 --signoff`

**Comment by demoManito** [comment]
> Please signoff the commit: `git rebase HEAD~1 --signoff`

modified

**Comment by ahrtr** [comment]
Please also update the commit message (see suggestion below) per [CONTRIBUTING.md#commit-your-change](https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#commit-your-change)

```
pkg: replace the deprecated Expect with ExpectWithContext in pkg/expect/expect_test.go
```

**Comment by ahrtr** [comment]
Run `git commit --amend`, then modify the commit message.

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @demoManito for your first contribution!

**Pull request merged**
