### PR TITLE
Update 3.5 changelog to cover the two bug fixes related to leases revoke and checkpoint

### PR DESCRIPTION
**Pull request by ahrtr**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by serathius — APPROVED** [review]
Would prefer to link to original PRs as they include full explanation of the issues vs backport PR that just links to original PR.
However as we discussed it before it's not critical. 

Approving it and leaving it up to @ahrtr to decide if they want to fix before merge.

**Comment by ahrtr** [comment]
Thanks @serathius for the feedback. There are links between PRs (the original PRs linking to the backport PR), so it would be OK. 

Personally, I prefer to the rules: 
1. each changelog item for a specific version (i.e. 3.6) only links to PR(s) of that specific version;
2. Each PR should link to the related issue if present;
3. Backport PR should have link(s) to the original PR(s). 

Please see diagram below,
changelog_links

**Comment by ahrtr** [comment]
This comment is raised multiple times, It would be better to get more feedback from others although it isn't a big deal. cc @spzala @ptabor for opinions.

**Comment by serathius** [comment]
Let's merge it and move the discussion to separate issue.

**Pull request merged**
