### PR TITLE
cherry pick "etcd_cluster_version" metric" (#10257, #11233, #11254, #11265) to release-3.3

### PR DESCRIPTION
**Pull request by wenjiaswe**
Cherry pick of #10257 on release-3.3.

#10257: etcdserver/*: add "etcd_cluster_version" metric

### CODE REVIEW

**Comment by wenjiaswe** [comment]
hmm, failed test said 

`etcd_release_upgrade_test.go:108: failed get with curl (read /dev/ptmx: input/output error (expected "etcd_cluster_version{cluster_version=\"3.3\"} 1", got ["# HELP etcd_cluster_version Which version is running. 1 for 'cluster_version' label with current cluster version\r\n" "# TYPE etcd_cluster_version gauge\r\n" "etcd_cluster_version{cluster_version=\"3.3.0\"} 1\r\n"`

But I brought up an etcd node and checked the metrics it is as expected:
`etcd_cluster_version{cluster_version="3.3"} 1`

**Comment by jingyih** [comment]
I can take a look. This test error is skipped in current master branch. Might be an actual bug we did not catch in the master before backporting.

**Comment by jingyih** [comment]
Oh I misread. This is a test fail on a backported test. No wonder I cannot reproduce locally...

**Comment by jingyih** [comment]
Please also cherry pick #11265 to fix the test failure.

**Comment by wenjiaswe** [comment]
@jingyih yes, the third commit already includes #11265, [failure mentioned earlier](https://github.com/etcd-io/etcd/pull/11261#issuecomment-542640433) is fixed:

`
=== RUN   TestReleaseUpgrade
--- PASS: TestReleaseUpgrade (5.22s)
`

but travis still failed:
`
Too many goroutines running after all test(s).
1 instances of:
os.(*Process).Release(...)
	/home/travis/.gimme/versions/go1.12.9.linux.amd64/src/os/exec.go:108 +0x5e
FAIL	github.com/coreos/etcd/tests/e2e	155.956s
`

**Comment by wenjiaswe** [comment]
@gyuho @jingyih Test passed now, looks like [this failure] is just flaky. Please help to review. Thanks!

**Comment by gyuho** [comment]
lgtm, thanks @jingyih @wenjiaswe

**Pull request merged**
