### PR TITLE
[2023-05-25] Bump dependencies identified by dependabot

### PR DESCRIPTION
**Pull request by lavacat**
This pull request completes this weeks etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1DDWzbcOx1p32MhyelaPZ_SfYtAD6xRsrtGRZ9QXPOyQ/edit#gid=0) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

Summary of actions:
- [x]  https://github.com/etcd-io/etcd/pull/15934
- [x] https://github.com/etcd-io/etcd/pull/15930
- [ ] https://github.com/etcd-io/etcd/pull/15937 - merged direct
- [ ] https://github.com/etcd-io/etcd/pull/15936 - Closed, purely indirect
- [ ] https://github.com/etcd-io/etcd/pull/15935 - Closed, blocked
- [ ] https://github.com/etcd-io/etcd/pull/15933 -  Closed, purely indirect
- [ ] https://github.com/etcd-io/etcd/pull/15932 - Closed, blocked
- [ ] https://github.com/etcd-io/etcd/pull/15931 - Closed, purely indirect

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]
LGTM

Nice! Thanks @lavacat

**Comment by ahrtr** [comment]
Just a reminder, [optional] for some purely indirect dependencies, we should also consider to 
- try to remove the dependency on them;
- or drive the modules, which have direct dependency on them, to bump them.

**Comment by ahrtr** [comment]
FYI. https://github.com/etcd-io/etcd/pull/15862#issuecomment-1545163060

**Review by jmhbnz — APPROVED** [review]

**Review by fuweid — APPROVED** [review]
LGTM

**Pull request merged**
