### PR TITLE
Robustness dir cleanup

### PR DESCRIPTION
**Pull request by serathius**
Keep only minimal files needed in robustness.

cc @ahrtr @siyuanfoundation @MadhavJivrajani @fuweid @henrybear327

### CODE REVIEW

**Comment by serathius** [comment]
ping @ahrtr @siyuanfoundation @MadhavJivrajani @fuweid @henrybear327

**Review by fuweid — APPROVED** [review]
LGTM

**Review by henrybear327 — APPROVED** [review]
Thanks for the refactoring and clean up @serathius :)

**Pull request merged**
