### PR TITLE
*: bump protoc to 3.6.1 and fix genproto.sh

### PR DESCRIPTION
**Pull request by hexfusion**
Since the update to go mod genproto.sh fails to run. This PR bumps protoc to latest (v3.6.1) and fixes genproto.sh.

Fixes: https://github.com/etcd-io/etcd/issues/10336

/cc @gyuho 

ref: https://github.com/protocolbuffers/protobuf/releases

### CODE REVIEW

**Comment by hexfusion** [comment]
Ping @gyuho any input here?

**Comment by spzala** [comment]
LGTM

**Comment by spzala** [comment]
Per @gyuho 's suggestion in the issue to bump to 3.6.1 it seems like we can safely merge it.

**Comment by jingyih** [comment]
cc @jpbetz

**Pull request merged**
