### PR TITLE
deleted infra-guide

### PR DESCRIPTION
**Pull request by TheInvincibleRalph**

### CODE REVIEW

**Comment by TheInvincibleRalph** [comment]
@fuweid @technoweenie @drnic @bmizerany

Cleaned up the Infra-guide folder. Kindly review.

**Review by jmhbnz — COMMENTED** [review]
Hi @TheInvincibleRalph - Thanks for tidying this up.  Can you please sign your commit to ensure the Developer Certificate of Origin check passes, i.e.:

```bash
git reset --soft HEAD~1
git commit --signoff --message "<message>"
git push --force
```

Additionally it looks like the directory would be empty after that file is removed so we may as well remove the directory also.

**Comment by TheInvincibleRalph** [comment]
@jmhbnz. Thank you for the help. Also, I deleted the directory as well.

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks for helping with this @TheInvincibleRalph 🙏🏻

**Comment by TheInvincibleRalph** [comment]
Thank you too, @jmhbnz

**Pull request merged**
