### PR TITLE
Replace unnecessary Lock()/Unlock()s with RLock()/RUnlock()s

### PR DESCRIPTION
**Pull request by CaojiamingAlan**
Follow up https://github.com/etcd-io/etcd/pull/16068#discussion_r1263664700

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by iuriatan — APPROVED** [review]

**Comment by ahrtr** [comment]
Is this PR still draft?

**Review by fuweid — APPROVED** [review]
LGTM

**Review by ahrtr — APPROVED** [review]
LGTM 

thx @CaojiamingAlan 

Could you also backport this PR to 3.5?

**Review by jmhbnz — APPROVED** [review]
LGTM

**Comment by CaojiamingAlan** [comment]
Feels like it is unnecessary to backport this to v3.4. The only place I found that we can replace is in `restore()`. Here's the pending PR: #16298

**Comment by ahrtr** [comment]
> Feels like it is unnecessary to backport this to v3.4. The only place I found that we can replace is in `restore()`. Here's the pending PR: #16298

Right. restore isn't a frequent operation, let's keep it as it's for 3.4.

For 3.5, I prefer to backport the PR, because obviously it has performance impact on Non-k8s use case when auth is enabled.

**Review by serathius — APPROVED** [review]
ok, let's just merge

**Pull request merged**
