### PR TITLE
Fix data race in testWatchOverlapContextCancel #14003

### PR DESCRIPTION
**Pull request by eval-exec**
This PR fix data race in `testWatchOverlapContextCancel()`

See #14003

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]
LGTM, thank you.

I believe this isn't the only place which has such similar issue. I am thinking probably we can review the repo, especially the test cases, and provide a better generic solution.

**Comment by eval-exec** [comment]
> LGTM, thank you.
> 
> I believe this isn't the only place which has such similar issue. I am thinking probably we can review the repo, especially the test cases, and provide a better generic solution. 

I would like to work on reviewing etcd's tests cases.

**Review by spzala — APPROVED** [review]
lgtm Thanks @eval-exec

**Comment by spzala** [comment]
> > LGTM, thank you.
> > I believe this isn't the only place which has such similar issue. I am thinking probably we can review the repo, especially the test cases, and provide a better generic solution.
> 
> I would like to work on reviewing etcd's tests cases.

That will be great. Please review, and share your findings/open issues/PR as needed for team's review. Thank you!

**Pull request merged**
