### PR TITLE
Update CHANGELOG 3.4 and 3.5 - initialization for epMu/mu in client context 

### PR DESCRIPTION
**Pull request by henrybear327**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
Please rebase this PR, the go version has already been bumped.

**Comment by ahrtr** [comment]
@henrybear327 does 3.4 have similar issue?

**Comment by henrybear327** [comment]
> @henrybear327 does 3.4 have similar issue?

@ahrtr I didn’t look into it (since the PR discussion only mention 3.5.x), but I will check it in a bit!

**Comment by henrybear327** [comment]
> Please rebase this PR, the go version has already been bumped.

Done as requested!

**Comment by henrybear327** [comment]
> @henrybear327 does 3.4 have similar issue?

I believe that the same issue will happen with `release-3.4`. #17714

**Review by serathius — APPROVED** [review]

**Pull request merged**
