### PR TITLE
*: bump dependabot dependency

### PR DESCRIPTION
**Pull request by vivekpatani**
- https://github.com/etcd-io/etcd/pull/16870
- https://github.com/etcd-io/etcd/pull/16871
- https://github.com/etcd-io/etcd/pull/16872
- https://github.com/etcd-io/etcd/pull/16873
- https://github.com/etcd-io/etcd/pull/16875
- https://github.com/etcd-io/etcd/pull/16878

### CODE REVIEW

**Comment by vivekpatani** [comment]
@ahrtr @jmhbnz @serathius PTAL when you have a few minutes.

**Comment by ahrtr** [comment]
Thanks @vivekpatani 

Please resolve. https://github.com/etcd-io/etcd/issues/16898 firstly. It should can resolve the workflow failure.

**Comment by ahrtr** [comment]
@vivekpatani please rebase this PR. thx

**Comment by vivekpatani** [comment]
@ahrtr rebased...

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Pull request merged**
