### PR TITLE
[2024-09-11] Bump dependency updates identified by dependabot

### PR DESCRIPTION
**Pull request by henrybear327**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

# Summary of actions

## Bumped
- https://github.com/etcd-io/etcd/pull/18566
- https://github.com/etcd-io/etcd/pull/18565
- https://github.com/etcd-io/etcd/pull/18562 + https://github.com/etcd-io/etcd/pull/18567
- https://github.com/etcd-io/etcd/pull/18564 + https://github.com/etcd-io/etcd/pull/18559
- https://github.com/etcd-io/etcd/pull/18558 + https://github.com/etcd-io/etcd/pull/18563
## Fully indirect
- https://github.com/etcd-io/etcd/pull/18560
- https://github.com/etcd-io/etcd/pull/18561

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by henrybear327** [comment]
Looks like there is an issue with one of the dependencies.  I will check in a bit to fix the CI

**Comment by henrybear327** [comment]
> Looks like there is an issue with one of the dependencies. I will check in a bit to fix the CI

Fixed, cc @ivanvc

**Review by ahrtr — APPROVED** [review]
LGTM

cc @jmhbnz @ivanvc

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @henrybear327

**Pull request merged**
