### PR TITLE
[3.5] tools/mod: go mod tidy

### PR DESCRIPTION
**Pull request by vivekpatani**
- perform tidy operation
- https://github.com/etcd-io/etcd/issues/17400
- https://github.com/etcd-io/etcd/issues/17401

### CODE REVIEW

**Comment by vivekpatani** [comment]
@jmhbnz @ivanvc @ahrtr last of the lot.

**Review by fuweid — COMMENTED** [review]
It looks good. Would you mind add `[3.5]` in the pull request's title? thanks

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @vivekpatani 

/retitle [3.5] tools/mod: go mod tidy

**Review by fuweid — APPROVED** [review]
LGTM

**Review by ahrtr — APPROVED** [review]

**Pull request merged**
