### PR TITLE
Refactor v2 deprecation tests to allow different cluster config

### PR DESCRIPTION
**Pull request by serathius**
Split from https://github.com/etcd-io/etcd/pull/16989

### CODE REVIEW

**Comment by serathius** [comment]
cc @ahrtr

**Review by chaochn47 — APPROVED** [review]
LGTM, this would be needed to reject unexpected v2 requests stored in WAL.

**Comment by serathius** [comment]
ping @ahrtr

**Review by ahrtr — APPROVED** [review]
lgtm

**Pull request merged**
