### PR TITLE
fix: use require.NoError instead of t.Fatal(err) in tests package (part 1)

### PR DESCRIPTION
**Pull request by mmorel-35**
There is no linter for this.
This uses testify instead of testing for
With 
```go
require.NoError(t, err)

require.Error(t, err)
```
instead of

```go
if err != nil {
    t.Fatal(err)
}


if err == nil {
    t.Fatal(err)
}
```

### CODE REVIEW

**Comment by ahrtr** [comment]
@mmorel-35 Thanks for you constant effort, but please try to make each each such PR as small as possible, i.e < 100 lines of code change, so that each one can be approved & merged soon.

**Review by serathius — APPROVED** [review]

**Comment by serathius** [comment]
Read through it, still +1 to what @ahrtr said. Don't optimize for number of lines changed, optimize for time it takes to review. That will help you land your work faster.

**Comment by serathius** [comment]
Please fix
```
robustness/model/deterministic_test.go:39:6: formatter: use require.NoErrorf (testifylint)
					require.NoError(t, err, "Failed to load state")
```

**Pull request merged**
