### PR TITLE
Modularization: Move dependencies of client (protos, version) to api/ module

### PR DESCRIPTION
**Pull request by ptabor**
There is small amount of code that is needed for client - mostly protos. 

The PR is moving them to 'api' directory such that client can depend on them without depending on the gory details of server.

  - mvcc/mvccpb -> api/mvccpb
  - etcdserver/etcdserverpb  -> api/etcdserverpb
  - etcdserver/api/membership/membershippb  -> api/membershippb
  - auth/authpb -> api/authpb
  - etcdserver/api/v3rpc/rpctypes -> api/v3rpc/rpctypes
  - version -> api/version

Majority of the payload of the CL is a consequence of running `./scripts/genproto.sh` (in a separate commit).
The generated code contains serialized descriptors, so a change in paths is causing a compressed blob regeneration.

### CODE REVIEW

**Comment by jingyih** [comment]
I would prefer to have the APIs (i.e., proto files and the files generated from them) in a separate folder, instead of nested under client folder.
cc @gyuho @xiang90 @spzala

**Comment by ptabor** [comment]
Thank you for feedback. Will move it top level. It means we are going towards following top level modules: 

  - pkg
  - api
  - client
  - server
  - tests
  - etcdctl
  - raft

**Comment by jingyih** [comment]
The top modules looks good to me. Any concerns and comments? @jpbetz @gyuho @xiang90 @spzala

**Comment by ptabor** [comment]
@jingyih Moved the changes to the top-level api/module.

**Pull request merged**
