### PR TITLE
[e2e] Fix bug in EtcdctlV3.HashKV() e2e implementation.

### PR DESCRIPTION
**Pull request by veshij**
Signed-off-by: Oleg Guba <oleg@dropbox.com>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by serathius — APPROVED** [review]

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @veshij 

Could you check whether release-3.5 and 3.4 have this issue and backport accordingly?

**Comment by veshij** [comment]
> LGTM
> 
> Thank you @veshij
> 
> Could you check whether release-3.5 and 3.4 have this issue and backport accordingly?

Sure, I'll need some guidance on how to create a backport PR.

**Comment by ahrtr** [comment]
> Sure, I'll need some guidance on how to create a backport PR.

You just need to create dev branch against release-3.5 and release-3.4 respectively, and make change accordingly.

**Pull request merged**
