### PR TITLE
Clean golang cache for arm64 ci workflows

### PR DESCRIPTION
**Pull request by jmhbnz**
We recently moved to container based nightly arm64 workflow runs which appear to be completing successfully however the e2e common suite is reporting unexpected caching, refer: https://github.com/etcd-io/etcd/actions/runs/5116632303/jobs/9198983536

We have a hypothesis that we can prevent this behavior with `cache: false` on the `setup-go` action, refer discussion in #15986.

### CODE REVIEW

**Comment by ahrtr** [comment]
After second thought, I think the better choice is to only disable cache for golang test by running `go clean -testcache` before each test suite. There is no reason not to reuse the setup-go cache, as long as there is no code change.

**Comment by jmhbnz** [comment]
> After second thought, I think the better choice is to only disable cache for golang test by running `go clean -testcache` before each test suite. There is no reason not to reuse the setup-go cache, as long as there is no code change.

This also crossed my mind.  I'm going to hit pause on any more work here just to see if @serathius or anyone else has a preference on which cache prevention option to use (for the record I'm happy with either approach as both address the issue and I think overall performance of one versus the other will be minimal).

**Comment by fuweid** [comment]
No cache looks good to me (8s is ok). or we can force to run test case with ` GO_TEST_FLAGS="-count=1"` with cache.

**Comment by serathius** [comment]
Caching go mod 👍
Caching go build 👍
Caching go test 👎

**Comment by jmhbnz** [comment]
Thanks for the feedback everyone - I've switched to the more targeted approach of just doing the `go clean -testcache` before each suite runs.

I've run multiple workflow runs to verify this is working as expected and we no longer see any cache for the common e2e tests as we were historically. Refer latest run https://github.com/etcd-io/etcd/actions/runs/5143019041/jobs/9257510705?pr=15989.

**Review by fuweid — APPROVED** [review]
LGTM

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @jmhbnz 

Please consider to disable golang test cache for all workflows as a followup PR

**Review by serathius — APPROVED** [review]

**Review by chaochn47 — APPROVED** [review]
LGTM

**Comment by jmhbnz** [comment]
> Please consider to disable golang test cache for all workflows as a followup PR

Defined follow-up task here as a good first issue https://github.com/etcd-io/etcd/issues/15995

**Pull request merged**
