### PR TITLE
[2024-12-23] Manual Dependency Bump

### PR DESCRIPTION
**Pull request by ArkaSaha30**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

#### Bumped:

- https://github.com/etcd-io/etcd/pull/19104
- https://github.com/etcd-io/etcd/pull/19101
- https://github.com/etcd-io/etcd/pull/19100
- https://github.com/etcd-io/etcd/pull/19099
- https://github.com/etcd-io/etcd/pull/19098
- https://github.com/etcd-io/etcd/pull/19097

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @ArkaSaha30

**Review by ivanvc — APPROVED** [review]
LGTM. Thank you so much, Arka.

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @ArkaSaha30

**Pull request merged**
