### PR TITLE
etcdclient: check mutex state in Unlock method of concurrency.Mutex

### PR DESCRIPTION
**Pull request by chenyahui**
Check the values of myKey and myRev first in Unlock method to prevent calling Unlock without Lock. Because this may cause the value of pfx to be deleted by mistake.

Signed-off-by: chenyahui <cyhone@qq.com>

### CODE REVIEW

**Comment by ahrtr** [comment]
Minor comment: please consider to squash the two commits.

**Comment by ahrtr** [comment]
Overall this PR looks good to me. Please squash the two commits into one. Once it's done, then this PR is ready to merge.

**Comment by chenyahui** [comment]
> Overall this PR looks good to me. Please squash the two commits into one. Once it's done, then this PR is ready to merge.

done @ahrtr

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @chenyahui

**Pull request merged**
