### PR TITLE
Fix 15877 and bump up gRPC from v1.52.0 to v1.57.0

### PR DESCRIPTION
**Pull request by chaochn47**
Fix https://github.com/etcd-io/etcd/issues/16290

Pending to evaluate potential breaking changes mentioned in https://github.com/etcd-io/etcd/issues/15145#issuecomment-1655972888. 

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by chaochn47** [comment]
One flaky robustness execution with LazyFS. Retry should help.

**Comment by ahrtr** [comment]
This PR seems to be almost identical to https://github.com/etcd-io/etcd/pull/16338

**Comment by liggitt** [comment]
> This PR seems to be almost identical to #16301

this picks up the genproto version I cared about, so if it's passing presubmits (https://github.com/etcd-io/etcd/pull/16301 is hitting a weird timeout), I'm happy to see this merge instead

**Comment by chaochn47** [comment]
> Pending to evaluate potential breaking changes mentioned in https://github.com/etcd-io/etcd/issues/15145#issuecomment-1655972888.

I have reviewed merged changes especially https://github.com/grpc/grpc-go/pull/6471 and https://github.com/grpc/grpc-go/pull/6481. Those should be backward compatible changes until grpc-go completely remove the deprecated API like `resolver.State.Addresses`. It will be obvious that etcd cannot compile since the symbols will be removed and captured by the CI.

> this picks up the genproto version I cared about, so if it's passing presubmits (https://github.com/etcd-io/etcd/pull/16301 is hitting a weird timeout), I'm happy to see this merge instead

Thanks, I will mark the PR as ready to review with the above two arguments.

**Comment by wenjiaswe** [comment]
lgtm

**Review by serathius — APPROVED** [review]

**Comment by ahrtr** [comment]
> I have reviewed merged changes especially https://github.com/grpc/grpc-go/pull/6471 and https://github.com/grpc/grpc-go/pull/6481. Those should be backward compatible changes until grpc-go completely remove the deprecated API like resolver.State.Addresses.

Confirmed. We still need to remove the dependency on the experimental gRPC API, as tracked in https://github.com/etcd-io/etcd/issues/15145. Let's continue the discussion in that issue separately.

**Review by ahrtr — APPROVED** [review]
LGTM

thx @chaochn47

**Pull request merged**
