### PR TITLE
[3.5] Backport release script fixes

### PR DESCRIPTION
**Pull request by jmhbnz**
This pull request:
- Backports https://github.com/etcd-io/etcd/pull/17677/commits/b82f882c3d9011bab9da05a6159f701e979b4348 to `release-3.5` to prevent issues with git remotes when the script attempts to push tags.
- Partially backports https://github.com/etcd-io/etcd/commit/396efd96080c2e7a111ffd340269b685c5f393f3#diff-1bba00e5aca52286a667c09eff92ba2ca8e3ca77e0d31b0599cc829ab0173389 to `release-3.5` to ensure all key etcd branches `release-3.4`, `release-3.5` and `main` all use the same name for the release script which aligns with our release documentation.

### CODE REVIEW

**Review by serathius — APPROVED** [review]

**Comment by serathius** [comment]
If you are trying to update the commit history to show file fork in code review, I can say I tried and it doesn't work on github.

**Comment by jmhbnz** [comment]
> If you are trying to update the commit history to show file fork in code review, I can say I tried and it doesn't work on github.

I was hoping github would show the file as renamed rather than just updated but I don't think it will work that way yeah. 

All good - ready for review now.

cc additional attendees of `3.5.13` release call @ahrtr, @spzala

**Comment by ahrtr** [comment]
BTW, I think we should release 3.5.14 and 3.4.32 based on the release criteria. @jmhbnz @spzala 

Will work together with @spzala to get 3.4.32 released.

**Review by spzala — APPROVED** [review]
Thanks @jmhbnz

**Pull request merged**
