### PR TITLE
tests: Switch regenerating functional/rpcpb proto to scripts/genproto.sh

### PR DESCRIPTION
**Pull request by serathius**
When trying to modify functional/rpcpb and running `./tests/functional/scripts/genproto.sh` I noticed that it didn't work and returned error:

```
./tests/functional/scripts/genproto.sh: line 20: pushd: ***/src/github.com/gogo/protobuf: No such file or directory
```

I fixed this by adding directory to `scripts/genproto.sh` and changing the import path to one used in other proto files. Don't know the original reason why the functional tests have separate genproto.sh script https://github.com/etcd-io/etcd/pull/9513 but having single script reduced maintenance cost and increases chance it will not break.

### CODE REVIEW

**Comment by serathius** [comment]
Ok found the original reason when tests started failing :P. There is a conflict in proto source. Functional tests proto needs to be regenerated from parent directory to have source `rpcpb/rpc.proto` to avoid conflict with `etcdserverpb`.

**Comment by lilic** [comment]
Ah nice! When I last ran it, it was from the `tests/functional` directory indeed. The issue was around this line, but I thought it was my local setup issue when commenting it out, all went smoothly:

```
echo "Installing gogo/protobuf..."GOGOPROTO_ROOT="$GOPATH/src/github.com/gogo/protobuf"rm -rf $GOGOPROTO_ROOT
```

But having one script makes sense to me 👍

**Review by ptabor — APPROVED** [review]

**Comment by serathius** [comment]
Ok found problem with script. Script doesn't work after fixing shellshock.
This is because I orginally dependend on globbing variables which shellshock doesn't allow. Will need some time to figure out how to fix it.

**Comment by serathius** [comment]
Managed to go around shellshock using a globstar. Should be ok now.

**Review by lilic — APPROVED** [review]
Nice! 🎉

**Comment by serathius** [comment]
Thanks, but I will not disclose how much time it took to figure it out.

**Pull request merged**
