### PR TITLE
3.5: remove the dependency on busybox

### PR DESCRIPTION
**Pull request by ahrtr**
Backport https://github.com/etcd-io/etcd/pull/15036 to 3.5

Signed-off-by: Benjamin Wang <wachao@vmware.com>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
Fix https://github.com/etcd-io/etcd/issues/15034

**Review by ptabor — APPROVED** [review]
Please add to the changelog.

**Comment by ahrtr** [comment]
changelog: https://github.com/etcd-io/etcd/pull/15039

**Comment by ahrtr** [comment]
We recently resolved some critical and HIGH vulnerabilities in release-3.5, when do you plan to release 3.5.7? @serathius  

Since there are some big change on the image (e.g changed the base image and bumped golang version to 1.17.13), I think we'd better to do at least sanity test on etcd image in K8s workflow.  Since [you maintain etcd version in K8s](https://github.com/etcd-io/etcd/issues/14138#issuecomment-1247676521), can we verify an etcd 3.5.7 dev image in K8s workflow/pipeline? @serathius  If you do not have bandwidth, can you guide us to do this? thx

**Comment by serathius** [comment]
Sure, will take a look this week.

**Pull request merged**
