### PR TITLE
[2024-02-20] Bump dependencies identified by dependabot

### PR DESCRIPTION
**Pull request by jmhbnz**
This pull request completes this weeks etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

Summary of actions:

- [x] https://github.com/etcd-io/etcd/pull/17454 - Bumped.
- [x] https://github.com/etcd-io/etcd/pull/17453 - Bumped.
- [x] https://github.com/etcd-io/etcd/pull/17452 - Bumped.
- [x] https://github.com/etcd-io/etcd/pull/17451 - Bumped.

- [ ] https://github.com/etcd-io/etcd/pull/17456 - Closed, indirect.
- [ ] https://github.com/etcd-io/etcd/pull/17457 - Closed, indirect.
- [ ] https://github.com/etcd-io/etcd/pull/17458 - Closed, indirect.
- [ ] https://github.com/etcd-io/etcd/pull/17459 - Closed, indirect.
- [ ] https://github.com/etcd-io/etcd/pull/17460 - Closed, indirect.

### CODE REVIEW

**Comment by jmhbnz** [comment]
Possible performance issue here. Robustness for both `amd64` and `arm64` failed to complete in 30m first run.  Then again on second run failed under `arm64` in 30m.

Will convert to draft and run benchmark and heatmaps.

**Comment by ivanvc** [comment]
@jmhbnz, heads up that the actual culprit may actually be #17450, see #17471.

**Review by ahrtr — APPROVED** [review]
lgtm

Thanks

**Pull request merged**
