### PR TITLE
client: update generated ugorji codec, manual remove "yynn2=0"

### LINKED ISSUE #10325: I used the etcd/embed cue panic: codecgen version mismatch: current: 8, need 10.
panic: codecgen version mismatch: current: 8, need 10. Re-generate file: /Users/yeyongyong/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go

goroutine 1 [running]:
github.com/coreos/etcd/client.init.0()
	/Users/yeyongyong/go/pkg/mod/github.com/coreos/etcd@v3.3.10+incompatible/client/keys.generated.go:45 +0x104

### PR DESCRIPTION
**Pull request by hexfusion**
Fixes #10325 

/cc @yeyongyong  @maps

### CODE REVIEW

**Comment by xiang90** [comment]
> manual remove "yynn2=0" 

Why do we need to remove this manually?

**Comment by gyuho** [comment]
@xiang90 I remember our CI linting was complaining about that variable being unused. I reported upstream code gen to not emit those kind of line, but haven't heard back.

**Comment by xiang90** [comment]
LGTM

**Comment by jingyih** [comment]
cc @jpbetz

**Pull request merged**
