### PR TITLE
add special periodical compaction

### PR DESCRIPTION
**Pull request by AlexStocks**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

If AutoCompactionMode is 'periodic', we can set a special time span in which the etcd does compaction task every @CompactSpecialCompactionInterval. The time span is [CompactSpecialStartHour:CompactSpecialStartMinute, CompactSpecialEndHour:CompactSpecialEndMinute].

### CODE REVIEW

**Review by lilic — COMMENTED** [review]
Thanks for your PR! Can you maybe explain your use case here for these special compaction times?

Also I would like to see some tests and a bit more description for end users. Thank you!

**Comment by AlexStocks** [comment]
> Thanks for your PR! Can you maybe explain your use case here for these special compaction times?
> 
> Also I would like to see some tests and a bit more description for end users. Thank you!

Fox example, I set the k8s cluster's compaction interval is 15m at day time and set the param to 5m at night. In this way, the spike of APIServer's RT curve will be less at grafana than the 5m compaction interval in a whole day.

**Comment by ptabor** [comment]
I think its too specific policy to maintain it. 
Alternatively to address such use-cases:
  - compactions should be triggered by cron using `etcdctl compaction`
  - we should provide runtime reconfiguration API where some properties can be altered in runtime, e.g. by writes to a meta bucket.

**Comment by lilic** [comment]
I agree with @ptabor here, seems like not needed complexity in etcd, as you can use a cron job to schedule the compaction. @AlexStocks would that solution work for you?

**Comment by AlexStocks** [comment]
> I agree with @ptabor here, seems like not needed complexity in etcd, as you can use a cron job to schedule the compaction. @AlexStocks would that solution work for you?

Indeedly, it makes sense.

**Pull request closed without merging**
