### PR TITLE
[3.5] server: refresh auth info when etcd recovers from a snapshot

### PR DESCRIPTION
**Pull request by mitake**
This PR backports https://github.com/etcd-io/etcd/pull/14647 to `release-3.5`
cc @ahrtr 

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
The unit failed as expected because the PR https://github.com/etcd-io/etcd/pull/14574 hasn't been backported to 3.5 yet.  I would suggest you backport [the](https://github.com/etcd-io/etcd/pull/14574) to 3.5 in this PR as well. We can just backport the one line code change for now, and ignore e2e test for now.

**Comment by mitake** [comment]
@veshij Can I backport your fix to this PR? We have a unit test to verify the behavior so can work on e2e test later.

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @mitake

**Comment by veshij** [comment]
> @veshij Can I backport your fix to this PR? We have a unit test to verify the behavior so can work on e2e test later.

Sure!

**Comment by mitake** [comment]
Thanks @veshij !

**Comment by ahrtr** [comment]
Also partially backport https://github.com/etcd-io/etcd/pull/14574

**Pull request merged**
