### PR TITLE
[2023-04-25] Bump dependencies identified by dependabot 

### PR DESCRIPTION
**Pull request by fuweid**
* [dependency: bump github.com/alexkohler/nakedret from 1.0.1 to 1.0.2](https://github.com/etcd-io/etcd/commit/aa787d9f515d45385a5a26532a9bdc93364b710f)

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
Based on [Indirect dependencies](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md#indirect-dependencies), usually we don't bump a dependency if all modules just indirectly depend on it, such as `github.com/benbjohnson/clock`. 

Note that [uber-go/zap/blob/v1.24.0](https://github.com/uber-go/zap/blob/v1.24.0/go.mod) depends on `github.com/benbjohnson/clock 1.1.0`, but it always bumps the dependency to 1.3.0 in its main branch.  Next time when we bump `go.uber.org/zap`, the `github.com/benbjohnson/clock` will be automatially updated.

**Comment by fuweid** [comment]
Hi @ahrtr 

For `github.com/benbjohnson/clock` dep, I will delete the commit in this pr.

I have a question about indirect deps in `tools/cmd`, 

The `github.com/hexfusion/schwag` requires the following two deps. But `schwag` hasn't been updated for a long time.
For this case, we just ignore it, right?

* github.com/go-openapi/spec
*  github.com/go-openapi/jsonpointer

And for the `publicsuffix-go` and `sqlx` deps, they are required by `cfssl` command. So we should handle it next time when `cfssl` is updated. Is it correct?

If my understand is correct, this pull-request only needs to bump one dep `nakedret`.

**Comment by ahrtr** [comment]
> If my understand is correct, this pull-request only needs to bump one dep `nakedret`.

Correct.

> The github.com/hexfusion/schwag requires the following two deps. 

I suggest to remove the dependency on `github.com/hexfusion/schwag`; of course, in a separate PR.

> So we should handle it next time when cfssl is updated. Is it correct?

`github.com/cloudflare/cfssl`--> `github.com/zmap/zcrypto` --> `github.com/weppos/publicsuffix-go`.

We should push `github.com/cloudflare/cfssl` to bump `github.com/zmap/zcrypto` firstly.

**Comment by ahrtr** [comment]
@fuweid could you please close all the PRs opened by dependabot?

**Comment by fuweid** [comment]
@ahrtr thanks for the help 😂  I will close it by myself next time.

**Comment by ahrtr** [comment]
> @fuweid could you please close all the PRs opened by dependabot?

Just closed the PRs myself.

**Comment by ahrtr** [comment]
followups:
1. push `github.com/cloudflare/cfssl` to bump `github.com/zmap/zcrypto`, or just raise a PR for `github.com/cloudflare/cfssl ` directly.
2. investigate how to remove the dependency on `github.com/hexfusion/schwag`

**Comment by fuweid** [comment]
handling the `github.com/hexfusion/schwag` case right now.

**Comment by chaochn47** [comment]
> LGTM
> 
> Thanks @fuweid
> 
> next turn: @chaochn47

I did not see any direct dependencies needs to be bumped up, so I closed all of PRs opened by dependabot. Could you please take a look if I did the right thing? @ahrtr, thanks!

**Comment by ahrtr** [comment]
Thanks @chaochn47.  It's correct to close the PRs bumping indirect dependencies. 

I see that the PR https://github.com/etcd-io/etcd/pull/15806 isn't closed. It isn't an indirect dependency, but I vaguely remember that it's also causing incompatibility issue, and it couldn't pass the workflow checks.  I am not sure whether you have already double checked it. Are you raising separate PR for it?

**Comment by chaochn47** [comment]
Good catch, somehow I missed that PR https://github.com/etcd-io/etcd/pull/15806, will raise a separate PR for it `otel` version bump up.

**Pull request merged**
