### PR TITLE
dependency: upgrade go to 1.22.3

### PR DESCRIPTION
**Pull request by lavishpal**
Bump go version to 1.22.3 Part of  #17964 

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by jmhbnz — COMMENTED** [review]
Hi @lavishpal, thanks for raising this. Could you please sign your commit? So the developer certificate of origin (DCO) check passes, i.e:

```
git rebase HEAD~1 --signoff
git push --force
```

Thanks!

Ref: https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#commit-your-change

**Comment by henrybear327** [comment]
@lavishpal I believe in the mod files within the codebase, there are lots of `toolchain go1.22.2` that also require updating!

**Comment by lavishpal** [comment]
> @lavishpal I believe in the mod files within the codebase, there are lots of `toolchain go1.22.2` that also require updating!

Sure i will change them also.

**Comment by lavishpal** [comment]
> Hi @lavishpal, thanks for raising this. Could you please sign your commit? So the developer certificate of origin (DCO) check passes, i.e:
> 
> ```
> git rebase HEAD~1 --signoff
> git push --force
> ```
> 
> Thanks!
> 
> Ref: https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#commit-your-change
> 
> /ok-to-test

Do I need to do this for  dco support for every commit?

**Comment by henrybear327** [comment]
> > Hi @lavishpal, thanks for raising this. Could you please sign your commit? So the developer certificate of origin (DCO) check passes, i.e:
> > ```
> > git rebase HEAD~1 --signoff
> > git push --force
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks!
> > Ref: https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#commit-your-change
> > /ok-to-test
> 
> Do I need to do this for dco support for every commit?

Yes! :)

**Comment by henrybear327** [comment]
> > @lavishpal I believe in the mod files within the codebase, there are lots of `toolchain go1.22.2` that also require updating!
> 
> Sure i will change them also.

Hey @lavishpal I think there are still missing some updates in the mod file commit!

For all these go mod files, we need bump the go toolchain version!

```
./etcdutl/go.mod:toolchain go1.22.2
./go.mod:toolchain go1.22.2
./tools/testgrid-analysis/go.mod:toolchain go1.22.2
./tools/rw-heatmaps/go.mod:toolchain go1.22.2
./tools/mod/go.mod:toolchain go1.22.2
./etcdctl/go.mod:toolchain go1.22.2
./tests/go.mod:toolchain go1.22.2
./server/go.mod:toolchain go1.22.2
./api/go.mod:toolchain go1.22.2
./client/internal/v2/go.mod:toolchain go1.22.2
./client/v3/go.mod:toolchain go1.22.2
./client/pkg/go.mod:toolchain go1.22.2
./pkg/go.mod:toolchain go1.22.2
```

**Review by jmhbnz — COMMENTED** [review]
Changes are looking good.  @lavishpal can you please squash the three commits into one so we can merge, i.e.

```bash
git reset --soft HEAD~3
git commit -s -m "Upgrade go to 1.22.3."
git push --force
```

**Comment by lavishpal** [comment]
> Changes are looking good. @lavishpal can you please squash the three commits into one so we can merge, i.e.
> 
> ```shell
> git reset --soft HEAD~3
> git commit -s -m "Upgrade go to 1.22.3."
> git push --force
> ```

Sure

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @lavishpal

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @lavishpal.

**Pull request merged**
