### PR TITLE
Fix tx buffer inconsistency if there are duplicate keys in one tx.

### PR DESCRIPTION
**Pull request by siyuanfoundation**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

related to https://github.com/etcd-io/etcd/issues/17158

### CODE REVIEW

**Comment by siyuanfoundation** [comment]
cc @serathius @ahrtr

**Review by fuweid — APPROVED** [review]
LGTM

**Review by serathius — APPROVED** [review]

**Review by ahrtr — APPROVED** [review]
lgtm

Please also backport the PR to 3.5 and 3.4.

**Comment by ahrtr** [comment]
> Please also backport the PR to 3.5 and 3.4.

Please read https://github.com/etcd-io/etcd/pull/17234

**Comment by serathius** [comment]
High chance this PR caused https://github.com/etcd-io/etcd/issues/17247

**Pull request merged**
