### PR TITLE
Remove infinite loop in doSerialize

### PR DESCRIPTION
**Pull request by horkhe**
### Problem

If authentication is enabled, then changing permissions of a role while there are active readers/writers authenticated with the role can cause Etcd nodes consume 100% of CPU.

### Root cause

Consider the following function:

```Golang
// doSerialize handles the auth logic, with permissions checked by "chk", for a serialized request "get". Returns a non-nil error on authentication failure.
func (s *EtcdServer) doSerialize(ctx context.Context, chk func(*auth.AuthInfo) error, get func()) error {
	for {
		ai, err := s.AuthInfoFromCtx(ctx)
		if err != nil {
			return err
		}
		if ai == nil {
			// chk expects non-nil AuthInfo; use empty credentials
			ai = &auth.AuthInfo{}
		}
		if err = chk(ai); err != nil {
			if err == auth.ErrAuthOldRevision {
				continue
			}
			return err
		}
		// fetch response for serialized request
		get()
		//  empty credentials or current auth info means no need to retry
		if ai.Revision == 0 || ai.Revision == s.authStore.Revision() {
			return nil
		}
		// avoid TOCTOU error, retry of the request is required.
	}
}
```
**Synopsis**: Once `chk(ai)` fails with `auth.ErrAuthOldRevision` it will always fail with the same error regardless how many times you retry.

**Details**: `ai` is retrieved from the incoming request auth token and has the version number of the role at the time when the connection was authenticated, so while in this loop this number never changes. On the other hand `chk` returns `auth.ErrAuthOldRevision` when the `ai` version number is not the same as the role version in `s.authStore`. The role version is incremented every time when the role is updated. So `ai` version is constant and the role version from `s.authStore` can only increase, hence the check will always fail.

### Solution
Just return the error and let the client deal with it by re-authenticating.

### CODE REVIEW

**Comment by xiang90** [comment]
> Just return the error and let the client deal with it by re-authenticating.

I would like someone to explore more if we can retry correctly in the server side. If there is no easy way to do it, we can let the client to handle it. 

@gyuho Only people in the maintainer list should be able to put lgtm label. It seems that everyone in the org can do this today, which is not what we want.

**Comment by gyuho** [comment]
@xiang90 Yeah, think `/lgtm` label is open to all reviewers. I will see if we can tweak it.

**Comment by xiang90** [comment]
@xiang90 oh. i see, we actually separate the approve and lgtm labels like k8s does... then it is fine...

**Comment by horkhe** [comment]
@xiang90 do you want me to investigate possible server side retries? Honestly I do not understand why you need to to check if the version is different at all? Unless you are shooting for the case that a role was revoked some permissions. In that case `chk` rather then return `auth.ErrAuthOldRevision` should confirm that the accessed range is still allowed. The downside of this is that the extra verification would need to be repeated on each subsequent request since the auth token would still contain old version. Making clients re-authenticate would allow avoiding the extra check, and it is the simplest possible solution IMHO.

**Comment by horkhe** [comment]
I looked a bit more and turned out that `chk` calls [auth.(*authStore).isOpPermitted](https://github.com/etcd-io/etcd/blob/master/auth/store.go#L867-L906) that checks if [the accessed range is allowed](https://github.com/etcd-io/etcd/blob/master/auth/store.go#L901). But first it checks if the version is correct. And I do not understand why you need to check if [the version is correct](https://github.com/etcd-io/etcd/blob/master/auth/store.go#L878), when you check if the range is allowed anyway? It seems to me as long as the accessed range is allowed who cares what the version was when the session was authenticated. Or am I missing something?

**Comment by mitake** [comment]
@horkhe thanks for your PR. It seems that continuing in the case of `auth.ErrAuthOldRevision` is incorrect. The motivation of checking the version is denying tokens which were issued with old auth information. In this case, ideal behaviour would be replying the error code and letting the client auth again or report the error.

In addition, the version number validation in this line (https://github.com/etcd-io/etcd/pull/10218/files#diff-a5a4bca15b031f18356513fe1382c3c7L560) should be performed because `doSerialize()` can be executed during auth store updates in a concurrent manner.

**Comment by horkhe** [comment]
@mitake my question is why does it matter what the version is? IMHO as long as [this range check](https://github.com/etcd-io/etcd/blob/master/auth/store.go#L901) passes, it should be irrelevant what the role version had been when the session was authenticated is not it?

**Comment by horkhe** [comment]
By the way, we checked, the client does not re-authenticate on `auth.ErrAuthOldRevision`. So it also needs to be fixed.

**Comment by mitake** [comment]
@horkhe sorry for my late reply.
>  IMHO as long as this range check passes, it should be irrelevant what the role version had been when the session was authenticated is not it?

The motivation of version number validation is a little bit complicated. I'd like to share it with you hopefully this weekend. Is this ok?

**Comment by horkhe** [comment]
@mitake sure, whenever it is convenient to you. Now that we are running a patched etcd version we are not in a rush :-).

**Comment by mitake** [comment]
@horkhe Sorry for my late reply. I'd like to explain why the version number validation is required.
The motivation behind the validation mechanism is rejecting operations which are authorized with stale information. Let's assume a schedule like this: 1. a client X calls Authenticate() RPC and gets a token 2. another client Y changes password of X and update auth store 3. X issues a KV request (Range() or Txn with read ops) with the token

If every operation is executed in a serialized manner, nothing bad will happen. Basically the state machine of etcd executes its command in a serialized manner so no problems seem to be possible. However, we cannot have a guarantee about the order of 2 and 3. This is because for avoiding auth overhead (especially bcrypt's hash value calculation), etcd executes the step 2 in the outside of the state machine loop. So X's token can be stale in the step 3 if the authorization in the step 1 is executed with the step 2 in a parallel manner.

For avoiding serving requests with a token based on stale auth store's state, the version number check is required. The staleness can be checked by comparing a version number in the token (a number of the auth store's state when the token was generated) and and current version number of auth store. If they are different, it means the token is invalid.

Probably the best way of handling this is simply rejecting a request with a stale token and letting the client auth again. How do you think?

**Comment by horkhe** [comment]
@mitake if I got you right, the point of version checking is to reject access to data via sessions authenticated with old passwords? Well in that case version checking is indeed needed.

The solution proposed in this PR solves the first part - it rejects requests made via sessions with stale auth tokens, but the client does not handle those errors internally, it just returns them to end users. So the client code also needs to be updated. I suggest you guys develop the solution on the client side. I do not know the code well enough for that.

**Comment by mitake** [comment]
@horkhe yes but you should not remove the validation starting from this line: https://github.com/etcd-io/etcd/pull/10218/files#diff-a5a4bca15b031f18356513fe1382c3c7L559

**Comment by horkhe** [comment]
@mitake I can put it back. But honestly I see no point. Consider this: the version of the store changes a nanosecond after the second check, how is it different? The second check only adds to be rejected a handful of reads, that happen between the first and the second check, in the interval of few milliseconds. I would say why bother. Any complication albeit small is still a complication... but it is you call and I will put it back.

**Comment by horkhe** [comment]
@mitake are there any more comments that I need to address?

**Comment by mitake** [comment]
@horkhe sorry for my late reply. Yeah it is a very corner case. But I think having the validation mechanism will make reasoning safer because it keeps the linearlizable semantics. It makes the behavior of etcd predictable e.g. combination of auth config update and network partitioning can allow reading keys with stale permission (the schedule will be like this: 1. client issues Authenticate() successfully 2. an etcd node is partitioned from majority of nodes 3. auth config is updated in the majority of the nodes 4. the client issues serializable read to the partitioned node). In addition, its runtime cost is very cheap.

I'll review your recent change later. Sorry for keeping you waiting.

**Comment by mitake** [comment]
@horkhe sorry for my very late reply... I think this can be merged. The failed CI wouldn't be related to this change. I rerun travis.

**Comment by horkhe** [comment]
@mitake thank you.

**Comment by xiang90** [comment]
CI failure is not related. So merging.

**Comment by horkhe** [comment]
@xiang90 thanks a lot. Well, now the client code needs to be fixed to reconnect on `auth.ErrAuthOldRevision` should I create an issue for that?

**Comment by xiang90** [comment]
@horkhe Can you fix it directly?

**Comment by horkhe** [comment]
@xiang90 sorry, but I am not familiar with that part of the code, and it has been awhile since I looked into it, and I have moved on since then.

**Comment by mitake** [comment]
@horkhe @xiang90 I can handle that part. Opened a new issue here: https://github.com/etcd-io/etcd/issues/10408

**Comment by horkhe** [comment]
Thank you very much @mitake.

**Pull request merged**
