### PR TITLE
Automated cherry pick of #12165

### PR DESCRIPTION
**Pull request by cfc4n**
Cherry pick of #12165 on release-3.4.

#12165: etcdserver: check authinfo if it is not

### CODE REVIEW

**Comment by cfc4n** [comment]
semaphoreci info is  ``
I tested `sudo HOST_TMP_DIR=/tmp TEST_OPTS="GOARCH=386 PASSES='build e2e'" make docker-test` on my MacBook ,and It works without fail message. 
https://gist.github.com/cfc4n/eae914c2316d132f3df42627b6e8303a


@mitake  Can you reset CI to recheck it? Thanks.

**Comment by mitake** [comment]
@cfc4n Got it, I restarted travis. In semaphore only 386 is failing, I think it's a nondeterministic issue.

**Comment by cfc4n** [comment]
ping 
/cc @mitake @jingyih

**Comment by mitake** [comment]
@cfc4n Sorry for my late reply. I think this PR can be merged because failed test cases are limited:
- linux-amd64-functional tends to be fleaky and it actually passes on my local env with this PR
- linux-amd64-grpcproxy is allowed to fail
- e2e test cases are only failing for 386 so the issue would be non deterministic

**Review by mitake — APPROVED** [review]
LGTM, thanks! Defer to @jingyih

**Comment by cfc4n** [comment]
> @cfc4n Sorry for my late reply. I think this PR can be merged because failed test cases are limited:
> 
> * linux-amd64-functional tends to be fleaky and it actually passes on my local env with this PR
> * linux-amd64-grpcproxy is allowed to fail
> * e2e test cases are only failing for 386 so the issue would be non deterministic

thank you for review. and Is it same problem with https://github.com/etcd-io/etcd/pull/12365 ?

**Comment by mitake** [comment]
@cfc4n #12365 is failing because of TARGET=linux-amd64-integration-4-cpu, but TARGET=linux-amd64-integration-1-cpu was passed successfully. I think the issue is non deterministic. Anyway I'll look at the PR.

**Comment by mitake** [comment]
@cfc4n Do you have a reason to close this PR (and https://github.com/etcd-io/etcd/pull/12365)? I think it can be merged to the stable releases. If it's ok for you, could you reopen?

**Comment by bbiao** [comment]
@cfc4n Hi，will release-3.14 branch cherry-pick these commits again and fix problem mentioned in #12165 ?

**Pull request closed without merging**
