### PR TITLE
Complete backport of OWNERS file.

### PR DESCRIPTION
**Pull request by thedtripp**
https://github.com/etcd-io/etcd/issues/16367

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you!

**Review by ivanvc — COMMENTED** [review]
Hi @thedtripp, thanks for your pull request. I see that there's still a mention of the `MAINTAINERS` file in the `README.md`:

https://github.com/etcd-io/etcd/blob/1956a4783e316ed4b9f64e67d4451e5ce50377a5/README.md?plain=1#L174

And there's also the `MAINTAINERS_RULE.md` file, which may be irrelevant with `OWNERS` (https://github.com/etcd-io/etcd/blob/1956a4783e316ed4b9f64e67d4451e5ce50377a5/MAINTAINERS_RULES.md). But I'm not sure what others think.

**Comment by thedtripp** [comment]
> Hi @thedtripp, thanks for your pull request. I see that there's still a mention of the `MAINTAINERS` file in the `README.md`:
> 
> https://github.com/etcd-io/etcd/blob/1956a4783e316ed4b9f64e67d4451e5ce50377a5/README.md?plain=1#L174
> 
> And there's also the `MAINTAINERS_RULE.md` file, which may be irrelevant with `OWNERS` (https://github.com/etcd-io/etcd/blob/1956a4783e316ed4b9f64e67d4451e5ce50377a5/MAINTAINERS_RULES.md). But I'm not sure what others think.

Fixed. Let me know if anything else needs attention.

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks for finishing this off @thedtripp

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, Daniel.

**Comment by ivanvc** [comment]
/retitle [3.4] Complete backport of OWNERS file

**Pull request merged**
