### PR TITLE
[3.5] client/v3/watch.go: use fmt go pkg for gRPC metadata map printing

### PR DESCRIPTION
**Pull request by mohamedawnallah**
## Description

This PR backports the changes from #18308 PR to the release-3.5 branch.

## Issue

Addresses Issue #18303 in the backport release-3.5.

### CODE REVIEW

**Comment by ivanvc** [comment]
/retitle [3.5] client/v3/watch.go: use fmt go pkg for gRPC metadata map printing

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @mohamedawnallah

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @mohamedawnallah.

**Pull request merged**
