### PR TITLE
Update grpc dependency to 1.32.

### PR DESCRIPTION
**Pull request by ptabor**
Simplify grpc testing infrastructure to align with upstream changes.

### CODE REVIEW

**Comment by ptabor** [comment]
I assume the PR is simple enough (just go.mod changes, and minor test adaptation), to merge without waiting for review.

**Comment by kprav33n** [comment]
Thank you for this fix. What should I be putting in my `go.mod` in order to pick up this change from master? Can someone please give me an example?

I tried putting a replace directive like this:

```
replace go.etcd.io/etcd v3.3.25+incompatible => go.etcd.io/etcd fa14a0af89e6d2626c6803654c1535e2e7e71240
```

However, I see this error message during build.

```
go: errors parsing go.mod:
**REDACTED**/go.mod:17: replace go.etcd.io/etcd: version "v0.5.0-alpha.5.0.20210223111928-fa14a0af89e6" invalid: go.mod has post-v0 module path "go.etcd.io/etcd/v3" at revision fa14a0af89e6
```

**Comment by kprav33n** [comment]
For now, I have created a `git submodule` in my repo under `submodules/etcd` and pinned it to commit fa14a0af89e6d2626c6803654c1535e2e7e71240

I then used the `replace` directive to use etcd client from my local submodule.

```
require (
	...
	go.etcd.io/etcd/client/v3 v3.5.0-pre
	...
)

replace (
	go.etcd.io/etcd/api/v3 => ./submodules/etcd/api
	go.etcd.io/etcd/client/v3 => ./submodules/etcd/client/v3
	go.etcd.io/etcd/pkg/v3 => ./submodules/etcd/pkg
)
```

Maybe there is a cleaner approach than this. But, I'm able to make progress with this hack.

**Comment by coolbaluk** [comment]
Thanks for all your work on this :)

I also have the same question, what should I be putting in my `go.mod` file to get these changes ?

**Comment by ptabor** [comment]
Now 3.5.0-alpha.0 got released. 

so: 
```
go get go.etcd.io/etcd/client/v3
``` 
or
```
go get go.etcd.io/etcd/client/v3@v3.5.0-alpha.0 
```

Should be all you need now. (without any 'replaces').

**Pull request merged**
