### PR TITLE
Reduce redundant code and memory allocation.

### PR DESCRIPTION
**Pull request by Comolli**

### CODE REVIEW

**Comment by Comolli** [comment]
@ahrtr Could you review the code?

**Comment by ahrtr** [comment]
Please signoff the commit using `git rebase HEAD~1 --signoff`.

**Comment by Comolli** [comment]
@ahrtr That my faultI will check the https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.  first next time ,thank you for your time.

**Comment by ahrtr** [comment]
Usually it isn't recommended to update the stable `raft` package, unless there is any real issue. 

But the change in PR looks good and safe to me. cc @spzala @serathius @ptabor

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @Comolli

**Review by ptabor — APPROVED** [review]

**Comment by ptabor** [comment]
LGTM. Thank you. I don't see any risk.

**Pull request merged**
