### PR TITLE
etcdserver: change the snapshot + compact into sync operation

### PR DESCRIPTION
**Pull request by clement2026**
@serathius @ahrtr 
Per the suggestion in (https://github.com/etcd-io/etcd/pull/18235#issuecomment-2209038945), I have changed the snapshot and compact operations to a synchronous process for simplification.

As a first step, I just removed `s.GoAttach(func() {})`. 

I will add benchmark results once all tests pass.

### CODE REVIEW

**Comment by clement2026** [comment]
The benchmark results are impressive.

Reading performance change: -1.67% ~ 27.31%
Writing performance change: -1.12% ~ 28.64%


compare_read
[main.csv](https://github.com/user-attachments/files/16104466/main.csv)
[patch.csv](https://github.com/user-attachments/files/16104468/patch.csv)

The benchmarks were conducted on a cloud VM with 8 vCPUs and 16 GB of memory using the following script:
```bash
export RATIO_LIST="4/1"
export REPEAT_COUNT=3
export RUN_COUNT=50000
./rw-benchmark.sh
```

**Comment by serathius** [comment]
That doesn't look very good, making snapshot sync creates up to 30% regression. cc @ahrtr

**Comment by wenzel2024** [comment]
> That doesn't look very good, making snapshot sync creates up to 30% regression. cc @ahrtr

Actually, my observations show a performance improvement of up to 30%. The `patch.csv` shows higher throughput.  @serathius Could you please recheck?😬

**Comment by serathius** [comment]
> Actually, my observations show a performance improvement of up to 30%. The patch.csv shows higher throughput. @serathius Could you please recheck?😬

Oh yea, sorry I read it incorrectly. I just have been reading benchmark results which show average request duration, and not throughput so made me thing more is worse.

**Comment by wenzel2024** [comment]
> Oh yea, sorry I read it incorrectly. I just have been reading benchmark results which show average request duration, and not throughput so made me thing more is worse.

lol. I got it. It happens.🤪

As the graph indicates a performance drop with larger value sizes, I am running the `rw-benchmark.sh` script with larger value sizes to verify this issue.

**Comment by clement2026** [comment]
# Summary
Here are the results of the 4 benchmarks performed using the `rw-benchmark.sh` script.

| Value Size Range |       | Performance Change |
|------------------|-------|--------------------|
| 256 B ~  16 KB   | read  | -1.67% ~ 27.31%    |
|                  | write | -1.12% ~ 28.64%    |
| 256 B ~  16 KB   | read  | -0.67% ~ 30.40%    |
|                  | write | -1.32% ~ 30.71%    |
| 256 B ~ 32 KB    | read  | 3.68%  ~ 33.13%    |
|                  | write | 3.00%  ~ 34.37%    |
| 8 KB ~  32 KB    | read  | 0.11%  ~ 20.38%    |
|                  | write | 0.97%  ~ 21.13%    |

# Details

**Hardware**
* Test 1 was conducted on a cloud VM with 8 vCPUs and 16 GB RAM. 
* The remaining 3 tests were conducted on cloud VMs with 8 vCPUs and 32 GB RAM.

**Script**
All 4 tests use this script but differ in their `VALUE_SIZE_POWER_RANGE` variable.
```bash
export RATIO_LIST="4/1"
export REPEAT_COUNT=3
export RUN_COUNT=50000
./rw-benchmark.sh
```

## Test 1
`export VALUE_SIZE_POWER_RANGE="8 14"` 

compare_read

[main.csv](https://github.com/user-attachments/files/16143207/main.csv)  [patch.csv](https://github.com/user-attachments/files/16143209/patch.csv)

## Test 2
`export VALUE_SIZE_POWER_RANGE="8 14"`

compare_read

[main.csv](https://github.com/user-attachments/files/16143236/main.csv)  [patch.csv](https://github.com/user-attachments/files/16143237/patch.csv)

## Test 3
`export VALUE_SIZE_POWER_RANGE="8 15"`

compare_read

[main.csv](https://github.com/user-attachments/files/16143240/main.csv)  [patch.csv](https://github.com/user-attachments/files/16143241/patch.csv)


## Test 4
`export VALUE_SIZE_POWER_RANGE="13 15"`

compare_read

[main.csv](https://github.com/user-attachments/files/16143247/main.csv)  [patch.csv](https://github.com/user-attachments/files/16143248/patch.csv)

**Comment by clement2026** [comment]
I ran multiple CPU profiles with different `value size` and `connection count`. The results show that MVCC operations
like `mvcc.(*keyIndex).get`, `mvcc.(*keyIndex).isEmpty`, and `mvcc.(*keyIndex).findGeneration` significantly impact
total CPU time. Other functions worth noting are `runtime.memmove`, `syscall.Syscall6`, and `cmpbody`.

Since this patch tends to increase throughput, so higher CPU usage wasn’t surprising. These results didn't give me a
clear conclusion. To better understand the issue, I should have collected and compared CPU profile data when the patch
showed lower throughput. Unfortunately, I didn't record the throughput during the CPU profiles.

Anyway, I’m sharing these results here and would love to know what you think before I dig deeper.

**CPU Time Usage**

| Connection Count | Value Size Range | Main    | Patch   | Change in CPU Time Usage | Files                                                                                                                                                                     |
|------------------|------------------|---------|---------|--------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 32               | 16 KB            | 322.51s | 331.32s | 2.73%                    | [main.pb.gz](https://github.com/user-attachments/files/16144448/main.pb.gz) [patch.pb.gz](https://github.com/user-attachments/files/16144452/patch.pb.gz)                 |
| 32               | 32 KB            | 467.14s | 460.28s | -1.47%                   | [main.pb.gz](https://github.com/user-attachments/files/16144290/main.pb.gz) [patch.pb.gz](https://github.com/user-attachments/files/16144291/patch.pb.gz)                 |
| 32               | 64 KB            | 596.94s | 588.16s | -1.47%                   | [main.pb.gz](https://github.com/user-attachments/files/16144299/main.pb.gz) [patch.pb.gz](https://github.com/user-attachments/files/16144300/patch.pb.gz)                 |
| 1024             | 16 KB            | 319.78s | 332.02s | 3.83%                    | [main.pb.gz](https://github.com/user-attachments/files/16144311/main-1024-14.pb.gz) [patch.pb.gz](https://github.com/user-attachments/files/16144313/patch-1024-14.pb.gz) |
| 1024             | 32 KB            | 424.93s | 435.31s | 2.44%                    | [main.pb.gz](https://github.com/user-attachments/files/16144316/main-1024-15.pb.gz) [patch.pb.gz](https://github.com/user-attachments/files/16144317/patch-1024-15.pb.gz) |
| 1024             | 64 KB            | 544.16s | 547.28s | 0.57%                    | [main.pb.gz](https://github.com/user-attachments/files/16144330/main-1024-16.pb.gz) [patch.pb.gz](https://github.com/user-attachments/files/16144333/patch-1024-16.pb.gz) |

**Script**
[run.sh.zip](https://github.com/user-attachments/files/16144338/run.sh.zip)
All these tests use this script but with different `VALUE_SIZE` and `CONN_CLI_COUNT`

**Comment by serathius** [comment]
cc @ahrtr

**Comment by ahrtr** [comment]
Thanks @clement2026 for the test report. The throughput increase up to 30% is a little weird. Theoretically, the performance should be very close. 

From implementation perspective, the only possible reason for the throughput increase  I can think of could be due to the code snippet below, which won't be executed anymore in this PR. Could you double confirm this to help us have a better understanding? e.g. temporarily remove the code snippet on main branch, and then compare with this PR again.

https://github.com/etcd-io/etcd/blob/b433760ca74be6522cb1f219905d32469286210e/server/etcdserver/server.go#L2432-L2440

The CPU usage is very close, which looks fine.

**Comment by clement2026** [comment]
> From implementation perspective, the only possible reason for the throughput increase I can think of could be due to the code snippet below, which won't be executed anymore in this PR. Could you double confirm this to help us have a better understanding? e.g. temporarily remove the code snippet on main branch, and then compare with this PR again.

@ahrtr The 30% increase is really puzzling for me too. Can't wait to do the comparison and see what we find out.

**Comment by clement2026** [comment]
# Summary

Please disregard the earlier benchmark results. They were incorrect. Here are the reliable ones. Each branch was tested multiple times, with `main 01` as the baseline.

| Branch                                                                                        |       | Performance Change |
|-----------------------------------------------------------------------------------------------|-------|--------------------|
| main 01                                                                                       | read  | -                  |
|                                                                                               | write | -                  |
| main 02                                                                                       | read  | [-5.38%, 6.66%]    | 
|                                                                                               | write | [-5.09%, 6.52%]    |
| main 03                                                                                       | read  | [-4.45%, 7.12%]    | 
|                                                                                               | write | [-3.82%, 7.20%]    |
| patch 01                                                                                      | read  | [-3.49%, 5.95%]    |
|                                                                                               | write | [-4.78%, 6.40%]    |
| patch 02                                                                                      | read  | [-4.68%, 4.62%]    |
|                                                                                               | write | [-5.07%, 6.42%]    |
| remove-rwlock 01(based on https://github.com/etcd-io/etcd/pull/18283#issuecomment-2228070484) | read  | [-3.41%, 4.79%]    |
|                                                                                               | write | [-3.87%, 5.34%]    |
| remove-rwlock 02                                                                              | read  | [-5.34%, 4.81%]    |
|                                                                                               | write | [-5.74%, 6.65%]    |

It seems this PR/patch doesn't show significant performance changes.

The benchmarks were conducted using the following script on a cloud VM with 8 vCPUs and 16 GB RAM.

```bash
export RATIO_LIST="4/1"
export REPEAT_COUNT=3
export RUN_COUNT=50000
date; cd ~/etcd/tools/rw-heatmaps && ./rw-benchmark.sh; date;
```

# Details

@ahrtr You were right about the strange 30% increase. The 30% turns out to be wrong data from my faulty script:

```
date; cd ~/etcd-sync/tools/rw-heatmaps && ./rw-benchmark.sh && cd ~/etcd/tools/rw-heatmaps &&  sleep 30 &&./rw-benchmark.sh; date
```

When running this script to benchmark 2 branches, the second one always shows the 30% drop in performance. I’m not sure if it’s a machine issue, as I didn't see unusual I/O, swap, or CPU activity after each benchmark.

Anyway, I managed to get solid benchmark results by rebooting the machine after each run. Below are benchmark details. Machine was rebooted after each benchmark.

### Test 1

Benchmark main branch for 3 times to ensure the results is reliable.

main-01-vs-main-02
main-01-vs-main-03
[main-01.csv](https://github.com/user-attachments/files/16352858/main-01.csv) [main-02.csv](https://github.com/user-attachments/files/16352860/main-02.csv) [main-03.csv](https://github.com/user-attachments/files/16352861/main-03.csv)

### Test 2

Benchmark this PR/patch twice

main-01-vs-patch
main-01-vs-patch-02
[patch.csv](https://github.com/user-attachments/files/16352873/patch.csv) [patch-02.csv](https://github.com/user-attachments/files/16352874/patch-02.csv)

### Test 3

Benchmark https://github.com/etcd-io/etcd/pull/18283#issuecomment-2228070484 twice. [Code is here](https://github.com/clement2026/etcd/tree/issues-17098-remove-RWLock-from-GoAttach)

main-01-vs-remove-rwlock
main-01-vs-remove-rwlock-02
[remove-rwlock.csv](https://github.com/user-attachments/files/16352889/remove-rwlock.csv) [remove-rwlock-02.csv](https://github.com/user-attachments/files/16352888/remove-rwlock-02.csv)

**Review by ahrtr — APPROVED** [review]
Thanks @clement2026 for the hard & nice work!

> It seems this PR/patch doesn't show significant performance changes.

This seems reasonable, and it aligns with our understanding.

Almost all the heatmap diagrams have very similar color distribution, so it's very clear that they have very similar performance data.

A separate but related topic... I still think it's worthwhile to implement the line charts (see https://github.com/etcd-io/etcd/pull/15060) as another visualisation method, which is clearer for comparison when there is bigger performance difference. cc @ivanvc

**Comment by ahrtr** [comment]
cc @ivanvc @jmhbnz @serathius

**Comment by ivanvc** [comment]
> A separate but related topic... I still think it's worthwhile to implement the line charts (see #15060) as another visualisation method, which is clearer for comparison when there is bigger performance difference. cc @ivanvc

Hey @ahrtr, I actually have a branch with this change, which I was working on some months ago. However, because of other tasks, I haven't been able to revisit it. I'll try to get back to this soon.

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @clement2026.

**Comment by serathius** [comment]
Thanks @clement2026 for thorough investigation. Exemplary work!

> When running this script to benchmark 2 branches, the second one always shows the 30% drop in performance. I’m not sure if it’s a machine issue, as I didn't see unusual I/O, swap, or CPU activity after each benchmark.

We should note this and keep in mind when doing any future performance testing. Would be worth figuring out how we can protect against such cases.

**Review by serathius — APPROVED** [review]

**Pull request merged**
