### PR TITLE
[3.4] etcdserver: resend ReadIndex request on empty apply request

### PR DESCRIPTION
**Pull request by ahrtr**
Backport https://github.com/etcd-io/etcd/pull/12795 and https://github.com/etcd-io/etcd/pull/12780 to 3.4. There is any integration test at all in release-3.4, so the integration test case isn't backported to 3.4. 

part of https://github.com/etcd-io/etcd/issues/14232.

Signed-off-by: Benjamin Wang <wachao@vmware.com>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
part of https://github.com/etcd-io/etcd/issues/14232

**Comment by ahrtr** [comment]
@serathius This may be the last backport PR for 3.4.

**Review by serathius — APPROVED** [review]

**Comment by serathius** [comment]
Sad we don't have e2e tests for this.

**Comment by ahrtr** [comment]
> Sad we don't have e2e tests for this.

This can only be accurately tested by integration test, but unfortunately we don't have integrate test at all in release-3.4. 

But I believe the existing changing leader e2e cases should can also cover the code change in this PR.

**Pull request merged**
