### PR TITLE
pkg/report: make use of builtin min/max function

### PR DESCRIPTION
**Pull request by callthingsoff**
This patch eliminates the minDuration and maxDuration functions, simplifies the code.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by ivanvc — APPROVED** [review]
/lgtm Thanks, @callthingsoff 👍

**Review by ahrtr — APPROVED** [review]

**Review by liangyuanpeng — COMMENTED** [review]
LGTM

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @callthingsoff

**Pull request merged**
