### PR TITLE
fix: enable compares and negative-positive rules from testifylint

### PR DESCRIPTION
**Pull request by mmorel-35**
This fixes [compares](https://github.com/Antonboom/testifylint?tab=readme-ov-file#compares) and [negative-positive](https://github.com/Antonboom/testifylint?tab=readme-ov-file#negative-positive) rules from [testifylint](https://github.com/Antonboom/testifylint).

### CODE REVIEW

**Comment by ivanvc** [comment]
Hi @mmorel-35, thanks for all your work and pull requests regarding addressing the `testifylint` rules. Are you planning on enabling all of them? If you still have more remaining, I'd want to create a parent issue to keep track of the work you have been doing.
Once again, thanks for everything you've done so far :)

**Review by ahrtr — APPROVED** [review]

**Comment by ivanvc** [comment]
/retest

Link to https://github.com/etcd-io/etcd/issues/18719

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @mmorel-35

**Pull request merged**
