### PR TITLE
etcdctl: support a "prefix" directive in txn comparisons

### PR DESCRIPTION
**Pull request by GeorgeMac**
This adds support for the directive "prefix" when using the txn
subcommand in the v3 etcdctl. This sets the `WithPrefix()` option on the
comparison when statement "prefix" is declared after the `<CMP>` is declared.

To enable leveraging key prefixes in comparisons, which is currently available to the API, but not the cli.

For example: `ver("some.keys/") prefix = "0"` would pass if there were no
keys with the prefix "some.keys/".

UPDATE:

I adjusted my PR to support prefix as a sufixed optional parameter as suggested below.

e.g. `ver("some.keys/") = "0" prefix`

### CODE REVIEW

**Comment by wenjiaswe** [comment]
cc @jpbetz

**Comment by jpbetz** [comment]
+1 to exposing API functionality through to etcdctl

It looks like the current grammar is:

```
<target>(<key>) <op> <val>
```

E.g.

```
ver("key1") = 0
```

```
# target = "ver"
# key = "key1"
# op = "="
# val = "0"
```

And we're aiming to add support for optional `WithX()` optional param support to that grammar, and the proposal is to use the form:

```
<target>(<key>) <optionalParam0> <optionalParam1> <...optionalParamN> <op> <val>
```

How about instead we do:

```
<target>(<key>) <op> <val> <optionalParam0> <optionalParam1> <...optionalParamN> 
```

This way the `op` remain infix between the two operands without being separated by the operional params, and we simplify our parsing if we introduce more optional params in the future since we know all trailing tokens are optional params?

**Comment by GeorgeMac** [comment]
I am all for this 👍

**Comment by GeorgeMac** [comment]
I adjusted my PR to account for the form described above. Plus I left room for other options to be added. For now it just supports the `WithPrefix` form.

**Pull request closed without merging**
