### PR TITLE
[2024-12-16] Manual Dependency Bump

### PR DESCRIPTION
**Pull request by ArkaSaha30**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

#### Bumped:

- https://github.com/etcd-io/etcd/pull/19072
- https://github.com/etcd-io/etcd/pull/19073
- https://github.com/etcd-io/etcd/pull/19074
- https://github.com/etcd-io/etcd/pull/19070
- https://github.com/etcd-io/etcd/pull/19071

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]

**Review by ivanvc — COMMENTED** [review]
Hi @ArkaSaha30, thanks for your pull request.

* I'd like to suggest squashing commits c7ebd0f5071afc1d553a683bb1234d7b2ec518cb and 4f55356b93c56686fd48c85d0728877b7559bbbb (but I'd say it's a no biggie).
* However, I think you forgot to bump `bump go.opentelemetry.io/otel/exporters/otlp/otlptrace` as commit c7ebd0f5071afc1d553a683bb1234d7b2ec518cb doesn't include it.

**Comment by ArkaSaha30** [comment]
> * I'd like to suggest squashing commits [c7ebd0f](https://github.com/etcd-io/etcd/commit/c7ebd0f5071afc1d553a683bb1234d7b2ec518cb) and [4f55356](https://github.com/etcd-io/etcd/commit/4f55356b93c56686fd48c85d0728877b7559bbbb) (but I'd say it's a no biggie).
> * However, I think you forgot to bump `bump go.opentelemetry.io/otel/exporters/otlp/otlptrace` as commit [c7ebd0f](https://github.com/etcd-io/etcd/commit/c7ebd0f5071afc1d553a683bb1234d7b2ec518cb) doesn't include it.

Sure, thank you! Updating the PR with the changes

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @ArkaSaha30

**Pull request merged**
