### PR TITLE
Scripts: fix read failure prompt in release

### LINKED ISSUE #11227: read prompts in scripts/release failing with "not a valid identifier"
3.4 release script has a problem with `read` commands that we should fix to ease future releases:

```
./scripts/release 3.4.2
Release version tag exists on remote. Checking out refs/tags/v3.4.2
Skpping release build step. /release directory already exists.
Generating sha256sums of release artifacts.

/tmp/etcd-release-3.4.2/etcd/release /tmp/etcd-release-3.4.2/etcd
/tmp/etcd-release-3.4.2/etcd
9ff566a77eb54b7e26842480c44e99eef7c9bc43190d420355557d78651a9800  etcd-v3.4.2-darwin-amd64.zip
f369cf0568a0413d2229ae405c16639badd47bef8a070cbfde9aa3e74f072528  etcd-v3.4.2-linux-amd64.tar.gz
8779d797cda8e19cfcb89c23539976904ad6c036dd61e795e7f7f262d2da2105  etcd-v3.4.2-linux-arm64.tar.gz
0df6ad483781dd66c51452f4ffa73ab2b502062798f002ad2e748be470872694  etcd-v3.4.2-linux-ppc64le.tar.gz
e16def3778aad3cf2803245aa2012953acc68dc3af4399eae90983694e8c0b62  etcd-v3.4.2-windows-amd64.zip
./scripts/release: line 163: read: `Upload etcd v3.4.2 release artifacts to gs://etcd [y/N]? ': not a valid identifier
```

@wenjiaswe @YoyinZyc @jingyih @hexfusion

### PR DESCRIPTION
**Pull request by YoyinZyc**
Fix #11227

### CODE REVIEW

**Comment by YoyinZyc** [comment]
cc @gyuho @jpbetz

**Comment by jpbetz** [comment]
LGTM

Looks great. Thanks!

Will merge once CI passes.

**Comment by jpbetz** [comment]
```
-- FAIL: TestRoundRobinBalancedResolvableFailoverFromRequestFail (0.05s)
    balancer_test.go:308: expected balanced loads for 20 requests, got switches 3
```
(https://travis-ci.com/etcd-io/etcd/jobs/244355763)

**Comment by jpbetz** [comment]
Gotta be a flake, rerunning CI. We should file an issue for the flake.

**Comment by gyuho** [comment]
@YoyinZyc Can we backport this to our release branches? Thx!

**Comment by YoyinZyc** [comment]
> Yuchen Zhou Can we backport this to our release branches? Thx!

I did it for 3.4. Do I need to backport it to other branches?

**Comment by gyuho** [comment]
@YoyinZyc For 3.3, let's just fix https://github.com/etcd-io/etcd/blob/3fae828623c194feb307c49c15d66dca9366e195/scripts/release#L54

**Pull request merged**
