### PR TITLE
tools: fix test case errors in etcd-dump-logs

### PR DESCRIPTION
**Pull request by viviyww**
tools:etcd-dump-logs

Fix test case errors in etcd-dump-logs and the error is the time zone.
When the GOST time zone is CST or PST and the test case will be failed.
So we should set UTC as the standard time zone.

Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by xiang90** [comment]
@viviyww Can you change the commit message to 'tools:xxxx'?

**Comment by viviyww** [comment]
@xiang90 ok, thanks for your review. I will recheck it.

**Comment by jingyih** [comment]
》 @viviyww Can you change the commit message to 'tools:xxxx'?

Please address this comment. (change commit title and force push)

**Comment by viviyww** [comment]
> force pus

ok.

**Review by jingyih — COMMENTED** [review]
LGTM

cc @wenjiaswe

**Comment by wenjiaswe** [comment]
LGTM, thanks for fixing.

**Comment by jingyih** [comment]
Tests failure unrelated.

**Pull request merged**
