### PR TITLE
Modularization: Move /client/ -> /client/v2 and make it a module

### PR DESCRIPTION
**Pull request by ptabor**
We make v2 client code a module `go.etcd.io/etcd/client/v2`.  

Pretty mechanical change that can be summarized as:
```
mkdir client/v2
cd client/v2 && git mod init go.etcd.io/etcd/client/v2

git mv client/*.go client/v2/
find -name '*.go' | xargs sed -i --follow-symlinks 's|/v3/client["]|/client/v2\"|g'
```

+ fixing changelog, go.mod etc.

Move of /clientv3 into /client/v3 will follow.

### CODE REVIEW

**Comment by jingyih** [comment]
I think the code under folder `client` is for etcd2. So moving the code to a new module `go.etcd.io/etcd/client/v2` sounds better to me.

@gyuho Any comment?

**Comment by ptabor** [comment]
> I think the code under folder `client` is for etcd2. So moving the code to a new module `go.etcd.io/etcd/client/v2` sounds better to me.
> 
> @gyuho Any comment?

Initially I liked the idea, but there is one pragmatic problem unfortunately:  

The version of module (v2, v3) needs to match the repository tags. 
So we cannot maintain go.etcd.io/etcd/client/v2 in repository that will be getting tagged as 3.5.1. 

What options I see: 
  1.  [in this PR] Single module (go.etcd.io/etcd/client/v3) that contains both go.etcd.io/etcd/client/v3/clientv2 & go.etcd.io/etcd/client/v3/clientv3

  2.  Two separate top-level modules: 
         -  go.etcd.io/etcd/clientv2/v3
         -  go.etcd.io/etcd/clientv3/v3

  3. Delete clientv2 from our master branch and put it in separate branch/repository where we can tag and version it as
     go.etcd.io/etcd/client/v2

@gyuho @jingyih @xiang90  @jpbetz

**Comment by gyuho** [comment]
> Move of /clientv3 into /client will follow
> Two separate top-level modules:

If that's the case, is it necessary we have `/client` for two versions of packages? Just rename `client` to `clientv2` and keep `clientv3` as it is?

**Comment by ptabor** [comment]
> > Move of /clientv3 into /client will follow
> > Two separate top-level modules:
> 
> If that's the case, is it necessary we have `/client` for two versions of packages? Just rename `client` to `clientv2` and keep `clientv3` as it is?

I think that answer to this question depends on the chosen option in: https://github.com/etcd-io/etcd/pull/12391#issuecomment-708536253.  If we go for 2 modules (separate for clientv2 & clientv3) they both can stay top-level side-by-side. If we go for a single client module, they need to have a common root.

**Comment by ptabor** [comment]
Picked option 4. from above list, as it seems to offer the most natural customer experience, where customer just picks an import from: 
  - go.etcd.io/etcd/client/v2
  - go.etcd.io/etcd/client/v3

I applied the approach from https://golang.org/ref/mod#vcs-dir: 
> Subdirectories with a major version suffix are major version subdirectories. They may be used to develop multiple major versions of a module on a single branch. 
This means I had to create client/v2 & client/v3 dirs with a common root. The nice property is that it also fully mimics the 'import' path.

**Comment by gyuho** [comment]
> go.etcd.io/etcd/client/v2
> go.etcd.io/etcd/client/v3

+1

**Review by gyuho — APPROVED** [review]
lgtm, can we make the same change for `clientv3`?

**Pull request merged**
