### PR TITLE
fix: different errc to avoid confused when timeout

### PR DESCRIPTION
**Pull request by Mskxn**
This pr is to fix issue #15666, using different errc for each testcase to avoid being confused when some of the testcases get a timeout.

### CODE REVIEW

**Comment by lavacat** [comment]
Looks good, but one nitpick - can you change commit msg?
Part before `:` is usually a component name. My suggestion:
`test: use separate errc for each case in TestTxnPanics`

**Review by jmhbnz — COMMENTED** [review]
Looks good, nice work @Mskxn.

Please address above feedback regarding commit message, additionally please ensure your updated commit is signed so the DCO check passes, i.e:

```bash
$ git reset --soft HEAD~1
$ git commit --signoff -m "tests: use separate errc for each case in TestTxnPanics"
$ git push --force-with-lease
```

**Comment by ahrtr** [comment]
Thanks @Mskxn for the fix, which makes sense to me. Please resolve the above comments, then it's ready to merge after passing the workflow tests.

BTW, the simpler way to signoff the commit: 
```
$ git rebase HEAD~1 --signoff
$ git push origin main -f
```

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @Mskxn

**Comment by Mskxn** [comment]
Thanks for your suggestion, I will pay more attention to these details in my subsequent pr.

**Pull request merged**
