### PR TITLE
*: namespace quota

### PR DESCRIPTION
**Pull request by vivekpatani**
To add functionality surroundind the namespace quotas.
Ability to set, delete, list, and get quotas.
Framework to interact with core etcd ops.

This PR is against master, a related PR against branch-3.4 is made here: https://github.com/etcd-io/etcd/pull/13486

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by vivekpatani** [comment]
@wenjiaswe @ptabor @serathius @wojtek-t @hexfusion @jingyih

3.4 - https://github.com/etcd-io/etcd/pull/13486/files (we had initially started developing on 3.4)

Technical document: https://docs.google.com/document/d/1POdNdFBgpcGqLwurZjy8qQki6beOoVIcElTqHy4DnnA/edit
etcd GitHub issue: https://github.com/etcd-io/etcd/issues/10084
k8s: https://github.com/kubernetes/kubernetes/issues/102078
k8s KEP: https://github.com/kubernetes/enhancements/issues/2754
Slide Deck: https://drive.google.com/file/d/1wmssxH0fpRwRKmL7TCW5S_LPzjkiLrHJ/view

**Comment by JmPotato** [comment]
Thx for your work! But I'm wondering that this big change is hard to review, so any splitting would be helpful 😢.

**Comment by vivekpatani** [comment]
@JmPotato Hi sure, let me logically chunk them out, thank you. I will update you once I break them apart.

**Comment by vivekpatani** [comment]
@JmPotato @wenjiaswe @ptabor @serathius @wojtek-t @hexfusion @jingyih rebased the PR, bumping again. Sorry it took so long.

I've tried to breakdown the PR into more logical components so that it builds up in the following fashion:
1. Added/Generated most of the `proto` files needed for this feature.
2. `NamespaceQuotaEnforcement` controls if the quota needs to be in `soft`, `hard`, or `disabled` mode.
3. Add metrics required to understand how quotas are being used and affect etcd, added `go.mod` changes, and creating an index required to CRUD quotas.
4. Add necessary functions to recover quotas when a member/cluster starts/restarts/join
5. Add the central part of the quota, the namespace quota manager. This has most of functionality of quotas.
6. Add relevant errors that may occur when dealing with quotas.
7. Server changes to accommodate quota operations, and subsequent raft changes.
8. Testing
9. Client side changes to accommodate quotas.
10. Minor fixes
11. gRPC proxy changes

Please feel free to reach out with any questions, feedback is welcome. Thank you.

**Comment by vivekpatani** [comment]
As discussed in meeting on June 2, 2022, this will be reviewed at a later time, potentially 3.7.x/3.8.x.

**Pull request closed without merging**
