### PR TITLE
Rollback increase timeout for deactivating failpoint

### PR DESCRIPTION
**Pull request by henrybear327**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

Because https://github.com/etcd-io/gofail/issues/64 is merged, we can roll back the change.

Reference:
- https://github.com/etcd-io/etcd/pull/17719

### CODE REVIEW

**Comment by henrybear327** [comment]
@ahrtr when gofail 0.2.0 is released, I will update the gofail dependencies in another PR and rebase this one on top of it!

Currently, this PR serves as double-checking the CI is still working normally after the recent gofail final changes are merged before releasing the new tag!

**Comment by henrybear327** [comment]
Pending PR https://github.com/etcd-io/gofail/pull/69 to bump gofail to 0.2.0 (https://github.com/etcd-io/gofail/pull/65#issuecomment-2111960126)

**Comment by serathius** [comment]
Don't think we need to block in integration tests

**Comment by henrybear327** [comment]
Completed via https://github.com/etcd-io/etcd/pull/17680.

**Pull request closed without merging**
