### PR TITLE
Modularization: Move contrib/recipies to clientv3/experimental/recipies/...

### PR DESCRIPTION
**Pull request by ptabor**
"recipies" is set of patterns / locking primitives implementation on top of clientv3.
It's used by integration tests, but targeted at end-consumer. It shouldn't be considered "server" code.
Moving closer to client/v3.

### CODE REVIEW

**Comment by jingyih** [comment]
godoc says `Package recipe contains experimental client-side distributed synchronization primitives.` So the file move sounds good. Is there a way that we emphasize the **experimental** nature of these APIs? My only concern is that people starts to rely on these APIs once we move them to client module.

**Comment by ptabor** [comment]
> godoc says `Package recipe contains experimental client-side distributed synchronization primitives.` So the file move sounds good. Is there a way that we emphasize the **experimental** nature of these APIs? My only concern is that people starts to rely on these APIs once we move them to client module.

It's why I left it in the 'contrib' directory:
  client/v3/contrib/recipes/watch.go

Options we have: 
   a) rename 'contrib' to 'experimental' or 'alpha'
   b) make the contrib/experimental/alpha module on its own. 
   c) combined a&b

My taste would be towards (a) rename it to 'experimental' and do NOT make it a module (as we already have pretty fine-grained modules, and this package does not adds more dependencies). 

@gyuho WDYT ?

**Comment by jingyih** [comment]
Renaming folder to 'experimental' sounds good to me. It aligns with naming of the unstable flags in etcd (e.g. experimental-some-flag).

**Comment by ptabor** [comment]
Renamed to experimental as requested.

**Review by jingyih — COMMENTED** [review]
lgtm

**Pull request merged**
