### PR TITLE
server/auth: protect rangePermCache with a RW lock

### PR DESCRIPTION
**Pull request by mitake**
Signed-off-by: Hitoshi Mitake <h.mitake@gmail.com>

Backports https://github.com/etcd-io/etcd/pull/13954

cc @ahrtr

### CODE REVIEW

**Comment by ahrtr** [comment]
Could you make the change per https://github.com/etcd-io/etcd/pull/14227#issuecomment-1188332663 ?

**Comment by mitake** [comment]
@ahrtr Updated `getAllUsers()`, could you check?

**Review by ahrtr — APPROVED** [review]
LGTM 

Thank you @mitake

**Comment by ahrtr** [comment]
cc @serathius @ptabor @ptabor

**Review by serathius — APPROVED** [review]

**Pull request merged**
