### PR TITLE
mvcc: optimize watch logic of watchableStore

### PR DESCRIPTION
**Pull request by viviyww**
Optimize watchableStore.watch func

Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by spzala — COMMENTED** [review]
lgmt
CI failure was networking related. Restarted it. Thanks @viviyww

**Comment by ptabor** [comment]
Failures in linux-amd64-grpcproxy might be my fault. Working on this.

**Comment by ptabor** [comment]
https://github.com/etcd-io/etcd/pull/12706 should fix the broken test.

**Pull request merged**
