### PR TITLE
auth: Support for EdDSA JWT algorithm

### PR DESCRIPTION
**Pull request by twz123**
The golang-jwt library supports this already, so supporting it is just a matter of wiring things up.

### CODE REVIEW

**Review by serathius — APPROVED** [review]
Looks simple enough, cc @ahrtr

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @twz123

**Comment by ahrtr** [comment]
The PR looks good to me, but unfortunately I don't see any document mentioning the supported signing methods.

Previously in [3.4 doc](https://etcd.io/docs/v3.4/op-guide/configuration/), there is a simple description for flag `–auth-token`, but I don't know why it's removed in 3.5+. Can we add the doc back?

**Review by ahrtr — APPROVED** [review]
LGTM thx @twz123 

Could you raise a followup ticket for https://github.com/etcd-io/website/?

**Comment by twz123** [comment]
> LGTM thx @twz123
> 
> Could you raise a followup ticket for https://github.com/etcd-io/website/?

For the documentation you mean? Like [this](https://github.com/etcd-io/website/issues/706)?

**Comment by ahrtr** [comment]
thx @twz123

**Pull request merged**
