### PR TITLE
clientv3: fix isOptsWithFromKey/isOptsWithPrefix

### PR DESCRIPTION
**Pull request by vivekpatani**
- Addressing: https://github.com/etcd-io/etcd/issues/13332
- Backporting: https://github.com/etcd-io/etcd/pull/13334

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
Thanks @vivekpatani , please signoff the commit,
```
git commit --signoff --amend
```

**Comment by vivekpatani** [comment]
@ahrtr done, let me know if that is indeed the correct format. Thanks.

**Review by ahrtr — APPROVED** [review]
LGTM

**Comment by ahrtr** [comment]
cc @spzala @serathius @ptabor

**Review by serathius — APPROVED** [review]

**Pull request merged**
