### PR TITLE
[release-3.5] backport fix watch event loss after compaction

### PR DESCRIPTION
**Pull request by chaochn47**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

xref. https://github.com/etcd-io/etcd/issues/17529

### CODE REVIEW

**Comment by ahrtr** [comment]
Thanks for the PR. 

I do not see the integration test case, did you intentionally not backporting the integration test?

**Comment by chaochn47** [comment]
> I do not see the integration test case, did you intentionally not backporting the integration test?

@ahrtr 

Yeah, go failpoint in the mainline integration test is not supported in release-3.5. 

I can create one similar e2e test just like [TestLeaseRevoke_IgnoreOldLeader](https://github.com/etcd-io/etcd/blob/4a90575ab2a83679741a3d8253f1d82ae20c7ee2/tests/e2e/v3_lease_no_proxy_test.go#L34) though.

**Comment by ahrtr** [comment]
Thanks for the clarification.  I am OK to leave it as it's for now.

**Review by ahrtr — APPROVED** [review]
lgtm

Thanks

cc @fuweid @jmhbnz @serathius

**Review by serathius — APPROVED** [review]

**Comment by ahrtr** [comment]
Please also update the changelog for 3.4 and 3.5, thx

**Comment by chaochn47** [comment]
Thanks @ahrtr for releasing [v3.4.31](https://github.com/etcd-io/etcd/releases/tag/v3.4.31)!

Is there a ETA for releasing [v3.5.13] including the bug fix so we can count on? @serathius

**Comment by jmhbnz** [comment]
> Is there a ETA for releasing [v3.5.13] including the bug fix so we can count on? @serathius

Created planning issue https://github.com/etcd-io/etcd/issues/17633 to start the process.

**Pull request merged**
