### PR TITLE
Update arm64 infra guide standard `arm64` runner definition

### PR DESCRIPTION
**Pull request by moficodes**
We updated our resource requirement for actuated instances. 

We should update the doc here as well.

### CODE REVIEW

**Comment by moficodes** [comment]
@jmhbnz

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @moficodes

**Comment by jmhbnz** [comment]
/retitle Update arm64 infra guide standard `arm64` runner definition

**Review by serathius — APPROVED** [review]

**Review by fuweid — APPROVED** [review]
LGTM

**Pull request merged**
