### PR TITLE
Doc: Fix typo in revision.go

### PR DESCRIPTION
**Pull request by majolo**

### CODE REVIEW

**Comment by majolo** [comment]
Thanks @spzala - trivial fix, how do I get this merged?

**Comment by xiang90** [comment]
@majolo the commit message needs to be fixed, not the github pr title.

**Comment by spzala** [comment]
> Thanks @spzala - trivial fix, how do I get this merged?

As @xiang90 mentioned, you need to fix the commit title to pass the build other than that it's trivial and looks good. Thanks!

**Comment by majolo** [comment]
Hey @spzala I've renamed the commit. Build still seems to be failing but can't see how it would relate to this trivial change?

**Comment by spzala** [comment]
@majolo thanks and yes, the build failures not related to the changes.

**Comment by spzala** [comment]
@xiang90 merging this one as it's trivial :-)

**Pull request merged**
