### PR TITLE
client: remaining errors.Is conversions

### PR DESCRIPTION
**Pull request by redwrasse**
PR for rest of errors.Is conversions for the client modules, as part of https://github.com/etcd-io/etcd/issues/18576

### CODE REVIEW

**Comment by ivanvc** [comment]
Thanks for the pull request, @redwrasse. I think we may be missing the following ones:

* `client/v3/retry_interceptor.go:257`
* `client/pkg/fileutil/preallocate_darwin.go:43`
* `client/v3/client.go:223`
* `client/internal/v2/client_test.go:441`
* `client/internal/v2/client_test.go:747`

**Review by ahrtr — APPROVED** [review]

**Comment by redwrasse** [comment]
Thanks @ivanvc, let me try to fix those...

**Comment by redwrasse** [comment]
@ivanvc I've updated the PR according to your list https://github.com/etcd-io/etcd/pull/18614#issuecomment-2364741673, 
with a few slight differences:

Updated as in your list with errors.Is:

- `client/v3/retry_interceptor.go:257`
- `client/pkg/fileutil/preallocate_darwin.go:43`
- `client/v3/client.go:223`


`client/internal/v2/client_test.go:441` and `client/internal/v2/client_test.go:747` I did not update because of the way those lines are structured. First check is against a nil error, second check is checking explicit error string equality given the variety of `tt.wantErr` in the testcases, so `errors.Is` doesn't appear to make sense here to me. Let me know if you think otherwise/should approach differently:

```
if (tt.wantErr == nil && tt.wantErr != err) || (tt.wantErr != nil && tt.wantErr.Error() != err.Error()) {
...
}
```

Found a couple more lines to fix:
- `additional client/v3/retry_interceptor.go:149`
- `additional client/v3/retry_interceptor.go:156`

And finally updated the example code in the README `client/internal/v2/README.md` to use `errors.Is` and `errors.As`.

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @redwrasse. Feel free to undraft whenever you're ready.

**Comment by redwrasse** [comment]
Marked ready for review again, thanks for your patience.

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @redwrasse

**Pull request merged**
