### PR TITLE
[2023-08-03] Bump dependencies identified by dependabot

### PR DESCRIPTION
**Pull request by iiamabby**
This pull request completes this weeks etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1DDWzbcOx1p32MhyelaPZ_SfYtAD6xRsrtGRZ9QXPOyQ/edit#gid=0) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

Summary of actions:
 - [x] https://github.com/etcd-io/etcd/pull/16351 
 - [x]  https://github.com/etcd-io/etcd/pull/16347

### CODE REVIEW

**Comment by jmhbnz** [comment]
Hi @ahrtr, @serathius - I paired with @iiamabby for this weeks manual dependency bump.  I just want to call specific attention to https://github.com/etcd-io/etcd/pull/16360/commits/0dcef55b89b8b9a36dccf83886cb07d328b0cd4c which automatically included a bump to `github.com/grpc-ecosystem/grpc-gateway/v2`. 

There is a second open pr relating to this dependency https://github.com/etcd-io/etcd/pull/16357 so we need to decide on an approach for that dependency.  Let us know if you want that commit removed from this pr.

**Comment by ahrtr** [comment]
I suggest to only bump `golang.org/x/net` and `go.uber.org/zap` in this PR, because obviously it's safe to bump them. Once this PR gets merged, we can try to bump the other two dependencies one by one, and let's see what's the workflow results by then.

**Comment by iiamabby** [comment]
> I suggest to only bump `golang.org/x/net` and `go.uber.org/zap` in this PR, because obviously it's safe to bump them. Once this PR gets merged, we can try to bump the other two dependencies one by one, and let's see what's the workflow results by then.

All done, thanks

**Review by ahrtr — APPROVED** [review]
LGTM

thx @iiamabby for your first contribution to etcd!

**Pull request merged**
