### PR TITLE
test: rename `tests/framework/testutils` to `tests/framework/utils`

### PR DESCRIPTION
**Pull request by ahrtr**
Please read https://go.dev/doc/effective_go#package-names

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
cc @mitake @ptabor @serathius @spzala

**Review by jmhbnz — APPROVED** [review]
Based on the go guidelines this change makes sense to me.

One question though, are we aware of anything external to etcd that might rely on this? I would think unlikely given this is just a project testing component?

**Comment by ahrtr** [comment]
> One question though, are we aware of anything external to etcd that might rely on this?

I don't think we guarantee API compatibility for test package.  Also note that [test framework](https://github.com/etcd-io/etcd/tree/main/tests/framework) is only present in `main` branch.

**Comment by ptabor** [comment]
The motivation for 'testutils' is to have ability to import the packages to a lot of tests without need to alias. 
'utils' is a very ubiquitous names so requires picking an alias name that might be difference between different tests.

**Comment by ahrtr** [comment]
thx  @ptabor

**Pull request closed without merging**
