### PR TITLE
[2024-11-18] Manual Dependency Bump

### PR DESCRIPTION
**Pull request by ArkaSaha30**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

#### Bumped:

- https://github.com/etcd-io/etcd/pull/18922
- https://github.com/etcd-io/etcd/pull/18921
- https://github.com/etcd-io/etcd/pull/18920
- https://github.com/etcd-io/etcd/pull/18919
- https://github.com/etcd-io/etcd/pull/18915
- https://github.com/etcd-io/etcd/pull/18914

#### Purely Indirect:

- https://github.com/etcd-io/etcd/pull/18917
- https://github.com/etcd-io/etcd/pull/18916
- https://github.com/etcd-io/etcd/pull/18913
- https://github.com/etcd-io/etcd/pull/18912

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @ArkaSaha30

**Comment by ahrtr** [comment]
We missed https://github.com/etcd-io/raft/releases/tag/v3.6.0-beta.0, @ArkaSaha30 could you raise a separate PR to bump it? thx

**Pull request merged**
