### PR TITLE
fix: close conn

### PR DESCRIPTION
**Pull request by falser101**
Signed-off-by: jianfei.zhang <jianfei.zhang@daocloud.io>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by falser101** [comment]
@new-dream

**Review by ahrtr — APPROVED** [review]
LGTM

Good catch, thank you @falser101

**Comment by ahrtr** [comment]
Could you backport this PR to both 3.5 and 3.4?

**Comment by falser101** [comment]
> Could you backport this PR to both 3.5 and 3.4?

ok

**Pull request merged**
