### PR TITLE
vendor: upgrade dependencies

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by gyuho** [comment]
```diff
diff --git a/go.mod b/go.mod
index 31eabdb8a..cb93d5d0d 100644
--- a/go.mod
+++ b/go.mod
@@ -1,64 +1,46 @@
 module go.etcd.io/etcd

 require (
-       github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973 // indirect
        github.com/bgentry/speakeasy v0.1.0
+       github.com/cheggaaa/pb/v3 v3.0.1
        github.com/cockroachdb/datadriven v0.0.0-20190531201743-edce55837238
        github.com/coreos/go-semver v0.2.0
        github.com/coreos/go-systemd v0.0.0-20180511133405-39ca1b05acc7
        github.com/coreos/pkg v0.0.0-20160727233714-3ac0863d7acf
-       github.com/davecgh/go-spew v1.1.1 // indirect
        github.com/dgrijalva/jwt-go v3.2.0+incompatible
        github.com/dustin/go-humanize v0.0.0-20171111073723-bb3d318650d4
-       github.com/fatih/color v1.7.0 // indirect
-       github.com/gogo/protobuf v1.0.0
+       github.com/gogo/protobuf v1.1.1
        github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b // indirect
        github.com/golang/groupcache v0.0.0-20160516000752-02826c3e7903
-       github.com/golang/protobuf v1.2.0
-       github.com/google/btree v0.0.0-20180124185431-e89373fe6b4a
-       github.com/google/uuid v1.0.0
+       github.com/golang/protobuf v1.3.1
+       github.com/google/btree v1.0.0
+       github.com/google/uuid v1.1.1
        github.com/gorilla/websocket v0.0.0-20170926233335-4201258b820c // indirect
        github.com/grpc-ecosystem/go-grpc-middleware v1.0.1-0.20190118093823-f849b5445de4
        github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
        github.com/grpc-ecosystem/grpc-gateway v1.4.1
-       github.com/inconshreveable/mousetrap v1.0.0 // indirect
        github.com/jonboulle/clockwork v0.1.0
-       github.com/json-iterator/go v1.1.5
-       github.com/kr/pty v1.0.0
-       github.com/mattn/go-colorable v0.0.9 // indirect
-       github.com/mattn/go-isatty v0.0.4 // indirect
-       github.com/mattn/go-runewidth v0.0.2 // indirect
-       github.com/matttproud/golang_protobuf_extensions v1.0.0 // indirect
-       github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
+       github.com/json-iterator/go v1.1.6
+       github.com/kr/pty v1.1.8
        github.com/modern-go/reflect2 v1.0.1
        github.com/olekukonko/tablewriter v0.0.0-20170122224234-a0225b3f23b5
-       github.com/onsi/gomega v1.4.2 // indirect
-       github.com/pkg/errors v0.8.0 // indirect
-       github.com/pmezard/go-difflib v1.0.0 // indirect
-       github.com/prometheus/client_golang v0.8.0
-       github.com/prometheus/client_model v0.0.0-20170216185247-6f3806018612
-       github.com/prometheus/common v0.0.0-20180518154759-7600349dcfe1 // indirect
-       github.com/prometheus/procfs v0.0.0-20180612222113-7d6f385de8be // indirect
-       github.com/sirupsen/logrus v1.0.5 // indirect
+       github.com/prometheus/client_golang v1.0.0
+       github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
        github.com/soheilhy/cmux v0.1.4
-       github.com/spf13/cobra v0.0.3
-       github.com/spf13/pflag v1.0.1
-       github.com/stretchr/testify v1.2.2 // indirect
+       github.com/spf13/cobra v0.0.5
+       github.com/spf13/pflag v1.0.3
        github.com/tmc/grpc-websocket-proxy v0.0.0-20170815181823-89b8d40f7ca8
        github.com/urfave/cli v1.20.0
        github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2
        go.etcd.io/bbolt v1.3.3
        go.uber.org/atomic v1.3.2 // indirect
        go.uber.org/multierr v1.1.0 // indirect
-       go.uber.org/zap v1.9.1
-       golang.org/x/crypto v0.0.0-20180608092829-8ac0e0d97ce4
-       golang.org/x/net v0.0.0-20180906233101-161cd47e91fd
+       go.uber.org/zap v1.10.0
+       golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
+       golang.org/x/net v0.0.0-20181114220301-adae6a3d119a
        golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2
        google.golang.org/genproto v0.0.0-20180608181217-32ee49c4dd80 // indirect
        google.golang.org/grpc v1.14.0
-       gopkg.in/airbrake/gobrake.v2 v2.0.9 // indirect
-       gopkg.in/cheggaaa/pb.v1 v1.0.25
-       gopkg.in/gemnasium/logrus-airbrake-hook.v2 v2.1.2 // indirect
        gopkg.in/yaml.v2 v2.2.2
        sigs.k8s.io/yaml v1.1.0
 )
```

Fails...

**Comment by spzala** [comment]
> /cc @spzala

@gyuho thanks! Will review after a meeting.

**Comment by spzala** [comment]
@gyuho hi, is there anything specific to keep in mind while reviewing these changes? Want me to test anything? Build seems happy. Thanks!

**Comment by gyuho** [comment]
@spzala Nothing special. You can just look at go.mod to make sure I am not upgrading any other vendors unintentionally.

**Comment by spzala** [comment]
> @spzala Nothing special. You can just look at go.mod to make sure I am not upgrading any other vendors unintentionally.

@gyuho OK, thanks! Looking at it now.

**Comment by gyuho** [comment]
@spzala PTAL.

**Comment by spzala** [comment]
@gyuho thanks much for addressing the comments!! LGTM.

**Comment by spzala** [comment]
@gyuho just thought of changelog and was about to comment that we should update changelog in a separate PR considering the size of this PR. I will create one. Thanks!

**Pull request merged**
