### PR TITLE
etcdserver: use defer+unlock to avoid potential race

### LINKED ISSUE #10871: etcdserver: a read instruction to a field may need be protected
### Summary
There is a small inconsistency in code, but potentially a threat in the future.
### Location
In [etcdserver/server.go](https://github.com/etcd-io/etcd/blob/master/etcdserver/server.go), there are a few usages of `s.be`:
```Go
// line 1112 to 1294:
func (s *EtcdServer) applySnapshot(ep *etcdProgress, apply *apply) {
	...//some irrelevant code

	s.bemu.Lock()
	oldbe := s.be
	go func() {
	...//some code to close oldbe
	}()
	s.be = newbe
	s.bemu.Unlock()

	...//some code to handle error

	s.cluster.SetBackend(s.be)

	...//some irrelevant code
}

//line 2579 to 2583:
func (s *EtcdServer) Backend() backend.Backend {
	s.bemu.Lock()
	defer s.bemu.Unlock()
	return s.be
}
```
As you can see above, in this package, `s.be` is always protected by `s.bemu`, except the line at 1294:`s.cluster.SetBackend(s.be)` 
### Discussion
I think in current version there is no data race, because in every goroutine, the parent `applySnapshot` is only called once.

However, the inconsistency may produce problems in the future. If someone didn't realize `s.cluster.SetBackend(s.be)` was not protected and called `applySnapshot` in multiple goroutines, the race would happen.
### Suggestion
I think we can just put a "defer" before `s.bemu.Unlock`

### PR DESCRIPTION
**Pull request by lzhfromustc**
In etcdserver/server.go, `s.be` is always protected by `s.bemu`, except one read operation to it at line 1294 that is not in critical section.

Before this commit:
```Go
// line 1112 to 1294:
func (s *EtcdServer) applySnapshot(ep *etcdProgress, apply *apply) {
	...//some irrelevant code

	s.bemu.Lock()
	oldbe := s.be
	go func() {
	...//some code to close oldbe
	}()
	s.be = newbe
	s.bemu.Unlock()

	...//some code to handle error

	s.cluster.SetBackend(s.be)

	...//some irrelevant code
}
```
This commit changed the position of `s.bemu.Unlock()` and put a `defer` before it, so now `s.cluster.SetBackend(s.be)` is also covered in critical section.

Using `defer` is cumbersome, but I think it will be fine because `s.bemu` is only used twice in the whole etcd project. Besides, it is safer to use `defer` since this function has many branches that can panic.

Fixes #10871

### CODE REVIEW

**Comment by xiang90** [comment]
@lzhfromustc 

can you update `s.cluster.SetBackend(s.be)` to `s.cluster.SetBackend(newbe)` instead?

**Comment by lzhfromustc** [comment]
Good idea! Then I will keep `s.bemu.Unlock()` in its original place and won't put a `defer` before it.

**Comment by xiang90** [comment]
@lzhfromustc Can you squash two commits into one?

**Comment by lzhfromustc** [comment]
Sorry I am not familiar with these operations. Is it possible for me to delete my first commit? If not, maybe I can close this PR and open another one.

**Comment by xiang90** [comment]
you can create a new pr and close this one.

**Comment by lzhfromustc** [comment]
This PR is messy, so I opened another one #10879

**Pull request closed without merging**
