### PR TITLE
Modularization: Make pkg a module (and distribute not pkg code)

### PR DESCRIPTION
**Pull request by ptabor**
As pkg folder definition states: 

```
pkg/ is a collection of utility packages used by etcd without being specific to etcd itself. A package belongs here
only if it could possibly be moved out into its own repository in the future.
```

I found it cleaner to make pkg its own module instead of moving some packages to client or server modules. 
This way we can easily enforce dependency that no code in 'pkg' depends on etcd (neither client nor server). 

There were 2 violations of the rule in pkg mode: 
  - mock code was depending on etcd.  I moved the code out of pkg. 
  - zap raft_log was depending on /raft. Moved the code to etcdserver/zap_raft.

### CODE REVIEW

**Review by jingyih — COMMENTED** [review]
Since /mock is a fake etcdserver for testing purpose, does it make sense to move it to the new tests module?

**Review by jingyih — COMMENTED** [review]
I am not sure if we want to pack this utility function into a separate zap_raft package. Maybe move it to etcdserver/util.go?

**Comment by ptabor** [comment]
> Since /mock is a fake etcdserver for testing purpose, does it make sense to move it to the new tests module?

/tests is the module that will contain integration-style tests. In particular the tests that span the functionality of client & server. 
Mocks are used for unit tests, and allow e.g. to avoid code that makes 'client' depend on the server. 

> I am not sure if we want to pack this utility function into a separate zap_raft package. Maybe move it to etcdserver/util.go?

Will move it there.

**Comment by ptabor** [comment]
@jingyih I rebased this PR and its review ready.

**Comment by gyuho** [comment]
@ptabor Think we merged your other PRs first. Can we resolve conflicts?

**Comment by ptabor** [comment]
@gyuho. Thank you for merging the other PRs. The conflicts should be resolved now.

**Comment by jpbetz** [comment]
LGTM

**Pull request merged**
