### PR TITLE
[3.5] Bump bbolt to 1.3.11

### PR DESCRIPTION
**Pull request by akshaym-3255**
Fixes [#18480]

### CODE REVIEW

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, Akshay.

**Comment by ivanvc** [comment]
@jmhbnz, looks like the prow tests for this pull request and #18488 weren't triggered even after `/ok-to-test`. I know that sometimes they get triggered when you close and open the pull request. I'd do it, but I don't know if I can reopen them.

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @akshaym-3255

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Pull request merged**
