### PR TITLE
[2023-03-18] Weekly dependency update

### PR DESCRIPTION
**Pull request by jmhbnz**
This pull request completes this weeks etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

Summary of actions:

- [x] https://github.com/etcd-io/etcd/pull/17631 - Bumped.
- [x] https://github.com/etcd-io/etcd/pull/17602 - Bumped.
- [x] https://github.com/etcd-io/etcd/pull/17601 - Bumped.

- [ ] https://github.com/etcd-io/etcd/pull/17608 - Closed, indirect.
- [ ] https://github.com/etcd-io/etcd/pull/17607 - Closed, indirect.
- [ ] https://github.com/etcd-io/etcd/pull/17606 - Closed, indirect.
- [ ] https://github.com/etcd-io/etcd/pull/17603 - Closed, indirect.
- [ ] https://github.com/etcd-io/etcd/pull/17604 - Closed, indirect.
- [ ] https://github.com/etcd-io/etcd/pull/17630 - Closed, indirect.
- [ ] https://github.com/etcd-io/etcd/pull/17629 - Closed, indirect.
- [ ] https://github.com/etcd-io/etcd/pull/17628 - Closed, indirect.

### CODE REVIEW

**Comment by jmhbnz** [comment]
/hold 

We got a second round of dependency pr's this week so need to update this before merge.

**Comment by jmhbnz** [comment]
/unhold

Now ready for review

**Review by ahrtr — APPROVED** [review]
lgtm

Thanks

**Pull request merged**
