### PR TITLE
pkg/adt: interval tree based on rbtree

### PR DESCRIPTION
**Pull request by xkeyideal**
Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by gyuho** [comment]
Please make this `Fatalf`:

https://github.com/etcd-io/etcd/blob/9a2af7378a937a3434dd126e225108c97bef0cdf/pkg/adt/interval_tree_test.go#L301

**Comment by xkeyideal** [comment]
@gyuho I didn't change the interval_tree_test.go file

**Comment by gyuho** [comment]
@xkeyideal I meant, we should change this to `Fatalf` with this PR, so we can validate the fix

https://github.com/etcd-io/etcd/blob/9a2af7378a937a3434dd126e225108c97bef0cdf/pkg/adt/interval_tree_test.go#L301

**Comment by xkeyideal** [comment]
@gyuho has changed

**Comment by gyuho** [comment]
@xkeyideal Awesome. Thanks for the contribution!

**Comment by gyuho** [comment]
This fix is merged as https://github.com/etcd-io/etcd/commit/003362ef8e0e16e34114bd499dee272a34f6c658.

Thanks @xkeyideal !

**Comment by jingyih** [comment]
@xkeyideal Thanks!

**Comment by jingyih** [comment]
@gyuho I think we need to backport this? Also update the changelog? Feel free to assign me.

**Comment by gyuho** [comment]
@jingyih Already backported :)

**Comment by gyuho** [comment]
I meant, backported to 3.4 branch. Not yet for 3.3. Let's run tests during our 3.4 release cycle. If it looks good, we can backport https://github.com/etcd-io/etcd/commit/003362ef8e0e16e34114bd499dee272a34f6c658 to 3.3

**Pull request merged**
