### PR TITLE
[3.4] Fix delete inconsistencies in read buffer

### PR DESCRIPTION
**Pull request by siyuanfoundation**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

backport https://github.com/etcd-io/etcd/pull/17195 to 3.4

part of https://github.com/etcd-io/etcd/issues/17158

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]

**Comment by fuweid** [comment]
Created https://github.com/etcd-io/etcd/issues/17241 to track e2e timeout issue.

**Review by fuweid — APPROVED** [review]
LGTM on green

**Comment by ahrtr** [comment]
The 3.4 e2e test has timedout for 5 times. Can anyone investigate why it gets slower and which tests consume most of the time? We should try to improvement it and increase the timeout if needed.

**Pull request merged**
