### PR TITLE
Add Cyberfusion to adopters

### PR DESCRIPTION
**Pull request by WilliamDEdwards**
Add Cyberfusion to adopters.

I added the URL to an article detailing our use of etcd. Of the available fields, the 'Backups' one seems most appropriate. If it should be (re)moved, please let me know.

### CODE REVIEW

**Review by jmhbnz — COMMENTED** [review]
Hey @WilliamDEdwards - Thanks for letting us know about this.

Please ensure your commit is signed so the developer certificate of origin (DCO) check passes, i.e:

```bash
git rebase HEAD~1 --signoff
git push --force
```

/ok-to-test

**Comment by WilliamDEdwards** [comment]
> Hey @WilliamDEdwards - Thanks for letting us know about this.
> 
> Please ensure your commit is signed so the developer certificate of origin (DCO) check passes, i.e:
> 
> ```shell
> git rebase HEAD~1 --signoff
> git push --force
> ```
> 
> /ok-to-test

Done.

**Comment by tjungblu** [comment]
/test pull-etcd-unit-test

reported the current failure as flake, otherwise /lgtm (non-binding)

**Comment by jmhbnz** [comment]
Hey @WilliamDEdwards - We had an issue recently with a change causing test timeouts which is now reverted.  Would you mind please rebasing this so all the tests pass, thanks!

**Comment by WilliamDEdwards** [comment]
> Hey @WilliamDEdwards - We had an issue recently with a change causing test timeouts which is now reverted. Would you mind please rebasing this so all the tests pass, thanks!

No problem. Done.

**Review by jmhbnz — APPROVED** [review]

**Review by ahrtr — APPROVED** [review]
lgtm

**Pull request merged**
