### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by zqzzq**
Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by jingyih** [comment]
Thank you! Could you update (and force push) the commit title? It needs to be in the format of `pkg: description`. So you can use `*: fix typo`

**Comment by jingyih** [comment]
> thanks, lgtm! Since it's a naming change in error code we should mention it into the changelog. Also since v3.4 will be around for sometime we should backport it too /cc @jingyih

Good point. Fortunately this error type is fairly new. If we correct it and backport now, hopefully we won't break many users.

**Comment by spzala** [comment]
> > thanks, lgtm! Since it's a naming change in error code we should mention it into the changelog. Also since v3.4 will be around for sometime we should backport it too /cc @jingyih
> 
> Good point. Fortunately this error type is fairly new. If we correct it and backport now, hopefully we won't break many users.

Thanks @jingyih I agree, good to go with the fix.

**Comment by spzala** [comment]
@zqzzq would you like to make changelog entries and work on backporting it to 3.4? You can do a separate PRs. Thanks!

**Pull request closed without merging**
