### PR TITLE
etcdserver: wait for raft being notified on confChange before responding to client

### PR DESCRIPTION
**Pull request by ahrtr**
See discussion in https://github.com/etcd-io/etcd/issues/15528

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
https://github.com/etcd-io/etcd/issues/15528#issuecomment-1505080365

**Comment by ahrtr** [comment]
> @ahrtr, how does "work on top of my PR" work? Is it cherry-pick your commit somehow and add my changes (rename and add tests) on top of it?

Sounds good to me. Or
1. fork a dev-branch on top of my dev-branch (`confchange_raft_sync_20230412` in this case);
2. rebase the branch;
3. add your new commits on top of it.

**Comment by chaochn47** [comment]
> > @ahrtr, how does "work on top of my PR" work? Is it cherry-pick your commit somehow and add my changes (rename and add tests) on top of it?
> 
> Sounds good to me. Or
> 
>     1. fork a dev-branch on top of my dev-branch (`confchange_raft_sync_20230412` in this case);
> 
>     2. rebase the branch;
> 
>     3. add your new commits on top of it.

That is easier! Thanks!!

**Comment by serathius** [comment]
Closing to avoid confusion as work will continue in https://github.com/etcd-io/etcd/pull/15708.

**Comment by ahrtr** [comment]
Reopen for test/verification only

**Pull request closed without merging**
