### PR TITLE
server/proxy/tcpproxy: use net.JoinHostPort rather than formatAddr

### PR DESCRIPTION
**Pull request by callthingsoff**
formatAddr is just like net.JoinHostPort, I think we can use net.JoinHostPort
directly, it's simpler and clearer.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks for the cleanup.

**Comment by callthingsoff** [comment]
Ping @serathius, @fuweid.

**Comment by callthingsoff** [comment]
cc @ivanvc @siyuanfoundation

**Review by ivanvc — COMMENTED** [review]
/lgtm

**Review by siyuanfoundation — APPROVED** [review]

**Comment by siyuanfoundation** [comment]
Thanks @callthingsoff for simplifying the code!

**Pull request merged**
