### PR TITLE
*: bump to go1.19.2 from 1.19.1

### PR DESCRIPTION
**Pull request by vivekpatani**
- update .github workflows
- update tests

Signed-off-by: vivekpatani <9080894+vivekpatani@users.noreply.github.com>

### CODE REVIEW

**Comment by vivekpatani** [comment]
I based it off of: https://github.com/etcd-io/etcd/commit/cb5f7276c39cb2e69765cd5fb5a4a8868367f728

@ahrtr @serathius question, why don't we pin the `go.mod` in all the packages to `1.19.2` and just leave them at `1.19` but while testing we pin the version. Just trying to understand the reasoning, instead of being consistent all across. Thanks.

**Comment by ahrtr** [comment]
> I based it off of: [cb5f727](https://github.com/etcd-io/etcd/commit/cb5f7276c39cb2e69765cd5fb5a4a8868367f728)
> 
> @ahrtr @serathius question, why don't we pin the `go.mod` in all the packages to `1.19.2` and just leave them at `1.19` but while testing we pin the version. Just trying to understand the reasoning, instead of being consistent all across. Thanks.

I did not quite catch your question. The go version included in go.mod file must match the format of `major.minor,` no patch version is allowed.

**Comment by vivekpatani** [comment]
Understood.

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @vivekpatani 

cc @serathius @spzala @ptabor @mitake for awareness.

**Comment by serathius** [comment]
Thanks! Would be great to validate that all versions in different files are consistent.

**Pull request merged**
