### PR TITLE
Adding support for RISC-V

### PR DESCRIPTION
**Pull request by advancedwebdeveloper**
Enabling support for RISC-V arch

### CODE REVIEW

**Comment by ahrtr** [comment]
@advancedwebdeveloper  Are you planning to deploy etcd on `linux` + `riscv64` in production environment? 

It's the first time I see the ask for supporting `linux` + `riscv64` in the past year. Golang started to add `riscv64` in go1.14 as [an experimental support](https://tip.golang.org/doc/go1.14#riscv). Although there are some improvements on that arch in the following releases, it's still new as compared to other arch. I would suggest to hold off until we get more requirement in the community. 

It seems we do not have a standard process/document to add support on new platform/arch. cc @spzala @serathius @ptabor

**Comment by serathius** [comment]
From what I found riskv64 is supported in golang. Experimental was true for go1.14. Since then it's fully supported. https://groups.google.com/g/golang-nuts/c/m4OF6nieGro

> It seems we do not have a standard process/document to add support on new platform/arch. cc @spzala @serathius @ptabor
I don't think we will need this too often (maybe 2-3 architectures) I think we can base introduction of riskv64 support on previous ones and https://etcd.io/docs/v3.6/op-guide/supported-platform/. 

@advancedwebdeveloper Please split this PR into two. First we want to start building `riskv64` in CI and only after it's stable we will mark it as supported.

**Comment by advancedwebdeveloper** [comment]
> @advancedwebdeveloper Please split this PR into two. First we want to start building `riskv64` in CI and only after it's stable we will mark it as supported.
@serathius , I am heading to create a CI related PR separately. As you requested

**Comment by advancedwebdeveloper** [comment]
I was able to build a container image:

> $ docker run eaf3bcfea4b1
> {"level":"warn","ts":"2022-09-27T09:46:48.211Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_UNSUPPORTED_ARCH=riscv64"}
> {"level":"info","ts":"2022-09-27T09:46:48.248Z","caller":"etcdmain/etcd.go:63","msg":"Running: ","args":["/usr/local/bin/etcd"]}
> {"level":"warn","ts":"2022-09-27T09:46:48.331Z","caller":"etcdmain/etcd.go:95","msg":"'data-dir' was empty; using default","data-dir":"default.etcd"}
> {"level":"info","ts":"2022-09-27T09:46:48.336Z","caller":"etcdmain/etcd.go:123","msg":"Initialize and start etcd server","data-dir":"default.etcd","dir-type":"empty"}
> {"level":"info","ts":"2022-09-27T09:46:48.344Z","caller":"embed/etcd.go:121","msg":"configuring peer listeners","listen-peer-urls":["http://localhost:2380"]}
> {"level":"info","ts":"2022-09-27T09:46:48.513Z","caller":"embed/etcd.go:129","msg":"configuring client listeners","listen-client-urls":["http://localhost:2379"]}
> {"level":"info","ts":"2022-09-27T09:46:48.537Z","caller":"embed/etcd.go:310","msg":"starting an etcd server","etcd-version":"3.6.0-alpha.0","git-sha":"4513671b6","go-version":"go1.19.1","go-os":"linux","go-arch":"riscv64","max-cpu-set":4,"max-cpu-available":4,"member-initialized":false,"name":"default","data-dir":"default.etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"default.etcd/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","wait-cluster-ready-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"],"listen-client-urls":["http://localhost:2379"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"default=http://localhost:2380","initial-cluster-state":"new","initial-cluster-token":"etcd-cluster","quota-backend-bytes":2147483648,"max-request-bytes":1572864,"max-concurrent-streams":4294967295,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","compact-check-time-enabled":false,"compact-check-time-interval":"1m0s","auto-compaction-mode":"periodic","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","discovery-token":"","discovery-endpoints":"","discovery-dial-timeout":"2s","discovery-request-timeout":"5s","discovery-keepalive-time":"2s","discovery-keepalive-timeout":"6s","discovery-insecure-transport":true,"discovery-insecure-skip-tls-verify":false,"discovery-cert":"","discovery-key":"","discovery-cacert":"","discovery-user":"","downgrade-check-interval":"5s","max-learners":1}
> {"level":"info","ts":"2022-09-27T09:46:48.716Z","caller":"storage/backend.go:81","msg":"opened backend db","path":"default.etcd/member/snap/db","took":"80.144438ms"}
> {"level":"info","ts":"2022-09-27T09:46:49.000Z","caller":"etcdserver/bootstrap.go:499","msg":"starting local member","local-member-id":"8e9e05c52164694d","cluster-id":"cdf818194e3a8c32"}
> {"level":"info","ts":"2022-09-27T09:46:49.057Z","logger":"raft","caller":"raft/raft.go:1665","msg":"8e9e05c52164694d switched to configuration voters=()"}
> {"level":"info","ts":"2022-09-27T09:46:49.080Z","logger":"raft","caller":"raft/raft.go:702","msg":"8e9e05c52164694d became follower at term 0"}
> {"level":"info","ts":"2022-09-27T09:46:49.090Z","logger":"raft","caller":"raft/raft.go:367","msg":"newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]"}
> {"level":"info","ts":"2022-09-27T09:46:49.092Z","logger":"raft","caller":"raft/raft.go:702","msg":"8e9e05c52164694d became follower at term 1"}
> {"level":"info","ts":"2022-09-27T09:46:49.140Z","logger":"raft","caller":"raft/raft.go:1665","msg":"8e9e05c52164694d switched to configuration voters=(10276657743932975437)"}
> {"level":"warn","ts":"2022-09-27T09:46:49.229Z","caller":"auth/store.go:1118","msg":"simple token is not cryptographically signed"}
> {"level":"info","ts":"2022-09-27T09:46:49.324Z","caller":"mvcc/kvstore.go:383","msg":"kvstore restored","current-rev":1}
> {"level":"info","ts":"2022-09-27T09:46:49.475Z","caller":"storage/quota.go:93","msg":"enabled backend quota with default value","quota-name":"v3-applier","quota-size-bytes":2147483648,"quota-size":"2.1 GB"}
> {"level":"info","ts":"2022-09-27T09:46:49.487Z","caller":"etcdserver/server.go:581","msg":"starting etcd server","local-member-id":"8e9e05c52164694d","local-server-version":"3.6.0-alpha.0","cluster-version":"to_be_decided"}
> {"level":"info","ts":"2022-09-27T09:46:49.507Z","caller":"etcdserver/server.go:466","msg":"started as single-node; fast-forwarding election ticks","local-member-id":"8e9e05c52164694d","forward-ticks":9,"forward-duration":"900ms","election-ticks":10,"election-timeout":"1s"}
> {"level":"info","ts":"2022-09-27T09:46:49.528Z","caller":"embed/etcd.go:596","msg":"serving peer traffic","address":"127.0.0.1:2380"}
> {"level":"info","ts":"2022-09-27T09:46:49.528Z","caller":"embed/etcd.go:568","msg":"cmux::serve","address":"127.0.0.1:2380"}
> {"level":"info","ts":"2022-09-27T09:46:49.604Z","caller":"embed/etcd.go:279","msg":"now serving peer/client/metrics","local-member-id":"8e9e05c52164694d","initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"],"listen-client-urls":["http://localhost:2379"],"listen-metrics-urls":[]}
> {"level":"info","ts":"2022-09-27T09:46:50.024Z","logger":"raft","caller":"raft/raft.go:1665","msg":"8e9e05c52164694d switched to configuration voters=(10276657743932975437)"}
> {"level":"info","ts":"2022-09-27T09:46:50.069Z","caller":"membership/cluster.go:404","msg":"added member","cluster-id":"cdf818194e3a8c32","local-member-id":"8e9e05c52164694d","added-peer-id":"8e9e05c52164694d","added-peer-peer-urls":["http://localhost:2380"],"added-peer-is-learner":false}
> {"level":"info","ts":"2022-09-27T09:46:50.863Z","logger":"raft","caller":"raft/raft.go:793","msg":"8e9e05c52164694d is starting a new election at term 1"}
> {"level":"info","ts":"2022-09-27T09:46:50.864Z","logger":"raft","caller":"raft/raft.go:731","msg":"8e9e05c52164694d became pre-candidate at term 1"}
> {"level":"info","ts":"2022-09-27T09:46:50.881Z","logger":"raft","caller":"raft/raft.go:853","msg":"8e9e05c52164694d received MsgPreVoteResp from 8e9e05c52164694d at term 1"}
> {"level":"info","ts":"2022-09-27T09:46:50.886Z","logger":"raft","caller":"raft/raft.go:715","msg":"8e9e05c52164694d became candidate at term 2"}
> {"level":"info","ts":"2022-09-27T09:46:50.888Z","logger":"raft","caller":"raft/raft.go:853","msg":"8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2"}
> {"level":"info","ts":"2022-09-27T09:46:50.889Z","logger":"raft","caller":"raft/raft.go:771","msg":"8e9e05c52164694d became leader at term 2"}
> {"level":"info","ts":"2022-09-27T09:46:50.889Z","logger":"raft","caller":"raft/node.go:336","msg":"raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2"}
> {"level":"info","ts":"2022-09-27T09:46:50.959Z","caller":"etcdserver/server.go:2281","msg":"setting up initial cluster version using v3 API","cluster-version":"3.6"}
> {"level":"info","ts":"2022-09-27T09:46:50.968Z","caller":"embed/serve.go:110","msg":"ready to serve client requests"}
> {"level":"info","ts":"2022-09-27T09:46:50.968Z","caller":"etcdserver/server.go:1728","msg":"published local member to cluster through raft","local-member-id":"8e9e05c52164694d","local-member-attributes":"{Name:default ClientURLs:[http://localhost:2379]}","cluster-id":"cdf818194e3a8c32","publish-timeout":"7s"}
> {"level":"info","ts":"2022-09-27T09:46:50.991Z","caller":"etcdmain/main.go:44","msg":"notifying init daemon"}
> {"level":"info","ts":"2022-09-27T09:46:51.000Z","caller":"etcdmain/main.go:50","msg":"successfully notified init daemon"}
> {"level":"info","ts":"2022-09-27T09:46:51.016Z","caller":"membership/cluster.go:547","msg":"set initial cluster version","cluster-id":"cdf818194e3a8c32","local-member-id":"8e9e05c52164694d","cluster-version":"3.6"}
> {"level":"info","ts":"2022-09-27T09:46:51.034Z","caller":"api/capability.go:76","msg":"enabled capabilities for version","cluster-version":"3.6"}
> {"level":"info","ts":"2022-09-27T09:46:51.037Z","caller":"etcdserver/server.go:2301","msg":"cluster version is updated","cluster-version":"3.6"}
> {"level":"info","ts":"2022-09-27T09:46:51.075Z","caller":"version/monitor.go:104","msg":"cluster version differs from storage version.","cluster-version":"3.6.0","storage-version":"3.5.0"}
> {"level":"info","ts":"2022-09-27T09:46:51.194Z","caller":"schema/migration.go:64","msg":"updated storage version","new-storage-version":"3.6.0"}
> {"level":"info","ts":"2022-09-27T09:46:51.422Z","caller":"embed/serve.go:162","msg":"serving client traffic insecurely; this is strongly discouraged!","address":"127.0.0.1:2379"}
>

**Comment by advancedwebdeveloper** [comment]
https://github.com/etcd-io/etcd/blob/abef537a90caece9dc3215f9ae9e2b3f643a88fa/Dockerfile-release.arm64#L10 
and
https://github.com/etcd-io/etcd/blob/abef537a90caece9dc3215f9ae9e2b3f643a88fa/Dockerfile-release.arm64#L11

are unclear to me

**Comment by advancedwebdeveloper** [comment]
I have created a file Dockerfile-release.riscv64

**Comment by ptabor** [comment]
I think that semi-process is here:
  https://etcd.io/docs/v3.5/op-guide/supported-platform/

But it seems the file and code diverged. 
  - Imho we should fail by default for all Tier3 architectures
  - We should print warning for Tier2 architectures. 
  
We should promote arm64 to Tier2 (and run tests on cloud provisioned ones).

**Comment by iggy** [comment]
Any thoughts on reviving this? There are now a number of riscv64 boards on (or approaching) the market. Most of them have better upstream Linux support than your average aarch64 board.

**Comment by ahrtr** [comment]
Does github runner support riscv64?

**Pull request closed without merging**
