### PR TITLE
tests/robustness: Implement proper range requests

### PR DESCRIPTION
**Pull request by serathius**
Change `key` in range requests to `start`, `end`

### CODE REVIEW

**Comment by serathius** [comment]
cc @ahrtr @ptabor @jmhbnz @fuweid @chaochn47

**Comment by serathius** [comment]
Interesting failure https://github.com/etcd-io/etcd/actions/runs/5319632601?pr=16113

**Comment by serathius** [comment]
Ups, force pushed empty branch.

**Comment by chaochn47** [comment]
The changes LGTM. 

The robustness failed though. 

```
operations.go:40: Model is not linearizable
```

` --- FAIL: TestRobustness/Kubernetes/ClusterOfSize3 (306.46s)` https://github.com/etcd-io/etcd/actions/runs/5320783132/jobs/9635013271?pr=16113

**Comment by serathius** [comment]
Yea, there is a bug somewhere :( 
Not sure where

**Comment by serathius** [comment]
Fixed the bug.

**Pull request merged**
