### PR TITLE
Robustness duplicated puts 3

### PR DESCRIPTION
**Pull request by serathius**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by serathius** [comment]
cc @ah8ad3 @ahrtr @MadhavJivrajani @henrybear327 @siyuanfoundation @jmhbnz @fuweid

**Comment by serathius** [comment]
ping @jmhbnz

**Review by jmhbnz — APPROVED** [review]
LGTM

**Pull request merged**
