### PR TITLE
Fix corruption checks v3.5

### PR DESCRIPTION
**Pull request by serathius**
Backport:
* https://github.com/etcd-io/etcd/pull/14049
* https://github.com/etcd-io/etcd/pull/14120
* https://github.com/etcd-io/etcd/pull/14272

cc @ahrtr

### CODE REVIEW

**Comment by serathius** [comment]
Change seem big as it adds 1800 LOC, however over 1500 of lines is just adding tests.

**Review by ahrtr — APPROVED** [review]

**Comment by serathius** [comment]
Want to validate Compact performance before merging.

**Review by ptabor — APPROVED** [review]

**Comment by serathius** [comment]
Verified performance and didn't find any significant difference with different configuration of auto-compaction and compact-hash-check.

**Comment by ahrtr** [comment]
Fixed https://github.com/etcd-io/etcd/pull/14282 in release-3.5.

It took me a couple of minutes to find this PR,  because you got the issue link instead of this PR included in the changelog-3.5

**Pull request merged**
