### PR TITLE
Update OWNERS: Retire ptabor

### PR DESCRIPTION
**Pull request by ptabor**
Hi, 
I think, it's a high time for me to retire. No contributions over last 6m.  There is a hope, I will be back working on etcd, but over last 6m it kept being just 2 months away, so not converging. 

Thank you all,
Piotr

### CODE REVIEW

**Review by serathius — APPROVED** [review]

**Comment by serathius** [comment]
Thanks for all your hard work!

Would be great if you could also add yourself to https://github.com/etcd-io/etcd/blob/main/README.md#etcd-emeritus-maintainers

**Comment by ahrtr** [comment]
> There is a hope, I will be back working on etcd

@ptabor 
You've played a vital role as a leading maintainer in the community.
Really hope you can come back someday!

Thank you!

**Review by jmhbnz — APPROVED** [review]
Many thanks for all your contributions @ptabor.  Best of luck and I hope there will be the opportunity for you to return in future 🙏🏻 

 

Sidenote: Can you please signoff the commits so we can merge.

**Comment by fuweid** [comment]
Hi @ptabor , Hope you can come back! Thank you!

**Review by ahrtr — APPROVED** [review]

**Pull request merged**
