### PR TITLE
Doc/etcd-mixin: provide better user experience for monitoring etcd

### PR DESCRIPTION
**Pull request by paulfantom**
A small change to add automatic refresh in grafana dashboard. This should provide better user experience when viewing etcd dashboard.

/cc: @brancz

### CODE REVIEW

**Comment by brancz** [comment]
could you also update the generated dashboard: https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/grafana.json

otherwise lgtm

**Comment by paulfantom** [comment]
done

**Comment by brancz** [comment]
lgtm on green

/cc @xiang90 @gyuho @hexfusion

**Comment by paulfantom** [comment]
CI failures seem to be unrelated to this change.

**Pull request merged**
