### PR TITLE
raft/log: remove redundant code logic

### PR DESCRIPTION
**Pull request by viviyww**
raft/log: remove redundant code logic

Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by viviyww** [comment]
cc @spzala

**Comment by ptabor** [comment]
LGTM: Indeed the `lo<fi` check happens in line 357 and fast-returns.

**Comment by viviyww** [comment]
cc @Jingyi Hu

**Comment by viviyww** [comment]
cc @jpbetz

**Pull request merged**
