### PR TITLE
[Do-not-review] add experimental flag for watch notify interval

### PR DESCRIPTION
**Pull request by jingyih**
For experimental purpose only.

### CODE REVIEW

**Comment by jingyih** [comment]
cc @jpbetz

**Comment by xiang90** [comment]
shall we make this a global flag? or a per watch configuration?

**Comment by xiang90** [comment]
my initial thought is to support global min value (do not overload server if user sets a very small value at per watcher level) and a per watcher value.

**Comment by jingyih** [comment]
> my initial thought is to support global min value (do not overload server if user sets a very small value at per watcher level) and a per watcher value.

This sounds good to me. So the global min value would be configured as a server flag, and the per watcher value is configured via an optional field in watch create request?

**Comment by xiang90** [comment]
> This sounds good to me. So the global min value would be configured as a server flag, and the per watcher value is configured via an optional field in watch create request?

yes. we can do this in two steps though.

**Comment by jingyih** [comment]
Reopening this PR (just rebased). It seems useful to make the watch progress notify interval configurable. For example, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1904-efficient-watch-resumption

cc @xiang90 @gyuho @wojtek-t @ptabor

**Comment by jingyih** [comment]
I cannot reopen this PR... Let me create a new one.

**Pull request closed without merging**
