### PR TITLE
Issue 11383: make mirror accept auth credentials

### PR DESCRIPTION
**Pull request by schlitzered**
Hi,

the request solves the issue in the title.

two new arguments have been introduced for the make-mirror subcommand:
 --dest-user and --dest-password.

both work similar to the --user and --password global arguments.

--dest-user can either be  "$USERNAM:$PASSWORD
or "$PASWORD".

if --dest-password is not provided, the cli will ask for "Destination Password"

the extension is working as expected, i tested it locally.

### CODE REVIEW

**Comment by jingyih** [comment]
For reference: fixes #11383

**Comment by xiang90** [comment]
lgtm

**Comment by yvanadamov** [comment]
Hi Guys,

In which version is added this? I tried it in 3.4.13:

etcdctl make-mirror http://$IP:2379 --prefix=test --dest-user $USER:PASSWORD

And I received:
Error: unknown flag: --dest-user

**Comment by spzala** [comment]
> Hi Guys,
> 
> In which version is added this? I tried it in 3.4.13:
> 
> etcdctl make-mirror http://$IP:2379 --prefix=test --dest-user $USER:$PASSWORD
> 
> And I received:
> Error: unknown flag: --dest-user

@yvanadamov I think this went into 3.4.15 - can you please check it? Thanks!

**Comment by JamesXNelson** [comment]
just fyi, these options are not documented, and it would be very helpful if they were in the command help / online documentation.

**Comment by xiang90** [comment]
@JamesXNelson 

Maybe you could help submit a PR to get this documented :)

**Pull request merged**
