### PR TITLE
[3.5] make: Include tools/mod when checking dependency versions

### PR DESCRIPTION
**Pull request by thedtripp**
Backport of https://github.com/etcd-io/etcd/pull/18280/commits/ba4b2bffebb37afd95144f53ab1e1e08b55caefc

Related issue: https://github.com/etcd-io/etcd/issues/18180

~~@ivanvc
I'm not sure how/if to do the version bump for genproto as in: ddfa70fb5591e933350dc37d8aed1241ac94287c.
Please advise on how/if to do this. Thanks!~~

### CODE REVIEW

**Comment by ivanvc** [comment]
> @ivanvc
> I'm not sure how/if to do the version bump for genproto as in: [ddfa70f](https://github.com/etcd-io/etcd/commit/ddfa70fb5591e933350dc37d8aed1241ac94287c).
> Please advise on how/if to do this. Thanks!

We don't need to update the following dependencies (refer to https://github.com/etcd-io/etcd/actions/runs/9800578072/job/27062635624):

```
FAIL: inconsistent versions for depencency: github.com/grpc-ecosystem/grpc-gateway
  ...
  - github.com/grpc-ecosystem/grpc-gateway@v1.16.0 from: go.etcd.io/etcd/tests/v3
  - github.com/grpc-ecosystem/grpc-gateway@v1.14.6 from: go.etcd.io/etcd/tools/v3
FAIL: inconsistent versions for depencency: github.com/mattn/go-colorable
  - github.com/mattn/go-colorable@v0.1.11 (indirect) from: go.etcd.io/etcd/v3
  - github.com/mattn/go-colorable@v0.1.7 (indirect) from: go.etcd.io/etcd/tools/v3
FAIL: inconsistent versions for depencency: github.com/mattn/go-runewidth
  ...
  - github.com/mattn/go-runewidth@v0.0.9 (indirect) from: go.etcd.io/etcd/v3
  - github.com/mattn/go-runewidth@v0.0.7 (indirect) from: go.etcd.io/etcd/tools/v3
FAIL: inconsistent versions for depencency: github.com/olekukonko/tablewriter
  ...
  - github.com/olekukonko/tablewriter@v0.0.5 from: go.etcd.io/etcd/etcdutl/v3
  - github.com/olekukonko/tablewriter@v0.0.4 (indirect) from: go.etcd.io/etcd/tools/v3
FAIL: inconsistent versions for depencency: github.com/spf13/cobra
  ...
  - github.com/spf13/cobra@v1.1.3 from: go.etcd.io/etcd/v3
  - github.com/spf13/cobra@v1.0.0 (indirect) from: go.etcd.io/etcd/tools/v3
FAIL: inconsistent versions for depencency: google.golang.org/genproto
  ...
  - google.golang.org/genproto@v0.0.0-20230822172742-b8732ec3820d (indirect) from: go.etcd.io/etcd/v3
  - google.golang.org/genproto@v0.0.0-20201008135153-289734e2e40c (indirect) from: go.etcd.io/etcd/tools/v3
FAIL: inconsistent versions for depencency: gopkg.in/yaml.v2
  ...
  - gopkg.in/yaml.v2@v2.4.0 from: go.etcd.io/etcd/tests/v3
  - gopkg.in/yaml.v2@v2.3.0 (indirect) from: go.etcd.io/etcd/tools/v3
FAIL: inconsistent dependencies
```

The versions specified in `tools/mod` need to match the versions used in the rest of the project.

i.e.,

* bump `tools/mod`'s `github.com/grpc-ecosystem/grpc-gateway` from v1.14.0 to v1.16.0
* bumo `tools/mod`'s `github.com/mattn/go-colorable` from v0.1.7 to v0.1.11 
* etc

**Comment by thedtripp** [comment]
> > @ivanvc
> > I'm not sure how/if to do the version bump for genproto as in: [ddfa70f](https://github.com/etcd-io/etcd/commit/ddfa70fb5591e933350dc37d8aed1241ac94287c).
> > Please advise on how/if to do this. Thanks!
> 
> We need to update the following dependencies (refer to https://github.com/etcd-io/etcd/actions/runs/9800578072/job/27062635624):
> 
> ```
> FAIL: inconsistent versions for depencency: github.com/grpc-ecosystem/grpc-gateway
>   ...
>   - github.com/grpc-ecosystem/grpc-gateway@v1.16.0 from: go.etcd.io/etcd/tests/v3
>   - github.com/grpc-ecosystem/grpc-gateway@v1.14.6 from: go.etcd.io/etcd/tools/v3
> FAIL: inconsistent versions for depencency: github.com/mattn/go-colorable
>   - github.com/mattn/go-colorable@v0.1.11 (indirect) from: go.etcd.io/etcd/v3
>   - github.com/mattn/go-colorable@v0.1.7 (indirect) from: go.etcd.io/etcd/tools/v3
> FAIL: inconsistent versions for depencency: github.com/mattn/go-runewidth
>   ...
>   - github.com/mattn/go-runewidth@v0.0.9 (indirect) from: go.etcd.io/etcd/v3
>   - github.com/mattn/go-runewidth@v0.0.7 (indirect) from: go.etcd.io/etcd/tools/v3
> FAIL: inconsistent versions for depencency: github.com/olekukonko/tablewriter
>   ...
>   - github.com/olekukonko/tablewriter@v0.0.5 from: go.etcd.io/etcd/etcdutl/v3
>   - github.com/olekukonko/tablewriter@v0.0.4 (indirect) from: go.etcd.io/etcd/tools/v3
> FAIL: inconsistent versions for depencency: github.com/spf13/cobra
>   ...
>   - github.com/spf13/cobra@v1.1.3 from: go.etcd.io/etcd/v3
>   - github.com/spf13/cobra@v1.0.0 (indirect) from: go.etcd.io/etcd/tools/v3
> FAIL: inconsistent versions for depencency: google.golang.org/genproto
>   ...
>   - google.golang.org/genproto@v0.0.0-20230822172742-b8732ec3820d (indirect) from: go.etcd.io/etcd/v3
>   - google.golang.org/genproto@v0.0.0-20201008135153-289734e2e40c (indirect) from: go.etcd.io/etcd/tools/v3
> FAIL: inconsistent versions for depencency: gopkg.in/yaml.v2
>   ...
>   - gopkg.in/yaml.v2@v2.4.0 from: go.etcd.io/etcd/tests/v3
>   - gopkg.in/yaml.v2@v2.3.0 (indirect) from: go.etcd.io/etcd/tools/v3
> FAIL: inconsistent dependencies
> ```
> 
> The versions specified in `tools/mod` need to match the versions used in the rest of the project.
> 
> i.e.,
> 
>     * bump `tools/mod`'s `github.com/grpc-ecosystem/grpc-gateway` from v1.14.0 to v1.16.0
> 
>     * bump `tools/mod`'s `github.com/mattn/go-colorable` from v0.1.7 to v0.1.11
> 
>     * **bump `tools/mod`'s `google.golang.org/genproto` to `@v0.0.0-20230822172742-b8732ec3820d`**
> 
>     * etc

Nice. I think I've got it working. Thanks!

**Comment by ivanvc** [comment]
I suggest not to squash the dependency bumps into a single commit but do one commit per dependency per our (dependency management guide)[https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md#steps-to-bump-a-dependency]. Refer to https://github.com/etcd-io/etcd/pull/18205/commits, https://github.com/etcd-io/etcd/pull/18207/commits

**Comment by thedtripp** [comment]
> I suggest not to squash the dependency bumps into a single commit but do one commit per dependency per our [dependency management guide](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md#steps-to-bump-a-dependency). Refer to https://github.com/etcd-io/etcd/pull/18205/commits, https://github.com/etcd-io/etcd/pull/18207/commits

Ok. I'll read those docs and split each dependency into a separate commit.

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @thedtripp

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @thedtripp

**Review by ahrtr — APPROVED** [review]

**Pull request merged**
