### PR TITLE
[main] Bump go toolchain to 1.23.1

### PR DESCRIPTION
**Pull request by henrybear327**
Reference:
- https://github.com/etcd-io/etcd/issues/18548
- https://github.com/kubernetes/release/issues/3650

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, Henry. By the way, it looks like there were a lot of test flakes :worried:.

**Comment by henrybear327** [comment]
> LGTM. Thanks, Henry. By the way, it looks like there were a lot of test flakes :worried:.

Yeah, I wasn't sure if it's just tonight because my other 2 PRs also are flaky :(

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @henrybear327

**Pull request merged**
