### PR TITLE
Robustness fix blackhole

### PR DESCRIPTION
**Pull request by serathius**
cc @ahrtr @ptabor

### CODE REVIEW

**Comment by serathius** [comment]
Enabling TLS fixes the issue  with blackholing https://github.com/etcd-io/etcd/actions/runs/4583625819

**Comment by ahrtr** [comment]
do not get time to follow up https://github.com/etcd-io/etcd/issues/15595, please clarify why the issue did not affect TLS.

**Comment by serathius** [comment]
Proxy we are using is doing byte manipulation on arbitrary byte, with no regards for packets. It just reads the stream of bytes and writes stream of bytes. This means that it doesn't really simulate packet loss line normal network will experience, as it will repackage remaining bytes into new packets. So for receiver behind the proxy they just get arbitrary bytes from stream, without any signs of manipulation (repackaging by proxy provides new control sums). I expect that for TLS this doesn't work as byte manipulation will make data invalid after decryption.

So without TLS blackholing is not really packet loss, but a removal of arbitrary bytes from connection stream. This is works more like arbitrary packet manipulation than what can happen in real network. Enabling TLS helps as receiver can detect corrupted byte stream and avoid using corrupted byte stream.

**Comment by ahrtr** [comment]
> I expect that for TLS this doesn't work as byte manipulation will make data invalid after decryption.

Thanks for the clarification.

**Review by ahrtr — APPROVED** [review]

**Review by jmhbnz — APPROVED** [review]
LGTM

**Review by ptabor — APPROVED** [review]

**Pull request merged**
