### PR TITLE
ETCDCTL_README: clarify the usage of ETCDCTL_* variables

### LINKED ISSUE #10840: etcdctl unsetting ETCDCTL_API in lock exec
`etcdctl lock <lockname> exec` appears to be unsetting the environment variable ETCDCTL_API for the executed command. (And it might be unsetting other ETCDCTL_X variables, I haven't checked...)

For example:

```shell
13:59 $ MY_API=3 ETCDCTL_API=3 etcdctl lock /locks env | grep API
MY_API=3
✔ ~
```

Only `MY_API` shows up in the output.

```shell
13:59 $ etcd --version
etcd Version: 3.3.12
Git SHA: GitNotFound
Go Version: go1.11.5
Go OS/Arch: darwin/amd64
✔ ~
```

### PR DESCRIPTION
**Pull request by spzala**
fixes #10840

Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by jingyih** [comment]
Just for clarification, is it only the `ETCDCTL_API` got unset in lock exec? Or every env starting `ETCDCTL_`?

**Comment by jingyih** [comment]
I just tried on 3.3 release where etcdctl API is defaulted to v2. The following command will not work because `ETCDCTL_API` is unset:

```
$ ETCDCTL_API=3 ./bin/etcdctl lock mylock ./bin/etcdctl put foo bar
No help topic for 'put'
Error:  exit status 3
```

Other `ETCDCTL_` env variables seem to work.

```
$ ETCDCTL_ENDPOINTS=http://127.0.0.1:2379 ETCDCTL_API=3 etcdctl lock mylock env | grep ETCDCTL
ETCDCTL_ENDPOINTS=http://127.0.0.1:2379
```

**Comment by jingyih** [comment]
I guess it is fine to just document the behavior clearly. But it is definitely a little wired if user wants to execute a v3 command upon lock acquisition.

**Comment by spzala** [comment]
@jingyih thanks and yes it's only `ETCDCTL_API` that etcdctl will unset [1]. Besides that, ETCTCTL_ are only allowed to use with etcdctl flags. So for example, ETCDCTL_X gives this error:
`2019-08-26 22:03:41.908806 W | pkg/flags: unrecognized environment variable ETCDCTL_X=3` 
[1] https://github.com/etcd-io/etcd/blob/master/etcdctl/main.go#L33

**Comment by spzala** [comment]
Safe merge so going for it :)

**Pull request merged**
