### PR TITLE
[3.5] fix(defrag): close temp file in case of error

### PR DESCRIPTION
**Pull request by ghouscht**
See https://github.com/etcd-io/etcd/issues/18841 for details. Backport of https://github.com/etcd-io/etcd/pull/18851 to 3.5

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ghouscht** [comment]
/assgin @ahrtr 

Should I prepare a changelog entry as well?

**Comment by ghouscht** [comment]
/assign @ahrtr

Should I prepare a changelog entry as well?

**Review by ahrtr — APPROVED** [review]

**Comment by ahrtr** [comment]
PLease also update the changelog for both. 3.5 and 3.4, thx

**Comment by ghouscht** [comment]
> This will make go vet fail and is already causing trouble on main https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/etcd-io_etcd/18821/pull-etcd-verify/1854634839446130688#1:build-log.txt%3A838

Thank you for raising this. Strange that it wasn't noticed by the checks that were run against the PR where this was added to main. I submitted https://github.com/etcd-io/etcd/pull/18857 to fix this in main and adapted this and the 3.4 backport PRs.

**Comment by ahrtr** [comment]
> Strange that it wasn't noticed by the checks that were run against the PR where this was added to main.

Right. It's the problem. Any idea why it wasn't detected on the PR? One possible reason was that you did not rebase your PR; in other words, your PR was based on the commit before the lint was enabled.

**Comment by ghouscht** [comment]
> > Strange that it wasn't noticed by the checks that were run against the PR where this was added to main.
> 
> Right. It's the problem. Any idea why it wasn't detected on the PR? One possible reason was that you did not rebase your PR; in other words, your PR was based on the commit before the lint was enabled.

Hmm I try to keep my for up-to-date so I don't think this was the issue. However the PR (https://github.com/etcd-io/etcd/pull/18851) had no `ok-to-test` label so that most likely explains this.

**Comment by ahrtr** [comment]
> the PR (#18851) had no `ok-to-test` label so that most likely explains this.

Right.

**Comment by ivanvc** [comment]
> Right. It's the problem. Any idea why it wasn't detected on the PR? One possible reason was that you did not rebase your PR; in other words, your PR was based on the commit before the lint was enabled.

This is also a reminder that we need to enable prow postsubmit jobs. I'll speak with James next week to plan this.

**Review by ivanvc — APPROVED** [review]
This backport LGTM. Thanks, Thomas.

**Pull request merged**
