### PR TITLE
Migrate documentation: Remove docs from etcd-io/etcd

### PR DESCRIPTION
**Pull request by nate-double-u**
Removing Documentation from etcd-io/etcd as a part of migrating it to the website.
- Leaving docs, files, etc that are required for generated documentation

fixes https://github.com/etcd-io/website/issues/97

Do not merge before related PR: https://github.com/etcd-io/website/pull/99

Affected PRs (these may have to be redirected towards [etcd-io/website](https://github.com/etcd-io/website/)):
- https://github.com/etcd-io/etcd/pull/12635
- https://github.com/etcd-io/etcd/pull/12343
- https://github.com/etcd-io/etcd/pull/12178
- https://github.com/etcd-io/etcd/pull/10913
- https://github.com/etcd-io/etcd/pull/12668

### CODE REVIEW

**Comment by nate-double-u** [comment]
/cc @spzala @ptabor

I've tried a first pass at removing the documentation as per issue https://github.com/etcd-io/website/issues/97. Could you look at this PR to ensure that I've not broken any of the documentation generation tools, and that the release scripts still work as intended?

**Comment by ptabor** [comment]
I think that you can move. If we discover broken scripts, we will fix them when we will attempt the release.

**Comment by nate-double-u** [comment]
Thanks @ptabor, in that case, I'll mark this PR "ready for review"

**Review by spzala — COMMENTED** [review]
lgtm
Let's keep it up for review for couple of more days before we merge. Thanks!

**Comment by spzala** [comment]
@ptabor @jingyih @gyuho I think we should merge this so that we don't have more updates and conflicts. I will merge it tomorrow, if you have any comments please add. Thanks!

**Comment by ptabor** [comment]
I'm for merging.

**Comment by spzala** [comment]
@nate-double-u please resolve conflicts when you get a chance :)

**Comment by spzala** [comment]
@nate-double-u the commit 2 doesn't sound right that I think you have created to fix the merge conflict. You just need to rebase not overwrite. Thanks!

**Comment by nate-double-u** [comment]
@spzala it's rebased now, thx :)

**Comment by spzala** [comment]
@nate-double-u cool,thanks :)

**Comment by nate-double-u** [comment]
Thanks everyone!

**Pull request merged**
