### PR TITLE
*: enable lease checkpoint via experimental flag

### PR DESCRIPTION
**Pull request by jingyih**
Discussed with @jpbetz. In etcd 3.4, let's put lease checkpoint feature #9924 behind an experimental flag. The primary concern is that the feature introduced a new raft entry type `LeaseCheckpointRequest`. This will make the design of HA cluster downgrade difficult, as servers of old version panics on unknown raft type (during apply).

With this PR, lease checkpoint feature is enabled only if "--experimental-enable-lease-checkpoint" is set.

cc @jpbetz @xiang90 @gyuho

### CODE REVIEW

**Comment by jpbetz** [comment]
+1 to making the etcd 3.4 safer from a RAFT compatibility perspective.

LGTM

**Comment by jingyih** [comment]
> lgtm, let's highlight this change in CHANGELOG as well. Thanks.

Thanks. Added https://github.com/etcd-io/etcd/pull/10797/commits/5af3723e287f73615362052148a25511f0a6208f.

**Comment by xiang90** [comment]
lgtm

**Comment by keeplowkey** [comment]
> lease checkpoint feature is enabled only if "--experimental-enable-lease-checkpoint" is set

@jingyih My etcd server is running with env flags, so flag "--experimental-enable-lease-checkpoint" is equal to env flag "ETCD_EXPERIMENTAL_ENABLE_LEASE_CHECKPOINT=true"? Looking forward to your reply.

**Pull request merged**
