### PR TITLE
README: explain "MAINTAINERS"

### PR DESCRIPTION
**Pull request by gyuho**
@ptabor @spzala @hexfusion

### CODE REVIEW

**Review by hexfusion — APPROVED** [review]

**Review by spzala — COMMENTED** [review]
LGTM Thanks @gyuho

**Comment by serathius** [comment]
Hmm, isn't the information about adding a new maintainer at odds with https://github.com/etcd-io/etcd/blob/main/GOVERNANCE.md#packagefeature-maintainer
```
New maintainers must be nominated by an existing maintainer and must be elected by a supermajority of maintainers.
```

**Comment by spzala** [comment]
> Hmm, isn't the information about adding a new maintainer at odds with https://github.com/etcd-io/etcd/blob/main/GOVERNANCE.md#packagefeature-maintainer
> 
> ```
> New maintainers must be nominated by an existing maintainer and must be elected by a supermajority of maintainers.
> ```
> 
> Just making sure we have one place that defines the role and nomination method.

@serathius ah, that was missed, thanks! While review, I thought the Maintainers link is pointing to the Governance file, sorry didn't check it @gyuho . We should keep the details in the Governance file and from ReadMe just point to that file for more visibility on finding details on maintainer role.

**Comment by spzala** [comment]
Updating here https://github.com/etcd-io/etcd/pull/13171 @gyuho @serathius Thanks!

**Pull request merged**
