### PR TITLE
Rename modules_exp to modules_for_bom to improve code and clarity

### LINKED ISSUE #18602: Rename scripts' `modules_exp` to `modules_for_bom`
### What would you like to be added?

This is a follow-up on https://github.com/etcd-io/etcd/pull/18590#issuecomment-2359057943. Currently, the function `modules_exp` defined in `scripts/test_lib.sh` is serving the only purpose of providing a list of modules for verifying and fixing the bill of materials (BOM).

https://github.com/etcd-io/etcd/blob/e094139b05244c5eab0e62172f92ac5e90feb73b/scripts/test_lib.sh#L199-L203

We should rename it from `modules_exp` to `modules_for_bom` for clarity and update the two instances where it is referenced:

1. `scripts/test.sh`: https://github.com/etcd-io/etcd/blob/4f9cd336a64e0b709b2f2ef37cf3fff21a86ba39/scripts/test.sh#L508-L512
2. `scripts/updatebom.sh`: https://github.com/etcd-io/etcd/blob/4f9cd336a64e0b709b2f2ef37cf3fff21a86ba39/scripts/updatebom.sh#L15

### Why is this needed?

To improve the code and clarity of the helper functions from the build and test scripts.

### PR DESCRIPTION
**Pull request by lekaf974**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

Fix #18602

### CODE REVIEW

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks for your first contribution, Matthieu!
/cc @ahrtr

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks for improving this @lekaf974

**Review by henrybear327 — APPROVED** [review]

**Review by serathius — APPROVED** [review]
Very nice improvement for clarity.

**Comment by ahrtr** [comment]
Thanks @lekaf974 for the quick fix!

**Pull request merged**
