### PR TITLE
fix: enable gofumpt instead of gofmt linter in client

### PR DESCRIPTION
**Pull request by mmorel-35**
enables and fixes [gofumpt](https://golangci-lint.run/usage/linters/#gofumpt) linter issues in client directory

### CODE REVIEW

**Comment by ivanvc** [comment]
@ahrtr, @serathius, thoughts on replacing `gofmt` with [`gofumpt`](https://github.com/mvdan/gofumpt)?

**Comment by ahrtr** [comment]
A quick question, are all the changes in this PR detected/suggested by `gofumpt`? 

It seems a little better to apply `gofumpt` based on the changes in this PR.

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Review by ivanvc — APPROVED** [review]
LGTM. Should we add a note in the contributor guide about using `gofumpt` instead of `gofmt`? I believe the latter is more widely used by editors, IDEs, etc. (To be done with the pull request when you enable this linter).

**Comment by ahrtr** [comment]
To be clearer, we enable both `gofmt` via [verify-gofmt](https://github.com/etcd-io/etcd/blob/a594a62eab8846294e0bd8a5b26ec40c1e0de9fc/Makefile#L77-L78) and [gofumpt](https://github.com/mvdan/gofumpt) via the [verify-lint](https://github.com/etcd-io/etcd/blob/a594a62eab8846294e0bd8a5b26ec40c1e0de9fc/Makefile#L93-L94). 

> Enforce a stricter format than gofmt, while being backwards compatible. That is, gofumpt is happy with a subset of the formats that gofmt is happy with.

**Pull request merged**
