### PR TITLE
Fix the race condition between goroutine and channel on the same leases to be revoked

### PR DESCRIPTION
**Pull request by ahrtr**
It's a classic mistake in using the Golang channel + goroutine.  When a goroutine accesses data in the closure environment, we should make a copy of the data for the goroutine. 

See the example in [effective_go#channels](https://go.dev/doc/effective_go#channels)

### CODE REVIEW

**Review by serathius — APPROVED** [review]
Great find! Did you find it yourself or used static analysis. Would be great if we could scan the codebase for more cases like this.

Still I would prefer if we just stop using anonymous functions. Could you maybe refactor this to call a function?

**Comment by ahrtr** [comment]
I just found it during code review on the lease related code. I am investigate how can we refactor lease. I have a bias for action, so submit a PR to fix it immediately when I see the issue. 

Probably some linter tools can discover such issue, and it's in my to do list. 

Just moved the code into a separate method, and it looks much better now.

**Comment by ahrtr** [comment]
cc @spzala as well. This is a minor change, and it should be safe.

**Review by ptabor — APPROVED** [review]

**Comment by ptabor** [comment]
Nice finding. Benefits of final variables in Java,

**Comment by ptabor** [comment]
Neither `intelij` nor `staticcheck` is reporting this as problem:
```(cd server && .../go/bin/staticcheck ./...)  | grep server.go```

**Pull request merged**
