### PR TITLE
Use http constant instead of a number

### PR DESCRIPTION
**Pull request by agargi**
embed: Replaced a number with Go http constant

To realize typical advantage of using a constant

### CODE REVIEW

**Comment by hexfusion** [comment]
per  https://golang.org/pkg/net/http/#pkg-constants
```
 StatusMisdirectedRequest           = 421 // RFC 7540, 9.1.2
```

**Comment by hexfusion** [comment]
@agargi can you please fix failing test[1]

[1]https://travis-ci.com/github/etcd-io/etcd/jobs/343906205#L418

**Comment by agargi** [comment]
// Request for review @gyuho @xiang90 @jpbetz @jingyih @spzala @cfc4n

**Comment by agargi** [comment]
@spzala Please review

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
