### PR TITLE
Automated cherry pick of #12264

### PR DESCRIPTION
**Pull request by cfc4n**
Cherry pick of #12264 on release-3.3.

#12264: clientv3: get AuthToken automatically when clientConn is

### CODE REVIEW

**Comment by cfc4n** [comment]
@jingyih Can you reivew this pr and merge it ?
/cc @gyuho

**Review by jingyih — APPROVED** [review]
LGTM

**Comment by jingyih** [comment]
Could you also help update the changelog for 3.3 and 3.4?

**Comment by cfc4n** [comment]
> Could you also help update the changelog for 3.3 and 3.4?

OK,No Problem.

**Pull request merged**
