### PR TITLE
Add integration test for Arm64

### PR DESCRIPTION
**Pull request by kevinzs2048**
Signed-off-by: Kevin Zhao <kevin.zhao@linaro.org>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by kevinzs2048** [comment]
Add the integration test, again will change to periodical job after the test on Arm64 is green

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @kevinzs2048

**Review by serathius — APPROVED** [review]

**Comment by serathius** [comment]
Thanks for PR, please change to periodic so we can merge.

**Comment by kevinzs2048** [comment]
@serathius thanks, done

**Comment by kevinzs2048** [comment]
Related with https://github.com/etcd-io/etcd/issues/14748

**Comment by ahrtr** [comment]
FYI. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-self-hosted-runners

Although the self-hosted label is not required, we strongly recommend specifying it when using self-hosted runners to ensure that your job does not unintentionally specify any current or future GitHub-hosted runners.

Example:
```
runs-on: [self-hosted, Linux, ARM64]
```

cc @dims

**Comment by dims** [comment]
@ahrtr sounds like a good thing to do! ( cc @geetasg )

**Pull request merged**
