### PR TITLE
[3.4] dependency: update go to 1.20.13

### PR DESCRIPTION
**Pull request by ivanvc**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.
Upgrades go version to 1.20.13.

Part of #17269.

### CODE REVIEW

**Review by jmhbnz — CHANGES_REQUESTED** [review]
Unfortunately our `release-3.4` branch still has multiple places where go version is referenced:

```bash
 ~  Documents  etcd  ?1  3.4-update-golang-t..  grep -Ri '1\.20\.12'
Makefile:GO_VERSION ?= 1.20.12
functional/scripts/docker-local-tester.sh:  GO_VERSION=1.20.12
functional/scripts/docker-local-agent.sh:  GO_VERSION=1.20.12
```

Suggest we update those as well, or add a second commit to this pr which makes those three all refer to the single file to fix it for good.

**Comment by ivanvc** [comment]
> Unfortunately our `release-3.4` branch still has multiple places where go version is referenced:
> 
> ```shell
>  ~  Documents  etcd  ?1  3.4-update-golang-t..  grep -Ri '1\.20\.12'
> Makefile:GO_VERSION ?= 1.20.12
> functional/scripts/docker-local-tester.sh:  GO_VERSION=1.20.12
> functional/scripts/docker-local-agent.sh:  GO_VERSION=1.20.12
> ```
> 
> Suggest we update those as well, or add a second commit to this pr which makes those three all refer to the single file to fix it for good.

Oops, I missed those ones. I'll update them and will amend my commit.

**Review by jmhbnz — APPROVED** [review]
LGTM on workflow green - thanks @ivanvc

**Review by ahrtr — APPROVED** [review]
lgtm

Thank you!

**Comment by ahrtr** [comment]
The linux-amd64-e2e has timed out for 5 times. 

Could you take https://github.com/etcd-io/etcd/issues/17241 as a high priority task? @fuweid thx

**Comment by fuweid** [comment]
Found the root cause and will file pr later.

**Comment by fuweid** [comment]
FYI, CI is happy right now https://github.com/etcd-io/etcd/actions/runs/7627029235

**Pull request merged**
