### PR TITLE
README: Fixed the link to `functional` test dir

### PR DESCRIPTION
**Pull request by 2hamed**
Fixed the link to `functional` test dir in the README.md file.

### CODE REVIEW

**Review by ptabor — APPROVED** [review]
Thank you for fixing that.

**Comment by ptabor** [comment]
Please change the title to: 
```
README: Fixed the link to `functional` test dir
```
to fix the presubmit test.

**Comment by 2hamed** [comment]
@ptabor, Done.

**Comment by ptabor** [comment]
> @ptabor, Done.

The commit name is important (not PR name) for the validation, so 
`git commit --amend`

**Comment by 2hamed** [comment]
Sorry, my bad. 😅
Thought you meant the PR title.
It should be ok now.

**Review by ptabor — APPROVED** [review]

**Review by spzala — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
