### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by ahrtr**
Please see commit messages, each of them bumps one dependency.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
@wenjiaswe FYI. 
- https://github.com/etcd-io/etcd/pull/15744
- https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md
- https://docs.google.com/spreadsheets/d/1DDWzbcOx1p32MhyelaPZ_SfYtAD6xRsrtGRZ9QXPOyQ/edit#gid=0

**Comment by chaochn47** [comment]
As part of the net stdlib update, from what I read from https://github.com/golang/go/issues/58804#issuecomment-1571909056, we should switch back http server to use default scheduler, is that understanding correct? 

https://github.com/etcd-io/etcd/blob/1f07d8f159e9071f9e7cf4e71e3cbcf76d83a7e6/server/embed/serve.go#L269-L276

**Comment by ahrtr** [comment]
@chaochn47 It's an unrelated comment, please raise the comment in https://github.com/etcd-io/etcd/issues/15402. 

Per my understanding, with the merge of [120fc90](https://github.com/golang/net/commit/120fc906b30bade8c220769da77801566d7f4ec8#diff-f930c2ef3e066fdc1a1fdd23284f6d7093374d662fcd5a29a23d5db515ef5191), the production code change in https://github.com/etcd-io/etcd/pull/15431 isn't necessary, but it will do any harm and the test case still makes sense.

BTW, the golang std lid commit [260a9b0a0](https://github.com/golang/go/commit/260a9b0a079935744df6a17d0e1d185a9d50631d) will only be included in golang 1.21+.

**Comment by chaochn47** [comment]
> It's an unrelated comment, please raise the comment in https://github.com/etcd-io/etcd/issues/15402.

Thanks @ahrtr! I will move the discussion to the right place. 

This PR looks good to me.

**Review by chaochn47 — APPROVED** [review]

**Review by jmhbnz — APPROVED** [review]
LGTM

**Comment by ahrtr** [comment]
thx @chaochn47 and @jmhbnz for the quick review.

**Pull request merged**
