### PR TITLE
Revert "etcd server shouldn't wait for the ready notification infinitely on startup"

### PR DESCRIPTION
**Pull request by serathius**
As proposed in https://github.com/etcd-io/etcd/issues/16666

This reverts commit 1713dc67b5149e74cd28bad7c080c646315d0b06.

cc @ahrtr @spzala @jmhbnz @wenjiaswe

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]

**Comment by serathius** [comment]
Reverting to draft due to TestInPlaceRecovery failing. Potentially will need to redesign the test.

**Comment by serathius** [comment]
PTAL @ahrtr 
I disabled the cluster_proxy testing for corrupt tests as I don't have energy to fight with the proxy.

**Review by jmhbnz — APPROVED** [review]
Based on discussion in https://github.com/etcd-io/etcd/issues/16666 I agree with decision to revert to prioritise consistency.

Defer decision on `tests/e2e/corrupt_test.go` `//go:build !cluster_proxy` to @ahrtr as I am not very familiar with this yet.

**Comment by ahrtr** [comment]
> I disabled the cluster_proxy testing for corrupt tests as I don't have energy to fight with the proxy.

Part of the test cases in cluster_proxy.go were added before the https://github.com/etcd-io/etcd/commit/1713dc67b5149e74cd28bad7c080c646315d0b06, pls at least raise a followup.

**Comment by serathius** [comment]
Done, https://github.com/etcd-io/etcd/issues/16690

**Review by ahrtr — APPROVED** [review]
LGTM

thx

**Comment by ahrtr** [comment]
Link to https://github.com/etcd-io/etcd/pull/13525

**Pull request merged**
