### PR TITLE
watch: remove cancelled watchers from resuming

### PR DESCRIPTION
**Pull request by fanminshi**
supposed that a watcher is cancelled at the moment that there is a client error.

watchGrpcStream can proceed to handle client error before removing watcher from
its watchGrpcStream. When this case happens, watchGrpcStream resends
 watch create request for a cancelled watcher when establishing a new connection.

this pr fixes the issue by removing cancelled watchers from the resuming array where
watchGrpcStream uses it to resume watchers.

### CODE REVIEW

**Comment by xiang90** [comment]
can we add a test for this case?

**Comment by heyitsanthony** [comment]
was anything breaking because of this?

**Comment by fanminshi** [comment]
@xiang90 I was able to reproduce this issue easily by comment out those lines 
```go
case ws := <-w.closingc:
			w.closeSubstream(ws)
			delete(closing, ws)
			if len(w.substreams)+len(w.resuming) == 0 {
				// no more watchers on this stream, shutdown
				return
			}
```
https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L498-L504.

add a debug statement at 
```go
case pbresp := <-w.respc:
			switch {
			case pbresp.Created:
				// response to head of queue creation
				if ws := w.resuming[0]; ws != nil {
					w.addSubstream(pbresp, ws)
					w.dispatchEvent(pbresp)
					w.resuming[0] = nil
				}
				if ws := w.nextResume(); ws != nil {
					wc.Send(ws.initReq.toPB())
				}
                               log.Printf("substreams %+v \n", w.substreams)
```
https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L448

and at
```go
	case <-ws.initReq.ctx.Done():
           log.Printf("DEBUG: %v cancelled", ws)
	   return
```
https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L652

and run following
```go
func TestWatchCancelledWatcher(t *testing.T) {
	defer testutil.AfterTest(t)
	clus := integration.NewClusterV3(t, &integration.ClusterConfig{Size: 1})
	defer clus.Terminate(t)
	cli := clus.Client(0)
	watchCli := clientv3.NewWatcher(cli)

	ctx1, cancel1 := context.WithCancel(context.Background())
	watchCli.Watch(ctx1, "foo")
	cancel1()
	for {
		clus.Members[0].Stop(t)
		clus.Members[0].Restart(t)
		time.Sleep(5 * time.Second)
	}
}
```

I see cancelled watcher is still in the `substreams` but it shouldn't.

**Comment by fanminshi** [comment]
@heyitsanthony nothing is broken from this. I was going over the watch code to understand how it handle reconnect and saw this issue. 

Also there is a comment about the exact same issue.
 `// closed ws will be removed from resuming`
https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L724

**Comment by fanminshi** [comment]
@xiang90 the issue lies below the api lvl. User won't see anything since cancelled watcher is still cancelled from user's perspective but not a etcd server's perspective.

**Comment by xiang90** [comment]
@fanminshi we can inspect the watcher internal state if we write a in pkg test.

**Comment by heyitsanthony** [comment]
just get `etcd_debugging_mvcc_watcher_total` and confirm it doesn't spike up on reconnect

**Comment by heyitsanthony** [comment]
another way to test it: pass a custom pb.WatchClient that wraps an ordinary pb.WatchClient into `NewWatchFromWatchClient` and monitor for Watch calls after the watches are canceled

**Comment by fanminshi** [comment]
@heyitsanthony this leaky watcher case happens if [`case err := <-w.errc:`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L484) happens before [`case ws := <-w.closingc:`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L498). To trigger the above is tricky. I wasn't able to trigger the case at all unless I comment out [`case ws := <-w.closingc:`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L498). 

@heyitsanthony @xiang90 any idea on how to trigger the case without comment out some code?

**Comment by xiang90** [comment]
> @heyitsanthony this leaky watcher case happens if case err := <-w.errc: happens before case ws := <-w.closingc:. To trigger the above is tricky. I wasn't able to trigger the case at all unless I comment out case ws := <-w.closingc:.

write a test. try to spin up N routines. racy might just happen. if the racy rate is very low, then we can put more effort to trigger it.

**Comment by fanminshi** [comment]
I took a look of the code again. The current watch code handles resending cancelled watcher create request with following logic. It appears to be correct to me.

1. suppose watcher A is cancelled and notified `watchGrpcStream` through [`w.closingc <- ws`]( https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L580)

2. `watchGrpcStream` processes client error  [`case err := <-w.errc:`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L484) before [`w.closingc <- ws`]( https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L580)

3. watcher A is appended to [`w.resuming = append(w.resuming, ws)`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L669) since it was not removed from `w.substreams` yet.

4. watcher A created request is sent [`wc.Send(ws.initReq.toPB())`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L493)

5. [`case err := <-w.errc:`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L484) finished.

At here two likely cases can happen.

case: `watchGrpcStream` removes watcher A [`w.closingc <- ws`]( https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L580) before `watchGrpcStream` 
 hears watcher A created resp [`case pbresp := <-w.respc:`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L446)

7. `watchGrpcStream` removes watcher A from `w.resuming ` and `w.substreams` in [`w.closeSubstream(ws)`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L499).

8. `watchGrpcStream` hears watcher A created resp [`case pbresp := <-w.respc:`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L446) and found watcher A is not in [`w.resuming[0]`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L480). Then it ignores this created req.

9. If etcd server sends a another watch event back for watcher A, then `watchGrpcStream` sends a cancel request [`cr := &pb.WatchRequest_CancelRequest{`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L475) since watcher A is not in `w.substreams`.

 If step 9 doesn't happen where etcd server never sends another watch event back, then watcher A will never be cancelled. Is that an expected behavior?


case: `watchGrpcStream` hears watcher A created resp [`case pbresp := <-w.respc:`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L446) before `watchGrpcStream` removes watcher A [`w.closingc <- ws`]( https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L580) 

7. `watchGrpcStream` adds watcher A to [`substream`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L451).

8. [`w.closingc <- ws`]( https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L580) triggers. `watchGrpcStream` removes watcher A from `w.resuming ` and `w.substreams` in [`w.closeSubstream(ws)`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L499).

9.  If etcd server sends a another watch event back for watcher A, then `watchGrpcStream` sends a cancel request [`cr := &pb.WatchRequest_CancelRequest{`](https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L475) since watcher A is not in `w.substreams`.

**Comment by fanminshi** [comment]
If I create 11 watchers and cancell 10, should etcd server also remove 10 watchers internally?

The following test shows that even I cancell 10 watchers from client, the etcd server still shows that 11 watchers are available. Is this expected?

```go
func TestWatchCancelledWatcherPropergateToServer(t *testing.T) {
	defer testutil.AfterTest(t)
	clus := integration.NewClusterV3(t, &integration.ClusterConfig{Size: 1})
	defer clus.Terminate(t)
	cli := clus.Client(0)

	cancelledWatchers := 10

	ctx1, cancel1 := context.WithCancel(context.Background())
	defer cancel1()
	cli.Watch(ctx1, "foo")

	for i := 0; i < cancelledWatchers; i++ {
		ctx, cancel := context.WithCancel(context.Background())
		cli.Watch(ctx, "foo")
		cancel()
	}
	time.Sleep(time.Second)
	totalWatches, err := clus.Members[0].Metric("etcd_debugging_mvcc_watcher_total")
	if err != nil {
		t.Fatal(err)
	}
	var totalWatchesInt int
	_, serr := fmt.Sscanf(totalWatches, "%d", &totalWatchesInt)
	if serr != nil {
		t.Fatal(serr)
	}
	log.Printf("total watchers %v ", totalWatchesInt)
	if totalWatchesInt > cancelledWatchers {
		t.Fatalf("too many watchers")
	}
}
```

output:
```sh
...
2017-05-17 11:10:56.825876 I | total watchers 11
--- FAIL: TestWatchCancelledWatcherPropergateToServerSide (1.14s)
	watch_test.go:1085: too many watchers
```

**Comment by heyitsanthony** [comment]
@fanminshi yes, the cancel is lazy https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L659

**Comment by fanminshi** [comment]
@heyitsanthony I wonder what's advantage of a lazy cancel over a direct cancel?

**Comment by heyitsanthony** [comment]
@fanminshi saves network traffic, simplifies the teardown path

**Pull request closed without merging**
