### PR TITLE
refactor IsValidVersionChange.

### PR DESCRIPTION
**Pull request by siyuanfoundation**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

refactor the function based on the feedbacks of https://github.com/etcd-io/etcd/pull/17821

### CODE REVIEW

**Comment by siyuanfoundation** [comment]
From this refactor, it seems obvious the version order of `IsValidClusterVersionChange` in `UpdateCapability` is reversed. 
Should I fix it? @ahrtr @serathius

**Comment by ahrtr** [comment]
> From this refactor, it seems obvious the version order of `IsValidClusterVersionChange` in `UpdateCapability` is reversed.
> Should I fix it?

Do you mean the change like below? Strange we did not see any issue in the test so far. It seems that we need to evaluate the downgrade's code. Please raise a separate issue to discuss this so as not to block your current PR.

```
$ git diff
diff --git a/server/etcdserver/api/capability.go b/server/etcdserver/api/capability.go
index 4cd9aca84..12dead393 100644
--- a/server/etcdserver/api/capability.go
+++ b/server/etcdserver/api/capability.go
@@ -64,7 +64,7 @@ func UpdateCapability(lg *zap.Logger, v *semver.Version) {
                return
        }
        enableMapMu.Lock()
-       if curVersion != nil && !serverversion.IsValidVersionChange(v, curVersion) {
+       if curVersion != nil && !serverversion.IsValidVersionChange(curVersion, v) {
                enableMapMu.Unlock()
                return
        }
```

**Comment by siyuanfoundation** [comment]
> > From this refactor, it seems obvious the version order of `IsValidClusterVersionChange` in `UpdateCapability` is reversed.
> > Should I fix it?
> 
> Do you mean the change like below? Strange we did not see any issue in the test so far. It seems that we need to evaluate the downgrade's code. Please raise a separate issue to discuss this so as not to block your current PR.
> 
> ```
> $ git diff
> diff --git a/server/etcdserver/api/capability.go b/server/etcdserver/api/capability.go
> index 4cd9aca84..12dead393 100644
> --- a/server/etcdserver/api/capability.go
> +++ b/server/etcdserver/api/capability.go
> @@ -64,7 +64,7 @@ func UpdateCapability(lg *zap.Logger, v *semver.Version) {
>                 return
>         }
>         enableMapMu.Lock()
> -       if curVersion != nil && !serverversion.IsValidVersionChange(v, curVersion) {
> +       if curVersion != nil && !serverversion.IsValidVersionChange(curVersion, v) {
>                 enableMapMu.Unlock()
>                 return
>         }
> ```

Yes, that's the change I meant. 
The reason we did not see any issue is that the capability does not change over the 3.x versions https://github.com/etcd-io/etcd/blob/dd4e35a58597e66b74a84a5a99ad42a7b7723415/server/etcdserver/api/capability.go#L36-L43. 
It would be a no-op change. But I will raise a separate PR for it.

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Review by serathius — APPROVED** [review]

**Pull request merged**
