### PR TITLE
Automated cherry pick of #11194 on release-3.4

### PR DESCRIPTION
**Pull request by jingyih**
Cherry pick of #11194 on release-3.4.

#11194: etcdctl: fix member add command

### CODE REVIEW

**Comment by gyuho** [comment]
Hmm, are test failures related? Is your 3.4 branch latest?

**Comment by jingyih** [comment]
Integration test failure is not related:
```
--- FAIL: TestBalancerUnderNetworkPartitionWatchFollower (3.27s)
    network_partition_test.go:266: took too long to detect leader lost
```
Haven't seen this e2e test failure before:
```
=== RUN   TestV3MetricsInsecure
--- FAIL: TestV3MetricsInsecure (0.94s)

=== RUN   TestV3MetricsSecure
--- FAIL: TestV3MetricsSecure (1.62s)
```

**Comment by jingyih** [comment]
e2e tests also failed for recent commits on release-3.4. Let me take a look.

**Comment by gyuho** [comment]
Ah, my commit should have broke it. Can we update this in 3.4 branch? https://github.com/etcd-io/etcd/blob/master/tests/semaphore.test.bash#L17

**Comment by jingyih** [comment]
> Ah, my commit should have broke it. Can we update this in 3.4 branch? https://github.com/etcd-io/etcd/blob/master/tests/semaphore.test.bash#L17

With this version override, cluster version test fails because in the test we do not trim `ver`
https://github.com/etcd-io/etcd/blob/d08bb07d6d9dbce33be7919a2036eec7ab138280/tests/e2e/metrics_test.go#L52

**Comment by gyuho** [comment]
right, let me quick-fix

**Comment by gyuho** [comment]
Should be fixed via https://github.com/etcd-io/etcd/commit/c91a6bf14f039b2b8cf384f96ea9a4cc42c48ac8.

**Comment by jingyih** [comment]
> Should be fixed via [c91a6bf](https://github.com/etcd-io/etcd/commit/c91a6bf14f039b2b8cf384f96ea9a4cc42c48ac8).

I actually found some inconsistency in our code base. Should the cluster version be "3.4" or 3.4.0"? 

In some places cluster version is trimmed via:
https://github.com/etcd-io/etcd/blob/a0d24279ee441a510ad7543ade71885ae64734b4/version/version.go#L50

Sometimes (for example in metrics endpoint) we keep the patch version:
https://github.com/etcd-io/etcd/blob/c2f23094c875ba1a668192b8324cbc599207bf00/etcdserver/api/membership/cluster.go#L576

**Comment by gyuho** [comment]
The patch version is truncated because the metrics is "cluster_version". Maybe we can just strip out the patch version for this metrics (e.g. `version.Cluster(ver.String())`)? It's pretty confusing right now :0

**Comment by jingyih** [comment]
Sounds good. Let's use "major.minor" for the "cluster_version" metrics.

**Pull request merged**
