### PR TITLE
scripts/release: shallow clone repository

### PR DESCRIPTION
**Pull request by ivanvc**
Minor improvement that was identified when releasing v3.5.14.

Related to #18013.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @ivanvc

**Comment by ivanvc** [comment]
@jmhbnz, should we backport this into 3.4 too?

**Comment by jmhbnz** [comment]
> @jmhbnz, should we backport this into 3.4 too?

Personally I think yes to try and keep release process consistent and given we believe this to be a low risk improvement. Though this decision would be to @ahrtr as overall release manager for 3.4. Also ref: https://github.com/etcd-io/etcd/pull/17677#discussion_r1545789197

**Comment by ahrtr** [comment]
@ivanvc please feel free to deliver a PR to 3.4. thx

**Pull request merged**
