### PR TITLE
Updated servePeers to remove the grpc server

### PR DESCRIPTION
**Pull request by ahrtr**
Fix [issues/13564](https://github.com/etcd-io/etcd/issues/13564)

@gyuho @serathius @ptabor

### CODE REVIEW

**Comment by ahrtr** [comment]
Just rebased the PR.

**Comment by ptabor** [comment]
That's pretty big change. 
  - I digged some context for this: https://github.com/etcd-io/etcd/pull/8420, seems to be added for hashkv support.

I agree that wide access to this port is misleading and promotes bad usage patterns.
 
If we want to proceed I think we should mention it as an explicit breaking change in the Changelog as  some user's might depend on this behavior.

**Comment by ahrtr** [comment]
Thanks @ptabor for the feedback.  Just added a breaking change item.

**Comment by ahrtr** [comment]
@ptabor  I removed the gRPC server from peer listener in the integration test as well. All tests passed.  Usually users do not know that the 2380 port can also serve client requests because there is no any documentation on this. So I think it might be safe to remove the misleading functionality. 

cc @serathius  @spzala

**Review by serathius — APPROVED** [review]
LGTM

**Comment by ptabor** [comment]
It seems it could break `--experimental-corrupt-check-time`. Maybe this mode is not properly tested.

**Comment by ahrtr** [comment]
> It seems it could break --experimental-corrupt-check-time. Maybe this mode is not properly tested.

@ptabor  I tested manually in my local environment, and confirmed that it doesn't break the [corruption check](https://github.com/etcd-io/etcd/blob/682b8676530cbaad70cb9e555e11d056eceeaf4d/server/etcdserver/corrupt.go#L123) functionality. 

Firstly I build the etcd binary using my branch [ahrtr:remove_peer_serve_client_requests](https://github.com/ahrtr/etcd/tree/remove_peer_serve_client_requests).  

Secondly, start a etcd cluster with only 2 members (note that I already got the etcd/bin directory included in the $PATH),

```
etcd --name infra1 --listen-client-urls http://127.0.0.1:2379 --advertise-client-urls http://127.0.0.1:2379 --listen-peer-urls http://127.0.0.1:12380 --initial-advertise-peer-urls http://127.0.0.1:12380 --initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380' --initial-cluster-state new --enable-pprof --logger=zap --log-outputs=stderr --experimental-corrupt-check-time 5s

etcd --name infra2 --listen-client-urls http://127.0.0.1:22379 --advertise-client-urls http://127.0.0.1:22379 --listen-peer-urls http://127.0.0.1:22380 --initial-advertise-peer-urls http://127.0.0.1:22380 --initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380' --initial-cluster-state new --enable-pprof --logger=zap --log-outputs=stderr --experimental-corrupt-check-time 5s
```

Thirdly, confirmed that infra1 is the leader,
```
$ etcdctl  --endpoints http://127.0.0.1:2379,http://127.0.0.1:22379 endpoint status -w table
+------------------------+------------------+-----------+---------+-----------+------------+-----------+------------+--------------------+--------+
|        ENDPOINT        |        ID        |  VERSION  | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+------------------------+------------------+-----------+---------+-----------+------------+-----------+------------+--------------------+--------+
|  http://127.0.0.1:2379 | 8211f1d0f64f3269 | 3.6.0-pre |   25 kB |      true |      false |         2 |          7 |                  7 |        |
| http://127.0.0.1:22379 | 91bc3c398fb3c146 | 3.6.0-pre |   25 kB |     false |      false |         2 |          7 |                  7 |        |
+------------------------+------------------+-----------+---------+-----------+------------+-----------+------------+--------------------+--------+
```

Lastly, the leader prints the following log entries periodically (every 5 seconds),

```
{"level":"info","ts":"2022-01-26T15:24:11.112+0800","caller":"etcdserver/corrupt.go:244","msg":"finished peer corruption check","number-of-peers-checked":1}
{"level":"info","ts":"2022-01-26T15:24:16.115+0800","caller":"etcdserver/corrupt.go:244","msg":"finished peer corruption check","number-of-peers-checked":1}
{"level":"info","ts":"2022-01-26T15:24:21.119+0800","caller":"etcdserver/corrupt.go:244","msg":"finished peer corruption check","number-of-peers-checked":1}
{"level":"info","ts":"2022-01-26T15:24:26.124+0800","caller":"etcdserver/corrupt.go:244","msg":"finished peer corruption check","number-of-peers-checked":1}
{"level":"info","ts":"2022-01-26T15:24:31.126+0800","caller":"etcdserver/corrupt.go:244","msg":"finished peer corruption check","number-of-peers-checked":1}
......
```

BTW, I rebased the PR.  Please let me know if you have other concerns or comments.

**Comment by ahrtr** [comment]
cc @spzala

**Comment by ahrtr** [comment]
Just rebased this PR.

**Comment by ahrtr** [comment]
FYI, the command `etcdctl endpoint hashkv --cluster ` is also working well on this PR, @ptabor 

```
$ etcdctl endpoint hashkv --cluster -w table
+------------------------+------------+
|        ENDPOINT        |    HASH    |
+------------------------+------------+
|  http://127.0.0.1:2379 | 1084519789 |
| http://127.0.0.1:22379 | 1084519789 |
| http://127.0.0.1:32379 | 1084519789 |
+------------------------+------------+
```

**Comment by ahrtr** [comment]
Hi @ptabor , Do you still have any concern? cc @serathius @spzala

**Comment by serathius** [comment]
@ptabor any other concerns?

**Review by ptabor — APPROVED** [review]
Thank you for checking.

**Pull request merged**
