### PR TITLE
Backport PR 14322 to release-3.5

### PR DESCRIPTION
**Pull request by mitake**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This PR backports https://github.com/etcd-io/etcd/pull/14322 to `release-3.5`. cc @ahrtr @kafuu-chino

### CODE REVIEW

**Review by spzala — APPROVED** [review]
@mitake thank you! lgtm. Rerunning failed test which seems not related to changes. I think this should be backported to 3.4 as well?

**Review by ahrtr — APPROVED** [review]
LGTM

Thank yo @mitake 

Please consider to backport this to 3.4 as well if needed.

**Comment by ahrtr** [comment]
Please update both 3.5 and 3.4 changelog after finishing the 3.4 backport, thx

**Comment by mitake** [comment]
Thanks @spzala @ahrtr ! Yeah I'll open PRs for backporting to 3.4 and updating the changelog.

**Pull request merged**
