### PR TITLE
Documentation: add generated metrics docs

### LINKED ISSUE #12424: metrics documentation not generated
etcd/Documentation/metrics/ is not up to date. Latest documented version is v3.4.3.

### PR DESCRIPTION
**Pull request by jingyih**
Fix #12424

### CODE REVIEW

**Comment by jingyih** [comment]
@ptabor 
Found the following test failure in this PR. I don't remember seen this before. Since you've done a lot of work on improve testing, I want to bring it to your attention. Is this a flake / known failure?

```
--- FAIL: TestIssue6361 (14.64s)
    ctl_v3_snapshot_test.go:261: [../../bin/etcdctl --endpoints http://localhost:20030 --dial-timeout 10s get foo1] read /dev/ptmx: input/output error (expected "val1", got ["{\"level\":\"warn\",\"ts\":\"2020-11-04T14:30:12.769Z\",\"caller\":\"v3/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"endpoint://client-454c2db3-3870-45ea-9fd0-63e3c0dad8c8/localhost:20030\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}\r\n" "Error: context deadline exceeded\r\n"]). Try EXPECT_DEBUG=TRUE
```

**Comment by ptabor** [comment]
I've seen this flake before. Added to the index of known flakes: 
  https://github.com/etcd-io/etcd/issues/12372#issuecomment-722320804

**Comment by ptabor** [comment]
How did you generated the docs ?

**Comment by jingyih** [comment]
> How did you generated the docs ?

I used https://github.com/etcd-io/etcd/tree/master/tools/etcd-dump-metrics

**Pull request merged**
