### PR TITLE
draft: reproduce root cause of flaky ExampleCluster_memberAddAsLearner

### PR DESCRIPTION
**Pull request by lavacat**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by lavacat** [comment]
This PR adds a delay to raft.advance to show that raftLog.applied can be incremented after grpc request returns.

https://github.com/etcd-io/etcd/issues/14040

**Comment by lavacat** [comment]
from the log 
`    logger.go:130: 2022-05-19T12:51:12.712-0700	INFO	m0	applied a configuration change through raft	{"member": "m0", "local-member-id": "5fccebd588516459", "raft-conf-change": "ConfChangeAddLearnerNode", "raft-conf-change-node-id": "fdbbbfa75c90a874"}
    logger.go:130: 2022-05-19T12:51:12.712-0700	INFO	m0.raft	5fccebd588516459 ignoring conf change {ConfChangeRemoveNode 18283417837774088308 [] 7230952367150642694} at config voters=(6903151631199724633) learners=(18283417837774088308): possible unapplied conf change at index 5 (applied to 4)	{"member": "m0"}
Advanced`

**Comment by ahrtr** [comment]
Are you still working on this PR?

**Comment by lavacat** [comment]
@ahrtr I've paused, but would like to submit a fix. Give me till the end of the week.

**Pull request closed without merging**
