### PR TITLE
fix: enable go-require rule from testifylint

### LINKED ISSUE #18719: Enable testifylint linter rules
### What would you like to be added?

This issue formalizes @mmorel-35's work (thanks!) to enable the linter rules from the `testifylint` linter.

The completion track is as follows:
- [x] bool-compare
  - [x] #18686 
  - [x] #18717
- [x] compares - #18715
- [x] empty - #18712
- [x] error-is-as - #18740
- [x] error-nil - #18716
- [x] expected-actual - #18720
- [x] float-compare - #18776
- [x] formatter - #18741
- [ ] go-require - #18827
- [x] len - #18712
- [x] negative-positive - #18715 
- [x] nil-compare
  - [x] #18689 
  - [x] #18717
- [x] require-error
  - [x] #18800
  - [x] #18814

### Why is this needed?

To improve the code quality.

### PR DESCRIPTION
**Pull request by mmorel-35**
This fixes [go-require](https://github.com/Antonboom/testifylint?tab=readme-ov-file#go-require) rule from [testifylint](https://github.com/Antonboom/testifylint)

Closes #18719

### CODE REVIEW

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @mmorel-35.

**Comment by ahrtr** [comment]
Pasted more context for others reference...

> The point of the check is that, according to the [documentation](https://pkg.go.dev/testing#T), functions leading to t.FailNow (essentially to runtime.GoExit) must only be used in the goroutine that runs the test. Otherwise, they will not work as declared, namely, finish the test function.

**Review by ahrtr — APPROVED** [review]
LGTM

**Pull request merged**
