### PR TITLE
Adding test for updateClusterVersionV3

### PR DESCRIPTION
**Pull request by geetasg**
Adding test for updateClusterVersionV3

Related to task - "V2 snapshots are generated from V3 data" - https://github.com/etcd-io/etcd/issues/12913
Eventually TestUpdateVersion which tests updateClusterVersionV2 will be removed.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by geetasg** [comment]
Requesting review. /cc @serathius @ahrtr @chaochn47

**Review by serathius — APPROVED** [review]

**Review by chaochn47 — APPROVED** [review]
LGTM, thanks @geetasg!

**Comment by geetasg** [comment]
cc @ptabor

**Comment by geetasg** [comment]
Can this PR be merged if there is no additional feedback?

**Review by ahrtr — APPROVED** [review]

**Pull request merged**
