### PR TITLE
expose op.isOptsWithFromKey and op.isOptsWithPrefix

### LINKED ISSUE #16217: Op.isOptsWithFromKey & Op.isOptsWithPrefix accessor
### What would you like to be added?

It would be nice if the access function of `Op.isOptsWithPrefix` and `Op.isOptsWithFromKey` were provided. Only the accessor to this field was missing, is there a history related to it?

```go
op := clientv3.OpDelete("mykey", clientv3.WithPrefix())
if op.IsOptsWithPrefix() {
  // ...
}
```

### Why is this needed?

For making detail logs in application.

### PR DESCRIPTION
**Pull request by CaojiamingAlan**
Fix #16217

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
They are already supported in https://github.com/etcd-io/etcd/pull/13334.

**Comment by CaojiamingAlan** [comment]
> They are already supported in #13334.

The exported [methods](https://github.com/etcd-io/etcd/blob/882edb3d63cca13d4b2541e4e39e29c53f3814a6/client/v3/op.go#L572C1-L589) in #13334 takes a list of `OpOption` as parameter, which means the user needs to keep the options of the op if he or she wants to check the fields `isOptsWithFromKey` and `isOptsWithPrefix` later. what I am trying to do here is to expose those fields directly.

**Comment by ahrtr** [comment]
> if he or she wants to check the fields `isOptsWithFromKey` and `isOptsWithPrefix` later

Yes, I understand that, but actually I don't see a real such use case.  After the `WithFromKey` or `WithPrefix` is evaluated, users only care about the field [end](https://github.com/etcd-io/etcd/blob/882edb3d63cca13d4b2541e4e39e29c53f3814a6/client/v3/op.go#L35). 

Of course, adding two methods (what this PR does) is harmless, but also unnecessary. I am neutral to this.

**Review by jmhbnz — APPROVED** [review]
This gets a tentative approval from me.  At the code level I see no issue, and we have had #16217 opened by a user asking for this for the purpose of making detailed logs in an application.

It still seems like a nice to have more than anything so I defer to maintainers to make final decision.   @changhoi please feel free to add any additional context here or in the issue in support of the pr.

**Comment by changhoi** [comment]
As described in [PR](https://github.com/etcd-io/etcd/issues/16217), if the feature is added, our team will add more details to the log depending on whether Operation has a Prefix option.

Also, since there are other flag accessors, it seems natural to add them if there are no problems :)

**Review by ahrtr — APPROVED** [review]

**Pull request merged**
