### PR TITLE
embed, pkg/types: allow metrics listener to bind to unix socket

### PR DESCRIPTION
**Pull request by nimdanitro**
Details:
* pkg/types/url: fixed valdiation in pkg/types to properly validate unix socket urls
* embed: properly create the unix socket listener for metrics sockets

### CODE REVIEW

**Comment by hexfusion** [comment]
ack

**Comment by hexfusion** [comment]
@nimdanitro sorry for delay I will review this tonight.

**Comment by hexfusion** [comment]
@nimdanitro we are working on some related unix socket issues I have not forgotten about you.

**Comment by nimdanitro** [comment]
sorry for my late answer. No particular reason for this unix path in the tests file.. What exactly do you mean with ${name}:${int}, something like etcd-metrics-socket?

**Comment by hexfusion** [comment]
@nimdanitro for example `--listen-client-urls unix://ectd:1` which literately translates to a socket path `./etcd:1` from where etcd is started.

**Pull request closed without merging**
