### PR TITLE
CHANGELOG: update with added audit report

### PR DESCRIPTION
**Pull request by spzala**
Update the changelog for recently added audit report. Also mention the
report in the security readme.

### CODE REVIEW

**Comment by philips** [comment]
Nice!

**Comment by spzala** [comment]
> Nice!

Thanks @philips

**Comment by spzala** [comment]
I noticed CI failure due to (mistakenly) using 'you' in the readme, so just fixed it.

**Comment by spzala** [comment]
Thanks @gyuho and @mitake

**Pull request merged**
