### PR TITLE
etcdserver: move range work out of the apply path

### PR DESCRIPTION
**Pull request by heyitsanthony**
The apply path is heavily contended so move the work for Range
from inside apply processing to after receiving the raft ack.

One caveat: compaction can cause requests that made it through consensus to return ErrCompacted back to the client.

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm. Defer to @xiang90 

Thanks.

**Comment by xiang90** [comment]
@heyitsanthony Sorry for the delay on this one. So we are trying to move the read out of the serialized apply path by always fetching the result with a given revision after applied put/delete ops?  

Did you do any benchmark on this? Any observable improvement?

**Comment by heyitsanthony** [comment]
@xiang90 yeah, that's the idea. The revision is the revision of the txn's view, not the rev after the txn commits. Performance turned out to be slightly (but probably not significantly; need t-testing to know for sure) worse for point ranges. Might be an improvement for large ranges, but haven't tried it.

**Comment by xiang90** [comment]
@heyitsanthony This complicates stuff. Can we wait until we see a real benefits? I can do some benchmark against this patch later.

**Comment by heyitsanthony** [comment]
@xiang90 sure, no rush.

**Comment by xiang90** [comment]
Too old PR.  Closing.

**Pull request closed without merging**
