### PR TITLE
Remaining errors.Is for error equality checks

### PR DESCRIPTION
**Pull request by redwrasse**
This PR follows up on https://github.com/etcd-io/etcd/pull/18510 to replace the rest of error equality/inequality checks with `errors.Is`, which is robust to error wrapping (https://pkg.go.dev/errors#pkg-overview).

Note I believe there are a number of cases of explicit error strings substring matching in tests for that are not covered in this PR. This PR just changes explicit `err ==` and `err != ` to `errors.Is` and `!errors.Is`.

@ivanvc

### CODE REVIEW

**Comment by redwrasse** [comment]
@ivanvc let me know if you see any missing cases. this PR also builds on top of https://github.com/etcd-io/etcd/pull/18510, so we could also close that one and just work on this PR.

**Comment by redwrasse** [comment]
Seeing some package name conflicts, let me fix

**Comment by redwrasse** [comment]
goimports error, i'll fix it

**Comment by ivanvc** [comment]
Hi @redwrasse, thanks for the pull request. Due to its size and ease of review, would you be able to help us break it into multiple smaller PRs? I suggest one per module, i.e., `client`, `contrib`, `etcdctl`, etc...

I also suggest waiting for #18510 to be merged so you can continue working on it after we have the maintainers' approval and get it merged into main.

Thanks again, Samir.

**Comment by ivanvc** [comment]
Link to https://github.com/etcd-io/etcd/issues/18576

**Comment by redwrasse** [comment]
@ivanvc sounds good, I'll hold off for now and if we move forward I can help with a separate PR per-module.

**Comment by ivanvc** [comment]
@redwrasse, is it okay to assign you to our new parent issue for this? (https://github.com/etcd-io/etcd/issues/18576) If that's ok, you can comment `/assign` on that issue, and k8s-bot will assign it to you.

**Comment by redwrasse** [comment]
Closing this PR, since as discussed the remaining errors.Is changes PRs should be submitted per-module.

**Pull request closed without merging**
