### PR TITLE
test: added e2e test case for issue 14571: etcd doesn't load auth info when recovering from a snapshot

### PR DESCRIPTION
**Pull request by ahrtr**
Signed-off-by: Benjamin Wang <wachao@vmware.com>

cc @mitake @biosvs @veshij

### CODE REVIEW

**Comment by ahrtr** [comment]
Added e2e test case for 3.5 for https://github.com/etcd-io/etcd/issues/14571

**Comment by mitake** [comment]
@ahrtr LGTM, thanks a lot for creating the e2e test case! I tested that not refreshing range perm cache can result in failure of the test on my env. I think it's also valuable to add the test case to the main branch?

**Comment by ahrtr** [comment]
> @ahrtr LGTM, thanks a lot for creating the e2e test case! I tested that not refreshing range perm cache can result in failure of the test on my env. I think it's also valuable to add the test case to the main branch?

@veshij already added e2e test on `main` branch in https://github.com/etcd-io/etcd/pull/14574. ` release-3.5` has huge difference from `main` branch, and there is no easy way to backport the e2e test to `release-3.5`. So I have to add a new e2e test for 3.5.

**Comment by mitake** [comment]
Sorry I compared the e2e tests and checked that they are essentially testing the exact same scenario, I misunderstood.

**Pull request merged**
