### PR TITLE
Increased timeout for scheduled compaction to finish

### PR DESCRIPTION
**Pull request by srivastav-abhishek**
Fixes : [TestHashKVWhenCompacting](https://github.com/etcd-io/etcd/issues/16963)

### CODE REVIEW

**Comment by ahrtr** [comment]
close/reopen to re-trigger all arm64 workflows

**Review by jmhbnz — COMMENTED** [review]
Hey @srivastav-abhishek - Thanks for raising this suggestion. I'm not sure I recall this flaking in github actions.  Are you able to please provide a link to the flaky actions run or some detail on how to reproduce the flake?

**Comment by zaitcev** [comment]
This is a problem for me too. I have a PR in Fedora Linux to package v3.5.10, and Fedora's CI fails with the mvcc thing. Symptoms is exactly the same

Here's a link, which has log (build.log), although the build is going to be purged in a few days:
https://koji.fedoraproject.org/koji/taskinfo?taskID=109382260

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x125cfee2c]
goroutine 566 [running]:
go.etcd.io/bbolt.(*Tx).Bucket(...)
	/usr/share/gocode/src/go.etcd.io/bbolt/tx.go:102
go.etcd.io/etcd/server/v3/mvcc/backend.unsafeForEach(0x0, {0x12636bc50?, 0x1267d6a00?}, 0x3?)
	/builddir/build/BUILD/etcd-3.5.10/_build/src/go.etcd.io/etcd/server/v3/mvcc/backend/batch_tx.go:235 +0x7c
go.etcd.io/etcd/server/v3/mvcc/backend.(*baseReadTx).UnsafeForEach(0xc0000f21e0, {0x12636bc50, 0x1267d6a00}, 0xc000434010)
	/builddir/build/BUILD/etcd-3.5.10/_build/src/go.etcd.io/etcd/server/v3/mvcc/backend/read_tx.go:69 +0x150
go.etcd.io/etcd/server/v3/mvcc.unsafeHashByRev({0x12636cee0, 0xc0000f21e0}, 0x126798300?, 0xc00067df98?, 0x2?)
	/builddir/build/BUILD/etcd-3.5.10/_build/src/go.etcd.io/etcd/server/v3/mvcc/hash.go:34 +0x160
go.etcd.io/etcd/server/v3/mvcc.(*store).hashByRev(0xc0002abad0, 0x2710)
	/builddir/build/BUILD/etcd-3.5.10/_build/src/go.etcd.io/etcd/server/v3/mvcc/kvstore.go:194 +0x3a4
go.etcd.io/etcd/server/v3/mvcc.(*hashStorage).HashByRev(0xc0002b8580, 0x2710)
	/builddir/build/BUILD/etcd-3.5.10/_build/src/go.etcd.io/etcd/server/v3/mvcc/hash.go:133 +0x230
go.etcd.io/etcd/server/v3/mvcc.TestHashKVWhenCompacting.func1()
	/builddir/build/BUILD/etcd-3.5.10/_build/src/go.etcd.io/etcd/server/v3/mvcc/kvstore_test.go:561 +0xb4
created by go.etcd.io/etcd/server/v3/mvcc.TestHashKVWhenCompacting in goroutine 522
	/builddir/build/BUILD/etcd-3.5.10/_build/src/go.etcd.io/etcd/server/v3/mvcc/kvstore_test.go:558 +0x2c4

Note it ends with a segfault.

**Comment by srivastav-abhishek** [comment]
Hi @jmhbnz  Here is the link for flaky actions, https://prow.ppc64le-cloud.cis.ibm.net/view/s3/ppc64le-prow-logs/logs/postsubmit-master-golang-etcd-build-test-ppc64le/1725287890176446464

It can be observed that `TestHashKVWhenCompacting` failed with timeout as compaction couldn't complete within 10 secs. Please note that this flakiness is observed on ppc64le architecture.

**Comment by jmhbnz** [comment]
Thanks for the supporting detail team. Before we double the timeout across the board do we have any understanding why compaction is taking so long on this cpu architecture only?  Has any profiling been done to investigate root cause?

**Comment by laboger** [comment]
I was able to generate a similar SEGV on an x86:
```
{"level":"info","msg":"storing new hash","hash":1071273429,"revision":9949,"compact-revision":9948}
{"level":"info","msg":"compact tree index","revision":9950}
{"level":"info","msg":"finished scheduled compaction","compact-revision":9950,"took":"99.238µs","hash":2035904312}
{"level":"info","msg":"storing new hash","hash":2035904312,"revision":9950,"compact-revision":9949}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ea793]

goroutine 64 [running]:
go.etcd.io/bbolt.(*Tx).Bucket(...)
	/home/boger/go/pkg/mod/go.etcd.io/bbolt@v1.3.8/tx.go:102
go.etcd.io/etcd/server/v3/mvcc/backend.(*baseReadTx).UnsafeRange(0xc000226410, {0xccc118, 0x118f040}, {0x11445e0, 0x13, 0x13}, {0x0, 0x0, 0x0}, 0x0)
	/home/boger/gocode/src/github.com/etcd-io/etcd/server/mvcc/backend/read_tx.go:102 +0x233
go.etcd.io/etcd/server/v3/mvcc.UnsafeReadScheduledCompact({0xccdb78?, 0xc000226410?})
	/home/boger/gocode/src/github.com/etcd-io/etcd/server/mvcc/util.go:54 +0x5d
go.etcd.io/etcd/server/v3/mvcc.(*store).checkPrevCompactionCompleted(0xc000100008?)
	/home/boger/gocode/src/github.com/etcd-io/etcd/server/mvcc/kvstore.go:235 +0x89
go.etcd.io/etcd/server/v3/mvcc.(*store).Compact(0xc000286820, 0xc0000f7f50, 0x26df)
	/home/boger/gocode/src/github.com/etcd-io/etcd/server/mvcc/kvstore.go:281 +0x52
go.etcd.io/etcd/server/v3/mvcc.TestHashKVWhenCompacting.func3()
	/home/boger/gocode/src/github.com/etcd-io/etcd/server/mvcc/kvstore_test.go:600 +0x10e
created by go.etcd.io/etcd/server/v3/mvcc.TestHashKVWhenCompacting in goroutine 43
	/home/boger/gocode/src/github.com/etcd-io/etcd/server/mvcc/kvstore_test.go:597 +0x4f3
FAIL	go.etcd.io/etcd/server/v3/mvcc	10.269s
FAIL
[boger@bohr etcd]$ go version
go version devel go1.22-3f2bf706f7 Wed Dec 6 17:59:12 2023 +0000 linux/amd64
```
I think the key is that it fails only if something else is running on the system.  If I run the test by itself it doesn't fail, but if I do go toolchain builds in another process then I can make it fail like this.

**Comment by ahrtr** [comment]
cc @Elbehery

**Comment by ahrtr** [comment]
> @srivastav-abhishek @zaitcev @laboger could you please let me know whether you can still see this issue on etcd 3.5.9?
> 
> > If I run the test by itself it doesn't fail, but if I do go toolchain builds in another process then I can make it fail like this.
> 
> Could you share a detailed step to reproduce this issue on x86? @laboger

@srivastav-abhishek @zaitcev @laboger  could you provide feedback on this comment?

**Comment by laboger** [comment]
I did a build and test of a Go toolchain. The full directions are here
https://go.dev/doc/install/source
Download a toolchain for use as a bootstrap as described in this doc.

git clone https://go.googlesource.com/go into a directory.
cd src
./all.bash

You might need to do this a few times to force the error to occur. Between
builds you should delete the bin and pkg directories.

**Comment by ahrtr** [comment]
FYI. I recently updated this test case in https://github.com/etcd-io/etcd/pull/17313

**Pull request closed without merging**
