### PR TITLE
etcdctl: remaining errors.Is conversions

### PR DESCRIPTION
**Pull request by redwrasse**
Remaining errors.Is conversions for the etcdctl module, as part of https://github.com/etcd-io/etcd/issues/18576.

### CODE REVIEW

**Review by jmhbnz — APPROVED** [review]
/ok-to-test

LGTM on green, thanks @redwrasse

**Review by ahrtr — APPROVED** [review]

**Comment by ivanvc** [comment]
Hi @redwrasse, Thanks for the pull request. I see this has already been merged. I couldn't review it before, but did we miss `ctlv3/command/ep_command.go:140`?

https://github.com/etcd-io/etcd/blob/0a355d3fbdeb74ffb3a59b2ace44abf639630016/etcdctl/ctlv3/command/ep_command.go#L140

**Comment by redwrasse** [comment]
Yes looks like we did, my fault. Should we open a PR for this, or wait to see if there's a few more stragglers?

**Comment by ahrtr** [comment]
> etcd/etcdctl/ctlv3/command/ep_command.go

Please raise a separate PR, thanks

**Comment by redwrasse** [comment]
Opened a PR https://github.com/etcd-io/etcd/pull/18625

**Pull request merged**
