### PR TITLE
Follow up manual Dependency Bump

### PR DESCRIPTION
**Pull request by ArkaSaha30**
This PR bumps github.com/prometheus/common from 0.54.0 to 0.55.0 in tools/mod missed in https://github.com/etcd-io/etcd/pull/18266

Dependabot raised raised the following PR:
- https://github.com/etcd-io/etcd/pull/18261

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ArkaSaha30** [comment]
cc @ivanvc @ahrtr

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @ArkaSaha30.

**Pull request merged**
