### PR TITLE
[3.5] Bump golang-jwt/jwt to 4.5.1 to address GO-2024-3250

### LINKED ISSUE #18898: [3.5] Bump golang-jwt/jwt to 4.5.1 to address GO-2024-3250
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

```
Vulnerability #1: GO-2024-3250
    Improper error handling in ParseWithClaims and bad documentation may cause
    dangerous situations in github.com/golang-jwt/jwt
  More info: https://pkg.go.dev/vuln/GO-2024-3250
  Module: github.com/golang-jwt/jwt/v4
    Found in: github.com/golang-jwt/jwt/v4@v4.4.2
    Fixed in: github.com/golang-jwt/jwt/v4@v4.5.1
    Example traces found:
Error:       #1: auth/jwt.go:48:26: auth.tokenJWT.info calls jwt.Parse

```

### What did you expect to happen?

No CVE failures

### How can we reproduce it (as minimally and precisely as possible)?

Refer to https://github.com/etcd-io/etcd/actions/runs/11851990849/job/33029399184?pr=18829

### Anything else we need to know?

_No response_

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tjungblu**
fixes #18898

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ivanvc** [comment]
/retitle [3.5] Bump golang-jwt/jwt to 4.5.1 to address GO-2024-3250
/retest

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @tjungblu

**Review by jmhbnz — APPROVED** [review]
LGTM - We bumped it in `main` last week in https://github.com/etcd-io/etcd/commit/fed92fa7ffa691768e4c05a4064d39812ab8d4f6

Thanks @tjungblu

**Comment by ivanvc** [comment]
We had a failure in the trivy scan. Again, GHCR replied with a 429 (https://github.com/etcd-io/etcd/actions/runs/11856210750/job/33042258548?pr=18899). Thomas' branch is up to date and has the ECR workaround. It also looks like the error was in another image (not trivy-db). We should keep an eye on this workflow.

> ERROR: failed to solve: ghcr.io/aquasecurity/trivy:0.50.1: failed to resolve source metadata for ghcr.io/aquasecurity/trivy:0.50.1: failed to copy: httpReadSeeker: failed open: unexpected status code https://ghcr.io/v2/aquasecurity/trivy/blobs/sha256:17e803800853ecc7564ad672b0d71df4870e4e7586701de79cc40e2ea9819671: 429 Too Many Requests - Server message: toomanyrequests: retry-after: 8.583µs, allowed: 44000/minute

**Pull request merged**
