### PR TITLE
Update genproto dependency

### PR DESCRIPTION
**Pull request by liggitt**
Updates to a version of genproto that splits out the generic api/rpc packages to avoid future "ambiguous imports" errors.

See https://github.com/googleapis/go-genproto/issues/1015 for more details.

### CODE REVIEW

**Comment by liggitt** [comment]
rebased

**Comment by liggitt** [comment]
`Tests / test (linux-amd64-integration-2-cpu) (pull_request) Failing after 20m` failure is a timeout:
```
integration/clientv3/examples (15m0.113s)
```

I can't reproduce this locally, `ETCD_VERIFY=all go test -v -json ./integration/... -timeout=15m --race --cpu=2 -p=2` passes just fine

```
ok  	go.etcd.io/etcd/tests/v3/integration/clientv3/examples	3.093s
```

**Comment by liggitt** [comment]
@ahrtr is the integration-2-cpu test timing out elsewhere, or is that specific to this PR? how close to the 15 minute timeout is it running normally when it passes in CI?

**Comment by ahrtr** [comment]
> @ahrtr is the integration-2-cpu test timing out elsewhere, or is that specific to this PR? how close to the 15 minute timeout is it running normally when it passes in CI?

I think It has nothing to do with this PR. It should be just flaky test case. We can follow it separately.

**Comment by ahrtr** [comment]
Closing this PR since a similar PR https://github.com/etcd-io/etcd/pull/16338 has already been merged per your [comment](https://github.com/etcd-io/etcd/pull/16338#issuecomment-1660977862).

[Note: This PR was raised earlier than https://github.com/etcd-io/etcd/pull/16338] thx @liggitt

**Pull request closed without merging**
