### PR TITLE
 mvcc: push down RangeOptions.limit argv into index tree to reduce memory overhead

### PR DESCRIPTION
**Pull request by tangcong**
if there are too many keys(key,rangeEnd), even if we set RangeOptions.limit to 1,range request is very expensive and it will result in oom. this pr will push down RangeOptions.limit argv into index tree to reduce memory overhead. @gyuho 
image

### CODE REVIEW

**Comment by tangcong** [comment]
before optimization:
```
time etcdctl get /config --prefix --limit 2
/config
/config/test1

real	0m1.036s
user	0m0.008s
sys	0m0.004s
```
after optimization:
```
time etcdctl get /config  --prefix --limit 2
/config
/config/test1

real	0m0.009s
user	0m0.002s
sys	0m0.009s
```

**Comment by xrmzju** [comment]
limit ==0 means fetch everything, but this pr merged will change this meaning

**Comment by tangcong** [comment]
> limit ==0 means fetch everything, but this pr merged seems will change the behavior

can you give me a failed case? if limit == 0, it seems will also fetch everything. thanks.

**Comment by xrmzju** [comment]
> > limit ==0 means fetch everything, but this pr merged seems will change the behavior
> 
> can you give me a failed case? if limit == 0, it seems will also fetch everything. thanks.

sry i miss some logic here..

**Comment by serathius** [comment]
@tangcong This PR broke Kubernetes api chunking feature. Kubernetes uses Range request Count returned by `CountRevisions` function for pagination. This PR changed `CountRevisions` to return after reaching limit. 

I don't this behavior is correct as it removes value provided by having a Count field as it will always equal number of keys returned. Count is only beneficial if it returns number of objects with Limit.

**Comment by ptabor** [comment]
Thank you for nailing this @serathius. 

Definitely its a wire-format breaking change and in scope of 3.x branch we cannot perform it. I think we shouldn't push down the limit if its count-only query (and I hope that count-only queries are not accumulating the memory). 

I see value of counting with limit - e.g.(for some use-cases like checking whether there is more than N objects, 
but I don't think they are critical and that they cannot wait till 4.x. 

Potentially etcd/clientv3 could print warning if both: count & limit are set if we imagine we could change the behavior in v4.

**Comment by gyuho** [comment]
> PR broke Kubernetes api chunking feature

> I think we shouldn't push down the limit if its count-only query 

Agree with @ptabor. `CountRevisions` is only used for range count query, we should revert such semantic changes.

@tangcong Can you share more about your use case for count revision with limit?

**Comment by tangcong** [comment]
There are two main scenarios：
1. [gRPC Proxy will query with limit](https://github.com/etcd-io/etcd/blob/main/server/proxy/grpcproxy/watch.go#L210-L226), we find that the overhead is relatively large when there are more keys
2. some non-K8S businesses will also specify limit queries through etcdctl and API when there are more keys.

unfortunately, it broke Kubernetes api chunking feature. i agree with @ptabor, etcd 3.5 coming soon，it is not critical, i hope we can optimize in a future version. thanks @serathius @ptabor @gyuho

**Comment by wilsonwang371** [comment]
Without this change, if we list all the pods with a limit specified, it will be a nightmare when we are going through millions of pod objects.

From what I observed in issue #13068, the write performance can get reduced to only 25% of the normal case.

**Comment by wilsonwang371** [comment]
Can we just add code to deal with the limit == 0 case? Will this work? @tangcong @ptabor @gyuho

**Comment by wilsonwang371** [comment]
> Can we just add code to deal with the limit == 0 case? Will this work? @tangcong @ptabor @gyuho

I saw the original issue: https://github.com/etcd-io/etcd/issues/13056#issuecomment-851526844

It seems to be very tricky...

**Comment by wilsonwang371** [comment]
cc @Jeffwan

**Comment by serathius** [comment]
Yep, K8s directly depends on this behavior to provide chunking in API.
Original proposal https://github.com/kubernetes/community/pull/3710

**Comment by tangcong** [comment]
image

It seems that this PR only affects the RemainingItemCount feature，it has always been an Alpha feature.  

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L771-L775

**Comment by JohnRusk** [comment]
@tangcong what was the final outcome about the effect on the RemainingTimeCount feature in Kubernetes?  I'm asking because this page shows that it is currently in Beta (not Alpha as you said above) and that it is _enabled_ by default.  https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Pull request merged**
