### PR TITLE
mvcc: reduce count-only range overhead

### PR DESCRIPTION
**Pull request by tangcong**
image
if there are too much keys(> 1 millions),count-only range is very slow(slice expansion) and cost too much memory. it is not necessary to return revpairs,so we can do a small optimization to reduce overhead.

### CODE REVIEW

**Comment by tangcong** [comment]
> I like the idea. Not sure if we want to change the existing function signature or create a new method. If the request is for count, can we create a method `CountRevisions`?

yes,it will be more clear and concise. I will take the time to update pr.

**Comment by tangcong** [comment]
@jingyih updated. PTAL. thanks.

**Comment by gyuho** [comment]
@tangcong Curious, what's your use case for counting API?

**Comment by tangcong** [comment]
Low frequency use, but we benefit a lot from it:
1. A dimension of consistency monitoring (report etcd_key_diff metric by comparing every member total key diff at the same time)
2. In the configuration system and k8s scenarios, quickly view the number of resources with a specified prefix.
Through this optimization, we tested that the latecny can be shortened by nearly 3 times in the ten million key scenario, and there is no expensive memory overhead. Thanks. @gyuho

**Comment by gyuho** [comment]
@tangcong Makes sense. Thanks!

**Pull request merged**
