### PR TITLE
change deleted a simple token log to debug level from info level.

### PR DESCRIPTION
**Pull request by siyuanfoundation**
https://github.com/etcd-io/etcd/issues/18244

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @siyuanfoundation

**Comment by ahmetb** [comment]
Erm, I already have #18245 :)

**Comment by jmhbnz** [comment]
> Erm, I already have #18245 :)

Thanks for the reminder. Let's prioritise merging #18245. Closing this in favor.

**Pull request closed without merging**
