### PR TITLE
changed the scorecard badge link to the standard format

### PR DESCRIPTION
**Pull request by harshitasao**
**Description:**

Changes the scorecard badge link from old format to the Standard human-readable OpenSSF Scorecard Report.

### CODE REVIEW

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @harshitasao

**Comment by ivanvc** [comment]
LGTM. Good catch. Thanks, @harshitasao

**Review by ivanvc — APPROVED** [review]
LGTM. Good catch. Thanks, @harshitasao

**Review by serathius — APPROVED** [review]

**Pull request merged**
