### PR TITLE
fix: enable nil-compare rule from testifylint

### PR DESCRIPTION
**Pull request by mmorel-35**
This fixes [nil-compare](https://github.com/Antonboom/testifylint?tab=readme-ov-file#nil-compare) rule from [testifylint](https://github.com/Antonboom/testifylint).

It also replaces `testutil.AssertNil` and `testutil.AssertNotNil` by `assert.Nil` and `require.NotNil`

The require package is used for NotNil replacement because of the Fatal method being used in testutil version of the method.

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]

**Comment by ahrtr** [comment]
Thank you!

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, Matthieu. Can you delete `client/pkg/testutil/assert.go` in a follow-up pull request?

**Comment by ivanvc** [comment]
> Are you sure that's not used by any project that depends on etcd.

Good point. Let's deprecate.

**Comment by ivanvc** [comment]
> OK, I updated the comments on the `client/pkg/testutil/assert.go` functions

Sorry, @mmorel-35. I think it'd be better in another PR, to open it up for discussion.

**Comment by ivanvc** [comment]
> Alright, it's reverted

Thank you so much.

/retest

**Comment by ivanvc** [comment]
@jmhbnz, Matthieu removed the deprecation notice from `client/pkg/testutil/assert.go`. The pull request is now back in the state it was in when Benjamin and I approved it. Could you PTAL at it? Thanks.

**Comment by ivanvc** [comment]
Link to https://github.com/etcd-io/etcd/issues/18719

**Pull request merged**
