### PR TITLE
chore: add newline as last char for .go-version

### PR DESCRIPTION
**Pull request by fuweid**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
It isn't a problem to not have a newline. There is no newline in K8s either,  I think it might be intentional.

**Comment by fuweid** [comment]
@ahrtr Most of files are end of newline. This pr is to align with existing files. If it is not acceptable, I can close it.

**Comment by ahrtr** [comment]
> @ahrtr Most of files are end of newline.

Yes, I am aware of it. But we get the go version using command `cat .go-version`, so I think we intentionally do not add the newline character. 

>  If it is not acceptable, I can close it.

Let's wait @serathius 's option, since he added the .go-version file.

**Comment by serathius** [comment]
Don't have strong opinion. As long as the goversion and release workflows work I'm happy.

**Comment by ahrtr** [comment]
Thanks for the feedback. 
 
I suggest to keep it consistent with K8s [.go-version](https://github.com/kubernetes/kubernetes/blob/master/.go-version), which has not a newline character at the end.

**Comment by fuweid** [comment]
Thanks for the comment. Closing~

**Pull request closed without merging**
