### PR TITLE
Fix tests for latest golang

### PR DESCRIPTION
**Pull request by mkumatag**
Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.
Fixes: https://github.com/etcd-io/etcd/issues/10539

### CODE REVIEW

**Comment by mkumatag** [comment]
@gyuho @hexfusion

**Comment by mkumatag** [comment]
Tests passed on gotip

**Comment by mkumatag** [comment]
@xiang90

**Comment by dims** [comment]
cc @spzala

**Comment by spzala** [comment]
@mkumatag so as @hexfusion pointed out in the issue we haven't yet moved to the latest go but the changes looks good to me overall to fix two tests that failed as provided in the issue and per your findings on changes in Errorf. What do you think about https://github.com/etcd-io/etcd/blob/master/client/members_test.go#L426 for a possible change there as well? I will defer to @hexfusion @xiang90 for final review. Thanks!

**Comment by mkumatag** [comment]
> @mkumatag so as @hexfusion pointed out in the issue we haven't yet moved to the latest go but the changes looks good to me overall to fix two tests that failed as provided in the issue and per your findings on changes in Errorf. What do you think about https://github.com/etcd-io/etcd/blob/master/client/members_test.go#L426 for a possible change there as well? I will defer to @hexfusion @xiang90 for final review. Thanks!

@spzala changes in https://github.com/etcd-io/etcd/blob/master/client/members_test.go#L426 not required because error origin is from https://github.com/etcd-io/etcd/blob/master/client/members_test.go#L426 is same as where it is [originated](https://github.com/etcd-io/etcd/blob/master/client/members.go#L153).

You can check the Travis log for the gotip version in which everything is green, so nothing else we need to worry about!

**Comment by spzala** [comment]
> > @mkumatag so as @hexfusion pointed out in the issue we haven't yet moved to the latest go but the changes looks good to me overall to fix two tests that failed as provided in the issue and per your findings on changes in Errorf. What do you think about https://github.com/etcd-io/etcd/blob/master/client/members_test.go#L426 for a possible change there as well? I will defer to @hexfusion @xiang90 for final review. Thanks!
> 
> @spzala changes in https://github.com/etcd-io/etcd/blob/master/client/members_test.go#L426 not required because error origin is from https://github.com/etcd-io/etcd/blob/master/client/members_test.go#L426 is same as where it is [originated](https://github.com/etcd-io/etcd/blob/master/client/members.go#L153).
> 
> You can check the Travis log for the gotip version in which everything is green, so nothing else we need to worry about!

@mkumatag cool, thanks! I was wondering about future when we bump the go version so just wanted to make sure that you verify it.

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
