### PR TITLE
bugfix: register of walWriteSec

### PR DESCRIPTION
**Pull request by andyxning**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

cherry-pick https://github.com/etcd-io/etcd/pull/18164 to release-3.5 

/cc @ivanvc

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]
Good catch!

Thank you.

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @andyxning. Could you open a PR to update 3.5's CHANGELOG with this bug fix as pointed out by Benjamin? Thanks again.

**Comment by andyxning** [comment]
@ivanvc This is a bugfix to adding support for `walWriteSec` and `walWriteSec` was added in v3.5. There is no need to update in the changelog, imho.

**Comment by ivanvc** [comment]
> @ivanvc This is a bugfix to adding support for `walWriteSec` and `walWriteSec` was added in v3.5. There is no need to update in the changelog, imho. 

Yes, but at least 3.5.14 was released with this bug. I think that's why we need the release note, and why Benjamin requested it.

**Pull request merged**
