### PR TITLE
fix: enable require-error rule from testifylint

### PR DESCRIPTION
**Pull request by mmorel-35**
This fixes [require-error](https://github.com/Antonboom/testifylint?tab=readme-ov-file#require-error) rule from [testifylint](https://github.com/Antonboom/testifylint)

Related to #18719

### CODE REVIEW

**Review by ivanvc — APPROVED** [review]
This PR is a bit long, but it LGTM nonetheless. Thanks, @mmorel-35.

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you!

**Pull request merged**
