### PR TITLE
Yxjetcd pprof UI

### PR DESCRIPTION
**Pull request by yangxuanjia**
add pprof UI for etcd

// http://127.0.0.1/debug/pprof/ui/
// http://127.0.0.1/debug/pprof/ui/allocs
// http://127.0.0.1/debug/pprof/ui/profile
// http://127.0.0.1/debug/pprof/ui/heap
// http://127.0.0.1/debug/pprof/goroutineui/

// http://127.0.0.1/debug/pprof/ui/block
// http://127.0.0.1/debug/pprof/ui/goroutine
// http://127.0.0.1/debug/pprof/ui/mutex
// http://127.0.0.1/debug/pprof/ui/threadcreate

### CODE REVIEW

**Comment by ptabor** [comment]
@tobilarscheid @yangxuanjia 
I see this is a clone of cockroachdb code. 
Assuming we want to incorporate the UI, we should find a better model of sharing the code than copying it.

**Comment by tobilarscheid** [comment]
Pretty sure I am tagged by mistake :-)

**Comment by ptabor** [comment]
I'm sorry about this. I should have tagged @tbg because of these commits: https://github.com/cockroachdb/cockroach/commit/9d7ca0ffa5f55fd5121bb2c50ee03724e181dc07

**Comment by yangxuanjia** [comment]
Yes, this feature is good when have problem online, we can easy and quickly troubleshoot. It's wonderful for online system.

**Comment by ptabor** [comment]
@yangxuanjia I'm not questioning whether its useful. I just think that etcd community does not want to maintain its own clone of 1kloc maintained in another project. I you think its reusable I would propose working with cockrouchdb community for finding accessible shared location for that code.

**Comment by yangxuanjia** [comment]
@ptabor you are right

**Comment by yangxuanjia** [comment]
@ptabor ,  Did you interest in #12343 ?

**Comment by tbg** [comment]
FYI panicparse v2 has this:

https://github.com/maruel/panicparse/blob/master/stack/webstack/webstack.go

You may want to just use that directly. We wrote our code before this was available.

**Comment by ptabor** [comment]
Closing this PR, but happy to review integration with library supporting this, e.g. panicparse v2 in a separate PR as Tobis mentioned.

**Pull request closed without merging**
