### PR TITLE
[2024-07-29] Manual Dependency Bump

### PR DESCRIPTION
**Pull request by ArkaSaha30**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

#### Bumped:

- https://github.com/etcd-io/etcd/pull/18378
- https://github.com/etcd-io/etcd/pull/18374

#### Purely Indirect:

- https://github.com/etcd-io/etcd/pull/18377
- https://github.com/etcd-io/etcd/pull/18376
- https://github.com/etcd-io/etcd/pull/18375

### CODE REVIEW

**Comment by ahrtr** [comment]
Thanks @ArkaSaha30 . 

Could you please update the second commit's message to contain the exact command you executed?

**Comment by ArkaSaha30** [comment]
> Thanks @ArkaSaha30 .
> 
> Could you please update the second commit's message to contain the exact command you executed?

Yes, I have just added in the command to run and the error encountered in the commit message

**Comment by ahrtr** [comment]
> > Thanks @ArkaSaha30 .
> > Could you please update the second commit's message to contain the exact command you executed?
> 
> Yes, I have just added in the command to run and the error encountered in the commit message

Thanks, please also consider to update https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md in a separate PR, thx

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @ArkaSaha30

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @ArkaSaha30

**Pull request merged**
