### PR TITLE
clientv3: simplify grpc dialer usage.

### PR DESCRIPTION
**Pull request by YoyinZyc**
fix https://github.com/etcd-io/etcd/issues/11519
verified by tests under tests/docker-dns, tests/dorker-dns-srv, tests/docker-static-ip
@jpbetz @gyuho

### CODE REVIEW

**Comment by xiang90** [comment]
There are a few exposed public method removed. Will this affect client API backward compatibility?

**Comment by YoyinZyc** [comment]
> There are a few exposed public method removed. Will this affect client API backward compatibility?

Most of them are the workaround from https://github.com/etcd-io/etcd/pull/11184. We can safely remove them after bumping into latest gRPC.

**Comment by gyuho** [comment]
lgtm, can we highlight this fix in CHANGELOG 3.5? thx

**Comment by YoyinZyc** [comment]
> lgtm, can we highlight this fix in CHANGELOG 3.5? thx

Sure. Will do after merged.

**Pull request merged**
