### PR TITLE
[release-3.3] vendor: bump gRPC-go to 1.24.0

### PR DESCRIPTION
**Pull request by hexfusion**
This PR bumps gRPC-go to 1.24.0 for `release-3.3`.

### CODE REVIEW

**Comment by hexfusion** [comment]
I think for the same reason that we would want the above PR we should be testing for regression with bumps in gRPC with the client.

Meaning because `3.3.17` is using gRPC-go `v1.23.0` can we safely bump it to `v1.24.0` on the server without regression. We should consider covering this testing. I am going to put this as WIP while I think about it.

**Comment by xiang90** [comment]
is this still wip?

**Comment by hexfusion** [comment]
@xiang90 I am nervous to bump gRPC in a patch release, love to hear your thoughts.

**Comment by xiang90** [comment]
then let us do this in a minor release unless the bump fixes a significant bug or something.

**Comment by hexfusion** [comment]
Agreed.

**Pull request closed without merging**
