### PR TITLE
Raft HTTP: fix pause/resume race condition

### PR DESCRIPTION
**Pull request by yznima**
(cherry picked from commit b1812a410fbca6fb77bf95b496408c7b75d0a370)

Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by yznima** [comment]
@xiang90 @gyuho Backporting the same commit. Could you review?

**Comment by xiang90** [comment]
lgtm

**Comment by xiang90** [comment]
ping @gyuho

**Comment by jingyih** [comment]
For bug fix, let's also backport to v3.2 and v3.1. Could you help? @yznima

**Comment by yznima** [comment]
> For bug fix, let's also backport to v3.2 and v3.1. Could you help? @yznima

I can help

**Pull request merged**
