### PR TITLE
backport 3.5: #13676 load all leases from backend

### PR DESCRIPTION
**Pull request by chaochn47**
Backport the PR #13676 to release-3.5 branch

@serathius @spzala @ptabor

### CODE REVIEW

**Comment by chaochn47** [comment]
`--- FAIL: TestV3CorruptAlarmWithLeaseCorrupted` in the release-3.5 branch. My guess is the integration tests framework won't close the corresponding v3 client when the member was removed from the cluster. I will look into the failure in details tomorrow and get the CI green back.

**Comment by chaochn47** [comment]
Resolved the test failures in the first try. 

The second attempt only failed on `semaphoreci` which is unrelated to this change. 
```
--- FAIL: TestCtlV3AuthFromKeyPerm (16.06s)
    testing.go:35: Changing working directory to: /tmp/TestCtlV3AuthFromKeyPerm374005025/001
    logger.go:130: 2022-02-22T18:26:35.720Z	INFO	starting server...	{"name": "test-0"}
    logger.go:130: 2022-02-22T18:26:35.720Z	INFO	spawning process	{"args": ["/go/src/go.etcd.io/etcd/bin/etcd", "--name", "test-0", "--listen-client-urls", "http://localhost:20000", "--advertise-client-urls", "http://localhost:20000", "--listen-peer-urls", "https://localhost:20001", "--initial-advertise-peer-urls", "https://localhost:20001", "--initial-cluster-token", "new", "--data-dir", "/tmp/TestCtlV3AuthFromKeyPerm374005025/002", "--snapshot-count", "100000", "--experimental-initial-corrupt-check", "--peer-auto-tls", "--initial-cluster", "test-0=https://localhost:20001"], "working-dir": "/tmp/TestCtlV3AuthFromKeyPerm374005025/001", "environment-variables": ["GOFLAGS=-mod", "HOSTNAME=d073a02c36d9", "PASSES=build e2e", "PWD=/go/src/go.etcd.io/etcd/tests/e2e", "GOARCH=386", "HOME=/root", "GOROOT=/usr/local/go", "GO_VERSION=1.16.3", "GO_DOWNLOAD_URL=https://storage.googleapis.com/golang", "SHLVL=1", "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "GOPATH=/go", "OLDPWD=/go/src/go.etcd.io/etcd", "_=/usr/bin/env", "ETCD_UNSUPPORTED_ARCH=386", "ETCD_VERIFY=all"]}
    logger.go:130: 2022-02-22T18:26:36.770Z	INFO	started server.	{"name": "test-0"}
    testutil.go:56: ---> Test failed: test timed out after 15s
    testutil.go:57: goroutine 688 [running]:
        go.etcd.io/etcd/client/pkg/v3/testutil.FatalStack(0xa62e2a0, 0xa429590, 0x18)
        	/go/src/go.etcd.io/etcd/client/pkg/testutil/testutil.go:55 +0x5c
        go.etcd.io/etcd/tests/v3/e2e.testCtlWithOffline(0xa62e2a0, 0x896a07c, 0x0, 0x0, 0x0, 0x0)
        	/go/src/go.etcd.io/etcd/tests/e2e/ctl_v3_test.go:273 +0x63b
make: *** [docker-test] Error 1
```

**Review by spzala — APPROVED** [review]
lgtm. Thanks @chaochn47

**Review by serathius — APPROVED** [review]

**Review by serathius — APPROVED** [review]

**Comment by ahrtr** [comment]
@chaochn47 can you backport this PR to 3.4? 
FYI. https://github.com/etcd-io/etcd/issues/14232

**Pull request merged**
