### PR TITLE
Automated cherry pick of #11621 to release-3.4

### PR DESCRIPTION
**Pull request by YoyinZyc**
@jingyih @wenjiaswe

### CODE REVIEW

**Comment by YoyinZyc** [comment]
Also, can we cut a new 3.4 release after merging this PR by this weekend? Recent corruption fix and corruption checker improvement are pretty worth to make a new release.  @gyuho

**Comment by gyuho** [comment]
yeah, can we take a look at CI failures.

I can do the release.

**Comment by YoyinZyc** [comment]
> yeah, can we take a look at CI failures.
> 
> I can do the release.

Thanks! The failure is the commit_title check complaining about a previous commit title. It is not about this PR.
```
bb5ba14 Add version, tag and branch checks to release script...
Expected commit title format '<package>{", "<package>}: <description>'
Got: bb5ba14 Add version, tag and branch checks to release script
```

**Comment by YoyinZyc** [comment]
Btw, can I ask when can we have this new release? It will be great we can get it by this Friday. Thanks. @gyuho

**Pull request merged**
