### PR TITLE
vendor: update grpc-go to v1.20.0

### PR DESCRIPTION
**Pull request by aanm**
This version includes patch from
https://github.com/grpc/grpc-go/pull/2695 which
fixes https://github.com/etcd-io/etcd/issues/9956

Signed-off-by: André Martins <aanm90@gmail.com>

### CODE REVIEW

**Comment by jingyih** [comment]
cc @jpbetz

**Comment by aanm** [comment]
cc @hexfusion

**Comment by gyuho** [comment]
Whenever we upgrade gRPC, a lot of things break... I will investigate more in May.

**Comment by jingyih** [comment]
Since we are bumping up the grpc version, can we try to bump the version to 1.22? We need to pick up https://github.com/grpc/grpc-go/pull/2777 which is included in 1.21 and above to fix #10087.

**Comment by gyuho** [comment]
@jingyih I will be working on gRPC balancer fix, with gRPC 1.22 bump up. Will start working on it after July 4

**Comment by hexfusion** [comment]
@gyuho I can dedicate cycles to assist in this effort as well, please touch base so we can coordinate.

**Comment by gyuho** [comment]
@hexfusion Let's sync up later next week. The changes that I need in clientv3 needs latest gRPC. So, I will bundle them in my later PR.

**Comment by gyuho** [comment]
Closing, to use gRPC 1.22.0

**Comment by pires** [comment]
@gyuho would be great to have a linked issue or PR to keep track of the follow-up.

**Comment by gyuho** [comment]
@pires Yes, I will keep posting updates here as well!

**Pull request closed without merging**
