### PR TITLE
Use method const in package http instead of literal

### PR DESCRIPTION
**Pull request by hainesc**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by ptabor — APPROVED** [review]

**Comment by ptabor** [comment]
Thank you.

**Review by lilic — APPROVED** [review]
Thank you! 🎉

**Comment by hainesc** [comment]
@lilic May I know how can I get this PR merged? I have no write access to this repo.

**Comment by lilic** [comment]
I don't have either, but I am sure @ptabor will merge it when he gets the notification.

**Comment by ptabor** [comment]
@lilic You are right.

**Pull request merged**
