### PR TITLE
Documentation/etcd-mixin: Reformulate alerting rules to use `without` rather than `by`

### PR DESCRIPTION
**Pull request by beorn7**
With aggregations using `by`, all additional target labels that a user
might have configured, are aggregated away. However, those target
labels are useful for e.g. alert routing. With this commit, nothing
should change for vanilla job/instance target labels, but whoever has
more target labels can now still make use of them.

### CODE REVIEW

**Comment by beorn7** [comment]
Anyone? @hexfusion perhaps?

**Comment by beorn7** [comment]
Fine-tuned the PR title in the hope to get some attention. Also paging @brancz .

**Comment by brancz** [comment]
Could we make the identifying labels configurable? It's not uncommon that etcd is a static pod in Kubernetes and namespace and pod get relabeled onto the targets.

**Comment by beorn7** [comment]
> Could we make the identifying labels configurable?

The intention of this change is to not need to configure the indentifying labels. By using `without` rather than `by`, we only aggregate away the labels that should be aggregated away in any case. Not more and not less.

**Comment by brancz** [comment]
I may very well be missing something, but I don't see how we will get the expected result from etcd targets that have the `instance`, `namespace`, and `pod` labels. Yes, the instance label will be ignored, but we still end up aggregating just within each etcd process itself, which for at least some of these does not appear to be what we are aiming for.

**Comment by beorn7** [comment]
:facepalm: Yes, obviously. I was blinded by the specific setup I'm currently working with. I'll rework this PR to parametrize the label that need to be aggregated away.

**Comment by beorn7** [comment]
Done, PHAL.

**Comment by beorn7** [comment]
The fmt test is still looking at the obsolete commit title. Don't know how to fix that.

**Comment by xiang90** [comment]
travis is strange... lgtm.

**Pull request merged**
