### PR TITLE
*: build etcd-test image for multiarch

### PR DESCRIPTION
**Pull request by zhlhahaha**
Script for building multi-arch etcd-test image

Signed-off-by: Howard Zhang <howard.zhang@arm.com>

For etcd to officially support a arm64 platform, CI test is necessary. However, the etcd-test image which is used by CI test is only support amd64. This PR is for building etcd-test image for multiarch platform. 

Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by zhlhahaha** [comment]
@xiang90 
As we discussed in #11270, this patch is for build etcd-test image for multi-arch. Can you review it when you have time?

**Comment by lubinszARM** [comment]
Hi @spzala 
Any comments?

**Comment by lubinszARM** [comment]
Related PR: https://github.com/etcd-io/etcd/pull/7714

**Pull request closed without merging**
