### PR TITLE
dependency: bump github.com/grpc-ecosystem/grpc-gateway/v2 from v2.7.0 to v2.17.1

### PR DESCRIPTION
**Pull request by liggitt**
This PR updates the grpc-gateway dependency to pick up https://github.com/grpc-ecosystem/grpc-gateway/pull/3317

This removes the direct dependency on google.golang.org/genproto (which clears the way to clean up that dependency tree once google.golang.org/genproto/googleapis/rpc drops the reference to google.golang.org/genproto, see https://github.com/googleapis/go-genproto/issues/1015 for details)

### CODE REVIEW

**Comment by serathius** [comment]
```
FAIL: inconsistent versions for depencency: google.golang.org/genproto/googleapis/api
  - google.golang.org/genproto/googleapis/api@v0.0.0-20230525234035-dd9d682886f9 from: go.etcd.io/etcd/api/v3
  - google.golang.org/genproto/googleapis/api@v0.0.0-202307261[55](https://github.com/etcd-io/etcd/actions/runs/5740357922/job/15557997172?pr=16357#step:7:56)614-23370e0ffb3e from: go.etcd.io/etcd/server/v3
  ```

**Comment by liggitt** [comment]
oops, fixed

**Comment by ahrtr** [comment]
Eventually we will upgrade grpc-gateway to v2 in https://github.com/etcd-io/etcd/pull/16454. But just as I mentioned in https://github.com/etcd-io/etcd/pull/16454#issuecomment-1692280452, I'd like to breakdown the big change, so I am happy to get this PR merged firstly. Could you please rebase this PR and bump grpc-gateway to latest version [2.17.1](https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.17.1)? Please feel free to let me know if you don't bandwidth to do it, than I can take care of it.

**Comment by liggitt** [comment]
done

**Comment by ahrtr** [comment]
Could you rebase this PR although github doesn't show conflict? Your dev branch is far lag behind the head of main branch; sometimes github can't detect some conflict.

**Comment by liggitt** [comment]
actually done this time :)

**Comment by ahrtr** [comment]
The workflow fails due to inconsistent google.golang.org/genproto/googleapis/api versions.

Please refer to https://github.com/etcd-io/etcd/pull/16454/commits/40c7f72b1d62790554a0e43cd325295d034deba0

**Review by ahrtr — APPROVED** [review]
LGTM

thx @liggitt 

cc @fuweid @jmhbnz @serathius

**Review by serathius — APPROVED** [review]

**Review by fuweid — APPROVED** [review]
LGTM

**Pull request merged**
