### PR TITLE
etcdctl: add global config file support for cli

### LINKED ISSUE #9779: File based user configuration
I'd like to suggest seeding pre-populated users through a config file.
This is particularly useful when habilitating CN authentication (even more when we're able to create user without passwords https://github.com/coreos/etcd/issues/9590).
So we wouldn't have to mess with the API.

Currently, when I need to create some users. The process looks like this:
```
echo rootpasswd | etcdctl user add root --interactive false

etcdctl auth enable

gen_passwd | etcdctl --user root:rootpasswd --interactive false user add kubernetes 
etcdctl --user root:rootpasswd user grant-role kubernetes-role root
etcdctl --user root:rootpasswd role grant-permission kubernetes-role --prefix=true readwrite /registry/

gen_passwd | etcdctl --user root:rootpasswd --interactive false user add calico
etcdctl --user root:rootpasswd user grant-role calico-role root
etcdctl --user root:rootpasswd role grant-permission calico-role --prefix=true readwrite /calico/
```

The file based configuration could look something like this and could be passed as an init flag `--user-config $FILE`:
```yaml
users:
- name: root
  password: rootpasswd
- name: kubernetes
  role: kubernetes-role
- name: calico
  role: calico-role
roles:
- name: calico-role
  access: readwrite
  prefix: /calico/
- name: kubernetes-role
  access: readwrite
  prefix: /registry/
```

### PR DESCRIPTION
**Pull request by harshanarayana**
# Purpose
This PR introduces a global configuration file that can be used to provide global settings for each of your `etcvdctl` command use. This falls in line with how `$HOME/.kube/config` file does the work.

# Why this change?
Currently `etcdctl` supports the use of env prefix-based global configuration that lets you run the `etcdctl` command without much complication with a common set of configuration. However, in systems and scripts where `etcdctl` commands are being largely leveraged to perform operations, it can be painful to add env prefix-based configuration. This means that one would have to go in and find all the places where these commands are being used and add necessary overrides. This PR by adding the global config file will simplify that workflow. 

You setup your configuration file and you need not worry about modifying any of your existing `etcdctl` commands.

# Limitations
As of version `v3.4.x` since the ETCD v3 APIs are the default, this PR only adds the configuration file support if you are using the `v3` APIs and not `v2`.

# Change Description
This change brings in the ability to use a global configuration file to set up the necessary configuration that will be used while running each and every `etcdctl` command. This change provides you two ways of providing a global configuration for your `etcdctl` command.
1. By default path provided in `$HOME/.etcd/config.yaml`
2. By specifying the `--etcdctlconfig` argument with `etcdctl` command

The value override precedence is as follows. 
1. ENV Prefix
2. Configuration File
3. CLI argument provided

The higher number configuration overrides the values set by the previous configuration. 

# New Dependencies
1. [viper](https://github.com/spf13/viper)

Fixes #9779

### CODE REVIEW

**Comment by harshanarayana** [comment]
Sorry to bother you, @gyuho @xiang90 

Any idea of how I can retrigger a failed build? `/retest` didn't work for me.

**Comment by maoling** [comment]
`git commit --amend` to generate a new commit hash
then  `git push feature etcd_config_file_support-master -f ` to retrigger the CI

**Comment by harshanarayana** [comment]
@maoling Gotcha. I was wondering if there was some way to retrigger it without that. Never mind. Let me amend the commit.

**Comment by harshanarayana** [comment]
cc @gyuho @wenjiaswe @jingyih

**Comment by harshanarayana** [comment]
cc @gyuho @wenjiaswe @jingyih

**Pull request closed without merging**
