### PR TITLE
[release-3.4] Bump go toolchain to 1.22.6

### PR DESCRIPTION
**Pull request by henrybear327**
Reference:
- https://github.com/etcd-io/etcd/issues/18443

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ivanvc** [comment]
The first part of the issue with the functional tests is that there's a trailing whitespace in the key of the map here (which was very obscure to find; note the `"/trace "`):

https://github.com/etcd-io/etcd/blob/5161b747991da9137ac33868a1a68478b9149d75/pkg/debugutil/pprof.go#L39

It should be

```golang
m[HTTPPrefixPProf+"/trace"] = http.HandlerFunc(pprof.Trace)
```

After fixing that, there are still more test failures :sweat_smile:

**Review by ahrtr — APPROVED** [review]

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, Henry.

**Comment by henrybear327** [comment]
> The first part of the issue with the functional tests is that there's a trailing whitespace in the key of the map here (which was very obscure to find; note the `"/trace "`):
> 
> https://github.com/etcd-io/etcd/blob/5161b747991da9137ac33868a1a68478b9149d75/pkg/debugutil/pprof.go#L39
> 
> It should be
> 
> ```go
> m[HTTPPrefixPProf+"/trace"] = http.HandlerFunc(pprof.Trace)
> ```
> 
> After fixing that, there are still more test failures 😅

Thanks for digging into this @ivanvc !!

It's actually the only part besides the linter issue which blocked the CI!

**Comment by ivanvc** [comment]
> Thanks for digging into this @ivanvc !!
> 
> It's actually the only part besides the linter issue which blocked the CI!

Yes, I realized later that some local changes were the cause of my other errors :speak_no_evil:

**Comment by ivanvc** [comment]
/retitle [3.4] Bump go toolchain to 1.22.6

**Pull request merged**
