### PR TITLE
CHANGELOG: remove mailing list reference

### LINKED ISSUE #10669: CHANGELOG-3.2.md description confused about mininum recommended etcd versions
CHANGELOG-3.2.md says the mininum recommended etcd versions is 3.1.11+, 3.2.26+, and 3.3.11+. But the provided mail group link says  the mininum recommended etcd versions is 3.1.11+,3.2.10+,3.3.0+.  
Is there some description that does not match?

### PR DESCRIPTION
**Pull request by spzala**
Recommendations for the production were bumped up recently. The related
ML email ref is old one so we should not provide the link.

Fixes #10669

### CODE REVIEW

**Comment by jingyih** [comment]
What about changelog 3.1?

**Comment by spzala** [comment]
> What about changelog 3.1?

@jingyih I was tempted to modify 3.1. too :) but I noticed the recommendations are the same so I didn't make any change.

**Comment by jingyih** [comment]
> > What about changelog 3.1?
> 
> @jingyih I was tempted to modify 3.1. too :) but I noticed the recommendations are the same so I didn't make any change.

Should the recommended versions in changelog 3.1 be updated to the same? I think we should keep the recommended versions the same across these 3 changelogs, otherwise it might cause confusion.

**Comment by spzala** [comment]
@jingyih yes but not sure if there was any specific reason 3.1 changelog wasn't modified earlier. @hexfusion the versions were updated made under https://github.com/etcd-io/etcd/pull/10396  - was there any reason for not updating 3.1? should we keep all of them the same? Thanks!

**Comment by hexfusion** [comment]
I agree with @jingyih this should be standard for each release it was an oversight by me as we did not release a 3.1 patch at that time. As we reference later minor versions in the doc it should be accurate.

**Comment by spzala** [comment]
@hexfusion @jingyih thanks! Updated 3.1 changelog.

**Comment by jingyih** [comment]
lgtm. Thanks for fixing this!

**Comment by spzala** [comment]
@hexfusion @jingyih yrw, and thank you! Since build failure is not related, I guess we can merge it?

**Comment by hexfusion** [comment]
This change is unrelated to test failures.

**Comment by spzala** [comment]
Thanks @hexfusion

**Pull request merged**
