### PR TITLE
[3.5] [serverWatchStream] terminate recvLoop on sws.close()

### PR DESCRIPTION
**Pull request by veshij**
Backport of https://github.com/etcd-io/etcd/pull/18739 to 3.5

### CODE REVIEW

**Comment by ahrtr** [comment]
@ivanvc @jmhbnz do you know why the integration test on arm64 being blocked?

**Review by serathius — APPROVED** [review]

**Comment by ivanvc** [comment]
> @ivanvc @jmhbnz do you know why the integration test on arm64 being blocked?

It looks like we don't have the actuated runners available anymore. They were supposed to be available until the end of the month. @jmhbnz mentioned it in https://github.com/kubernetes/test-infra/pull/33715. We're working on migrating the ARM64 workloads to the prow infra. I spotted the release-3.5 branch, which James will work on ( https://github.com/kubernetes/test-infra/pull/33715#pullrequestreview-2390068301).

**Comment by ahrtr** [comment]
> > @ivanvc @jmhbnz do you know why the integration test on arm64 being blocked?
> 
> It looks like we don't have the actuated runners available anymore. They were supposed to be available until the end of the month. @jmhbnz mentioned it in [kubernetes/test-infra#33715](https://github.com/kubernetes/test-infra/pull/33715). We're working on migrating the ARM64 workloads to the prow infra. I spotted the release-3.5 branch, which James will work on ( [kubernetes/test-infra#33715 (review)](https://github.com/kubernetes/test-infra/pull/33715#pullrequestreview-2390068301)).

Thanks for the clarification. The arm64 support should be available until we finish migration all of them, including main and all stable releases, to prow.

We need to unblock the PRs for 3.5.

**Comment by ivanvc** [comment]
> Thanks for the clarification. The arm64 support should be available until we finish migration all of them, including main and all stable releases, to prow.
> 
> We need to unblock the PRs for 3.5.

I'm not sure if that's something you can request from the CNCF. From looking at the error message, it seems like we don't have runners available anymore (https://github.com/etcd-io/etcd/actions/runs/11528005687/job/32094556498?pr=18784):
> This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.

I can work tomorrow on migrating the ARM64 integration tests from the release-3.5 branch. Therefore, the jobs will run on the prow infra instead.

**Comment by ahrtr** [comment]
> I can work tomorrow on migrating the ARM64 integration tests from the release-3.5 branch. Therefore, the jobs will run on the prow infra instead.

Thanks.

**Comment by ivanvc** [comment]
/retitle [3.5] [serverWatchStream] terminate recvLoop on sws.close()

**Comment by ivanvc** [comment]
Hi @ahrtr, James and I worked today to enable the ARM64 prow jobs. The CI for this pull request will be broken until #18802 is merged and this PR is rebased.

**Review by ivanvc — APPROVED** [review]
From a backport point of view, it LGTM. Thanks, @veshij.

**Comment by ahrtr** [comment]
> Hi @ahrtr, James and I worked today to enable the ARM64 prow jobs. The CI for this pull request will be broken until #18802 is merged and this PR is rebased.

Thank you both! @ivanvc @jmhbnz

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Comment by ahrtr** [comment]
Link to https://github.com/etcd-io/etcd/issues/18704

**Pull request merged**
