### PR TITLE
etcdserver: Restructure storage packages to make place for schema

### PR DESCRIPTION
**Pull request by serathius**
cc @ptabor

### CODE REVIEW

**Comment by serathius** [comment]
cc @wenjiaswe @jingyih

**Comment by gyuho** [comment]
@serathius @ptabor This is pretty big change. What's the context? Also, we need to document this in the CHANGELOG.

**Comment by serathius** [comment]
@gyuho is renaming package considered a big change (not counting a number of lines changed)? It just an `git mv` and `sed` to rename imports.  

As for CHANGELOG, what kind of changes we document there? I would expect that changelog should include user facing changes, is renaming package withing `server` package a user facing change? I would expect it true for `api` package, but not for `server`. Please let me know if I'm missing something.

Context: We are introducing an versioning of storage as proposed in https://github.com/etcd-io/etcd/issues/13168. To properly version fields stored in bbolt we need to abstract logic that marshals field values into bytes stored in bbolt. This PR moves `mvcc` package as subpackage of new `storage` package to create place for higher level abstraction that will be aware of storage version.

Even without storage version effort I think that moving all file manipulation under single package is an improvement to package structure.

**Review by ptabor — APPROVED** [review]

**Comment by gyuho** [comment]
@serathius 

> As for CHANGELOG, what kind of changes we document there? I would expect that changelog should include user facing changes, is renaming package within server package a user facing change?

Please update CHANGELOG. We should try to document any changes made to the public packages (unless we move this to `internal`) -- the package `mvcc` is used for benchmark tools.

LGTM thanks.

**Comment by serathius** [comment]
PTAL @gyuho @ptabor

**Review by lilic — APPROVED** [review]
lgtm

**Comment by gyuho** [comment]
lgtm thanks @serathius !

**Pull request merged**
