### PR TITLE
Update go version to 1.21.8

### PR DESCRIPTION
**Pull request by liangyuanpeng**
Changes:

- Update go version to 1.21.8 for better security.

/hold

Fixes:  #17533

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by jmhbnz — COMMENTED** [review]
Suggest putting changelog entries as a separate pr. Or at minimum separate commit.

**Comment by jmhbnz** [comment]
I believe @ivanvc will be opening pr for this weeks dependency updates tomorrow as per https://github.com/etcd-io/etcd/pull/17428#issuecomment-1979731566.

We definitely need help in future with dependencies, we have instructions and a rotation worksheet here: https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md

**Comment by ahrtr** [comment]
Superseded by https://github.com/etcd-io/etcd/pull/17393

**Pull request closed without merging**
