### PR TITLE
Revert "Remove mixin from Doc"

### PR DESCRIPTION
**Pull request by spzala**
The kube-prometheous had a PR merged updating the new mixin location https://github.com/prometheus-operator/kube-prometheus/pull/932  However, for time being, they requested to keep mixin at both places (docs and contrib) until they work out their back compatibility. 

Reverts etcd-io/etcd#12687

### CODE REVIEW

**Comment by matkapi** [comment]
thank you @spzala

**Comment by underrun** [comment]
mitigation has been made in kube-prometheus to handle this - thanks for juggling locations!

etcd-mixin _should_ be safe to remove from Documentation now

**Comment by spzala** [comment]
@underrun awesome, thanks, we will remove the doc then to keep it clean!

**Pull request merged**
