### PR TITLE
embed: Fix HTTPs -> HTTPS in error message

### PR DESCRIPTION
**Pull request by CydeWeys**

### CODE REVIEW

**Comment by spzala** [comment]
@CydeWeys thanks for the PR. Please update your commit title in a similar format as PR title i.e. with `embed:` prefix to pass the build failure. Thanks!

**Comment by CydeWeys** [comment]
Done.

**Comment by spzala** [comment]
lgtm

**Comment by hexfusion** [comment]
failure not related

**Comment by spzala** [comment]
We are using `HTTPS` other places in doc so going ahead with merge, @hexfusion thanks for quick look at it and restarting travis!

**Pull request merged**
