### PR TITLE
etcdserver: separate raft log compact from snapshot 

### PR DESCRIPTION
**Pull request by clement2026**
Part of  #17098

## Key Changes

* Added a new function `compactRaftLog` for raft log compaction.
* Introduce 2 variables: `RaftLogCompactionStep` and `DefaultRaftLogCompactionStep` to manage how often the raft log is compacted.
* Refactor some existing tests. These tests previously expected a compaction immediately after a snapshot to ensure a snapshot was sent to followers. This PR broke those tests, so I modified them to ensure they still work.
* Add unit and integration tests for this PR.

- [ ] Blocked by #18494

### CODE REVIEW

**Comment by clement2026** [comment]
# Benchmark Summary

Here are the benchmark results for compacting the raft log every time `applied index` increases by 1, 10, 100, and 1000 (let's call this "step").

| Branch            |       | Throughput       |
|-------------------|-------|------------------|
| main(as the base) | read  | -                |
|                   | write | -                |
| step_1            | read  | [2.86%, 17.00%]  |
|                   | write | [3.02%, 16.75%]  |
| step_10           | read  | [2.82%, 16.53%]  |
|                   | write | [2.98%, 16.95%]  |
| step_100          | read  | [-2.09%, 9.77%]  |
|                   | write | [-1.00%, 10.93%] |
| step_1000         | read  | [-4.13%, 7.27%]  |
|                   | write | [-4.91%, 7.65%]  |
| main again        | read  | [-4.19%, 7.39%]  |
|                   | write | [-4.41%, 9.03%]  |

Throughput performs best when the step is 1 or 10. There isn’t much difference between the two. I've set the default step value to 10 in the code.

**Comment by clement2026** [comment]
## Benchmark Details

Here's how I ran the benchmark:
1. Run benchmark on `main`, `step_1`, `step_10`, `step_100`, `step_1000` and `main` branch in that order. 
2. Reboot the OS between each run.
3. Collect .csv files and generate the heat maps.

### step_1 vs main
Compact raft log every time `applied index` increases by 1.

step_1_read

### step_10  vs main
Compact raft log every time `applied index` increases by 10.

step_10_read

### step_100  vs main
Compact raft log every time `applied index` increases by 100.

step_100_read

### step_1000  vs main
Compact raft log every time `applied index` increases by 1000.

step_1000_read

### main vs main
Re-run benchmarks on the main branch to ensure results are consistent

main_2_read

### step_1 vs step_10
Since the benchmark results for step_1 and step_10 are pretty close, here I compare them to see the difference:

step_1-vs-step_10_read


---

GitHub workflow: https://github.com/clement2026/etcd-benchmark-action/actions/runs/10424407957

The archive containing .csv files and the script: [etcd-benchmark-20240817-06-00-29.zip](https://github.com/user-attachments/files/16644019/etcd-benchmark-20240817-06-00-29.zip)

The benchmark was run on a cloud VM with:
* 16GB RAM
* 8 vCPUs
* 150GB NVMe SSD
* Ubuntu 24.04 LTS x64

**Comment by clement2026** [comment]
# Reason for the failure
The robustness test failed at `panic("need non-empty snapshot")` in the raft library. 

This happens before the leader creates any snapshot, and `raftStorage.ents` has already been compacted and lacks the entries a slow follower needs. So, the slow follower requests a snapshot instead, causing the leader to panic.

https://github.com/etcd-io/raft/blob/ba8d7e340d530ae106118f059d3da4d89f933d23/raft.go#L662C1-L689
```go
// maybeSendSnapshot fetches a snapshot from Storage, and sends it to the given
// node. Returns true iff the snapshot message has been emitted successfully.
func (r *raft) maybeSendSnapshot(to uint64, pr *tracker.Progress) bool {
	if !pr.RecentActive {
		r.logger.Debugf("ignore sending snapshot to %x since it is not recently active", to)
		return false
	}


	snapshot, err := r.raftLog.snapshot()
	if err != nil {
		if err == ErrSnapshotTemporarilyUnavailable {
			r.logger.Debugf("%x failed to send snapshot to %x because snapshot is temporarily unavailable", r.id, to)
			return false
		}
		panic(err) // TODO(bdarnell)
	}
	if IsEmptySnap(snapshot) {
		panic("need non-empty snapshot")
	}
	sindex, sterm := snapshot.Metadata.Index, snapshot.Metadata.Term
	r.logger.Debugf("%x [firstindex: %d, commit: %d] sent snapshot[index: %d, term: %d] to %x [%s]",
		r.id, r.raftLog.firstIndex(), r.raftLog.committed, sindex, sterm, to, pr)
	pr.BecomeSnapshot(sindex)
	r.logger.Debugf("%x paused sending replication messages to %x [%s]", r.id, to, pr)


	r.send(pb.Message{To: to, Type: pb.MsgSnap, Snapshot: &snapshot})
	return true
}
```

# Visualization
Here are some images to help us understand the situation better.

### Main branch
Compaction only happens right after a snapshot is created. 

Untitled-2024-08-16-18062

### This PR
Compaction can happen before a snapshot is created. 

Untitled-2024-08-16-1806 3

# Solutions
* Modify the implementation of `func (r *raft) maybeSendSnapshot(to uint64, pr *tracker.Progress) bool` to send an empty snapshot instead of causing a panic. However, I’m not sure about the expected behavior or potential risks.
* Ensure a snapshot is created if it doesn’t exist when etcd starts up. This might sound silly, I know 😂

I'm stumped right now. Any ideas would be awesome!

**Comment by serathius** [comment]
> Ensure a snapshot is created if it doesn’t exist when etcd starts up. This might sound silly, I know

Sounds reasonable. We are separating mechanisms for raft log compaction and snapshots, meaning that now we need to guarantee that snapshot is always available. Creating empty snapshot at the etcd start sounds like a good first iteration.

**Comment by clement2026** [comment]
> Sounds reasonable. We are separating mechanisms for raft log compaction and snapshots, meaning that now we need to guarantee that snapshot is always available. Creating empty snapshot at the etcd start sounds like a good first iteration.

Thank you for the info! I'll give this a shot and open a new PR soon.

**Comment by ahrtr** [comment]
> Compaction can happen before a snapshot is created.
> 
> Untitled-2024-08-16-1806 3

leader sending a snapshot means that the leader sends the whole bbolt db snapshot. It doesn't care about what's the current applied index the follower is.

**Comment by clement2026** [comment]
@ahrtr the image isn't loading; It's not set to public: https://private-user-images.githubusercontent.com/27894831/358932866-df2dbdb7-2165-492c-93b8-907e09651fd4.png


> leader sending a snapshot means that the leader sends the whole bbolt db snapshot. It doesn't care about what's the current applied index the follower is.

Though the leader doesn't care about the follower, the leader itself can panic before sending out the snapshot.

Before sending a snapshot to a follower,  the leader runs `maybeSendSnapshot()` and may panic here:

https://github.com/etcd-io/raft/blob/ba8d7e340d530ae106118f059d3da4d89f933d23/raft.go#L678-L680

```go
	if IsEmptySnap(snapshot) {
		panic("need non-empty snapshot")
	}
```

All the leader wants is actually a bbolt db snapshot, not a raft log snapshot. But it seems I can't walk around `maybeSendSnapshot()` as it's part of the raft mechanism.

**Comment by ahrtr** [comment]
> Though the leader doesn't care about the follower, the leader itself can panic before sending out the snapshot.
> 
> Before sending a snapshot to a follower, the leader runs `maybeSendSnapshot()` and may panic here:
> 
> https://github.com/etcd-io/raft/blob/ba8d7e340d530ae106118f059d3da4d89f933d23/raft.go#L678-L680
> 
> ```go
> 	if IsEmptySnap(snapshot) {
> 		panic("need non-empty snapshot")
> 	}
> ```

It's concerning we mix a potential bug with enhancement. Can you raise a separate issue to clearly clarify how to reproduce the issue?

**Comment by clement2026** [comment]
> It's concerning we mix a potential bug with enhancement. Can you raise a separate issue to clearly clarify how to reproduce the issue?

Sure, I'll create the issue a bit later.

**Comment by clement2026** [comment]
After chatting with serathius, I've realized this PR isn’t needed anymore. I'll keep working on https://github.com/etcd-io/etcd/issues/17098 in a new PR.
Closing this.

**Pull request closed without merging**
