### PR TITLE
Backport 15656 to release-3.5

### PR DESCRIPTION
**Pull request by mitake**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This PR backports #15656 to release-3.5

cc @serathius @ahrtr @spzala

### CODE REVIEW

**Comment by ahrtr** [comment]
Will take a look after the workflow failures are resolved.

**Review by jmhbnz — APPROVED** [review]
LGTM

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @mitake

**Comment by ahrtr** [comment]
@mitake Please add changelog item for both 3.5 and 3.4, thx

**Pull request merged**
