### PR TITLE
tool: save test parameters in mixed read/write benchmark script.

### PR DESCRIPTION
**Pull request by wilsonwang371**
modified script to include test parameters inside the output csv file so that we can get more information out of the test.

### CODE REVIEW

**Comment by wilsonwang371** [comment]
This is a performance testing of yesterday's main branch vs. branch two days ago.

I am not exactly sure about the commit number. In case needed, we can run this again to get a better understanding of the performance.

Since now I set the mixed read/write script to use range operations with a limit of 100 entries, the number of total read operations done gets reduced.

result

**Comment by wilsonwang371** [comment]
collected data with this patch.
[mix-beta3.csv](https://github.com/etcd-io/etcd/files/6549334/mix-beta3.csv)
[mix-main.csv](https://github.com/etcd-io/etcd/files/6549335/mix-main.csv)

**Comment by ptabor** [comment]
That's cool. 

Just a few readability suggestions 

- 'delta' to me suggests B-A. 
  I would consider `Gain` or `Improvement` or `Ratio` or `B/A` or `mix-main.csv÷result.csv` . 

- I slightly prefer `-0.15` than `-15.0%`, but if we go for percentages, I think we should put `%` symbol near each of the values.

**Comment by wilsonwang371** [comment]
result

@ptabor please take a look at the new graph

**Comment by ptabor** [comment]
Awesome. Forgive me 2 more ideas: 
  - can you make '0' to be always white for 'gain' such that 'red' is OK, and blue is a 'warning' signal. 
  - can `git log --pretty=format:'%h' -n 1` be part of the 'env' description: `key_size=..., .... ,..., commit=4af7fc393`

**Comment by wilsonwang371** [comment]
> Awesome. Forgive me 2 more ideas:
> 
> * can you make '0' to be always white for 'gain' such that 'red' is OK, and blue is a 'warning' signal.
> * can `git log --pretty=format:'%h' -n 1` be part of the 'env' description: `key_size=..., .... ,..., commit=4af7fc393`

Tested and I can see the commit id get generated:

`key_size=256,key_space_size=65536,backend_size=21474836480,range_limit=100,commit=d6bc743e2`

Also, here is the new graph generated. I used a flag in the script to enable zero-centered plot.

result

**Comment by ptabor** [comment]
Thank you. 
Final question: Is there a reason why the first row compares 0.0070 ratio to 0.0078 ration ? I assume its an artifact of how the *.csv data were collected in the first place and in case of 'healthy' input data the rows would be consistent.

**Comment by wilsonwang371** [comment]
> Thank you.
> Final question: Is there a reason why the first row compares 0.0070 ratio to 0.0078 ration ? I assume its an artifact of how the *.csv data were collected in the first place and in case of 'healthy' input data the rows would be consistent.

Actually, it was because previous data was generated with a different float number precision. This won't happen with the latest code and it will always be 0.0078.

**Pull request merged**
