### PR TITLE
Release-3.5: server/etcdmain: add configurable cipher list to gRPC proxy listener

### PR DESCRIPTION
**Pull request by dusk125**
This is a backport of #14308

### CODE REVIEW

**Comment by ahrtr** [comment]
Please fix the fmt & test error. 

Usually we only backport bug fix to stable release, but exposing secure ciphers is a common and important part of any service, so It's OK to backport it.

**Comment by ahrtr** [comment]
Please also remove the CHANGELOG item from 3.6 and add a new item for changelog-3.5.  FYI. https://github.com/etcd-io/etcd/pull/14476#issuecomment-1249192558

**Comment by dusk125** [comment]
Changelog PR [here](https://github.com/etcd-io/etcd/pull/14524). Quick question, I'm planning on backporting this change to 3.4, should I just wait to update the changelog until I get that PR open, or should we go through this and #14524 and when I have the 3.4 PR just open another for moving the changelog item from 3.5 to 3.4?

**Comment by ahrtr** [comment]
1. It's OK to backport this PR to both 3.5 and 3.4 to me, but we still need other maintainers' approval.
2. Based on https://github.com/etcd-io/etcd/pull/14476#issuecomment-1249192558 , eventually we need to add changelog items for both 3.4 and 3.5.

**Comment by dusk125** [comment]
> 1. It's OK to backport this PR to both 3.5 and 3.4 to me, but we still need other maintainers' approval.
> 2. Based on [Changelog: add item into 3.6 for the fix on panic in readonly serializable txn #14476 (comment)](https://github.com/etcd-io/etcd/pull/14476#issuecomment-1249192558) , eventually we need to add changelog items for both 3.4 and 3.5.

Sounds good, thanks!

**Review by spzala — COMMENTED** [review]
lgtm. Re-running failed tests.

**Review by ahrtr — APPROVED** [review]
LGTM 

Thanks both @dusk125 and @spzala

**Pull request merged**
