### PR TITLE
[3.5] Backport updates for opentelemetry dependencies.

### PR DESCRIPTION
**Pull request by jmhbnz**
The dependency updates include a fix (https://github.com/open-telemetry/opentelemetry-go/commit/1f4b606be8921c4e2193c0059e99d86d8b98bdd9) for ipv6 parsing for the `net_host_name` attribute/label in etcd metrics which are currently not displaying correctly for IPv6.

Fixes: #15400

### CODE REVIEW

**Comment by jmhbnz** [comment]
Note: Leaving in draft as I am still figuring out how to test that this actually resolves the label issue. Steps I am currently following are:

1. Compile and run etcd using ipv6 via `./bin/etcd --listen-client-urls 'http://[::1]:2379' --advertise-client-urls 'http://[::1]:2379'` which starts as expected.

2. Spin up a local prometheus instance `docker run -p 9090:9090 --network=host -v ./prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus` with a scrape config to reach etcd with ipv6 local address:
```yaml
scrape_configs:
  - job_name: 'etcd'
    scrape_interval: 5s
    static_configs:
      - targets: ['[::1]:2379']
    metrics_path: '/metrics'
```
3. Open prometheus at `localhost:9090` and check the `etcd_server_is_leader` metric which returns `etcd_server_is_leader{instance="[::1]:2379", job="etcd"}` so doesn't include the `net_host_name` attribute.  I'm wondering if this attribute is only present when running in k8s?

**Comment by jmhbnz** [comment]
Hey @dashpole - I'm a bit stuck trying to get an open telemetry collector running specifically for etcd.

I've spun up the otel collector [demo environment](https://opentelemetry.io/docs/collector/getting-started/#demo).

I then start etcd with `--experimental-enable-distributed-tracing=true`.

Opening the bundled demo prometheus console I don't see any metrics for etcd and my hunch is I need to be updating the `otel-collector-config.yaml` file somehow to specify that I want to get metrics from etcd, reading the docs I'm struggling to get my head around this.

Do you have any etcd specific experience with getting this collector working?

**Comment by dashpole** [comment]
Etcd uses OpenTelemetry for tracing, not metrics, so you won't find anything in prometheus.  You would need to run jaeger, or something similar to see traces coming from etcd.  If you have etcd running locally, try following this: https://www.jaegertracing.io/docs/1.46/getting-started/.  The OTLP grpc port is 4317, which is also where etcd should send traces by default.

See https://kubernetes.io/blog/2021/09/03/api-server-tracing/#enabling-etcd-tracing for the flags I would recommend setting on etcd.

**Comment by jmhbnz** [comment]
Closing - I have competing priorities at the moment and have not had time to return to this.

**Pull request closed without merging**
