### PR TITLE
Fix link for maintainers role and responsibilities in README.md

### LINKED ISSUE #15671: Fix link for maintainers role and responsibilities in readme
### What happened?

We merged https://github.com/etcd-io/etcd/pull/15593 this week. One of the key changes was extracting the community membership to a separate file and moving maintainer role info from `GOVERNANCE.md` to that new file.

In our project `README.md` we have the following paragraph:

> ### Maintainers
> [MAINTAINERS](https://github.com/etcd-io/etcd/blob/main/MAINTAINERS) strive to shape an inclusive open source project culture where users are heard and contributors feel respected and empowered. MAINTAINERS maintain productive relationships across different companies and disciplines. Read more about [MAINTAINERS role and responsibilities](https://github.com/etcd-io/etcd/blob/main/GOVERNANCE.md#maintainers).

The maintainers roles and responsibilities link needs to be updated to point to https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md#maintainers 

### What did you expect to happen?

Links should go to the right place.

### How can we reproduce it (as minimally and precisely as possible)?

1) View project `README.md`
2) Click link for Maintainers roles and responsibilities
3) Be taken to `GOVERNANCE.md` which no longer contains this content.

### Anything else we need to know?

We should think about updating the main project readme contributing section to also mention and link to our new community membership page.

### PR DESCRIPTION
**Pull request by HeavenTonight**
Signed-off-by: guiyong.ou [guiyong.ou@daocloud.io](mailto:guiyong.ou@daocloud.io)
fixed #15671 
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by jmhbnz — COMMENTED** [review]
Hey @HeavenTonight thanks for fixing this :)

Can you please also consider my suggestion at the bottom of the github issue:

> We should think about updating the main project readme contributing section to also mention and link to our new community membership page.

I think it would be nice to also have a quick sentence added to the contributing section that points people to the new guide, perhaps something like:

```diff
See [CONTRIBUTING](https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md) for details on setting up your development environment, submitting patches and the contribution workflow.
+ Please refer to [community-membership.md](Documentation/contributor-guide/community-membership.md#members) for information on becoming an etcd project member.  We welcome and look forward to your contributions to the project!
```

Maintainers may have some feedback on that wording.

**Comment by HeavenTonight** [comment]
> Hey @HeavenTonight thanks for fixing this :)↳
> 
> Can you please also consider my suggestion at the bottom of the github issue:
> 
> 您能否也考虑一下我在 github 问题底部的建议：
> 
> > We should think about updating the main project readme contributing section to also mention and link to our new community membership page.我们应该考虑更新主要项目自述文件贡献部分，以提及并链接到我们新的社区成员页面。
> 
> I think it would be nice to also have a quick sentence added to the contributing section that points people to the new guide, perhaps something like:
> 
> 我认为最好在贡献部分添加一个简短的句子，将人们指向新指南，也许是这样的：
> 
> ```diff
> See [CONTRIBUTING](https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md) for details on setting up your development environment, submitting patches and the contribution workflow.
> + Please refer to [community-membership.md](Documentation/contributor-guide/community-membership.md#members) for information on becoming an etcd project member.  We welcome and look forward to your contributions to the project!
> ```
> 
> Maintainers may have some feedback on that wording.
> 
> 维护者可能对该措辞有一些反馈。
thanks for your suggestion! it`s great

**Review by ahrtr — APPROVED** [review]
LGTM

**Review by jmhbnz — APPROVED** [review]

**Review by ahrtr — APPROVED** [review]
LGTM

**Pull request merged**
