### PR TITLE
Automated cherry pick of #11652 #11670 #11699 #11710

### PR DESCRIPTION
**Pull request by tangcong**
Cherry pick of #11652 #11670 #11699 #11710 on release-3.4.

#11652: *: fix auth revision corruption bug
#11670: auth: print warning log when error is ErrAuthOldRevision
#11699: *: refactor consistent index
#11710: auth: ensure RoleGrantPermission is compatible with older

### CODE REVIEW

**Comment by tangcong** [comment]
#11652 fix a data corruption bug when restarting etcd,but the old consistent index implementation is not elegant to call.
#11699 refactor  consistent index to make the code look more concise and elegant.

**Comment by tangcong** [comment]
ci failed to pass due to no space left on device.

**Comment by jingyih** [comment]
I prefer we do not backport #11699. It was recently merged and we do not have enough soak time. Ideally we should ensure each patch release is strictly better. Backporting code refactor code adds more risk which overweights the gain in my opinion.

**Comment by gyuho** [comment]
Agree with @jingyih. Refactored code doesn't need be backported.

**Comment by tangcong** [comment]
thanks. i see. i will close this pr and submit another pr.

**Pull request closed without merging**
