### PR TITLE
mvcc/kvstore: Optimize compaction

### PR DESCRIPTION
**Pull request by shenjiangc**
mvcc/kvstore: Optimize compaction

when the number of key-value index is greater than one million, compact take too long and blocks other requests.
Move the “kvindex.Compact” to  “fifoSched.Schedule” func

### CODE REVIEW

**Comment by jingyih** [comment]
Could you elaborate how this change helps? This is still the same amount of work but is done at a different time? Do you have test data showing the improvement? Thanks!

Also if we move index compaction to the scheduled FIFO, we need to adjust the metric "indexCompactionPauseMs" accordingly.

**Comment by shenjiangc** [comment]
> Could you elaborate how this change helps? This is still the same amount of work but is done at a different time? Do you have test data showing the improvement? Thanks!
> 
> Also if we move index compaction to the scheduled FIFO, we need to adjust the metric "indexCompactionPauseMs" accordingly.

Yes, Just let index compact do in another goroutine。

first，I put 1000000 or more key-value：
./tools/benchmark  --target-leader --conns=50 --clients=50 put --key-size=64 --sequential-keys --total=5000000 --val-size=256 --key-space-size=5000000 

then，i do compact use：
rev=$(./etcdctl --endpoints=http://127.0.0.1:2379 endpoint status --write-out="json" | egrep -o '"revision":[0-9]*' | egrep -o '[0-9].*') ; echo $rev
 ./etcdctl --endpoints=http://127.0.0.1:2379 compact $rev
the compaction took more than 1 sec。

when the compact is going on， the other new put request is blocked, and Completion delay > 1 sec.  The reason is the index compact took too time to  assign map[]，when the tree is big enough。

Move index compaction to the scheduled FIFO， let the compaction don't block the new request。

TEST ：（put 5 key，when compacting）
Before Modification：
#./tools/benchmark  --target-leader --conns=1 --clients=1 put --key-size=64 --sequential-keys --total=5 --val-size=256 --key-space-size=5
Summary:
  Total:	2.9459 secs.
  Slowest:	2.9445 secs.
  Fastest:	0.0002 secs.
  Average:	0.5892 secs.
  Stddev:	1.1776 secs.
  Requests/sec:	1.6973
Response time histogram:
  0.0002 [1]	|∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.2947 [3]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.5891 [0]	|
  0.8835 [0]	|
  1.1779 [0]	|
  1.4723 [0]	|
  1.7668 [0]	|
  2.0612 [0]	|
  2.3556 [0]	|
  2.6500 [0]	|
  2.9445 [1]	|∎∎∎∎∎∎∎∎∎∎∎∎∎

After Modification：
# ./tools/benchmark  --target-leader --conns=1 --clients=1 put --key-size=64 --sequential-keys --total=5 --val-size=256 --key-space-size=5
 Summary:
  Total:	0.0028 secs.
  Slowest:	0.0014 secs.
  Fastest:	0.0003 secs.
  Average:	0.0005 secs.
  Stddev:	0.0004 secs.
  Requests/sec:	1783.4436

Response time histogram:
  0.0003 [1]	|∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.0004 [3]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.0005 [0]	|
  0.0006 [0]	|
  0.0007 [0]	|
  0.0009 [0]	|
  0.0010 [0]	|
  0.0011 [0]	|
  0.0012 [0]	|
  0.0013 [0]	|
  0.0014 [1]	|∎∎∎∎∎∎∎∎∎∎∎∎∎

**Comment by jingyih** [comment]
Thanks for doing benchmark testing!

With this change, when the actual index compaction happens later, it will still block other requests such as put request. Is my understanding correct?

**Comment by shenjiangc** [comment]
With this modification, compaction will no longer block other request messages。;)

**Comment by jingyih** [comment]
> With this modification, compaction will no longer block other request messages。;)

Sorry I don't quite understand. This modification basically postponed the compaction work in index tree to a later time. So I can understand the compaction request does not block other requests immediately. But later when the actual compaction work happens, it has the same effect on other requests, right?

**Comment by shenjiangc** [comment]
Hi,
The etch process normal request messages such as put/get/compact in the same goroute “go run()”. When it is processing compact,it will can’t process other messages. The fifo scheduler is another goroute.  So I move the index compact to fifo scheduler, to let the goroute “go run()” to process the next request as soon.

**Comment by jingyih** [comment]
Thanks I see your point. My previous thinking was that the index compaction does hold a write lock most of the time during its execution, so it blocks other request (which also need read or write the same index tree) anyway.

Another potential concern is the function returns w/o actually doing the compaction work in index tree (because it is just scheduled). So depends on when the index compaction happens, the returned "keep" could be different, meaning the keys to be deleted in the data base is different. I don't think there are any correctness concerns, but it makes consistency checking among nodes more difficult. - not completely sure about what I said here, need some time to read and think through.

**Comment by WIZARD-CXY** [comment]
@jingyih I understand your concern. why do we use this as consistency checking?  I think we can allow different etcd node have a little different boltdb state.

**Comment by WIZARD-CXY** [comment]
@shenjiangc 
>The etcd process normal request messages such as put/get/compact in the same goroute “go run()”. ??
can you show the code?

**Comment by jingyih** [comment]
> I think we can allow different etcd node have a little different boltdb state.

Do you mean for the same store revision and compact revision, we allow boltdb on each member to have different state? If this is the case, it might be difficult to do consistency checking among members in the same cluster. Today we can use this API to make sure members stay consistent:
https://github.com/etcd-io/etcd/blob/b5afbdd8d0e3098b3d7038fc1e4241de3de494d3/etcdserver/corrupt.go#L353

**Comment by WIZARD-CXY** [comment]
@jingyih yeah If we enable corrupt check, It may cause the etcd server can not start since peer's hash not match. But in fact I don't enable it...

**Comment by jingyih** [comment]
> So depends on when the index compaction happens, the returned "keep" could be different, meaning the keys to be deleted in the data base is different.

I think my previous statement was wrong. "keep" does not depend on key modifications after compaction rev.

So this should be safe.

**Comment by jingyih** [comment]
This conflicts with the tracing we recently added in #11179. 

@YoyinZyc Could you help take a look? If we move the compaction of in-memory index to scheduled, can we still time it? Or maybe we need to drop the corresponding step?

`trace.Step("compact in-memory index tree")`

**Comment by jingyih** [comment]
Oh actually we also need to adjust the calculation of metrics `indexCompactionPauseMs`.

**Comment by YoyinZyc** [comment]
> This conflicts with the tracing we recently added in #11179.
> 
> Yuchen Zhou Could you help take a look? If we move the compaction of in-memory index to scheduled, can we still time it? Or maybe we need to drop the corresponding step?
> 
> `trace.Step("compact in-memory index tree")`

We can remove this step in that case. It will be timed with the backend together as a whole scheduled job.

**Comment by jingyih** [comment]
@shenjiangc Could you please rebase to current master? And then:
1. remove `trace.Step("compact in-memory index tree")`.
2. move the calculation of "indexCompactionPauseMs" to the scheduled function. It is used to measure the duration of `s.kvindex.Compact(rev)`.

**Comment by shenjiangc** [comment]
> @shenjiangc Could you please rebase to current master? And then:
> 
> 1. remove `trace.Step("compact in-memory index tree")`.
> 2. move the calculation of "indexCompactionPauseMs" to the scheduled function. It is used to measure the duration of `s.kvindex.Compact(rev)`.

I made some mistacks, the new pull request is https://github.com/etcd-io/etcd/pull/11330 , Please take a look。

**Pull request closed without merging**
