### PR TITLE
Fix the data inconsistency by moving the SetConsistentIndex into the transaction lock

### PR DESCRIPTION
**Pull request by ahrtr**
Try to fix [13766](https://github.com/etcd-io/etcd/issues/13766).

### CODE REVIEW

**Comment by ahrtr** [comment]
The [SetConsistentIndex](https://github.com/etcd-io/etcd/blob/be2929568f81080b20ef6812992f2e09c8dac91b/server/etcdserver/server.go#L1804) and the [applyV3.Apply](https://github.com/etcd-io/etcd/blob/be2929568f81080b20ef6812992f2e09c8dac91b/server/etcdserver/server.go#L1856) are supposed to be an atomic operation, obviously there aren't. It should be a real issue. 

But I can still reproduce the data inconsistency issue with this PR. So this PR isn't a complete fix. 
```

   logger.go:130: 2022-03-28T00:01:28.981-0700	INFO	tester	received response	{"operation": "INITIAL_START_ETCD", "from": "127.0.0.1:3379", "success": false, "status": "\"INITIAL_START_ETCD\" is not valid; last server operation was \"INITIAL_START_ETCD\""}
    logger.go:130: 2022-03-28T00:01:28.981-0700	INFO	tester	received response	{"operation": "INITIAL_START_ETCD", "from": "127.0.0.1:2379", "success": false, "status": "\"INITIAL_START_ETCD\" is not valid; last server operation was \"INITIAL_START_ETCD\""}
    logger.go:130: 2022-03-28T00:01:28.981-0700	INFO	tester	sent request	{"operation": "INITIAL_START_ETCD", "to": "127.0.0.1:1379"}
    logger.go:130: 2022-03-28T00:01:28.982-0700	INFO	tester	received response	{"operation": "INITIAL_START_ETCD", "from": "127.0.0.1:1379", "success": false, "status": "\"INITIAL_START_ETCD\" is not valid; last server operation was \"INITIAL_START_ETCD\""}
    etcd_tester_test.go:43: Bootstrap failed {error 26 0  "INITIAL_START_ETCD" is not valid; last server operation was "INITIAL_START_ETCD", "INITIAL_START_ETCD" is not valid; last server operation was "INITIAL_START_ETCD", "INITIAL_START_ETCD" is not valid; last server operation was "INITIAL_START_ETCD"}
--- FAIL: TestFunctional (0.01s)
FAIL
FAIL: (code:1):
  % ./bin/etcd-tester --config ./tests/functional/functional.yaml -test.v
ETCD_TESTER_EXIT_CODE: 1
```

**Comment by serathius** [comment]
@ahrtr Thanks for looking into this, logs you linked are a bug in functional framework and not a prof of reproduction
```
   logger.go:130: 2022-03-28T00:01:28.981-0700	INFO	tester	received response	{"operation": "INITIAL_START_ETCD", "from": "127.0.0.1:3379", "success": false, "status": "\"INITIAL_START_ETCD\" is not valid; last server operation was \"INITIAL_START_ETCD\""}
    logger.go:130: 2022-03-28T00:01:28.981-0700	INFO	tester	received response	{"operation": "INITIAL_START_ETCD", "from": "127.0.0.1:2379", "success": false, "status": "\"INITIAL_START_ETCD\" is not valid; last server operation was \"INITIAL_START_ETCD\""}
    logger.go:130: 2022-03-28T00:01:28.981-0700	INFO	tester	sent request	{"operation": "INITIAL_START_ETCD", "to": "127.0.0.1:1379"}
    logger.go:130: 2022-03-28T00:01:28.982-0700	INFO	tester	received response	{"operation": "INITIAL_START_ETCD", "from": "127.0.0.1:1379", "success": false, "status": "\"INITIAL_START_ETCD\" is not valid; last server operation was \"INITIAL_START_ETCD\""}
    etcd_tester_test.go:43: Bootstrap failed {error 26 0  "INITIAL_START_ETCD" is not valid; last server operation was "INITIAL_START_ETCD", "INITIAL_START_ETCD" is not valid; last server operation was "INITIAL_START_ETCD", "INITIAL_START_ETCD" is not valid; last server operation was "INITIAL_START_ETCD"}
```
Means that previous state from last run was not properly cleaned up I recommend running:
```
sudo killall etcd && sudo killall etcd-agent
```

**Comment by ahrtr** [comment]
Thanks for the info. I do not get time to read through the functional test's source code so far. What's log which can prove that the issue is reproduced? 

I will continue to work on this tomorrow.

**Comment by serathius** [comment]
Please read the https://github.com/etcd-io/etcd/pull/13838#issuecomment-1079236638

**Comment by serathius** [comment]
I also recommend qualifying on the commit that first introduced the bug 50051675f9740a4561e13bc5f00a89982b5202ad as it will reduce a change of any other issues arising

**Comment by ahrtr** [comment]
Thanks @serathius & @ptabor for the feedback, which makes sense.

> It's not clear to me that it solves the root problem.

This PR is just a draft, and I was planning to quickly verify my thought.


> My current thinking:
> 
>     1. There should exist ability to wrap Backend with custom implementation that provision hooks to transaction lifecycle.
> 
>     2. Out out apply() transactions should use Backend wrapper that has no registered Hooks.
> 
>     3. The transactions in `Apply()` should use Backend that has Hooks() like currently with additional verification that
>        there was only one Unlock() per transaction called. i.e. Apply calls `hook->VerifyApplyEnd()` and `hook->VerifyApplyBegin()` or checks counters...

Exactly, I will try to get all these sorted out, and provide a more robust solution and send out for review.

**Comment by ahrtr** [comment]
> Please rerun them and look for hash inconsistency log present in one of the members. I will also try to verify this PR.


I just tried this PR on top of your PR [13838](https://github.com/etcd-io/etcd/pull/13838), and do not reproduce the data inconsistent issue. I do not reproduce the issue without this PR either. Probably it's because my local VM isn't powerful enough, which has 4 CPU (each with Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz), and 8Gb memory.  

@serathius Have you tried this PR in your workstation?

**Comment by ahrtr** [comment]
> I also recommend qualifying on the commit that first introduced the bug [5005167](https://github.com/etcd-io/etcd/commit/50051675f9740a4561e13bc5f00a89982b5202ad) as it will reduce a change of any other issues arising

Actually the root cause of this issue isn't coming from the commit [5005167](https://github.com/etcd-io/etcd/commit/50051675f9740a4561e13bc5f00a89982b5202ad). It just increases the possibility of reproducing this issue. The key point is to make sure we either support atomic operation (just one transaction/Lock & Unlock) or Reentrant transaction.

**Comment by serathius** [comment]
> @serathius Have you tried this PR in your workstation?

Yes, I was not able to reproduce the issue with this fix. I have run tests for over an hour, so I think we are ok.

> > I also recommend qualifying on the commit that first introduced the bug [5005167](https://github.com/etcd-io/etcd/commit/50051675f9740a4561e13bc5f00a89982b5202ad) as it will reduce a change of any other issues arising
> 
> Actually the root cause of this issue isn't coming from the commit [5005167](https://github.com/etcd-io/etcd/commit/50051675f9740a4561e13bc5f00a89982b5202ad). It just increases the possibility of reproducing this issue. The key point is to make sure we either support atomic operation (just one transaction/Lock & Unlock) or Reentrant transaction.

This would be very worrying, because I was not able to reproduce the issue on previous commits at all. If the issue is not caused by 50051675f9740a4561e13bc5f00a89982b5202ad then we don't have a good way to qualify our results. If the root cause is to rare to be detected then we need to improve our testing. 

@ptabor @ahrtr if 50051675f9740a4561e13bc5f00a89982b5202ad is not a root cause, do you have any inclination of when the real issue was introduced? Any idea how to improve our approach to testing to detect the issue?

**Comment by ahrtr** [comment]
> Yes, I was not able to reproduce the issue with this fix. I have run tests for over an hour, so I think we are ok.

Thanks @serathius for the feedback, it's really good news.  I will think about a formal solution/fix in the next step. 



> This would be very worrying, because I was not able to reproduce the issue on previous commits at all. If the issue is not caused by [5005167](https://github.com/etcd-io/etcd/commit/50051675f9740a4561e13bc5f00a89982b5202ad) then we don't have a good way to qualify our results. If the root cause is to rare to be detected then we need to improve our testing.
> 
> @ptabor @ahrtr if [5005167](https://github.com/etcd-io/etcd/commit/50051675f9740a4561e13bc5f00a89982b5202ad) is not a root cause, do you have any inclination of when the real issue was introduced? Any idea how to improve our approach to testing to detect the issue?

No need to worry:), I do not read through the functional test's source code so far, but I believe the reason why we do not see such issue before the commit `505167` is we do not perform operations such as periodic compaction or other operations which may call `Commit` or `ForceCommit` in functional test, or at least the frequency is really low.

**Comment by ahrtr** [comment]
> do you have any inclination of when the real issue was introduced?

The root cause is coming from [server.go#L1774](https://github.com/etcd-io/etcd/blob/27e222e2d7141e63935d36d0e3b3e8f32ff847cb/server/etcdserver/server.go#L1774) and [server.go#L1804](https://github.com/etcd-io/etcd/blob/27e222e2d7141e63935d36d0e3b3e8f32ff847cb/server/etcdserver/server.go#L1804). 

And of course the addition of `OnPreCommitUnSafe` also contributes to the root cause.

**Comment by ptabor** [comment]
> The root cause is coming from [server.go#L1774](https://github.com/etcd-io/etcd/blob/27e222e2d7141e63935d36d0e3b3e8f32ff847cb/server/etcdserver/server.go#L1774) and [server.go#L1804](https://github.com/etcd-io/etcd/blob/27e222e2d7141e63935d36d0e3b3e8f32ff847cb/server/etcdserver/server.go#L1804).

Yes. And precisely SetConsistentIndex() started to be harmful potentially when any 'Unlock' could prematurely submit transaction.  I'm not sure if it's worth to test the issue on commit in the middle of the PR, vs. the whole PR boundary, i.e #f1123d696c9f772119c04b9dee72b5b1e050f57c.

**Comment by ahrtr** [comment]
I just submitted another PR [13854](https://github.com/etcd-io/etcd/pull/13854),  so closing this one.

**Pull request closed without merging**
