### PR TITLE
check resuming len to avoid panic

### PR DESCRIPTION
**Pull request by yangxuanjia**
check resuming len to avoid panic

### CODE REVIEW

**Comment by ptabor** [comment]
Thank you for the fix. 
Have you seen this crashing in practice, or its just a defense in depth ?

**Review by ptabor — APPROVED** [review]

**Comment by xiang90** [comment]
@yangxuanjia can you change the commit message? right now it is "proxy auth".

**Comment by yangxuanjia** [comment]
> @yangxuanjia can you change the commit message? right now it is "proxy auth".

done

**Comment by xiang90** [comment]
the commit is still there. now you have three commits in one pull request. you need to squash them into one.

**Comment by yangxuanjia** [comment]
> the commit is still there. now you have three commits in one pull request. you need to squash them into one.

done again

**Pull request merged**
