### PR TITLE
Update codecov config to support commenting in PR

### PR DESCRIPTION
**Pull request by henrybear327**
- add missing directory fixing go.etcd.io/etcd/etcdutl/v3/::etcdutl/
- update codecov config to support commenting in PR

Reference: 
- https://github.com/etcd-io/etcd/issues/18131
- https://docs.codecov.com/docs/unexpected-coverage-changes#reasons-for-indirect-changes

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by henrybear327** [comment]
@serathius I was checking [other project's codecov configuration file](https://github.com/kubernetes/dashboard/blob/f5bd92216e3783aeab0d266ae973c655c30ab0f6/.github/workflows/ci.yml#L139) and [the official documentation](https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage#github-actions), we should consider putting codecov token in Github Secret (maybe we need to regenerate a new token first, but we need to have access to the codecov account, which I don't know who to ping). 

I can't do this on my own since I don't have Github Repo Setting access, so this part I might need your help to look into it!

Thanks

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @henrybear327, the preview above in this pr is looking good.

**Comment by henrybear327** [comment]
> LGTM - Thanks @henrybear327, the preview above in this pr is looking good.

Thanks for reviewing @jmhbnz! :) 

Currently, the Codecov comment is set to update the existing code coverage comment when a new commit is pushed (default behavior), instead of deleting the existing comment and creating a new one. 

Using the default behavior means that the code coverage information will likely be at the top of the comment, so PRs with long discussion threads will require some scrolling to view the code coverage information. Deleting the old one and adding a new comment with each commit will generate more email notifications though.

In order to avoid email spamming, I think it's better that we use the default behavior. 

What do you think? :)

**Comment by ahrtr** [comment]
> see 20 files with indirect coverage changes

Thanks @henrybear327 for the PR. But I am curious why the coverage decreased for many go files even this PR doesn't change any go source code?

**Comment by jmhbnz** [comment]
> In order to avoid email spamming, I think it's better that we use the default behavior.

Agreed. Let's keep it to one coverage comment per pr that is always up to date.

**Comment by henrybear327** [comment]
> > see 20 files with indirect coverage changes
> 
> Thanks @henrybear327 for the PR. But I am curious why the coverage decreased for many go files even this PR doesn't change any go source code?

@ahrtr I suspect it's due to rebasing. I will look into this!

**Comment by henrybear327** [comment]
> > > see 20 files with indirect coverage changes
> > 
> > 
> > Thanks @henrybear327 for the PR. But I am curious why the coverage decreased for many go files even this PR doesn't change any go source code?
> 
> @ahrtr I suspect it's due to rebasing. I will look into this!

This is due to [indirect changes](https://app.codecov.io/gh/etcd-io/etcd/pull/18143/indirect-changes) [1]. 

I suspect that during test coverage execution, we have some of the tests written in a way that is not deterministic. Because when I check the "indirect changes" of PRs from this [list](https://app.codecov.io/gh/etcd-io/etcd/pulls), hit/miss differences come from things like select cases (e.g. error handling, timeout, etc.), cache eviction, etc. 

Screenshot 2024-06-12 at 8 07 18 AM
Screenshot 2024-06-12 at 8 07 00 AM

So our test coverage percentage will have a small variation across runs, as you can see [here](https://app.codecov.io/gh/etcd-io/etcd/commits?branch=main).

Do you think this make sense @ahrtr?

Reference:
[1] https://docs.codecov.com/docs/unexpected-coverage-changes#reasons-for-indirect-changes

**Comment by ahrtr** [comment]
> [1] https://docs.codecov.com/docs/unexpected-coverage-changes#reasons-for-indirect-changes

Thanks for the clarification, which basically makes sense. Can you pls add a comment to include the link for reference?

**Comment by henrybear327** [comment]
> > [1] https://docs.codecov.com/docs/unexpected-coverage-changes#reasons-for-indirect-changes
> 
> Thanks for the clarification, which basically makes sense. Can you pls add a comment to include the link for reference?

Thanks @ahrtr! I have
- updated the PR description 
- updated the commit message
- added link to the discussion comment in the issue

Not sure if this is what you expected :)

**Comment by henrybear327** [comment]
> https://docs.codecov.com/docs/unexpected-coverage-changes#reasons-for-indirect-changes

No worries :) 

Done as requested! Thanks

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @henrybear327

**Pull request merged**
