### PR TITLE
[3.4] Backport clientv3: Replace balancer with upstream grpc solution

### PR DESCRIPTION
**Pull request by chaochn47**
Part of https://github.com/etcd-io/etcd/issues/16740 

This PR fully removes etcd customized implementation of gRPC old balancer API without breaking changes. 

Backported 
- #11574
- #12671 
- #12706 (stripped grpc proxy changes)
- #13203 
- #13359 (only e2e test is implemented, corresponding integration test is not deserved to be back-ported given its risk caused by large number of test code changes) 

#16826 should be merged first and this PR will be rebased on top of that.

This should allow us bump gRPC to v1.51.0 easier in release-3.4 in the follow up PR. 

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by chaochn47** [comment]
All the tests including the new added test around resolver, endpoint and proper h2 authority header passed. 

Next step would be evaluating the proxy test coverage along with the client changes~

**Comment by ahrtr** [comment]
@chaochn47 please rebase this PR. thx

**Comment by chaochn47** [comment]
@ahrtr 

This PR has been rebased. PTAL, thanks~

**Comment by ahrtr** [comment]
This is a huge PR. Could you break down this PR, such as backporting each PR in the list separately?

**Comment by chaochn47** [comment]
> This is a huge PR. Could you break down this PR, such as backporting each PR in the list separately?

It's doable. 

Just want to confirm that even if the backported PR introduces bug, it's okay to backport the fix separately, correct?

**Comment by ahrtr** [comment]
> Just want to confirm that even if the backported PR introduces bug, it's okay to backport the fix separately, correct?

I think so. The goal right now is to break down this huge PR to make the reviewing easier.

**Comment by chaochn47** [comment]
> > Just want to confirm that even if the backported PR introduces bug, it's okay to backport the fix separately, correct?
> 
> I think so. The goal right now is to break down this huge PR to make the reviewing easier.

First one is out.

**Comment by ahrtr** [comment]
@chaochn47 are you still working on backporting the last PR?

**Comment by chaochn47** [comment]
Yeah, I will help my colleague @jasdel to finish the remaining gRPC version upgrade to resolve the CVE. 

Is there a deadline so we can adjust the priorities on our TODO list?

**Comment by ahrtr** [comment]
It's a blocker for https://github.com/etcd-io/etcd/issues/16751. I expect it can be resolved asap to unblock the release of 3.4.28 (which includes fixes to two CVEs). Thanks.

**Pull request closed without merging**
