### PR TITLE
*: upgrade zap logger to 1.15, replace global logger

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by jingyih** [comment]
Thanks @gyuho! It is unclear to me what is the global zap logger in etcd?

**Comment by jingyih** [comment]
On another topic related to logger, is it still the plan to deprecate `logutil.Logger` in v3.5?

https://github.com/etcd-io/etcd/blob/93cf4492055c8b8a823a92a39567dc9e6ddca086/pkg/logutil/logger.go#L20-L21

**Comment by gyuho** [comment]
> On another topic related to logger, is it still the plan to deprecate `logutil.Logger` in v3.5?
> 
> https://github.com/etcd-io/etcd/blob/93cf4492055c8b8a823a92a39567dc9e6ddca086/pkg/logutil/logger.go#L20-L21

Yes, I believe this is only needed for gRPC.

**Comment by gyuho** [comment]
> Thanks @gyuho! It is unclear to me what is the global zap logger in etcd?

This means now we don't have to pass around `*zap.Logger` objects.

Just

```
zap.L().Info(...)
```

:)

**Comment by jingyih** [comment]
> > Thanks @gyuho! It is unclear to me what is the global zap logger in etcd?
> 
> This means now we don't have to pass around `*zap.Logger` objects.
> 
> Just
> 
> ```
> zap.L().Info(...)
> ```
> 
> :)

This is awesome!

**Pull request merged**
