### PR TITLE
*: Fix concurrent clientv3 client creation in 3.4 by using proper UUIDs

### PR DESCRIPTION
**Pull request by jpbetz**
Fixes https://github.com/etcd-io/etcd/issues/10035, which found that the `time.Now().UnixNano()` to uniquely identify clients is unsafe. Collisions can easily happen on architectures with larger timestamp steps.

Kubernetes uses `github.com/pborman/uuid` as it's UUID library, and `github.com/google/uuid` is based on it with a couple improvements, so it seemed like a solid UUID library choice.

### CODE REVIEW

**Comment by xiang90** [comment]
can you separate the import and fix into two commits?

**Comment by jpbetz** [comment]
@xiang90 Sure, will do.

**Comment by jpbetz** [comment]
commits fixed and description updated with some rationale for UUID library choice

**Comment by xiang90** [comment]
lgtm. thanks @jpbetz

**Comment by jpbetz** [comment]
CI test failure is `TestDropReadUnderNetworkPartition`. Rerunning to see what flakes.

**Comment by xiang90** [comment]
lgtm. merging.

**Pull request merged**
