### PR TITLE
raft: return non-nil Inflights in raft status

### PR DESCRIPTION
**Pull request by tbg**
Recent refactoring to the String() method of `Progress` hit an NPE
because we return nil Inflights as part of the Raft status. Just
fix this at the source and properly populate the Raft status instead
of teaching String() to ignore nil. A real Progress always has a
non-nil Inflights.

### CODE REVIEW

**Comment by bdarnell** [comment]
Aren't we concerned about allocations on this code path? I think I'd rather make it nil-safe than add another copy if we don't need the data.

**Comment by nvanbenschoten** [comment]
Agreed. I think we should avoid making `Status` even more expensive and allocation-heavy than it already is unless there's a good reason to do so.

**Comment by tbg** [comment]
It turns out that there's a good reason. A `nil` `Inflights` is a very annoying gotcha. For example, `IsPaused()` also calls a method on `Inflights` and causes another NPE. I don't want to play whack-a-mole with this, I'd rather fix the allocations in CRDB. But for the newly added `*Config`, this is similarly unfortunate.
I think it's time to change the `Status` API a bit more holistically, will do that tomorrow.

**Comment by tbg** [comment]
I added a commit that splits up `Status` into a `BasicStatus` plus the fields that we need to allocate for. `RawNode` can now return a `BasicStatus`. As I pull this into CRDB, I'll make sure to watch out for allocation heavy paths. Interestingly, at first glance there weren't any -- there might be a lot of small ones that add up mostly from the queues (frequently in shouldQueue, which we call a lot) but I'm relatively certain there isn't anything in the hot paths.

**Pull request merged**
