### PR TITLE
[2024-04-08] Bump dependency updates identified by dependabot

### PR DESCRIPTION
**Pull request by henrybear327**
This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

Summary of actions
- Bumped
    - github.com/golangci/golangci-lint from 1.57.1 to 1.57.2 
      - https://github.com/etcd-io/etcd/pull/17738
    - google.golang.org/grpc from 1.62.1 to 1.63.0 
      - https://github.com/etcd-io/etcd/pull/17748
      - https://github.com/etcd-io/etcd/pull/17749
      - https://github.com/etcd-io/etcd/pull/17750
      - https://github.com/etcd-io/etcd/pull/17740
    - golang.org/x/crypto from 0.21.0 to 0.22.0
      - https://github.com/etcd-io/etcd/pull/17746
      - https://github.com/etcd-io/etcd/pull/17742
    - go.opentelemetry.io/proto/otlp from v1.1.0 to v1.2.0
      - https://github.com/etcd-io/etcd/pull/17750
- Closed (fully indirect)
    - https://github.com/etcd-io/etcd/pull/17747
    - https://github.com/etcd-io/etcd/pull/17741
    - https://github.com/etcd-io/etcd/pull/17739

### CODE REVIEW

**Comment by henrybear327** [comment]
Thanks to @ivanvc for the help!

**Comment by ivanvc** [comment]
@henrybear327, seems like the commits are not properly signed

**Review by jmhbnz — COMMENTED** [review]
Nit: Suggest following the commit message format specified here: https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md#steps-to-bump-a-dependency

**Comment by henrybear327** [comment]
> Nit: Suggest following the commit message format specified here: https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md#steps-to-bump-a-dependency

Fixed :)

**Comment by henrybear327** [comment]
> @henrybear327, seems like the commits are not properly signed

Thanks for spotting! :)

**Review by jmhbnz — CHANGES_REQUESTED** [review]
Hey @henrybear327 - Thanks for taking care of dependencies this week. We need to bump `golang.org/x/crypto` it is not purely indirect, refer:

```bash
 james  ~  D  etcd   dependencies/0..                                                                          12:06:53 
 ➜ grep -Ri "golang.org/x/crypto v" | grep -v sum
tests/go.mod:   golang.org/x/crypto v0.21.0
server/go.mod:  golang.org/x/crypto v0.21.0
tools/mod/go.mod:       golang.org/x/crypto v0.21.0 // indirect
go.mod: golang.org/x/crypto v0.21.0 // indirect
etcdutl/go.mod: golang.org/x/crypto v0.21.0 // indirect
```

We also need to bump grpc in all places, checking this pr there are a couple of instances where grpc is using an older version:

```bash
 james  ~  D  etcd   dependencies/0..                                                                          12:07:16 
 ➜ grep -Ri "google.golang.org/grpc v" | grep -v sum
etcdctl/go.mod: google.golang.org/grpc v1.63.0
pkg/go.mod:     google.golang.org/grpc v1.63.0
tests/go.mod:   google.golang.org/grpc v1.63.0
server/go.mod:  google.golang.org/grpc v1.63.0
tools/mod/go.mod:       google.golang.org/grpc v1.62.1 // indirect
tools/testgrid-analysis/go.mod: google.golang.org/grpc v1.62.1 // indirect
client/v3/go.mod:       google.golang.org/grpc v1.63.0
go.mod: google.golang.org/grpc v1.63.0
etcdutl/go.mod: google.golang.org/grpc v1.63.0 // indirect
api/go.mod:     google.golang.org/grpc v1.63.0
```

**Comment by ivanvc** [comment]
Hi @jmhbnz, I also noticed `google.golang.org/grpc v1.62.1` in `tools/testgrid-analysis`. While I was looking at it, I realized that `scripts/fix.sh`, specifically `scripts/test_lib.sh`'s `run_for_modules` is not running for `tools/{testgrid-analysis,rw-heatmaps}`.

I'm not sure we want to add those two new directories with go modules to `module_dirs`. I'm also not sure if they will dodge some of the checks that the current library does over the code (i.e., static checks).

**Comment by jmhbnz** [comment]
> Hi @jmhbnz, I also noticed `google.golang.org/grpc v1.62.1` in `tools/testgrid-analysis`. While I was looking at it, I realized that `scripts/fix.sh`, specifically `scripts/test_lib.sh`'s `run_for_modules` is not running for `tools/{testgrid-analysis,rw-heatmaps}`.
> 
> I'm not sure we want to add those two new directories with go modules to `module_dirs`. I'm also not sure if they will dodge some of the checks that the current library does over the code (i.e., static checks).

Good spotting. My first instinct is we should probably update `test_lib.sh`, @ahrtr do you agree?

**Comment by ahrtr** [comment]
> I realized that `scripts/fix.sh`, specifically `scripts/test_lib.sh`'s `run_for_modules` is not running for `tools/{testgrid-analysis,rw-heatmaps}`.

Yes, please update the script to cover the `tools/*` as well. It's another minor technical debt I noticed long time ago. Thanks both @ivanvc @jmhbnz

**Comment by henrybear327** [comment]
> Hey @henrybear327 - Thanks for taking care of dependencies this week. We need to bump `golang.org/x/crypto` it is not purely indirect, refer:
> 
> ```shell
>  james  ~  D  etcd   dependencies/0..                                                                          12:06:53 
>  ➜ grep -Ri "golang.org/x/crypto v" | grep -v sum
> tests/go.mod:   golang.org/x/crypto v0.21.0
> server/go.mod:  golang.org/x/crypto v0.21.0
> tools/mod/go.mod:       golang.org/x/crypto v0.21.0 // indirect
> go.mod: golang.org/x/crypto v0.21.0 // indirect
> etcdutl/go.mod: golang.org/x/crypto v0.21.0 // indirect
> ```
> 
> We also need to bump grpc in all places, checking this pr there are a couple of instances where grpc is using an older version:
> 
> ```shell
>  james  ~  D  etcd   dependencies/0..                                                                          12:07:16 
>  ➜ grep -Ri "google.golang.org/grpc v" | grep -v sum
> etcdctl/go.mod: google.golang.org/grpc v1.63.0
> pkg/go.mod:     google.golang.org/grpc v1.63.0
> tests/go.mod:   google.golang.org/grpc v1.63.0
> server/go.mod:  google.golang.org/grpc v1.63.0
> tools/mod/go.mod:       google.golang.org/grpc v1.62.1 // indirect
> tools/testgrid-analysis/go.mod: google.golang.org/grpc v1.62.1 // indirect
> client/v3/go.mod:       google.golang.org/grpc v1.63.0
> go.mod: google.golang.org/grpc v1.63.0
> etcdutl/go.mod: google.golang.org/grpc v1.63.0 // indirect
> api/go.mod:     google.golang.org/grpc v1.63.0
> ```

Thanks @jmhbnz for reviewing and catching issues! :) 

I have ended up adding `go.opentelemetry.io/proto/otlp` as it's not fully indirect, either!

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @henrybear327

**Review by ahrtr — APPROVED** [review]
lgtm

Thanks

**Comment by ivanvc** [comment]
Hi @henrybear327, it looks like the summary of actions in the description got out of date after you bumped other dependencies.

**Comment by henrybear327** [comment]
> Hi @henrybear327, it looks like the summary of actions in the description got out of date after you bumped other dependencies.
> 
> Edit: You mentioned that #17748 was going to be bumped. It's direct, but it isn't part of these commits.

That's a miss ... sorry. I will fix it in #17767

**Pull request merged**
