### PR TITLE
Set backend to cindex before recovering the lessor in applySnapshot

### PR DESCRIPTION
**Pull request by ahrtr**
Fix [13922](https://github.com/etcd-io/etcd/issues/13922).

Copy the comment I added in the source code here so as save the effort to explain again:
```

	// We need to set the backend to consistIndex before recovering the lessor,
	// because lessor.Recover will commit the boltDB transaction, accordingly it
	// will get the old consistent_index persisted into the db in OnPreCommitUnsafe.
	// Eventually the new consistent_index value coming from snapshot is overwritten
	// by the old value.
```

### CODE REVIEW

**Comment by ahrtr** [comment]
cc @ptabor @serathius @spzala

**Comment by ahrtr** [comment]
Will backport to [3.5](https://github.com/etcd-io/etcd/pull/13930), once it's merged.

**Review by ptabor — APPROVED** [review]
Awesome catch !!!

**Review by serathius — APPROVED** [review]
Confirmed that this addresses the issue, awesome work!

**Pull request merged**
