### PR TITLE
Try reproduce https://github.com/etcd-io/etcd/issues/17247

### PR DESCRIPTION
**Pull request by serathius**
Change-Id: Ieed5f16ded627ac27f6acae99fea23211e6f718d

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by serathius** [comment]
Got a repro https://github.com/etcd-io/etcd/actions/runs/7531548184/job/20500348689?pr=17248

**Comment by serathius** [comment]
Will re-enable testing amd to verify that this is arm specific.

**Comment by serathius** [comment]
cc @ahrtr @jmhbnz @siyuanfoundation

**Comment by serathius** [comment]
Got a repro on `amd64` https://github.com/etcd-io/etcd/actions/runs/7539634396/job/20522525891?pr=17248

**Comment by fuweid** [comment]
Use the following command and I can reproduce it in my local

```
EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results taskset -c 0,1,2 make test-robustness
```

**Pull request closed without merging**
