### PR TITLE
clientv3/balancer: enable test again instead of skip.

### PR DESCRIPTION
**Pull request by johncming**
enable test again instead of skip.

### CODE REVIEW

**Comment by jingyih** [comment]
Is this unit test part of our CI? Did you try it locally?

**Comment by johncming** [comment]
> Is this unit test part of our CI? Did you try it locally?

yes. I try locally first, then I try travis ci in my fork repo. Both is ok.

the testcase using fatal is ok.

**Comment by jingyih** [comment]
It is interesting that there is a `// TODO: FIX ME`. Defer to the original author @gyuho.

**Comment by jingyih** [comment]
cc @jpbetz

**Pull request closed without merging**
