### PR TITLE
etcdserver: nil-logger issue fix for version 3.4

### LINKED ISSUE #14402: [3.4.20] Panic probably due to nil log object
Based on the feedback from @JohnJAS, this issue can't be reproduced in 3.4.19, instead it can only be reproduced on 3.4.20.

It looks like the [lg](https://github.com/etcd-io/etcd/blob/1e2682301c2947619214e6497b5432e7717d921d/etcdserver/v3_server.go#L805) is `nil`. 

Thanks both @JohnJAS and @rtheis. 

```
2022-08-29 06:29:02.702707 E | rafthttp: failed to read 88d5d8ebd854df5a on stream MsgApp v2 (unexpected EOF)
2022-08-29 06:29:02.702723 I | rafthttp: peer 88d5d8ebd854df5a became inactive (message send to peer failed)
2022-08-29 06:29:02.703504 W | rafthttp: lost the TCP streaming connection with peer 88d5d8ebd854df5a (stream Message reader)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x75745b]

goroutine 287 [running]:
go.uber.org/zap.(*Logger).check(0x0, 0x1, 0x10a3ea5, 0x36, 0xc003fb7480)
        /root/go/pkg/mod/go.uber.org/zap@v1.10.0/logger.go:264 +0x9b
go.uber.org/zap.(*Logger).Warn(0x0, 0x10a3ea5, 0x36, 0xc003fb7480, 0x2, 0x2)
        /root/go/pkg/mod/go.uber.org/zap@v1.10.0/logger.go:194 +0x45
go.etcd.io/etcd/etcdserver.(*EtcdServer).requestCurrentIndex(0xc000398600, 0xc005210f00, 0xd15682e845891c12, 0x0, 0x0, 0x0)
        /tmp/etcd-release-3.4.20/etcd/release/etcd/etcdserver/v3_server.go:805 +0x873
go.etcd.io/etcd/etcdserver.(*EtcdServer).linearizableReadLoop(0xc000398600)
        /tmp/etcd-release-3.4.20/etcd/release/etcd/etcdserver/v3_server.go:721 +0x2d6
go.etcd.io/etcd/etcdserver.(*EtcdServer).goAttach.func1(0xc000398600, 0xc00011ec20)
        /tmp/etcd-release-3.4.20/etcd/release/etcd/etcdserver/server.go:2698 +0x57
created by go.etcd.io/etcd/etcdserver.(*EtcdServer).goAttach
        /tmp/etcd-release-3.4.20/etcd/release/etcd/etcdserver/server.go:2696 +0x1b1
```

### PR DESCRIPTION
**Pull request by vsvastey**
In v3.5 it is assumed that the logger should not be nil, however it is
still a case in v3.4. The PR targeted to v3.5 was backported to 3.4 and
that's why it's possible to get panic on nil logger in 3.4. This commit
fixed this issue.

Fixes #14402

### CODE REVIEW

**Comment by ahrtr** [comment]
Looks good to me.

@JohnJAS  @rtheis could you double check whether you can still reproduce the issue https://github.com/etcd-io/etcd/issues/14402?

**Comment by rtheis** [comment]
@ahrtr I will send to my team for a test.

**Comment by JohnJAS** [comment]
@ahrtr I can confirm it works after I had a quick test on my own cluster with the manually built etcd including the current PR.

Build info:

I have no name!@autovmCOS76VM01:/> etcd --version
etcd Version: 3.4.20
Git SHA: 38342e88d

commit 38342e88da5d641fe9e09a9203c0ba1f1a212c94 (HEAD -> release-3.4)
Author: Vladimir Sokolov <vsvastey@gmail.com>
Date:   Sat Sep 3 04:24:03 2022 +0300

    etcdserver: nil-logger issue fix for version 3.4

**Comment by ahrtr** [comment]
Thank you @JohnJAS !

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @vsvastey

**Comment by ahrtr** [comment]
@vsvastey  Please add one changelog item into [CHANGELOG-3.4.md](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.4.md). You can add one more section for 3.4.21.

**Comment by ahrtr** [comment]
FYI. Updated the changelog in https://github.com/etcd-io/etcd/pull/14430

**Pull request merged**
