### PR TITLE
ci: add drone.io for arm64 verification

### PR DESCRIPTION
**Pull request by zhlhahaha**
Enable arm64 CI test by applying drone CI,
Includes build test, unit test and integration test

Signed-off-by: Howard Zhang <howard.zhang@arm.com>

Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by xiang90** [comment]
can we not introduce another CI system? Can you try travis CI?

**Comment by zhlhahaha** [comment]
> can we not introduce another CI system? Can you try travis CI?

Hi, Xiang, Thanks for comment. I am total fine with travis CI.
Drone CI is a fast way to enable etcd CI test on arm platform, as the docker image, etcd-test, used by travis CI only support x86 platform. 
I can provide a pr for build etcd-test image for muti-arch, and then make travis CI support arm platform.

**Comment by xiang90** [comment]
@zhlhahaha OK

**Comment by zhlhahaha** [comment]
Hi @gyuho, can you tell me where the source code of binary, marker, that used in etcd-test image?
There is only x86 version binary, so I want to compile it to support arm64 platform.
Thanks a lot.

**Comment by lubinszARM** [comment]
Related issue: https://github.com/etcd-io/etcd/pull/11270
Related checklist: ttps://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/supported-platform.md#supporting-a-new-system-platform 

Hi @glevand @spzala @mkumatag 
We want to remove ETCD_UNSUPPORTED_ARCH=arm64, and try to deliver the PR-s by the checklist to support etcd on Arm64 platform.

So, can anyone help to review the PR?
Thanks.
Other related PR: https://github.com/etcd-io/etcd/pull/11270
cc @vielmetti

**Comment by vielmetti** [comment]
It may be worth mentioning that Travis CI now also has native arm64 support.

**Comment by gyuho** [comment]
Please see https://github.com/etcd-io/etcd/pull/12929. arm64 is now officially supported.

**Comment by zhlhahaha** [comment]
> Please see #12929. arm64 is now officially supported.

Nice, feel free to tell me if there is anything I can help with.

**Pull request closed without merging**
