### PR TITLE
integration: gracefully shut down gRPC server

### PR DESCRIPTION
**Pull request by hormes**
kubernetes unit tests may occasionally get the following error, after some analysis and testing we find that it is related to etcd exit mechanism.

tests like: 
staging/src/k8s.io/client-go/rest/request_test.go
1803:func TestWatch(t *testing.T) {
staging/src/k8s.io/cli-runtime/pkg/resource/builder_test.go
1500:func TestWatch(t *testing.T) {

========================================================
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15afb1a]

goroutine 908 [running]:
k8s.io/kubernetes/vendor/github.com/coreos/bbolt.(*Tx).Bucket(...)
	/home/t4/chorus/f9f659c/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/bbolt/tx.go:101
k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/backend.(*readTx).UnsafeRange(0xc0009ece60, 0x3111326, 0x3, 0x3, 0xc00075d600, 0x11, 0x12, 0x0, 0x0, 0x0, ...)
	/home/t4/chorus/f9f659c/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/backend/read_tx.go:75 +0x67a
k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc.(*storeTxnRead).rangeKeys(0xc000c800f0, 0xc000213e40, 0x1a, 0x20, 0x0, 0x0, 0x0, 0x7, 0x0, 0x2, ...)
	/home/t4/chorus/f9f659c/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/kvstore_txn.go:140 +0x287
k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc.(*storeTxnRead).Range(0xc000c800f0, 0xc000213e40, 0x1a, 0x20, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc0000a0000, ...)
	/home/t4/chorus/f9f659c/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/kvstore_txn.go:45 +0xb0
k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc.(*metricsTxnWrite).Range(0xc000c80120, 0xc000213e40, 0x1a, 0x20, 0x0, 0x0, 0x0, 0x0, 0x2, 0x1af2500, ...)
	/home/t4/chorus/f9f659c/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/metrics_txn.go:38 +0xaf
k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc.(*readView).Range(0xc0009a5ee0, 0xc000213e40, 0x1a, 0x20, 0x0, 0x0, 0x0, 0x0, 0x2, 0x0, ...)
	/home/t4/chorus/f9f659c/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/kv_view.go:38 +0x10f
k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*serverWatchStream).sendLoop(0xc000db8300)
	/home/t4/chorus/f9f659c/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:345 +0x1da
k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch.func1(0xc000db8300)
	/home/t4/chorus/f9f659c/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:145 +0x2b
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch
	/home/t4/chorus/f9f659c/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:144 +0x27f
FAIL	k8s.io/kubernetes/pkg/registry/core/secret/storage	3.773s

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by jingyih** [comment]
The code change is in etcd integration testing unities. How does this fix issues for kubernetes unit test? Did I miss anything?

**Comment by xiang90** [comment]
@jingyih k8s unit test pulls in etcd integration setup code to create etcd clusters i assume.

**Comment by jingyih** [comment]
> @jingyih k8s unit test pulls in etcd integration setup code to create etcd clusters i assume.

You are right. Found it. Thanks!

**Pull request merged**
