### PR TITLE
tests: remaining errors.Is conversions

### PR DESCRIPTION
**Pull request by redwrasse**
tests directory errors.Is conversions, as part of https://github.com/etcd-io/etcd/issues/18576

### CODE REVIEW

**Comment by ivanvc** [comment]
Hi @redwrasse, thanks for opening this pull request. I know this is a draft, but I see the following instances that need to be updated:

* `tests/integration/v3_grpc_test.go:1565:       if err != nil && err != context.DeadlineExceeded {`
* `tests/integration/v3_watch_test.go:737:       if resp, err := wStream.Recv(); err != nil || !resp.Created {`
* `tests/integration/v3_lease_test.go:1089:              if terr != nil && terr != gofail.ErrDisabled {`
* `tests/integration/clientv3/maintenance_test.go:307:   if err != nil && err != context.Canceled {`
* `tests/integration/clientv3/watch_test.go:812:         if err := cli.Close(); err != nil && err != context.Canceled {`

**Comment by redwrasse** [comment]
Added those is @ivanvc . Let me know if you see anymore, otherwise I'll mark this ready for review.

**Comment by ivanvc** [comment]
> I suggest to address nil error before calling `errors.Is()`
> 
> By the way, have you considered activate [errorlint](https://golangci-lint.run/usage/linters/#errorlint) with golangci, that can be very helpful.
> 
> You can see [how I did that on prometheus](https://github.com/prometheus/prometheus/pulls?q=is%3Apr+errorlint+is%3Aclosed+author%3Ammorel-35) if you need an idea on how to split the work

Thanks for the suggestions, @mmorel-35. I was looking for a linter rule but couldn't find one (refer to: https://github.com/etcd-io/etcd/pull/18510#issuecomment-2364184198). We're tracking the work in the parent task #18576.

Given the changes you suggested, it may be a good idea to revise the merged PRs. @redwrasse, are you okay with opening this to more contributors? @mmorel-35, would you be interested in working on this, too?

**Comment by ivanvc** [comment]
Thank you so much, @mmorel-35 :bow: :star2:

**Comment by ivanvc** [comment]
Hi @redwrasse, I enabled `errorlint`, as Matthieu suggested, and do see some issues comparing errors with `==`. If you don't have the bandwidth to continue working on this right now, we could undraft this pull request, merge it, and work on the remaining issues in a follow-up pull request. What do you think?

Thanks again for your help!

**Comment by redwrasse** [comment]
Rebased, squashed, opened for review. Hopefully this one is good to go.

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, Samir.

**Review by ahrtr — APPROVED** [review]
LGTM

**Pull request merged**
