### PR TITLE
api: fix duplicate gateway url issue

### PR DESCRIPTION
**Pull request by fuweid**
The HashKV should use `/v3/maintenance/hashkv` as url

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by fuweid** [comment]
Will mark it ready after CI green

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @fuweid

**Comment by fuweid** [comment]
I was using gateway-v2 openapiv2 to find the duplicate issue since the tool returns error. I think the script/genproto.sh can cover it.

**Comment by fuweid** [comment]
> I mean the REST API isn't covered at all in the existing e2e test

Yes. 😂  It needs time to add more test cases for it

**Review by jmhbnz — APPROVED** [review]
Nice work @fuweid. LGTM.

**Comment by ahrtr** [comment]
Manually verified that both `/v3/maintenance/hash` and `/v3/maintenance/hashkv` work. Merging...

Will add e2e tests cases in separate PR.

**Comment by ahrtr** [comment]
@fuweid can you please backport this PR to 3.5 as well? thx

**Pull request merged**
