### PR TITLE
*: Fix embedded mutexes leaking methods

### PR DESCRIPTION
**Pull request by s111**
This pull request cleans up all exported structs that were leaking the Lock/Unlock methods from an embedded mutex.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
@s111 is there a linter/tool for detecting this?

**Comment by s111** [comment]
I've written a quick extension of golint for my own use: https://github.com/s111/lint.

**Comment by heyitsanthony** [comment]
@s111 any way that patch can get into golint upstream or some other linter? If it's a style problem worth fixing I'd like to be able to catch it as part of CI...

**Comment by gyuho** [comment]
@sebschrader If your patch https://github.com/s111/lint/commit/d196a16cdcfe62812e210d72d908d3aa81660ef0 goes in upstream, it would be great.

lgtm. Thanks!

**Comment by sebschrader** [comment]
Hey @gyuho, you seem to have erroneously mentioned me here.

**Comment by gyuho** [comment]
@sebschrader Apology! I meant to mention @s111 

Thanks!

**Pull request closed without merging**
