### PR TITLE
pkg/adt: merge etcd master & fix interval tree

### PR DESCRIPTION
**Pull request by xkeyideal**
Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by gyuho** [comment]
@xkeyideal Could you rebase your branch from current master, and cherry-pick your patch? It makes code review much easier. Thanks!

**Comment by gyuho** [comment]
Also please squash all your commits into one, without merge commit.

**Comment by gyuho** [comment]
Also change this line to `Fatalf` to validate the fix.

https://github.com/etcd-io/etcd/blob/9a2af7378a937a3434dd126e225108c97bef0cdf/pkg/adt/interval_tree_test.go#L282-L301

**Comment by xkeyideal** [comment]
@xkeyideal #10978

**Pull request closed without merging**
