### PR TITLE
fix: enable errorlint in api, client and pkg

### PR DESCRIPTION
**Pull request by mmorel-35**
This enable errorlint in packages api, client and pkg

Related to #18576

### CODE REVIEW

**Comment by serathius** [comment]
Thanks for contributing improvements to the codebase. Adding new static analysis can be good, but we don't want to overdo it as not all of it might make sense for the project. Is there any issue we track which analysers we want to enable? cc

**Comment by ivanvc** [comment]
Hi @serathius, I think you may have forgotten to mention the people you were trying to cc :sweat_smile:. But let me weigh in on this pull request.

This PR helps towards https://github.com/etcd-io/etcd/issues/18576. We aim to address comparing errors using the functions `errors.Is`/`errors.As`. This should also help with compatibility issues with the next Go 1.24 release. By enabling this static check, we'll be addressing this comment https://github.com/etcd-io/etcd/pull/18510#pullrequestreview-2317435078 and will avoid new code that checks for error equality using `==` or `!=`.

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @mmorel-35.

**Pull request merged**
