### PR TITLE
etcdctl: Remove V2 API commands

### PR DESCRIPTION
**Pull request by serathius**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

Part of https://github.com/etcd-io/etcd/issues/12913
cc @ptabor

### CODE REVIEW

**Comment by serathius** [comment]
cc @ptabor @spzala @ahrtr

**Review by ahrtr — APPROVED** [review]
LGTM

**Comment by ahrtr** [comment]
One more comment, we still support v2 discovery in 3.6. Should we keep the V2 commands, and delete them together the clientv2 & v2 discovery in future?

**Comment by ahrtr** [comment]
FYI [discussion_r855723472](https://github.com/etcd-io/etcd/pull/13963#discussion_r855723472)

**Pull request merged**
