### PR TITLE
dependency: bump yamlfmt,sys,otelgrpc,otlptracegrpc

### PR DESCRIPTION
**Pull request by sharathsivakumar**
The dependabot created the following PRs:

- https://github.com/etcd-io/etcd/pull/16534
- https://github.com/etcd-io/etcd/pull/16535
- https://github.com/etcd-io/etcd/pull/16536
- https://github.com/etcd-io/etcd/pull/16537
- https://github.com/etcd-io/etcd/pull/16538
- https://github.com/etcd-io/etcd/pull/16539
- https://github.com/etcd-io/etcd/pull/16541
- https://github.com/etcd-io/etcd/pull/16542
- https://github.com/etcd-io/etcd/pull/16543

### CODE REVIEW

**Comment by sharathsivakumar** [comment]
@ahrtr and @jmhbnz Here is the PR for dependencies raised by the bot. Please review and let me know if any changes are required.

Also, I am unable to close the PRs created by the bot. Looks like I dont have the permission. Need help with closing the PRs created by the bot.

**Review by ahrtr — APPROVED** [review]
LGTM

thx @sharathsivakumar

**Comment by ahrtr** [comment]
> Also, I am unable to close the PRs created by the bot. Looks like I dont have the permission. Need help with closing the PRs created by the bot.

Once this PR gets merged, the dependabot PRs will be closed automatically.

**Comment by sharathsivakumar** [comment]
Ah ok Then its cool!

**Pull request merged**
