### PR TITLE
The public key doesn't match if any field doesn't match

### PR DESCRIPTION
**Pull request by ahrtr**
Fix https://github.com/etcd-io/etcd/issues/13381

### CODE REVIEW

**Comment by ahrtr** [comment]
Just rebased the PR and squashed the commits.

**Review by serathius — APPROVED** [review]
Thanks @joelegasse, your comment was very helpful.
+1 based on @joelegasse comment

**Comment by ahrtr** [comment]
Rebased again although there is no conflict with the base branch.

**Comment by serathius** [comment]
cc @hexfusion @ptabor

**Pull request merged**
