### PR TITLE
etcdserver: use time.Ticker to improve the syncWatchersLoop

### PR DESCRIPTION
**Pull request by guozhao-coder**
Using time.After will create a new Timer in each cycle, In this case of syncWatchersLoop, it is better to use time.Ticker.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by ptabor — APPROVED** [review]

**Review by ptabor — CHANGES_REQUESTED** [review]
Please `git --signoff` the commit.

**Comment by guozhao-coder** [comment]
I pulled the following changes and resubmit this，ready for review

**Comment by guozhao-coder** [comment]
I modified some other similar points here [https://github.com/etcd-io/etcd/pull/15130](url)

**Comment by guozhao-coder** [comment]
I modified some other similar points here [https://github.com/etcd-io/etcd/pull/15130](https://github.com/etcd-io/etcd/pull/15130)

**Pull request closed without merging**
