### PR TITLE
clientv3: Clarify lessor KeepAlive docs

### PR DESCRIPTION
**Pull request by jpbetz**
Per https://github.com/etcd-io/etcd/issues/10170, attempt to clarify the KeepAlive function documentation based on my understanding of the current implementation.

### CODE REVIEW

**Comment by jpbetz** [comment]
@gyuho As far as I can tell, the channel never contains nil, so I've removed that comment from the doc, but maybe I missed something?

**Comment by ae6rt** [comment]
First, thank you for working on this. 

I'm still stumped, though.

Suppose I setup the keepalive  like this

```
ch, kaerr := t.cli.KeepAlive(context.Background(), leaseResp.ID)
```
Assume kaerr is nil, followed by ch being immediately read by the application.  I read ch again, correctly (I presume) blocking until something significant happens.  Wait a while longer, then assume the "keep alive loop halts with an unexpected error".  In that case specifically where would ErrKeepAliveHalted be available to my downstream code?   

Or maybe you mean kaerr is not nil and *that's* where to look for ErrKeepAliveHalted, but that seems like an oddly early time for the loop to have already been determined to have failed.

**Comment by ae6rt** [comment]
My motivation is to sense if the keepalive has been compromised in some way, such that I should attempt to restart the keepalive.  That's the idiom I'm looking for.

**Comment by jpbetz** [comment]
> Or maybe you mean kaerr is not nil and _that's_ where to look for ErrKeepAliveHalted, but that seems like an oddly early time for the loop to have already been determined to have failed.

Yes, that's what I mean.

I'm still reviewing all the cases when this can happen. It certainly can happen when `Close` has already been called on the Lease:

https://github.com/etcd-io/etcd/blob/d5c93a7b0b5c434bf87d8de4d55d5a3b4ed4ed64/clientv3/lease.go#L277

But you typically wouldn't see that if manage lifecycles and only call `KeepAlive` on `Leases` you haven't closed.

But it can also happen if an unexpected error occurs in the Lease, in which case it looks like the Lease closes itself.  I don't see this documented yet, I'll amend this PR.

**Comment by jpbetz** [comment]
> My motivation is to sense if the keepalive has been compromised in some way, such that I should attempt to restart the keepalive. That's the idiom I'm looking for.

There are higher level conveniences in the etcd client that might be appropriate depending on your needs like [sessions](https://github.com/etcd-io/etcd/blob/404f7d820cc667f0855f0bf0353a63e28597d018/clientv3/concurrency/session.go#L28) or [leasing clients](https://github.com/etcd-io/etcd/blob/404f7d820cc667f0855f0bf0353a63e28597d018/clientv3/leasing/doc.go#L15).

`NewSession` might be a good reference for `KeepAlive` idioms:

https://github.com/etcd-io/etcd/blob/404f7d820cc667f0855f0bf0353a63e28597d018/clientv3/concurrency/session.go#L54

**Comment by gyuho** [comment]
@jpbetz 

> channel never contains nil, so I've removed that comment from the doc

You are right. The documentation was wrong.

Thanks for fix!

**Pull request merged**
