### PR TITLE
[3.4] Backport clientv3 naming implementation

### PR DESCRIPTION
**Pull request by chaochn47**
Part of https://github.com/etcd-io/etcd/issues/16740

Backport #12614, #12667, #12669 and #12675 to release-3.4

Corresponding tests should have been enabled. 

Please DO NOT MERGE until this PR is rebased on top of #16795

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
https://github.com/etcd-io/etcd/pull/16795 has been merged, please rebase this PR, thx

**Comment by chaochn47** [comment]
Thanks @ahrtr! I have rebased the PR. PTAL~

**Comment by chaochn47** [comment]
Known flaky test should be fixed by https://github.com/etcd-io/etcd/pull/15708 once it is backported. Retrying...

```
=== RUN   TestMemberPromoteMemberNotLearner
{"level":"warn","ts":"2023-10-24T16:05:20.153924Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-506ab2c9-cfe6-49c3-ad6a-a51f4cd85750/localhost:56549785845390747520","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}
{"level":"warn","ts":"2023-10-24T16:05:20.159936Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-506ab2c9-cfe6-49c3-ad6a-a51f4cd85750/localhost:56549785845390747520","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}
{"level":"warn","ts":"2023-10-24T16:05:25.361631Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-506ab2c9-cfe6-49c3-ad6a-a51f4cd85750/localhost:56549785845390747520","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
    cluster_test.go:326: expect error to contain can only promote a learner member, got etcdserver: request timed out
--- FAIL: TestMemberPromoteMemberNotLearner (5.35s)
```

https://github.com/etcd-io/etcd/actions/runs/6629437579/job/18008727923?pr=16800

**Review by ahrtr — APPROVED** [review]
LGTM

thx

**Comment by ahrtr** [comment]
cc @fuweid @jmhbnz @serathius @wenjiaswe

**Review by serathius — APPROVED** [review]

**Pull request merged**
