### PR TITLE
*: update test Go version / release version

### PR DESCRIPTION
**Pull request by gyuho**
Test images have been uploaded already.

### CODE REVIEW

**Comment by gyuho** [comment]
TLS cipher suite tests are failing in 1.13.....

**Comment by vimalk78** [comment]
will setting the TLS Max version to TLS12 in `integration/TestTLSClientCipherSuitesMismatch` help here?
I tested locally with go1.13 and the test case passes.

**Comment by gyuho** [comment]
@vimalk78 Could you help fix?

**Comment by vimalk78** [comment]
> @vimalk78 Could you help fix?

yes @gyuho , sent https://github.com/etcd-io/etcd/pull/11129

**Comment by gyuho** [comment]
```
# internal/cpu

flag provided but not defined: -unsafeptr

shadow: check for possible unintended shadowing of variables

Usage: shadow [-flag] [package]

This analyzer check for shadowed variables.

A shadowed variable is a variable declared in an inner scope

with the same name and type as a variable in an outer scope,

and where the outer variable is mentioned after the inner one

is declared.

(This definition can be refined; the module generates too many

false positives and is not yet enabled by default.)

For example:

	func BadRead(f *os.File, buf []byte) error {

		var err error

		for {

			n, err := f.Read(buf) // shadows the function variable 'err'

			if err != nil {

				break // causes return of wrong value

			}

			foo(buf)

		}

		return err

	}

Flags:  -V	print version and exit

  -all

    	no effect (deprecated)

  -c int

    	display offending line with this many lines of context (default -1)

  -cpuprofile string

    	write CPU profile to this file

  -debug string

    	debug flags, any subset of "fpstv"

  -fix

    	apply all suggested fixes

  -flags

    	print analyzer flags in JSON

  -json

    	emit JSON output

  -memprofile string

    	write memory profile to this file

  -source

    	no effect (deprecated)

  -strict

    	whether to be strict about shadowing; can be noisy

  -tags string

    	no effect (deprecated)

  -trace string

    	write trace log to this file

  -v	no effect (deprecated)

# internal/bytealg

flag provided but not defined: -unsafeptr

shadow: check for possible unintended shadowing of variables
```

Skipping go vet tests...

**Pull request merged**
