### PR TITLE
*: Upgrade to use go.opentelemetry.io/otel@v1.2.0

### PR DESCRIPTION
**Pull request by KushalP**
Upgrading from v1.0.1.

Upgrading related dependencies
------------------------------

The following dependencies also had to be upgraded:

- go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.26.1
  From v0.25.0. This gets rid of a transitive dependency on go.opentelemetry.io/otel@v1.0.1.
- google.golang.org/genproto@v0.0.0-20211118181313-81c1377c94b1

### CODE REVIEW

**Comment by hexfusion** [comment]
Thanks to the PR does this change in grpc-go regaiding unix sockets[1] affect us? 

[1] https://github.com/grpc/grpc-go/pull/4817
ref: https://github.com/grpc/grpc-go/releases/tag/v1.42.0

**Comment by KushalP** [comment]
> Thanks for the PR does this change in grpc-go regarding unix sockets[1] affect us?

Looks like there's already code in place to deal with the relative path case: https://github.com/etcd-io/etcd/blob/main/client/v3/internal/endpoint/endpoint.go#L103

**Comment by hexfusion** [comment]
try running scripts/fix.sh to cleanup the deps failing in static fail[1]

https://github.com/etcd-io/etcd/runs/4313064751?check_suite_focus=true

**Comment by KushalP** [comment]
@hexfusion thanks for the tip about `scripts/fix.sh` ! I had to amend the last commit here. I've made sure all commits here work cleanly with that script. I'll also update the PR title and description as it's slightly larger than what was originally intended here.

**Comment by hexfusion** [comment]
once tests are green let's squash these commits please, thanks!

**Comment by KushalP** [comment]
Is it normal for some of these builds to take 30+ minutes to complete?

**Comment by hexfusion** [comment]
looks like the tests are in a pending state might be some sort of throttling, but it is not expected.

**Comment by KushalP** [comment]
Have squashed this change into a single commit as requested. I've also moved `grpc-go` back to v1.41.0 so there's less of a concern about this change.

**Comment by KushalP** [comment]
Amended the commit message and PR description as they both referenced a newer version that isn't part of the diff here.

**Comment by hexfusion** [comment]
cc @hasbro17 @dusk125 PTAL

**Comment by dusk125** [comment]
Looks good to me

**Review by hexfusion — APPROVED** [review]

**Review by spzala — APPROVED** [review]
lgtm
Thanks @KushalP

**Pull request merged**
