### PR TITLE
clientv3/concurrency: add TryLock function

### PR DESCRIPTION
**Pull request by dglei**
TryLock locks the mutex will not be blocked any time. If the mutex is occupied
while trying to acquire the lock, this function will return an error immediately.

#10493 

@jingyih

### CODE REVIEW

**Comment by leonchen83** [comment]
@dglei 
miss edit I think
[lock.go](https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3lock/lock.go)
[v3lock.proto](https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3lock/v3lockpb/v3lock.proto)
[lock_command.go](https://github.com/etcd-io/etcd/blob/master/etcdctl/ctlv3/command/lock_command.go)

**Comment by dglei** [comment]
@leonchen83 I have a look

**Comment by dglei** [comment]
Add TryLock on the client, TryLock just won't waitDeletes when the lock is occupied. 
This will have a lot of duplicate code in directory [/etcdserver/api/v3lock/](https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3lock/) and file [/etcdctl/ctlv3/command/lock_command.go](https://github.com/etcd-io/etcd/blob/master/etcdctl/ctlv3/command/lock_command.go). 
Should we consider support on TryLock compatibility with Lock?

**Comment by dglei** [comment]
@jingyih @technoweenie @bmizerany @drnic Help Wanted

**Comment by xiang90** [comment]
@dglei Will lock with a short timeout context attached work for your use case?

**Comment by dglei** [comment]
@xiang90 Hello，Xiang Li
First of all, no matter how short the timeout is set, it is blocked waiting before it times out.
Secondly, if A acquires the lock first, and it enters the critical section for less than timeout, then B can still obtain the lock. But we expect A and B to compete for locks at the same time, only one of them can successfully acquire the lock.
Finally, TryLock is not something I imagined, and many scenarios require non-blocking locks. There is also a trylock function in the C language pthread library.

**Comment by xiang90** [comment]
> But we expect A and B to compete for locks at the same time, only one of them can successfully acquire the lock.

No, you cannot assume this in a distributed environment since you cannot tell the ordering and the arrival gap between the locking requests. Basically, there is no "at the same time" in a distributed environment. The real risk is the possibility to cancel a acquired lock due to a timeout, since you cannot separate the waiting timeout and the usage timeout.

> Finally, TryLock is not something I imagined, and many scenarios require non-blocking locks. There is also a trylock function in the C language pthread library.

Distributed locking is quite different from pthread lib. 

Can you provide a concrete example of your use case of TryLock?

**Comment by dglei** [comment]
But we don't care the ordering and the arrival gap between the locking requests。 As long as multiple locking requests are queued, only one acquired lock. There is an example for my case of TryLock, :

```
func watcher() {
	for {
		eventType, _ := watcher.Next()
		switch eventType {
		case EventDeleted:
			if err := TryLock(); err != nil {
				continue
			}
			//do something
			Unlock()
		}
	}
}
```

If don't have a trylock function, and we don't want every event to be processed by every program, we need to lock the entire watcher. If the program responsible for handling the Watch() exits abnormally, then the event will be lost.

```
func watcher() {
	Lock()
	defer Unlock()
	for {
		eventType, _ := watcher.Next()
		switch eventType {
		case EventDeleted:
			//do something only once
		}
	}
}
```

**Comment by dglei** [comment]
@xiang90 Will you support TryLock?

**Pull request closed without merging**
