### PR TITLE
*: make "initial-corrupt-check", "corrupt-check-time" stable

### PR DESCRIPTION
**Pull request by gyuho**
@jpbetz @spzala

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by jpbetz** [comment]
lgtm

Thanks for enabling for the functional tester as well.

**Comment by jingyih** [comment]
Does this feature work if TLS is enabled among peers [1]? If not, we probably want to fix it before promoting the flag?

[1] https://github.com/etcd-io/etcd/blob/388d15f521906aad09790f0ab88064856ca7412e/etcdserver/corrupt.go#L311

**Comment by gyuho** [comment]
@jingyih Good point. We need fix that.

**Comment by jingyih** [comment]
> @jingyih Good point. We need fix that.

I am looking at how to fix it. Fundamentally, the server does not have the cert files of the client side, which means we cannot create a clientv3 on server side and reach out to another server. Instead, we need to get peer hash from the peer http [1]?

@gyuho, could you comment?

[1] https://github.com/etcd-io/etcd/blob/master/etcdserver/api/etcdhttp/peer.go

**Comment by jingyih** [comment]
@gyuho Never mind. I think I misunderstood some concepts.

**Comment by jpbetz** [comment]
At some point, maybe as a future task, we should clean up the peer communication infrastructure. It should be possible to introduce a new request type without having to sort out TLS each time..

**Comment by gyuho** [comment]
As @jpbetz mentioned, there's no easy way to configure client cert from a remote peer, when peer-to-peer is TLS-enabled. Please let me know if anyone has a better idea. Let's move this to etcd v4.

**Comment by jingyih** [comment]
@gyuho 
I just merged #11621. Let's reopen this PR and make the flags stable.

**Pull request closed without merging**
