### PR TITLE
[3.5] etcd: upgrade go version from 1.20.10 to 1.20.11

### PR DESCRIPTION
**Pull request by arjunmalhotra1**
To keep etcd projects up to date with the latest patch releases & incorporate the latest security updates.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by serathius** [comment]
Please sign DCO

**Comment by arjunmalhotra1** [comment]
Hey @serathius 
Thank you for the comment. But you'll have to tell me a but more about what DCO is 😅

**Comment by arjunmalhotra1** [comment]
I see what you are saying @serathius So my commit does have 
``` Signed-off-by: Arjun Malhotra <am2cj@virginia.edu>```
I thought that would be sufficient 🤔

**Comment by jmhbnz** [comment]
If you click "Details" next to the failing DCO (Developer certificate of origin) check you will see at the bottom:

> Commit sha: [5447560](https://github.com/etcd-io/etcd/pull/16915/commits/5447560149c9bb6b2c4e07e224321c6117468da9), Author: arjunmalhotra1, Committer: arjunmalhotra1; Expected "arjunmalhotra1 [am2cj@virginia.edu](mailto:am2cj@virginia.edu)", but got "Arjun Malhotra [am2cj@virginia.edu](mailto:am2cj@virginia.edu)".

**Review by jmhbnz — CHANGES_REQUESTED** [review]
Hey @arjunmalhotra1 - I was expecting this backport to only be a patch version increase from `1.20.10` to `1.20.11` as described in the associated issue https://github.com/etcd-io/etcd/issues/16891.

I don't think the community has broadly agreed to bump minor version for stable version policy yet?

**Comment by arjunmalhotra1** [comment]
Thanks @jmhbnz. I see a test failing. I ran the command 
```cd tests && 'env' 'go' 'test' '-timeout=15m' '--race=false' '--cpu=2' './integration/...'``` locally and it passed.
Screenshot 2023-11-12 at 5 38 51 PM

**Comment by arjunmalhotra1** [comment]
Thanks @jmhbnz I have fixed it.

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @arjunmalhotra1

**Review by fuweid — APPROVED** [review]
LGTM

**Review by ahrtr — APPROVED** [review]
lgtm

Thanks.

**Pull request merged**
