### PR TITLE
etcdserver: remove infinite loop for auth in raftRequest

### PR DESCRIPTION
**Pull request by jingyih**
Remove auth validation loop in v3_server.raftRequest(). Re-validation when error ErrAuthOldRevision occurs should be handled on client side.

This is a follow up to #10218.  The client side implementation is tracked in #10408.

### CODE REVIEW

**Comment by jingyih** [comment]
Do we still need to distinguish between raftRequest() and raftRequestOnce()?

**Comment by jingyih** [comment]
Just saw there is a failed test TestV3AuthOldRevConcurrent, I will take a look.

**Comment by mitake** [comment]
@jingyih thanks for handling this! I took a look about the failed test. The failed reason after removing the loop is that simple token always uses the latest revision (see `tokenSimple.info()`) and it isn't working as a validation mechanism (simple token is just for testing purposes, but probably we should fix it). So the test relies on and checks the wrong validation and retry mechanism.
I think disabling the test for now is ok. After moving the validation to client side, it should be revived. How do you think?

**Comment by jingyih** [comment]
Thanks @mitake for the explanation.  I am worried that we might forget to re-enable the test if we disable it now.  Maybe we can keep this PR open until the client side retry get implemented.

**Comment by jingyih** [comment]
Disable integration test `TestV3AuthOldRevConcurrent`, until #10408 is fixed.

**Comment by jingyih** [comment]
@mitak @gyuho PTAL.
I think we should get this merged. Once `ErrAuthOldRevision` happens, this loop will utilize all the CPU resource, as reported in #11033 and #10408.

**Pull request merged**
