### PR TITLE
Support setting http client timeout when enable/disable failpoint

### PR DESCRIPTION
**Pull request by ahrtr**
Extracted from https://github.com/etcd-io/etcd/pull/16822, to make the review on that PR easier.

Once this PR is merged, I will rebase https://github.com/etcd-io/etcd/pull/16822.

### CODE REVIEW

**Comment by fuweid** [comment]
```
2023-12-01T15:35:08.0681305Z panic: test timed out after 30m0s
2023-12-01T15:35:08.0681838Z running tests:
2023-12-01T15:35:08.0682265Z 	TestRobustness (22m38s)
2023-12-01T15:35:08.0682975Z 	TestRobustness/Kubernetes/HighTraffic/ClusterOfSize3 (22m0s)
2023-12-01T15:35:08.0683561Z 
```

It got timeout.

**Comment by ahrtr** [comment]
Raised a separate ticket for the robustness test failure,

https://github.com/etcd-io/etcd/issues/17052

**Comment by ahrtr** [comment]
cc @fuweid @serathius

**Review by fuweid — APPROVED** [review]
LGTM

**Review by jmhbnz — APPROVED** [review]
LGTM

**Pull request merged**
