### PR TITLE
integration: fix a data race about `i` and `tt` in TestV3WatchFromCur…

### LINKED ISSUE #10899: Dara Race in TestV3WatchFromCurrentRevision
Two loop variables are contained in an anonymous function closure.

The loop variables are here `i` and `tt`:
https://github.com/etcd-io/etcd/blob/9fba06ba3b832a6cb6d3342eb719132ad2da4fd6/integration/v3_watch_test.go#L206

Also they are used in a go closure here inside loop:
https://github.com/etcd-io/etcd/blob/9fba06ba3b832a6cb6d3342eb719132ad2da4fd6/integration/v3_watch_test.go#L247-L256
 
May I submit a PR to fix it?

### PR DESCRIPTION
**Pull request by yuzeming**
…rentRevision

don't references to loop variables from within go anonymous function

Fixes #10899

### CODE REVIEW

**Comment by jingyih** [comment]
How about just waiting for the go routine to finish at the end of each loop?

**Comment by yuzeming** [comment]
I updated my PR. Could you have look on my code? Thanks.

**Comment by jingyih** [comment]
Could you squash the commits?

**Comment by yuzeming** [comment]
I made some mistakes and this PR was closed. I create a new PR here. 
https://github.com/etcd-io/etcd/pull/10904

Sorry for this inconvenience.

**Pull request closed without merging**
