### PR TITLE
Automated cherry pick of #10218 #10468 on release 3.3

### LINKED ISSUE #11377: etcdserver hang with syntactically valid but old token?
With this script, and v3.3.11 or v3.3.17, I see that etcdserver does not respond promptly when presented with an Authorization token that is expired but syntactically valid:
```
#!/bin/bash -x

ETCD_IMAGE=quay.io/coreos/etcd:${ETCD_VERSION:-v3.3.11}

docker rm -f etcdserver || true
docker run \
       --detach \
       --net=host \
       --name etcdserver \
       ${ETCD_IMAGE} \
       etcd \
       --advertise-client-urls "http://127.0.0.1:2379" \
       --listen-client-urls "http://0.0.0.0:2379"

function ectl {
    docker run \
	   --rm \
	   -i \
	   --net=host \
	   -e ETCDCTL_API=3 \
	   -e ETCDCTL_ENDPOINTS=http://127.0.0.1:2379 \
	   ${ETCD_IMAGE} \
	   etcdctl \
	   "$@"
}

ectl user add root --interactive=false <<EOF
rootpasswd
EOF
ectl auth enable

time timeout 5s curl -w '%{http_code}' -L http://127.0.0.1:2379/v3alpha/kv/range -X POST -d '{"key": "L2NhbGljbwo="}'

time timeout 5s curl -w '%{http_code}' -L http://127.0.0.1:2379/v3alpha/kv/range -H 'Authorization: IsbMEkdCkHxvTUkO.22' -X POST -d '{"key": "L2NhbGljbwo="}'

time timeout 5s curl -w '%{http_code}' -L http://127.0.0.1:2379/v3alpha/kv/range -H 'Authorization: IsbMEkdCkHxvTUkO.' -X POST -d '{"key": "L2NhbGljbwo="}'
```

The output for the last 3 curls shows:
```
+ timeout 5s curl -w '%{http_code}' -L http://127.0.0.1:2379/v3alpha/kv/range -X POST -d '{"key": "L2NhbGljbwo="}'
{"error":"etcdserver: user name is empty","code":3}400
real	0m0.008s
user	0m0.006s
sys	0m0.001s
+ timeout 5s curl -w '%{http_code}' -L http://127.0.0.1:2379/v3alpha/kv/range -H 'Authorization: IsbMEkdCkHxvTUkO.22' -X POST -d '{"key": "L2NhbGljbwo="}'

real	0m5.003s
user	0m0.008s
sys	0m0.002s
+ timeout 5s curl -w '%{http_code}' -L http://127.0.0.1:2379/v3alpha/kv/range -H 'Authorization: IsbMEkdCkHxvTUkO.' -X POST -d '{"key": "L2NhbGljbwo="}'
{"error":"etcdserver: invalid auth token","code":16}401
real	0m0.013s
user	0m0.007s
sys	0m0.005s
```
In other words, with no Authorization header, or with a malformed token, we get an immediate negative response (which is good).  But with a well formed but non-current token, the etcd server appears to hang.  (In other experiments, I've waited up to a minute.)

Is this behavior explicable or somehow expected?

### PR DESCRIPTION
**Pull request by jingyih**
Cherry pick of #10218 #10468 on release-3.3.

#10218: etcdserver: Remove infinite loop in doSerialize
#10468: etcdserver: remove auth validation loop

Fixes #11377

### CODE REVIEW

**Comment by jingyih** [comment]
Fixes #11377

**Comment by davissp14** [comment]
Hey @jingyih , curious why this didn't end up getting merged?

**Comment by jingyih** [comment]
> Hey @jingyih, could you provide some context on why this wasn't merged?

My guess is that I accidentally deleted the branch which caused this PR to be closed.

**Comment by jingyih** [comment]
@gyuho @mitake Could you please take a look?

**Comment by cjquinon** [comment]
Hi @jingyih @gyuho @mitake .  Wanted to check in on this.

We have some production workloads on 3.3 that are impacted by this issue.  Any way we can merge this in and create a new 3.3 patch?

**Comment by mitake** [comment]
@jingyih sorry for my late reply. LGTM, thanks! I'm merging this, the test case `TestBalancerUnderNetworkPartitionWatchFollower` seems to be failed because of timing issue.

**Comment by cjquinon** [comment]
Hi @mitake @jingyih - is it possible to create a new patch on 3.3 with this fix (e.g, 3.3.19)?  We have some production workloads impacted by this issue.

**Pull request merged**
