### PR TITLE
Remove defunct release-3.5 arm64 github actions workflows

### PR DESCRIPTION
**Pull request by jmhbnz**
These jobs have now been migrated to prow in:
- https://github.com/kubernetes/test-infra/pull/33733
- https://github.com/kubernetes/test-infra/pull/33734

### CODE REVIEW

**Comment by ivanvc** [comment]
@jmhbnz, just a heads up that I'm also testing the prow jobs in this PR: #18784

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @jmhbnz.

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Comment by ivanvc** [comment]
/retitle [3.5] Remove defunct release-3.5 arm64 github actions workflows

**Pull request merged**
