### PR TITLE
Bump dependencies identified by dependabot

### PR DESCRIPTION
**Pull request by jmhbnz**
Refer to commits for individual summary.

@ahrtr This is my first attempt at trying to complete the manual actions for a round of dependabot updates, can you please take a close look? 

Notes: 
  - I used `scripts/update_dep.sh`.
  - I did not include the dependabot pr's for `in tools/mod` items, should they be included here manually or can they be merged directly from dependabot?

If this does look ok I can do the cleanup to close down the associated dependabot pr's, or I think they might auto close once this merges?

### CODE REVIEW

**Comment by ahrtr** [comment]
I will try to provide a doc this week as I promised last week.

**Comment by ahrtr** [comment]
Please follow https://github.com/etcd-io/etcd/pull/15744 to update this PR.

**Comment by jmhbnz** [comment]
> Please follow #15744 to update this PR.

Will take a look after kubecon today, thanks for creating the guide @ahrtr 👍🏻

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @jmhbnz

**Pull request merged**
