### PR TITLE
Bump dependencies manually

### PR DESCRIPTION
**Pull request by sharathsivakumar**
The bot raised the following dependencies:

- https://github.com/etcd-io/etcd/pull/17210
- https://github.com/etcd-io/etcd/pull/17211 --> Bumped
- https://github.com/etcd-io/etcd/pull/17213 -->Bumped
- https://github.com/etcd-io/etcd/pull/17214
- https://github.com/etcd-io/etcd/pull/17215
- https://github.com/etcd-io/etcd/pull/17216
- https://github.com/etcd-io/etcd/pull/17217

### CODE REVIEW

**Comment by sharathsivakumar** [comment]
@serathius @ahrtr @jmhbnz Here are the dependencies for this week. Please take a look and let me know if any changes are required. 
I was concerned with the grpc-gateway bump. But I suppose since its not a major version change(v2), its alright to bump the dependency. Is this correct?

**Comment by jmhbnz** [comment]
> I was concerned with the grpc-gateway bump. But I suppose since its not a major version change(v2), its alright to bump the dependency. Is this correct?

This should be fine I think.  We just need to review changes here https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.19.0 and check for any impacts to etcd. I don't see anything problematic at first glance but a second pair of eyes from @ahrtr or @fuweid would be good.

**Review by jmhbnz — APPROVED** [review]
LGTM on green - Thanks @sharathsivakumar

**Pull request merged**
