### PR TITLE
etcdctl: add command to generate shell completion

### LINKED ISSUE #13111: etcdctl: Provide shell completion
It would be nice to have shell completion for etcdctl. Many projects do this, either by generating some shell code or handling in the code. Also, cobra support completion OOTB, but the current version in the 3.4 release branch is too low.

https://github.com/spf13/cobra/blob/master/shell_completions.md

### PR DESCRIPTION
**Pull request by avorima**
To improve the UX of etcdctl. Completion is generated by cobra
according to defined commands and flags.

Fixes #13111

### CODE REVIEW

**Comment by ptabor** [comment]
Nice. Could you please add an `tests/e2e/ctl_v3_*.go` test to cover the command is working (even on individual example).

**Review by lilic — COMMENTED** [review]
Thanks! Works like a charm 🎉  👍 

Would you mind adding it for `etcdutl` in a follow up maybe?

@ptabor should we add this to the release notes as well what do you think?

**Comment by ptabor** [comment]
@ptabor +1 for release notes. The notable first entry for 3.6.

**Comment by avorima** [comment]
> Nice. Could you please add an tests/e2e/ctl_v3_*.go test to cover the command is working (even on individual example).

I'll look into writing tests. Do you mean one for one shell only?

> Would you mind adding it for etcdutl in a follow up maybe?

Sure, I can do that.

**Comment by ptabor** [comment]
> > Nice. Could you please add an tests/e2e/ctl_v3_*.go test to cover the command is working (even on individual example).
> 
> I'll look into writing tests. Do you mean one for one shell only?

Yes - mostly to make sure someone didn't turned off the group incidentally. 
> 
> > Would you mind adding it for etcdutl in a follow up maybe?
> 
> Sure, I can do that.

**Comment by avorima** [comment]
@ptabor I've added a really basic test that verifies the generated shell code is valid. Testing the completion itself is kind of tricky and probably not feasible in a non-interactive environment. I could add some test cases for the hidden `__complete` command that the shell code uses though.

The test is for `bash`, but can easily be extended for `zsh` and `fish`. They just have to be installed in CI.

**Review by ptabor — APPROVED** [review]
Great . Thank you.

**Review by lilic — APPROVED** [review]
Thank you! 🎉

**Pull request merged**
