### PR TITLE
[3.5] Differentiate the warning message for rejected client and peer connections

### PR DESCRIPTION
**Pull request by ahrtr**
Backport https://github.com/etcd-io/etcd/pull/18313 to 3.5

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @ahrtr

**Comment by ivanvc** [comment]
@ahrtr, do we want a change log entry for this backport? It sounds user-facing, so I thought we did.

**Comment by ahrtr** [comment]
> @ahrtr, do we want a change log entry for this backport? It sounds user-facing, so I thought we did.

Already done. https://github.com/etcd-io/etcd/pull/18320

**Comment by ivanvc** [comment]
> Already done. #18320

Duh, yeah, my bad :smiley:, I didn't see it.

**Pull request merged**
