### PR TITLE
client: Add logger argument to NewCtxClient

### PR DESCRIPTION
**Pull request by serathius**
Ref https://github.com/etcd-io/etcd/issues/12326

Follow up from https://github.com/etcd-io/etcd/pull/12948

### CODE REVIEW

**Comment by serathius** [comment]
cc @ptabor

**Comment by ptabor** [comment]
I'm sorry for keep asking changes, but if we are breaking/improving the API, I would go for future proof syntax: 

```
func NewCtxClient(ctx context.Context, options Options) *Client {
```

```
func WithZapLogger(lg *zap.Logger) { // as we cannot just use WithLogger unless we will remove it entirelly
   ... 
}
```

**Comment by serathius** [comment]
What `Options` object you are refereeing to? Should I create a new struct?

**Comment by ptabor** [comment]
> What `Options` object you are refereeing to? Should I create a new struct?

It does not exists yet. 

It doesn't need to be a struct, it might be potentially an interface

```
interface Option {
   func apply(cfg *Config)
}
```

that we do replay internally during 'Client' construction:

Refs: 
  - https://commandcenter.blogspot.com/2014/01/self-referential-functions-and-design.html
  - https://www.sohamkamani.com/golang/options-pattern/

**Comment by serathius** [comment]
sg

**Comment by ptabor** [comment]
In the perfect word: 
  - `Config` is a struct that contains all the options and can be stored in JSON (e.g. config files). 
  - `Option` pattern is a way to override specific properties of the default Config. 

The Client object is always internally created from the full `Config`. 
For convenience there are additional constructors that can allow to create Client from the supplied Options(), 
by taking the `DefaultConfig()` and applying the `Options` on top of it. 

Unfortunetelly currently not all the constructors do use `newClient` that makes it a bigger refactor. 

I think that the refactor can be done later including changing: 
```
type Option  func(cfg *Config)
```
without to much break into actual invocations.

**Review by ptabor — APPROVED** [review]

**Review by gyuho — APPROVED** [review]

**Pull request merged**
