### PR TITLE
etcdserver/api/etcdhttp: checkHealth refactoring

### PR DESCRIPTION
**Pull request by GSokol**
Small refactoring of
`go.etcd.io/etcd/etcdserver/api/etcdhttp/metrics.go.checkHealth`
function just to avoid annoying repeatings of `if h.Health == "true" {`

### CODE REVIEW

**Comment by jingyih** [comment]
LGTM. How about defer the code block which handles the metric. This way we can get rid of the inline function.

**Comment by GSokol** [comment]
@jingyih, done.

**Comment by jingyih** [comment]
LGTM. Could you squash the commits and force push?

**Comment by GSokol** [comment]
@jingyih, done

**Pull request merged**
