### PR TITLE
[backport 3.4]: server/auth: enable tokenProvider if recoved store enables auth

### PR DESCRIPTION
**Pull request by cfz**
this is a manual backport of #13172
we would also like to have this fix in release 3.4
cc @mitake @spzala

### CODE REVIEW

**Review by spzala — COMMENTED** [review]
lgmt

**Comment by mitake** [comment]
the CI fail shouldn't be related to the change, lgtm, thanks @cfz

**Review by mitake — APPROVED** [review]

**Comment by mitake** [comment]
@hexfusion could you check it's ok to merge this PR to the stable branch?

**Comment by tangcong** [comment]
etcd 3.4 and 3.5 have not yet fixed the lease leak issue and It will cause etcd to accumulate millions of keys over time until the db is full. We should reopen and merge this pr. thanks. @mitake @spzala @serathius

**Comment by ahrtr** [comment]
@cfz Could you please rebase this PR? Sorry for the delay of reviewing this PR.

**Comment by cfz** [comment]
@ahrtr done, PTAL

**Review by ahrtr — APPROVED** [review]
LGTM

The pipeline failures are unrelated to this PR.

**Comment by mitake** [comment]
Sorry to miss this PR, LGTM too.

**Comment by mitake** [comment]
Sorry for missing this PR, LGTM.

**Pull request merged**
