### PR TITLE
Update golang/x/net dependency to release-branch.go1.11

### PR DESCRIPTION
**Pull request by PrasadG193**
Fixes: https://github.com/etcd-io/etcd/issues/10500

### CODE REVIEW

**Comment by PrasadG193** [comment]
cc: @wenjiaswe

**Comment by hexfusion** [comment]
Hi @PrasadG193 thanks for the PR, could you please run this again with the scripts/updatedep.sh script to bump the vendored files. Also please take a look at CI failure https://travis-ci.com/etcd-io/etcd/jobs/180704842#L594 and resolve per [CONTRIBUTING.md#format-of-the-commit-message](https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#format-of-the-commit-message)

**Comment by xiang90** [comment]
@PrasadG193 This pr does not change the version of go-humanize I believe. But the vendor code of the package is changed. Do you know why?

**Comment by PrasadG193** [comment]
@xiang90 I think I committed that pkg by mistake. Fixed.

**Pull request closed without merging**
