### PR TITLE
Documentation: added ETCD Manager tool

### PR DESCRIPTION
**Pull request by gtamas**
New tool: ETCD Manager

ETCD Manager is a multi-platform ETCD v3 client. Currently, builds are available form Mac, Wiindows and Linux, but iOS / Android builds will also be added in the future.
It aims to be a modern, efficient and easy to use GUI with full coverage of ETCD APIs / functionality. The first public (beta) release is already available.

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm. thanks!

**Comment by gtamas** [comment]
@xiang90 
Thank you!
Can't see the change in ETDC docs though. It'll be published later, right?

**Comment by gtamas** [comment]
@xiang90 
I can see that a new version of ETCD has been published (3.4.0, cool!), but the "libraries and tools" page on your website seem to be unchanged. The list still doesn't include ETCD Manager.

I was told that the ETCD documentation is generated from this repo, so I created the PR here, but now I'm a bit confused :). In order to update the docs on your website, do I need to create another pull request in that repo (etcd-io/website) as well?

Thanks in advance!

**Comment by spzala** [comment]
@gtamas I think what probably happened was that the 3.4 branch was already created when this PR was merged, and so this PR only made it to the master branch. 
 /cc @xiang90 @gyuho  - I guess considering this is doc only changes, a separate PR in the website repo should be good enough?. Thanks!

**Pull request merged**
