### PR TITLE
Separate robustness test scenarios and increase number of times we run exploratory tests in nightly

### PR DESCRIPTION
**Pull request by serathius**
Not the best solution, but should be good enough without needing to wrap/customize golang testing.

For TestRobustness we run:
* 8x TestRobustnessExploratory
* 5x TestRobustnessRegression

Which is not as bad as I thought, still we can double number of times we do exploratory test that randomizes etcd configuration and failpoint.

Keeping regression test for CI.

cc @ahrtr @siyuanfoundation 

Fixes https://github.com/etcd-io/etcd/issues/17259

### CODE REVIEW

**Comment by siyuanfoundation** [comment]
LGTM

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @serathius

**Review by fuweid — APPROVED** [review]
LGTM

**Pull request merged**
