### PR TITLE
picker: replace picker with  V2Picker ，picker is deprecated

### PR DESCRIPTION
**Pull request by Murphylu1993**
Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by Murphylu1993** [comment]
。

**Comment by ptabor** [comment]
Thank you for the contribution. Could you, please elaborate/link more in commit & PR description on the purpose of the change. 

Looking at the current state of https://godoc.org/google.golang.org/grpc/balancer#Picker, in the current version its called "Picker" again (but conforms to your interface).  Is there a plan to rename it back after update of the grpc library ?

**Comment by Murphylu1993** [comment]
> Thank you for the contribution. Could you, please elaborate/link more in commit & PR description on the purpose of the change.
> 
> Looking at the current state of https://godoc.org/google.golang.org/grpc/balancer#Picker, in the current version its called "Picker" again (but conforms to your interface). Is there a plan to rename it back after update of the grpc library ?

done

**Comment by ptabor** [comment]
> > Thank you for the contribution. Could you, please elaborate/link more in commit & PR description on the purpose of the change.
> > Looking at the current state of https://godoc.org/google.golang.org/grpc/balancer#Picker, in the current version its called "Picker" again (but conforms to your interface). Is there a plan to rename it back after update of the grpc library ?
> 
> done

I see the title changed. But what about lack of V2 picker in the current state of library: https://godoc.org/google.golang.org/grpc/balancer#Picker

**Comment by ptabor** [comment]
I think this PR overlaps with broader: 
  https://github.com/etcd-io/etcd/pull/12398/commits/2859e9f94608b44c9c351c7ccfcff21665573627

**Pull request closed without merging**
