### PR TITLE
Automated cherry pick of #11735 on release-3.4

### PR DESCRIPTION
**Pull request by wswcfan**
Cherry pick of #11735 on release-3.4.

#11735: auth: optimize lock scope for CheckPassword

### CODE REVIEW

**Comment by tangcong** [comment]
this pr  improves checkPassword( Authenticate interface) performance by more than 10 times. could we merge it into release-3.4? thanks. @gyuho

**Comment by gyuho** [comment]
@tangcong @wswcfan can you help backport this to 3.4? Then, we can release a new 3.4.

**Comment by tangcong** [comment]
it is also backported to 3.4, do you mean also backport it to 3.3? @gyuho

**Comment by gyuho** [comment]
Oh, I misread the branch name. Never mind :)

**Pull request merged**
