### PR TITLE
[3.5] Fix delete inconsistencies in read buffer

### PR DESCRIPTION
**Pull request by siyuanfoundation**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

backport https://github.com/etcd-io/etcd/pull/17195 to 3.5

### CODE REVIEW

**Review by fuweid — APPROVED** [review]
LGTM

**Review by serathius — APPROVED** [review]

**Comment by siyuanfoundation** [comment]
cc @ahrtr

**Review by ahrtr — APPROVED** [review]
lgtm

thanks

**Pull request merged**
