### PR TITLE
fix release pipeline failure

### PR DESCRIPTION
**Pull request by ahrtr**
I forgot to execute ./script/fix.sh in previous PR. :(

Signed-off-by: Benjamin Wang <wachao@vmware.com>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

cc @serathius

### CODE REVIEW

**Comment by ahrtr** [comment]
The Release pipeline is broken,

https://github.com/etcd-io/etcd/actions/runs/3553267055/jobs/5968689132

**Comment by ahrtr** [comment]
cc @spzala and @ptabor as well.

**Review by serathius — APPROVED** [review]

**Comment by ahrtr** [comment]
The Release failure is because this PR isn't merged yet. Once this PR is merged, it can be resolved automatically.

**Comment by serathius** [comment]
@ahrtr That's annoying, have you looked if this can be fixed?

**Comment by ahrtr** [comment]
Yes, it's possible, and it should a minor fix. But it's a tradeoff. 

Currently the release.sh always pull the repo and checkout the `main` branch. So any change in curernt PR isn't included. It's safer because we can kick off the release anywhere and in any branch. 

The other option is to always kick off release process in current branch. So it requires us to manually checkout main branch before triggering the release process. 

It seems that we should follow the second approach?

**Comment by ahrtr** [comment]
The better choice seems to be adding a flag to control it. We should enable the flag to trigger release in current branch in github workflow. 

When we manually trigger release, follow the existing logic.

**Pull request merged**
