### PR TITLE
Add tag "etcd-mixin" into the Grafana dashboard

### PR DESCRIPTION
**Pull request by nlamirault**

### CODE REVIEW

**Comment by xiang90** [comment]
what problem does this tag solve?

**Comment by xiang90** [comment]
ping.

**Comment by frittentheke** [comment]
ping.

**Comment by frittentheke** [comment]
> ping.

again

**Comment by nlamirault** [comment]
none. It was just to add a tag to the dashboard in Grafana.

**Comment by nlamirault** [comment]
Sorry for delay.
@xiang90 no problem. Others mixins could have tags, like `kubernetes-mixin` to identify where does this dashboard come from

**Pull request merged**
