### PR TITLE
[2024-06-10] Bump dependency updates identified by dependabot

### PR DESCRIPTION
**Pull request by henrybear327**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md). 

### Summary of actions

- Bumped
    - bump [golang.org/x/text](http://golang.org/x/text) from 0.15.0 to 0.16.0
        - https://github.com/etcd-io/etcd/pull/18146
    - bump [golang.org/x/net](http://golang.org/x/net) from 0.25.0 to 0.26.0
        - https://github.com/etcd-io/etcd/pull/18150
    - [golang.org/x/crypto](http://golang.org/x/crypto) from 0.23.0 to 0.24.0
        - https://github.com/etcd-io/etcd/pull/18149
- Closed (fully indirect)
    - bump [github.com/golangci/misspell](http://github.com/golangci/misspell) from 0.5.1 to 0.6.0
        - https://github.com/etcd-io/etcd/pull/18157
    - [golang.org/x/term](http://golang.org/x/term) from 0.20.0 to 0.21.0
        - https://github.com/etcd-io/etcd/pull/18156
    - bump [github.com/sivchari/tenv](http://github.com/sivchari/tenv) from 1.7.1 to 1.9.1
        - https://github.com/etcd-io/etcd/pull/18155
    - bump [github.com/spf13/viper](http://github.com/spf13/viper) from 1.12.0 to 1.19.0
        - https://github.com/etcd-io/etcd/pull/18154
    - bump [github.com/go-logr/logr](http://github.com/go-logr/logr) from 1.4.1 to 1.4.2
        - https://github.com/etcd-io/etcd/pull/18153
    - [github.com/gorilla/websocket](http://github.com/gorilla/websocket) from 1.4.2 to 1.5.2
        - https://github.com/etcd-io/etcd/pull/18148

### CODE REVIEW

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @henrybear327

**Review by fuweid — APPROVED** [review]
LGTM

**Pull request merged**
