### PR TITLE
Update etcd to use the new raft module go.etcd.io/raft/v3

### PR DESCRIPTION
**Pull request by ahrtr**
Update etcd to use the new raft module `go.etcd.io/raft/v3`. Currently we depend on the latest commit of [raft](https://github.com/etcd-io/raft). When we  release new tagged raft version, we can bump etcd by then.

The only left work is to update [modules.svg](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/modules.svg).  Of course, we also need to update the changelog. Both tasks will be done in separate PR(s).

Please note that the [etcd/raft](https://github.com/etcd-io/etcd/tree/main/raft) isn't removed, instead it is just marked as Deprecated for now. We can remove it in 3.7.

### CODE REVIEW

**Comment by ahrtr** [comment]
cc @mitake @ptabor @serathius @spzala @tbg PTAL.

**Review by ptabor — APPROVED** [review]

**Comment by serathius** [comment]
Not sure about deprecation and removal in v3.7. I'm worried that wait doesn't have any benefits but could cause a lot of confusion for etcd contributors. Can be discussed in separate PR.

**Review by serathius — APPROVED** [review]

**Comment by ahrtr** [comment]
Thanks both @ptabor and @serathius for the quick review.

> I'm worried that wait doesn't have any benefits but could cause a lot of confusion for etcd contributors. Can be discussed in separate PR.

The only concern is that some applications might already depend on the raft on main, such as cockroachdb db (@tbg ). So we can't directly remove it. It's safer to remove it in 3.7.  

Of course, we can discuss it separately.

**Comment by ahrtr** [comment]
> Based on how much technical depth is in etcd repo, I would prefer to pay it off earlier than later.

Personally I'd like to remove it soon. But at least, let's send formal notification and wait some time, e.g. 1 month?

**Comment by serathius** [comment]
> The only concern is that some applications might already depend on the raft on main, such as cockroachdb db (@tbg ). So we can't directly remove it. It's safer to remove it in 3.7.

You cannot depend on branches, you depend on commit hashes. Don't think  cockroachdb makes a difference here.

**Comment by ahrtr** [comment]
> You cannot depend on branches, you depend on commit hashes.

Right. If there is no any objection, Let me deliver a PR to remove it.

**Comment by ahrtr** [comment]
https://github.com/etcd-io/etcd/pull/14882

**Comment by ahrtr** [comment]
Linked to https://github.com/etcd-io/etcd/issues/14713

**Pull request merged**
