### PR TITLE
Rollback the pull/14080: which fixed the potential deadlock

### PR DESCRIPTION
**Pull request by ahrtr**
Rollback https://github.com/etcd-io/etcd/pull/14080

Please read https://github.com/etcd-io/etcd/pull/16035#discussion_r1413820384

### CODE REVIEW

**Comment by serathius** [comment]
Could you add a test to confirm the fix?

**Comment by ahrtr** [comment]
> Could you add a test to confirm that there is no longer a leak and prevent future regressions?

This PR just rollback, can we do whatever other thing separately?

**Comment by serathius** [comment]
It's a partial rollback, which means it should be treated as normal change.

**Comment by ahrtr** [comment]
I don't understand why we are wasting time on such small thing. 

The part I did not rollback is a trivial change. If you are insist on, I can totally rollback the PR.

**Comment by ahrtr** [comment]
Completely rollbacked, pls let me know if you still have any concern. @serathius

**Comment by serathius** [comment]
> I don't understand why we are wasting time on such small thing.

Reverts are only trivial if they revert us to exactly the same stable point as before. Partial revert moves us to new unknown place. Possibly it is an improvement, but to verify we need to either review it thoroughly or have test shows the improvement.

The revert was motivated by issue that issue slipped our review, meaning it's as trivial as originally assumed. We didn't have any tests before, we should invest in them to reduce the dependency on review.

**Review by serathius — APPROVED** [review]

**Pull request merged**
