### PR TITLE
*: avoid closing a watch with ID 0 incorrectly

### PR DESCRIPTION
**Pull request by kafuu-chino**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This PR backports https://github.com/etcd-io/etcd/pull/14296 to release-3.5. cc @ahrtr  @mitake

### CODE REVIEW

**Comment by ahrtr** [comment]
It seems release-3.5 doesn't have `client/pkg/v3/verify `either.

**Comment by kafuu-chino** [comment]
> It seems release-3.5 doesn't have `client/pkg/v3/verify `either.

Yes, there is no `client/pkg/v3/verify` and seem to no integration test. I have modified them. @ahrtr

**Comment by kafuu-chino** [comment]
> It seems release-3.5 doesn't have `client/pkg/v3/verify `either.

Yes, there is no client/pkg/v3/verify and the test also has some issues. I have solved them. @ahrtr

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @kafuu-chino

**Comment by ahrtr** [comment]
@kafuu-chino  please add a changelog item for [3.4 ](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.4.md)and [3.5](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md) respectively. Thank.

**Comment by ahrtr** [comment]
cc @spzala @mitake to double check

**Comment by mitake** [comment]
LGTM, thanks @kafuu-chino !

**Pull request merged**
