### PR TITLE
fix: use require.NoError instead of t.Fatal(err) in client package

### PR DESCRIPTION
**Pull request by mmorel-35**
There is no linter for this.
This uses testify instead of testing for
With 
```go
require.NoError(t, err)

require.Error(t, err)
```
instead of

```go
if err != nil {
    t.Fatal(err)
}


if err == nil {
    t.Fatal(err)
}
```

### CODE REVIEW

**Comment by ahrtr** [comment]
Thanks for the PR. Please try not raise huge PR. Please try to breakdown this PR, thx

**Comment by ahrtr** [comment]
> One PR per first level folder shall be enough ?

works for me

**Comment by ivanvc** [comment]
This looks good. Thanks for your pull request, @mmorel-35. Two files have changes that are not related to `t.Fatal()`:

1. [`client/v3/ctx_test.go`](https://github.com/etcd-io/etcd/pull/18705/files#diff-c6de5bf6bb4e58d70fa8b01cf4440dbd8bd237ffe921115d71cf27247e12b01e)
2. [`client/pkg/tlsutil/cipher_suites_test.go`](https://github.com/etcd-io/etcd/pull/18705/files#diff-09f8f883c5daddb4d822e415eccb6069151f3da649c2f69278b53bbc0d17a67c)

I just wanted to point it out. It could be a minor nitpick, but if others think it's ok to include them in this PR, then this PR LGTM.

Thanks.

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, Matthieu!

**Pull request merged**
