### PR TITLE
*: rename "master" branch references to "main" in source code

### PR DESCRIPTION
**Pull request by gyuho**
Renaming to "main" across our source code first, and I will make the change in GitHub setting to actually rename the git branch from "master" to "main".

- https://github.com/etcd-io/website/issues/149#issuecomment-839804288
- https://github.com/etcd-io/website/pull/282
- https://github.com/github/renaming

Address https://github.com/etcd-io/etcd/issues/12949

@ptabor @xiang90 @spzala @hexfusion @lilic @chalin @nate-double-u

### CODE REVIEW

**Comment by gyuho** [comment]
Expecting test failures because I have not made the git renaming yet.

**Comment by gyuho** [comment]
https://github.com/etcd-io/website/issues/149#issuecomment-839854317

Quoting @chalin 

> Done!
> 
> FYI, here is what GitHub had to say:
> 
> > Renaming this branch: will update 8 pull requests targeting this branch across 8 repositories.
> 
> **If you have a _fork_** of this repo, you should visit your fork and rename the default branch to `main` as well -- in fact GitHub will invite you to do so.
> 
> **If you have a _local clone_**, you can update it by running the following commands provided by GitHub (this will work for most folks):
> 
> ```
> git branch -m master main
> git fetch origin
> git branch -u origin/main main
> git remote set-head origin -a
> ```

**Review by ptabor — APPROVED** [review]

**Review by hexfusion — APPROVED** [review]

**Comment by hexfusion** [comment]
thanks @gyuho

**Comment by gyuho** [comment]
Done.

> git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a

**Comment by spzala** [comment]
Awesome, @gyuho!

**Comment by lilic** [comment]
Thank you! 🎉

**Pull request merged**
