### PR TITLE
[wip] Linearizable LeaseLeases

### PR DESCRIPTION
**Pull request by endocrimes**
Rough look at what a Linearizable LeaseLeases would look like.

Opening before adding a `ListLeases` API to get feedback on using `linearizableReadNotify` which based on reading the impl _seems_ like it should be safe without needing to forward to the leader.

### CODE REVIEW

**Comment by serathius** [comment]
Not sure if we should introduce this field when we are planning to introduce ListLease. cc @ptabor

**Comment by ahrtr** [comment]
> Not sure if we should introduce this field when we are planning to introduce ListLease. cc @ptabor

I think It should be a three steps plan:
1. Step 1 is to introduce a `linearizable` field;
2. Step 2 is to deprecate the `LeaseLeases`;
3. Step 3 is to add ListLeases.

**Comment by serathius** [comment]
PTAL https://github.com/etcd-io/etcd/pull/13690
I we will use different approach to fix leases.

**Comment by ptabor** [comment]
I think we still need linearizable leases: https://github.com/etcd-io/etcd/issues/13915

**Comment by ahrtr** [comment]
> I think we still need linearizable leases: #13915

Yes, I agree. At least we need linearizable ListLeases at first.

**Pull request closed without merging**
