### PR TITLE
Updating links in .md files after removing Documentation.

### PR DESCRIPTION
**Pull request by nate-double-u**
fixes: https://github.com/etcd-io/etcd/issues/12700

### CODE REVIEW

**Comment by nate-double-u** [comment]
https://etcd.io/docs/latest/ links to the latest official release, so I've standardized on that rather than using https://etcd.io/docs/current/ as `current` may not reflect a release yet.

**Review by ptabor — APPROVED** [review]

**Review by spzala — APPROVED** [review]
lgmt 
Thanks @nate-double-u

**Comment by nate-double-u** [comment]
Thanks everyone!

**Pull request merged**
