### PR TITLE
Add contributor docs

### PR DESCRIPTION
**Pull request by serathius**
cc @spzala @ahrtr

### CODE REVIEW

**Review by spzala — APPROVED** [review]
@serathius thanks! As discussed in the website repo, moving dev specific content here makes sense. The changes looks good but one comment with postmorterm doc. We may want to create a folder `Postmortem` and keep this issue specific postmortem and any future ones there. Also, I think good to add a separate `template` file by modifying this file. Thanks!

**Comment by ahrtr** [comment]
It makes sense to move dev specific docs here. 

But can we move all the dev related docs into the existing directory [Documentation/dev-guide](https://github.com/etcd-io/etcd/tree/main/Documentation)/[dev-guide](https://github.com/etcd-io/etcd/tree/main/Documentation/dev-guide)? 

I agree with @spzala, we can create a folder `Postmortem` under the [Documentation](https://github.com/etcd-io/etcd/tree/main/Documentation).

**Comment by serathius** [comment]
ups, pushed postmortem unintentionally :P

**Comment by serathius** [comment]
FYI I want to separate persona of developer and contributor, thus have separate directories for `dev-guide` and `contributor-guide`. Developer is just a person that want's to use Etcd API, aka develop something on it. Contributor wants to develop the etcd itself, aka contribute to the project itself.

Removed postmortem, it will be added in seperate PR.

**Review by ahrtr — APPROVED** [review]
LGTM

**Pull request merged**
