### PR TITLE
raft: dont drop read index requests when the peer hasn't committed to its term

### LINKED ISSUE #11483: leader needs responses an invalid `ReadIndexResp` when it hasn't committed to current term
In the current implementation about handling `ReadIndex`:
```go
if r.raftLog.zeroTermOnErrCompacted(r.raftLog.term(r.raftLog.committed)) != r.Term {
        // Reject read only request when this leader has not committed any log entry at its term.
        return nil
}
```
Leader drops read index request silently if it hasn't been ready. However this leaves associated callbacks on followers un-cleanup. So followers need some extra mechanisms to cleanup them out from raft.

So here I think the leader can response an invalid `ReadIndexResp` so that followers can cleanup callbacks quickly and correctly. And, I think `ReadIndexResp` with `index == 0` is a good to be used as an invalid one.

Would you like to introduce the behavior? @tbg

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

Close #11483 .

Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by hicqu** [comment]
Could you take a look @xiang90 ? thanks.

**Comment by hicqu** [comment]
Sorry for ping again. Any one can take a look?

**Comment by xiang90** [comment]
@hicqu It seems that you mix some cleanup work with the actual required change. can you separate them into two PRs or at least two commits?

**Comment by xiang90** [comment]
`not ready` is a bad term. it is too general and confusing. `CommitedEntryInCurrentTerm` is probably better...

**Comment by hicqu** [comment]
@xiang90 The PR has been updated. Could you take a look?

**Comment by hicqu** [comment]
Friendly ping @xiang90 .

**Comment by hicqu** [comment]
@xiang90 could you take a look?

**Comment by hicqu** [comment]
Friendly ping @xiang90 .

**Comment by hicqu** [comment]
@gyuho could you help me to take a look?

**Pull request closed without merging**
