### PR TITLE
go.mod: name packages with go.etcd.io/etcd/v3

### PR DESCRIPTION
**Pull request by philips**
Attempt to fix https://github.com/etcd-io/etcd/issues/11820

- [x] make works
- [x] ./scripts/genproto.sh makes no changes after running
- [x] make test passes
- [x] ensure bill-of-materials.json is OK
- [x] TEST_OPTS="PASSES='functional'" make test

### CODE REVIEW

**Comment by philips** [comment]
This is weird, consistently getting this error after all of this:

```
coverage: 28.1% of statements                                                                                                      
Too many goroutines running after all test(s).                                                                                     
1 instances of:                                                                                                                    
go.etcd.io/etcd/v3/pkg/testutil.interestingGoroutines(...)                                                                         
        /home/philips/etcd/pkg/testutil/leak.go:113 +0x8f                                                                          
go.etcd.io/etcd/v3/pkg/testutil.CheckLeakedGoroutine(...)                                                                          
        /home/philips/etcd/pkg/testutil/leak.go:45 +0xe1                                                                           
go.etcd.io/etcd/v3/etcdserver/api/v2v3_test.TestMain(...)                                                                          
        /home/philips/etcd/etcdserver/api/v2v3/main_test.go:40 +0x31c                                                              
main.main()                                                                                                                        
        _testmain.go:104 +0x334  
```

**Comment by philips** [comment]
Integration is failing on a test that almost certainly latency flakey:

```
--- FAIL: TestBalancerUnderNetworkPartitionWatchLeader (3.24s)
2220    network_partition_test.go:266: took too long to detect leader lost
```

**Comment by xiang90** [comment]
@philips 

Have you tried to write a simple program with etcd/client dependency?

**Comment by philips** [comment]
What do you mean? What is it you are trying to test?

**Comment by xiang90** [comment]
> What do you mean? What is it you are trying to test?

Something like

```go
import go.etcd.io/etcd/v3/clientv3

func main() {
    _, _ = clientv3.New(...)
   ...
}
```

Just to make sure the client dependency can be resolved correctly outside the etcd project.

**Comment by xiang90** [comment]
I gave it a try. It seems working well.

**Comment by philips** [comment]
OK, thanks.

Does it all LGTY then?

**Comment by xiang90** [comment]
LGTM

**Comment by philips** [comment]
cc @etcd-io/maintainers-etcd we should all take a look at this go.mod change

**Comment by philips** [comment]
I am going to merge this at 2pm Pacific today (Tues. 2020-04-28) if there
are no objections.

**Comment by gyuho** [comment]
@philips Can we update https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.5.md in a separate PR (or just separate commit is good too)?

**Comment by philips** [comment]
i will add the changelog and try to fix markdown docs before merging

**Comment by philips** [comment]
@gyuho Take a look at the docs and CHANGELOG entry here: https://github.com/etcd-io/etcd/pull/11823/commits/d88d765ba4bfd51c0b50b47d8f1315520bc8f9a5

**Pull request merged**
