### PR TITLE
[2023-05-16] Bump dependencies identified by dependabot

### PR DESCRIPTION
**Pull request by jmhbnz**
This pull request completes this weeks etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1DDWzbcOx1p32MhyelaPZ_SfYtAD6xRsrtGRZ9QXPOyQ/edit#gid=0)  and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

Summary of actions:
- [x] https://github.com/etcd-io/etcd/pull/15902
- [x] https://github.com/etcd-io/etcd/pull/15894
- [x] https://github.com/etcd-io/etcd/pull/15901
- [x] https://github.com/etcd-io/etcd/pull/15896
- [ ] https://github.com/etcd-io/etcd/pull/15899 - Merge direct
- [ ] https://github.com/etcd-io/etcd/pull/15898 - Close, purely indirect
- [ ] https://github.com/etcd-io/etcd/pull/15897 - Close, purely indirect
- [ ] https://github.com/etcd-io/etcd/pull/15895 - Close, purely indirect
- [ ] https://github.com/etcd-io/etcd/pull/15903 - Closed, blocked
- [ ] https://github.com/etcd-io/etcd/pull/15900 - Closed, blocked

### CODE REVIEW

**Review by jmhbnz — COMMENTED** [review]
Hi @ahrtr - If you are happy with my summary above and the changes I will go ahead and close off the pure indirects pull requests 🙏🏻

**Review by ahrtr — APPROVED** [review]
Great work! Thanks @jmhbnz

**Comment by fuweid** [comment]
I will take it next week.

**Comment by ahrtr** [comment]
> I will take it next week.

@lavacat already resigered for next week. Please register your name after that. thx

https://docs.google.com/spreadsheets/d/1DDWzbcOx1p32MhyelaPZ_SfYtAD6xRsrtGRZ9QXPOyQ/edit#gid=0

**Comment by fuweid** [comment]
Updated. Thanks for the reminder.

**Pull request merged**
