### PR TITLE
tests: Fix building incorrect etcd version and make switch strict

### PR DESCRIPTION
**Pull request by serathius**
cc @ahrtr @ptabor

### CODE REVIEW

**Comment by serathius** [comment]
Looks like at some point our usage of `GITHUB_REF` environment variable stopped working as it always was overridden.

**Comment by serathius** [comment]
ping @ahrtr @ptabor

**Review by jmhbnz — APPROVED** [review]
LGTM

**Review by ahrtr — APPROVED** [review]
LGTM

**Pull request merged**
