### PR TITLE
Generate and push multi-arch docker manifest list

### LINKED ISSUE #10380: Push mulit-arch fat manifest image for etcd
Push mulit-arch fat manifest image for etcd

I already see that we are pushing the images for following [supported architectures](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/supported-platform.md) into the gcr: https://console.cloud.google.com/gcr/images/etcd-development/GLOBAL/etcd?gcrImageListsize=30. So this task is to push multi-arch fat manifest pointing to all the supported platforms.

### PR DESCRIPTION
**Pull request by anguslees**
Change amd64 docker image to use a `-amd64` suffix, consistent with
other architectures.  Introduce a multiarch docker manifest list with
the original (no-arch) docker tag.

Fixes #10380

### CODE REVIEW

**Comment by anguslees** [comment]
I'm suspicious of the `scripts/release` script, since I note it still refers to s390x in the arch 'for' loop, even though this arch has been commented out of `scripts/build-release.sh`.  I _suspect_ this means `scripts/release` is not actually used? :raised_eyebrow:

**Comment by ptabor** [comment]
> I'm suspicious of the `scripts/release` script, since I note it still refers to s390x in the arch 'for' loop, even though this arch has been commented out of `scripts/build-release.sh`. ~I _suspect_ this means `scripts/release` is not actually used? raised_eyebrow~
> Edit: Aha. ^this is only true on `master`. Everything looks fine on `release-3.4`.

I'm reverting this in https://github.com/etcd-io/etcd/pull/12629. 

Thank you. Overall the change looks good to me, but someone with more docker expertise should take another look.

**Review by ptabor — APPROVED** [review]
LGTM - but second approval from maintainer with more docker experience needed.

**Review by gyuho — APPROVED** [review]
lgtm thx @anguslees !

**Pull request merged**
