### PR TITLE
Supporting setting LocalAddr in peer communication

### PR DESCRIPTION
**Pull request by highpon**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This PR addresses https://github.com/etcd-io/etcd/issues/17068

### CODE REVIEW

**Review by jmhbnz — COMMENTED** [review]
Hey @highpon - Thanks for raising this proposal.

Please ensure your commit is signed so the developer certificate of origin (DCO) check passes, i.e:

```bash
git rebase HEAD~1 --signoff
git push --force
```

**Comment by highpon** [comment]
@jmhbnz 
Thanks for your help!
I signed my commit.

**Comment by ahrtr** [comment]
@highpon any update on this?

**Comment by ivanvc** [comment]
I think we can close this pull request, as #17661 superseded this pull request, and is already merged.

**Pull request closed without merging**
