### PR TITLE
Manually bump dependencies

### PR DESCRIPTION
**Pull request by sharathsivakumar**
Here are the dependencies raised by the bot this week:

- https://github.com/etcd-io/etcd/pull/17374
- https://github.com/etcd-io/etcd/pull/17375
- https://github.com/etcd-io/etcd/pull/17376
- https://github.com/etcd-io/etcd/pull/17377
- https://github.com/etcd-io/etcd/pull/17378
- https://github.com/etcd-io/etcd/pull/17379  --> Bumped

### CODE REVIEW

**Comment by sharathsivakumar** [comment]
@ahrtr @serathius @jmhbnz Please review the dependency update and let me know if changes are required.

**Comment by sharathsivakumar** [comment]
Yes. We can close those. They are indirect dependencies

**Review by ahrtr — APPROVED** [review]
lgtm

Thanks

**Pull request merged**
