### PR TITLE
etcd: modify declaring empty slices 

### PR DESCRIPTION
**Pull request by demoManito**
declare an empty slice to `var s []int` replace `s :=[]int{}`, https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices

### CODE REVIEW

**Comment by ahrtr** [comment]
Please fix the test failures.

**Comment by serathius** [comment]
Please consider introducing a static analysis that will prevent future regressions. I expect something already exists in golangci, just needs to be enabled in https://github.com/etcd-io/etcd/blob/main/.golangci.yaml

**Comment by ahrtr** [comment]
> Please consider introducing a static analysis that will prevent future regressions. I expect something already exists in golangci, just needs to be enabled in https://github.com/etcd-io/etcd/blob/main/.golangci.yaml

Yes, let's do this in a separate PR. 

@demoManito Please fix the test failures.

**Comment by demoManito** [comment]
> Details

ok

**Comment by demoManito** [comment]
> > Please consider introducing a static analysis that will prevent future regressions. I expect something already exists in golangci, just needs to be enabled in [`main`/.golangci.yaml](https://github.com/etcd-io/etcd/blob/main/.golangci.yaml?rgh-link-date=2022-09-16T10%3A22%3A39Z)
> 
> Yes, let's do this in a separate PR.
> 
> @demoManito Please fix the test failures.

ok

**Comment by cenkalti** [comment]
I couldn't find any linter for this task in https://golangci-lint.run/usage/linters/

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @demoManito 

cc  @spzala @serathius @mitake to double check

**Comment by ahrtr** [comment]
The change looks safe to me, so merging it

**Comment by ahrtr** [comment]
> I couldn't find any linter for this task in https://golangci-lint.run/usage/linters/

Thanks @cenkalti for the feedback.

**Pull request merged**
