### PR TITLE
[3.4] server: add a unit test case for authStore.Reocver() with empty rangePermCache

### PR DESCRIPTION
**Pull request by mitake**
This PR backports https://github.com/etcd-io/etcd/pull/14647 to release-3.4
cc @ahrtr

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
I suggest to backport https://github.com/etcd-io/etcd/pull/14574 to 3.4 in this PR as well. FYI https://github.com/etcd-io/etcd/pull/14648#issuecomment-1295732130

**Comment by mitake** [comment]
@veshij Can I backport your fix to this PR? We have a unit test to verify the behavior so can work on e2e test later.

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @mitake

**Comment by ahrtr** [comment]
Also partially backport https://github.com/etcd-io/etcd/pull/14574

**Pull request merged**
