### PR TITLE
[3.5] *: LeaseTimeToLive returns error if leader changed

### PR DESCRIPTION
**Pull request by fuweid**
* Enable failpoints for integration
* Cherry-pick: #17642

### CODE REVIEW

**Comment by fuweid** [comment]
hold it until bump go version

**Comment by ahrtr** [comment]
Please rebase this PR, the go version has already been bumped.

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Comment by ahrtr** [comment]
Link to https://github.com/etcd-io/etcd/issues/17506

**Review by serathius — APPROVED** [review]

**Pull request merged**
