### PR TITLE
etcd-e2d-test:rename e2e-arm64 file and runs it on every pull request…

### PR DESCRIPTION
**Pull request by mingli103**
… #16912

KubeconNA 2023 Contribfest issue #16893 . Recently in #16801 we introduced on demand github actions runners for the arm64 platform. Having on demand runner infrastructure in place means we should now have enough capacity to begin running arm64 tests for every pull request. Currently we have: .github/workflows/e2e-arm64-template.yaml - Shared template .github/workflows/e2e-arm64-nightly.yaml - Runs template against both release-3.5 and main branches nightly. Moving forward we can just rename .github/workflows/e2e-arm64-template.yaml to
.github/workflows/e2e-arm64.yaml and delete the other file. We can then just make the template file a standard workflow that will run on pull request.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by jmhbnz** [comment]
@mingli103 This pr is looking good, if you're ready for review please mark the pr as ready thanks 🙏🏻

**Review by jmhbnz — APPROVED** [review]
LGTM on green - Thanks @mingli103 

/lgtm
/approve

**Review by serathius — APPROVED** [review]

**Comment by mingli103** [comment]
Hi @jmhbnz, this PR is ready to merge.

**Comment by jmhbnz** [comment]
Thanks for closing off the other pr. Agree this one is good to go, thanks @mingli103.

Gentle ping @serathius / @ahrtr for merge.

**Review by ahrtr — APPROVED** [review]

**Pull request merged**
