### PR TITLE
vendor: bump go-systemd to v22.0.0 to fix mod tidy error

### LINKED ISSUE #11345: cannot find module providing package github.com/coreos/go-systemd/journal
when i use go get -v go.etcd.io/etcd/clientv3, it shows cannot find module providing package github.com/coreos/go-systemd/journal

who know how to fix it?

### PR DESCRIPTION
**Pull request by ms2008**
[go-systemd](https://github.com/coreos/go-systemd) had completed of switching to Go modules between `v21` and `v22.0.0`. 
This pr fix mod error due to semver not being applied correctly. 
Ref. [coreos/go-systemd#321](https://github.com/coreos/go-systemd/issues/321)

Fixes #11345

### CODE REVIEW

**Comment by xiang90** [comment]
@ms2008 

can you squash the two commits into one?

**Comment by ms2008** [comment]
Fixed, thanks.

**Comment by xiang90** [comment]
@ms2008 can you run etcd/scripts/updatebom.sh to update the bill of materials

**Comment by ms2008** [comment]
@xiang90 done

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
