### PR TITLE
[3.4] server: set multiple concurrentReadTx instances share one txReadBuffer.

### PR DESCRIPTION
**Pull request by fuweid**
(cherry picked from commit 9c82e8c72b96eec1e7667a0e139a07b944c33b75)
Signed-off-by: Wei Fu <fuweid89@gmail.com>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

----

Related to #15072

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]
Given the big performance improvement pointed out in https://github.com/etcd-io/etcd/pull/12933#issuecomment-843385468 and the change looks safe, so backporting the PR is accepted.

Thank you!

**Comment by ahrtr** [comment]
Please add changelog item as well.

**Comment by fuweid** [comment]
> Please add changelog item as well.

Thanks for the review! Will do after merge.

**Comment by fuweid** [comment]
@ahrtr added by https://github.com/etcd-io/etcd/pull/15198.

**Pull request merged**
