### PR TITLE
[3.4] fix(defrag): close temp file in case of error

### PR DESCRIPTION
**Pull request by ghouscht**
See https://github.com/etcd-io/etcd/issues/18841 for details. Backport of https://github.com/etcd-io/etcd/pull/18851 to 3.4

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ghouscht** [comment]
/assgin @ahrtr

Should I prepare a changelog entry as well?

**Comment by ghouscht** [comment]
/assign @ahrtr

Should I prepare a changelog entry as well?

**Review by ahrtr — APPROVED** [review]

**Comment by ghouscht** [comment]
> This will make go vet fail and is already causing trouble on main https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/etcd-io_etcd/18821/pull-etcd-verify/1854634839446130688#1:build-log.txt%3A838

Thank you for raising this. Strange that it wasn't noticed by the checks that were run against the PR where this was added to main. I submitted https://github.com/etcd-io/etcd/pull/18857 to fix this in main and adapted this and the 3.5 backport PRs.

**Review by ivanvc — APPROVED** [review]
This backport LGTM. Thanks, Thomas.

**Pull request merged**
