### PR TITLE
[3.4] Bump bbolt to v1.3.7

### PR DESCRIPTION
**Pull request by ahrtr**
Linked to https://github.com/etcd-io/etcd/pull/15221

Signed-off-by: Benjamin Wang <wachao@vmware.com>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ahrtr** [comment]
Sine both the PR for main https://github.com/etcd-io/etcd/pull/15221 and for release-3.5 https://github.com/etcd-io/etcd/pull/15222 had already been approved and merged, could you approve this PR? thx @ptabor @spzala

**Comment by ahrtr** [comment]
and also https://github.com/etcd-io/etcd/pull/15224 thx

**Review by spzala — APPROVED** [review]
Thanks @ahrtr !!

**Comment by ahrtr** [comment]
> Thanks @ahrtr !!

Thanks @spzala for reviewing this PR and https://github.com/etcd-io/etcd/pull/15224

**Pull request merged**
