### PR TITLE
*: use Go 1.11 module for dependency management, replace "dep"

### PR DESCRIPTION
**Pull request by gyuho**
Also updates `./scripts/updatedep.sh` with example commits to upgrade `go.uber.org/zap` to https://github.com/uber-go/zap/releases/tag/v1.9.1.

### CODE REVIEW

**Comment by gyuho** [comment]
ref. https://github.com/etcd-io/etcd/issues/10083#issuecomment-420456817

/cc @h8liu

**Comment by hexfusion** [comment]
@gyuho could you outline your plan regarding implementation. Makes sense this would be 3.4+ is that right?

**Comment by gyuho** [comment]
> could you outline your plan regarding implementation

? This is just tooling update?

**Comment by hexfusion** [comment]
> ? This is just tooling update?

My point/question is that Go is calling this `experimental`  for 1.11 with preliminary support for versioned modules. So I was curious if this was going to be part of all patch releases moving forward or the next minor bump? Changes to modules in 1.12 will be backward compatible so I guess the experimental aspect is not very intrusive.

ref: https://github.com/golang/go/wiki/Modules#go-111-modules

**Comment by gyuho** [comment]
@hexfusion This should be safe, since we still have months to test v3.4. I have been using go module for other projects and haven't hit any issues yet.

**Comment by vtolstov** [comment]
when this happened?

**Comment by gyuho** [comment]
@vtolstov Will try to merge by this week.

**Comment by jingyih** [comment]
lgtm

**Pull request merged**
