### PR TITLE
[3.4] Backport livez/readyz

### PR DESCRIPTION
**Pull request by siyuanfoundation**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

Similar to https://github.com/etcd-io/etcd/pull/17039

### CODE REVIEW

**Comment by siyuanfoundation** [comment]
cc @serathius @ahrtr

**Comment by ahrtr** [comment]
Overall looks good to me.

@siyuanfoundation could you manually run each probe (/health, /livez, /readyz) based on **this PR** and paste the output?

@fuweid @jmhbnz could you also double check?

**Comment by siyuanfoundation** [comment]
> Overall looks good to me.
> 
> @siyuanfoundation could you manually run each probe (/health, /livez, /readyz) based on **this PR** and paste the output?

I will backport the e2e tests after merging this PR. 
Here are the manual test results:
```
curl http://127.0.0.1:2379/health
> {"health":"true"}
curl http://127.0.0.1:2379/livez
> ok
curl http://127.0.0.1:2379/readyz
> ok
curl http://127.0.0.1:2379/livez?verbose=true
> [+]serializable_read ok
> ok
curl http://127.0.0.1:2379/readyz?verbose=true
> [+]serializable_read ok
> [+]linearizable_read ok
> [+]data_corruption ok
> ok
```

**Review by ahrtr — APPROVED** [review]
lgtm

Thanks

**Review by fuweid — APPROVED** [review]
LGTM

**Pull request merged**
