### PR TITLE
[2024-11-04] Manual Dependency Bump

### PR DESCRIPTION
**Pull request by ArkaSaha30**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

#### Bumped:

- https://github.com/etcd-io/etcd/pull/18839
- https://github.com/etcd-io/etcd/pull/18835
- https://github.com/etcd-io/etcd/pull/18837
- https://github.com/etcd-io/etcd/pull/18830
- https://github.com/etcd-io/etcd/pull/18836
- https://github.com/etcd-io/etcd/pull/18833

#### Purely Indirect:

- https://github.com/etcd-io/etcd/pull/18834
- https://github.com/etcd-io/etcd/pull/18832
- https://github.com/etcd-io/etcd/pull/18831

### CODE REVIEW

**Comment by ivanvc** [comment]
Question, should we squash commits 84096c6 and fdb7302, as technically updating `github.com/grpc-ecosystem/grpc-gateway/v2` was the change that updated `api/etcdserverpb/gw/rpc.pb.gw.go`?

**Comment by ahrtr** [comment]
> Question, should we squash commits [84096c6](https://github.com/etcd-io/etcd/commit/84096c60390159130626aefc6e64f1f6454b883e) and [fdb7302](https://github.com/etcd-io/etcd/commit/fdb730284721df776fbd59b23e1d9622829e1035), as technically updating `github.com/grpc-ecosystem/grpc-gateway/v2` ([84096c6](https://github.com/etcd-io/etcd/commit/84096c60390159130626aefc6e64f1f6454b883e)) was the change that updated `api/etcdserverpb/gw/rpc.pb.gw.go` and therefore caused [fdb7302](https://github.com/etcd-io/etcd/commit/fdb730284721df776fbd59b23e1d9622829e1035)?

@ArkaSaha30 can you please add more context to the commit message for the commit "fix genproto error" for future reference?
- Why there is such error?
- How did you fix the genproto error? manually or automatically?

**Comment by ArkaSaha30** [comment]
> Question, should we squash commits [84096c6](https://github.com/etcd-io/etcd/commit/84096c60390159130626aefc6e64f1f6454b883e) and [fdb7302](https://github.com/etcd-io/etcd/commit/fdb730284721df776fbd59b23e1d9622829e1035), as technically updating `github.com/grpc-ecosystem/grpc-gateway/v2` ([84096c6](https://github.com/etcd-io/etcd/commit/84096c60390159130626aefc6e64f1f6454b883e)) was the change that updated `api/etcdserverpb/gw/rpc.pb.gw.go` and therefore caused [fdb7302](https://github.com/etcd-io/etcd/commit/fdb730284721df776fbd59b23e1d9622829e1035)?

Yes it makes sense to squash it into one commit 👍

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, Arka.

**Pull request merged**
