### PR TITLE
[2024-03-25] Bump dependencies identified by dependabot

### PR DESCRIPTION
**Pull request by ivanvc**
This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).

Summary of actions:
- [x] #17649 - Bumped
- [x] #17647 - Bumped **but see my comment**
- [x] #17644 - Bumped
- [ ] #17648 - Indirect
- [ ] #17646 - Indirect
- [ ] #17645 - Indirect

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by ivanvc** [comment]
Hey @jmhbnz, @ahrtr, I noticed that dependabot caught an update to `yq`. I dug in the code to see where it was used (as it is defined in `tools/go.mod`/`tools/mod/tools.go`). However, it was initially used to extract the go version from `.travis.yaml`. Of course, this is not used anymore, and the reference got deleted at 577c898feea768e20b9f3c26357abc15b22a3ff3.

Should we delete it from `tools/mod/tools.go`? And reduce the BOM?

**Comment by jmhbnz** [comment]
> Should we delete it from `tools/mod/tools.go`? And reduce the BOM?

Great catch @ivanvc - I can't see any reference so I would absolutely agree to remove it now 👍🏻

**Comment by ahrtr** [comment]
> Should we delete it from `tools/mod/tools.go`? And reduce the BOM?

Yes, please. We should always try to cleanup any unused dependencies as much as possible.

**Comment by ahrtr** [comment]
> @ahrtr, should I address that in a follow-up PR or in this PR?

Either way works for me.  Let's merge this PR firstly, feel free to resolve it in a followup PR. Thanks.

**Review by ahrtr — APPROVED** [review]

**Comment by ivanvc** [comment]
I created issue #17658 to track removing `yq`.

**Pull request merged**
