### PR TITLE
Automated cherry pick of #9997

### PR DESCRIPTION
**Pull request by wenjiaswe**
Cherry pick of #9997 on release-3.3.

#9997: etcdserver/api/snap: add v3 snapshot fsync metrics

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
@wenjiaswe Can you squash commits? Then lgtm thanks!

**Comment by gyuho** [comment]
@wenjiaswe 

I see compile error?

```
# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver
../vendor/github.com/coreos/etcd/etcdserver/server.go:63:2: context redeclared as imported package name
	previous declaration at ../vendor/github.com/coreos/etcd/etcdserver/server.go:18:2
```

https://travis-ci.com/etcd-io/etcd/jobs/142774936#L616-L618?

And the import paths should just work, since we did not update release-3.3 import paths.

**Comment by wenjiaswe** [comment]
@gyuho you are right! I must have looked at somewhere wrong... But it's wield that my branch builds successfully locally and  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:63 and https://github.com/wenjiaswe/etcd/blob/d5d12a4b985400f5a8fbafdb957a3ad83629f5a8/etcdserver/server.go#L63 mentioned in https://travis-ci.com/etcd-io/etcd/jobs/142774936#L616 and https://travis-ci.com/etcd-io/etcd/jobs/142774936#L706 don't even have anything, it's an empty line:( context is declared once. The file is not changed anyway with the back port.

**Comment by jingyih** [comment]
@wenjiaswe 
The compile error is caused by a previously merged PR on this branch, it is fixed by #10093.  Can you do a rebase?

**Comment by wenjiaswe** [comment]
@jingyih ah! thanks for the fix!

**Pull request merged**
