### PR TITLE
[test] Support dynamically adding & starting new member

### PR DESCRIPTION
**Pull request by ahrtr**
Continue to work on https://github.com/etcd-io/etcd/pull/14404, because there is no response from the original author for a long time. 

We need to resolve this because the other PR https://github.com/etcd-io/etcd/pull/14574 is blocked by this one

cc @spzala @mitake @serathius @ptabor 

cc @veshij @biosvs

### CODE REVIEW

**Comment by ahrtr** [comment]
@spzala @mitake @serathius @ptabor The original PR is already well reviewed, so please only take a look at the second commit https://github.com/etcd-io/etcd/pull/14589/commits/24ad49091e68ebb8ede2edbf6df5d47101516fda .

**Review by spzala — APPROVED** [review]
@ahrtr I looked at the commit you mentioned and that look good to me. Thanks for working on it!

**Comment by ahrtr** [comment]
Thanks @spzala

**Comment by biosvs** [comment]
I was unavailable, sorry.

Thanks for finishing PR!

**Pull request merged**
