### PR TITLE
release-3.3: bump gRPC to 1.23

### LINKED ISSUE #9956: 3.3.7 panic: send on closed channel
hi,
i got a panic on 3.3.7.
happend today and 10 days ago
version:
```
 ./etcd --version
etcd Version: 3.3.7
Git SHA: 56536de55
Go Version: go1.9.6
Go OS/Arch: linux/amd64
```

cmdline:

> /opt/etcd/etcd --name xxx --discovery-srv xxx --initial-advertise-peer-urls=https://xxx:2380 --initial-cluster-token xxx --initial-cluster-state new --advertise-client-urls=https://xxxx --listen-client-urls=https://xxx:2379 --listen-peer-urls=https://xxx:2380 --cert-file=/etc/certificates/etcd/server.crt --key-file=/etc/certificates/etcd/server.key --trusted-ca-file=/etc/certificates/etcd/ca.crt --client-cert-auth --peer-cert-file=/etc/certificates/etcd/cluster.crt --peer-key-file=/etc/certificates/etcd/cluster.key --peer-trusted-ca-file=/etc/certificates/etcd/ca.crt --auto-compaction-retention=2 --proxy off

stacktrace:
```
panic: send on closed channel
goroutine 167547782 [running]:
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport.(*serverHandlerTransport).do(0xc4258a4ba0, 0xc4202b0960, 0x411648, 0x10)
#011/tmp/etcd-release-3.3.7/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport/handler_server.go:169 +0x115
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport.(*serverHandlerTransport).Write(0xc4258a4ba0, 0xc420507900, 0xc424ed134a, 0x5, 0x5, 0xc4201b5650, 0x2b, 0x2b, 0xc424ed1350, 0x5, ...)
#011/tmp/etcd-release-3.3.7/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport/handler_server.go:255 +0xe6
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*serverStream).SendMsg(0xc422327d80, 0xf4d7a0, 0xc42497baa0, 0x0, 0x0)
#011/tmp/etcd-release-3.3.7/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/stream.go:611 +0x275
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*serverStreamWithCtx).SendMsg(0xc422a85e90, 0xf4d7a0, 0xc42497baa0, 0xc42000d2b8, 0xc4204b2df8)
#011<autogenerated>:1 +0x50
github.com/coreos/etcd/cmd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*monitoredServerStream).SendMsg(0xc422b1dcc0, 0xf4d7a0, 0xc42497baa0, 0x160b820, 0xc425e6f4c0)
#011/tmp/etcd-release-3.3.7/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:179 +0x4b
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb.(*leaseLeaseKeepAliveServer).Send(0xc423b2b640, 0xc42497baa0, 0xc425e6f4c0, 0xc8a648e8a853ccb)
#011/tmp/etcd-release-3.3.7/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3687 +0x49
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*LeaseServer).leaseKeepAlive(0xc4244d0580, 0x16110c0, 0xc423b2b640, 0xc4258a4ba0, 0xc420507900)
#011/tmp/etcd-release-3.3.7/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/lease.go:138 +0x18d
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*LeaseServer).LeaseKeepAlive.func1(0xc4258a4c60, 0xc4244d0580, 0x16110c0, 0xc423b2b640)
#011/tmp/etcd-release-3.3.7/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/lease.go:89 +0x3f
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*LeaseServer).LeaseKeepAlive
#011/tmp/etcd-release-3.3.7/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/lease.go:88 +0x91
```

### PR DESCRIPTION
**Pull request by hexfusion**
#9956 has been very disruptive and while I am looking forward to the new balancer backport for 3.3 it seems practical to cut a release patching 3.3 with the old balancer then backporting the new balancer after it is stable. This would give folks an option to use the old or new balancers while having a patched release.

Backports to release-3.3 :

- Eliminate direct use of the gRPC transport package #9934
- raft: fix logger variadic parameter 1136ba0e0d4ab628cb13ffd76da47dbea357d0a6
- clientv3: pass "grpc.WithBlock" on "TestDialTimeout" commit 994a569f53f48129387027a532b5d1024ec5339b #9860
- clientv3: add "IsConnCanceled", deprecate "grpc.ErrClientConnClosing" 6e521d2f3f1ec4e8dc7d9a4fb16079fc265da803 #9860

### TODO

- [ ] Bump to gRPC 1.23.0 when released
- [ ] Create 1.11.12 test image
- [ ] remove `GRPC_GO_REQUIRE_HANDSHAKE` from testing as it will be resolved more gracefully in 1.23.0 via https://github.com/grpc/grpc-go/pull/2904/commits
- [ ] Update CHANGELOG

 Fixes #9956

/cc @gyuho @jpbetz @xiang90 @spzala @jingyih @wenjiaswe

### CODE REVIEW

**Comment by gyuho** [comment]
> cut a release patching 3.3 with the old balancer then backporting the new balancer after it is stable

We are already backporting new balancer + new gRPC later https://github.com/etcd-io/etcd/issues/10980. Given 3.4 time-frame, it doesn't make sense to support two balancer implementation. If we find a bug in gRPC, we should fix based on latest balancer implementation, not on the old ones.

Defer to @jpbetz @xiang90

**Comment by xiang90** [comment]
Yea... Let us just maintain one balancer.

**Comment by hexfusion** [comment]
> Yea... Let us just maintain one balancer.

While this does seem pragmatic, bumping a dependency to a patch release does not add additional support. The plan is to upgrade to new balancer once stable. At that time we would only be supporting a single balancer, not two. Introducing a new balancer to two versions does add risk. I will close this but if we find a flaw in the new balancer we should consider this as an alternative as it does not change balancer functionality for 3.3. Thanks for the review.

**Pull request closed without merging**
