### PR TITLE
tests: increases unit test coverage for etcd/server/auth isRangeOpPermitted

### PR DESCRIPTION
**Pull request by owayss**
fixes https://github.com/etcd-io/etcd/issues/15746

### CODE REVIEW

**Comment by lavacat** [comment]
please sign the commit. See [example](https://github.com/etcd-io/etcd/pull/15741#pullrequestreview-1390771159)

**Comment by owayss** [comment]
thanks for the heads-up, @lavacat. I have added the signoff trailer and force-pushed.

**Review by chaochn47 — APPROVED** [review]
LGTM, thanks!

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @owayss

**Pull request merged**
