### PR TITLE
pkg/schedule: recover from job panic[TODO]

### PR DESCRIPTION
**Pull request by LuFred**
This commits adds asynchronous TODO execution ,
record to std by capturing job panic, avoids the entire Scheduler panic caused by a JobPanic

### CODE REVIEW

**Comment by ptabor** [comment]
Thank you for the change. 

I think that the code is correct, but I have some doubts whether this behavior is expected in etcd.

Etcd panics when a write to e.g. bbolt is not successful, e.g. transaction cannot be committed for physical reasons. In such situation etcd currently crashes and gets restarted from precious snapshot & WAL log or master replica. 
The worse think that can happen in such failure gets sillently ignored, so some data are not getting written, that are expected to be stored. 

Do you have a particular use-case / crash that the PR is addressing ?

**Comment by LuFred** [comment]
@ptabor 
Use-Case/Crash has been fixed,
CHAN was not initialized in fifo struct initializer.

**Comment by LuFred** [comment]
@gyuho @ptabor  Please confirm that this is reasonable。
I look forward to having more suggestions
thanks

**Comment by ptabor** [comment]
I think that my comment from: https://github.com/etcd-io/etcd/pull/12868#issuecomment-822537784 was not addresssed. 

Let's do this case-by-case. For each panic 'stacktrace' we should take a look and decide whether its recoverable or potential data corruption that should halt etcd ASAP.

**Comment by LuFred** [comment]
> Thank you for the change.
> 
> I think that the code is correct, but I have some doubts whether this behavior is expected in etcd.
> 
> Etcd panics when a write to e.g. bbolt is not successful, e.g. transaction cannot be committed for physical reasons. In such situation etcd currently crashes and gets restarted from precious snapshot & WAL log or master replica.
> The worse think that can happen in such failure gets sillently ignored, so some data are not getting written, that are expected to be stored.
> 
> Do you have a particular use-case / crash that the PR is addressing ?



> I think that my comment from: [#12868 (comment)](https://github.com/etcd-io/etcd/pull/12868#issuecomment-822537784) was not addresssed.
> 
> Let's do this case-by-case. For each panic 'stacktrace' we should take a look and decide whether its recoverable or potential data corruption that should halt etcd ASAP.

Sorry, I left out your topic of discussion.
I think the two points you consider are really necessary.
But I can't think of a reasonable solution at the moment to distinguish between whether it's recoverable or potential data corruption that should halt etcd ASAP.
On the other hand, I have not fully understood many aspects of ETCD.
Can you give me some suggestions so that I can test it?

**Comment by ptabor** [comment]
I think there are 2 options: 
  - If you need this change because you use the library outside of etcd, you might expand the API with a callback called on errors. 
     - In etcd we would use the 'panic' behavior, while your implementation would have custom cod.e 
  - If you want to solve a real problem in etcd, please show an examplar stack-trace, and we will decide whether it should panic or get swallowed.

**Pull request closed without merging**
